/- GENERATED by gen_note_reshape_balance_seating.py — do not edit. -/
import ShielddGnarkFormal.Deployed.NoteReshape8x1BalanceCompressRunsSupport

set_option maxRecDepth 1000000
set_option maxHeartbeats 1000000

namespace Shieldd.GnarkFormal.Deployed.NoteReshape8x1BalanceCompressRunX1

open Shieldd.GnarkFormal
open Contracts.NoteReshape8x1

theorem seated (rho : Nat → Seg168.F) :
    StrideRun.sumAux (Seg168.localRho rho) 151 1 101 =
      StrideRun.sumAux rho 130357 8 101 :=
  NoteReshape8x1BalanceCompressRunsSupport.seatedRun_eq
    rho 151 130357 8 101 (by rfl)

end Shieldd.GnarkFormal.Deployed.NoteReshape8x1BalanceCompressRunX1
