"""Review only maintained portable generation delta; mathematics separately reviewed."""
import json,hashlib,subprocess,time
from pathlib import Path
H=Path(__file__).resolve().parent;F=H/'frozen';R=H.parents[1]
sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
assert sha(F/'successor-manifest04.json')=='4dfc5d82d6897563a90fcf847d80d234db0db662d990aa5aac6f58888d5098b3'
m=json.loads((F/'successor-manifest04.json').read_text());assert all(sha(F/Path(x['path']).relative_to('work/mac-poseidon-width6-upstream11-portable04'))==x['sha256'] for x in m['files'])
prompt=f'''Review immutable portable-hygiene SUCCESSOR at {F}, Read/Glob/Grep only, no execution/build/edit. Previous Opus provenance03 identified unlistedmaintaineddirectory/pycache trustgap; mathematics/rootproofbytes stayunchanged87fresh496audits,0newLean. Focus maintain/supported_verify_replay.py (actualmaintainedpath), replay-inventory04.json, README, controls04/result.json and controller vs priorrecipe {R/'work/parent-width6-upstream11-review03/frozen/supported_verify_replay.py'}. Newrunnerrequires-I-B-S forparentandchild, selfpath/hash equalitytoinventory, exactflat18maintained/2helpers listings inclbefore/aftereachgenerator, noexistingdirectories/caches/symlinks/unlistedfiles, removesPYTHON*env, importsrunpy/stdlibBEFOREexplicitqualifiedsys.pathinsertion, newoutputdir, unchanged85generatedcensus1799905B, recordsinterpreter+generatorstatuses/stdoutstderrhashes. ParentfreshisolatedreplayalreadyPASSED85exact0Lean andno__pycache__created. Verifythese changesclosepreviousstale/plantedpyc and unlistedjson.py shadowing gaps and preservestandardevidencetrust; don'tinvokehypotheticalunboundedthreatmodel. Inputcompact/fullSHAtrustfromoriginalmanifestandparentrecursiveprojectionalreadychecked; keepinventoryexternalmanifesttrustexplicit. Original386+6producerentriesunchanged512fbc7.../2be900...; successor28+1entries append-only. Six finite DATAguardcontrols rejectunlistedmodule,cachedirectory,pyc,symlink,wrongrecipehash,nonisolatedinvocation with0Lean. Checkanyregressioninclosed-flatbeforeafter, supportedexplicitpathhelpers/generatorheaders; no baselinecopy. Optional source-history/censusedge guard notrequiredwheregeneratoridentitypinnedandunchanged generatedfiles verified, butreportactualcorrectness/provenance issue ifpresent. FullTransfer/native/fullrelation/parentrowAt/cutsemanticsremainOPEN. Thisreviewonlyrepairprovenance, notadditionalmathresult. Report actionabledefect ornone inpreciseisolatedclosedbyte-generationroute.'''
(H/'review-prompt.txt').write_text(prompt+'\n');start=time.monotonic()
cmd=['/Users/antoinecyr/.local/bin/claude','--model','claude-opus-5-5','--effort','high','--permission-mode','plan','--tools','Read,Glob,Grep','--strict-mcp-config','--no-session-persistence','--output-format','json','--print',prompt]
with (H/'opus55-review.json').open('w') as out,(H/'opus55-review.stderr').open('w') as err:r=subprocess.run(cmd,stdout=out,stderr=err,timeout=900)
j=json.loads((H/'opus55-review.json').read_text());assert r.returncode==0 and not j['is_error'] and 'claude-opus-5-5' in j['modelUsage']
assert all(sha(F/Path(x['path']).relative_to('work/mac-poseidon-width6-upstream11-portable04'))==x['sha256'] for x in m['files'])
print(json.dumps({'review':'complete','delta_files':len(m['files']),'seconds':time.monotonic()-start,'model':list(j['modelUsage'])}))
