-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- Deterministically assembled by normalize-aeneas-lean-v7.
import Ipp.Extracted.AeneasRuntime

open Aeneas Aeneas.Std Result ControlFlow Error
open Std.Do
set_option linter.unusedVariables false
set_option maxHeartbeats 1000000
set_option maxRecDepth 2048

noncomputable section

namespace ark_ip_proofs
def
  applications.groth16_aggregation.structured_scalar_final_from_raw_transcript_inner_loop.body
  {F : Type} (corecloneCloneInst : core.clone.Clone F) (coreopsarithAddInst :
  core.ops.arith.Add F F F) (coreopsarithMulInst : core.ops.arith.Mul F F F)
  (product : F) (raw_transcript_reversed : Slice F)
  (iter : core.ops.range.Range Std.Usize) (power : F) (product1 : F) :
  Result (ControlFlow ((core.ops.range.Range Std.Usize) × F × F) F)
  := do
  let (o, iter1) ←
    core.iter.range.IteratorRange.next core.iter.range.StepUsize iter
  match o with
  | none => ok (done product1)
  | some i =>
    let t ← Slice.index_usize raw_transcript_reversed i
    let challenge ← corecloneCloneInst.clone t
    let t1 ← corecloneCloneInst.clone power
    let t2 ← coreopsarithMulInst.mul challenge t1
    let t3 ← coreopsarithAddInst.add product t2
    let product2 ← coreopsarithMulInst.mul product1 t3
    let power1 ← coreopsarithMulInst.mul t1 power
    ok (cont (iter1, power1, product2))
def
  applications.groth16_aggregation.structured_scalar_final_from_raw_transcript_inner_loop
  {F : Type} (corecloneCloneInst : core.clone.Clone F) (coreopsarithAddInst :
  core.ops.arith.Add F F F) (coreopsarithMulInst : core.ops.arith.Mul F F F)
  (product : F) (iter : core.ops.range.Range Std.Usize)
  (raw_transcript_reversed : Slice F) (power : F) (product1 : F) :
  Result F
  := do
  loop
    (fun (iter1, power1, product2) =>
      applications.groth16_aggregation.structured_scalar_final_from_raw_transcript_inner_loop.body
      corecloneCloneInst coreopsarithAddInst coreopsarithMulInst product
      raw_transcript_reversed iter1 power1 product2)
    (iter, power, product1)
def
  applications.groth16_aggregation.structured_scalar_final_from_raw_transcript_inner
  {F : Type} (corecloneCloneInst : core.clone.Clone F)
  (num_traitsidentitiesOneInst : num_traits.identities.One F)
  (coreopsarithAddInst : core.ops.arith.Add F F F) (coreopsarithMulInst :
  core.ops.arith.Mul F F F) (raw_transcript_reversed : Slice F) (r : F) :
  Result F
  := do
  let power ← corecloneCloneInst.clone r
  let product ← num_traitsidentitiesOneInst.one
  let i := Slice.len raw_transcript_reversed
  applications.groth16_aggregation.structured_scalar_final_from_raw_transcript_inner_loop
    corecloneCloneInst coreopsarithAddInst coreopsarithMulInst product
    { start := 0#usize, «end» := i } raw_transcript_reversed power product

end ark_ip_proofs
