import Ipp.ShippingAdaptiveAcceptedReplayKzgProbabilityTransport

/-!
Axiom audit for fixed-deployed-setup KZG probability transport.
-/

#print axioms Ipp.ShippingMultiStatement.cachePreservingCommonFork?_eq_some_rawTree_of_kzg
#print axioms Ipp.ShippingMultiStatement.fixedAcceptedReplayBls12377KzgVGame_eq_map
#print axioms Ipp.ShippingMultiStatement.fixedAcceptedReplayBls12377KzgWGame_eq_map
#print axioms Ipp.ShippingMultiStatement.cachePreservingKzgVWin_implies_fixedAcceptedReplayKzgVWin_of_supported
#print axioms Ipp.ShippingMultiStatement.cachePreservingKzgWWin_implies_fixedAcceptedReplayKzgWWin_of_supported
#print axioms Ipp.ShippingMultiStatement.randomizerGoodCachePreservingKzgVWin_le_fixedAcceptedReplayKzgVWin
#print axioms Ipp.ShippingMultiStatement.randomizerGoodCachePreservingKzgWWin_le_fixedAcceptedReplayKzgWWin
