import Ipp.Extracted.ShippingBundleProgramConstruction

/-!
Audit surface for production-origin and concurrent-bundle construction.

The cached endpoint is audited separately from the runtime erasure and the
raw planner shape so neither can be substituted for the other.
-/

#print axioms Ipp.Extracted.ShippingBundleProgramConstruction.SharedCacheBundleExecutionEquation.acceptedOutputDerived
#print axioms Ipp.Extracted.ShippingBundleProgramConstruction.SharedCacheBundleExecutionEquation.leastInvalidOutput_mem_projected
#print axioms Ipp.Extracted.ShippingBundleProgramConstruction.SharedCacheBundleExecutionEquation.acceptedLeastInvalidOutput
#print axioms Ipp.Extracted.ShippingBundleProgramConstruction.AcceptedConcurrentBundleSerialization.canonicalOutputExact
#print axioms Ipp.Extracted.ShippingBundleProgramConstruction.OutputDerivedBundleProgramEquations.rawAcceptedOutputDerivedOrigin
#print axioms Ipp.Extracted.ShippingBundleProgramConstruction.OutputDerivedBundleProgramEquations.fiberLiftedAcceptedOutputDerivedOrigin
#print axioms Ipp.Extracted.ShippingBundleProgramConstruction.OutputDerivedBundleProgramEquations.toBundleByteOriginReindexing
#print axioms Ipp.Extracted.ShippingBundleProgramConstruction.OutputDerivedBundleProgramEquations.toProjectedBundleProgramConstruction
#print axioms Ipp.Extracted.ShippingBundleProgramConstruction.OutputDerivedBundleProgramEquations.toCachedProjectedBundleConstruction
#print axioms Ipp.Extracted.ShippingBundleProgramConstruction.OutputDerivedBundleProgramEquations.cachedCanonical_evalDist_exact
#print axioms Ipp.Extracted.ShippingBundleProgramConstruction.OutputDerivedBundleProgramEquations.rawProgram_distinctQueryBounds
#print axioms Ipp.Extracted.ShippingBundleProgramConstruction.OutputDerivedBundleProgramEquations.cachedProjectedAcceptedOutputDerivedOrigin
#print axioms Ipp.Extracted.ShippingBundleProgramConstruction.OutputDerivedBundleProgramEquations.productionReplayOriginAt
