import Ipp.ShippingBundleCachedComposition

/-!
Audit surface for concurrent-runtime erasure and the cached bundle endpoint.

These roots exclude the rejected raw-equals-cached route and keep bundle-only
changes out of unrelated proof audits.
-/

#print axioms Ipp.ShippingBundleCachedComposition.ConcurrentCallObservation.eraseSemantic_mk
#print axioms Ipp.ShippingBundleCachedComposition.ConcurrentCallObservation.eraseLocalTrace_mk
#print axioms Ipp.ShippingBundleCachedComposition.AcceptedConcurrentSemanticProjection.semanticProjection_exact
#print axioms Ipp.ShippingBundleCachedComposition.AcceptedConcurrentSemanticProjection.semanticResult_accepted
#print axioms Ipp.ShippingBundleCachedComposition.RawBundleAttemptBounds.ofByteOriginReindexing
#print axioms Ipp.ShippingBundleCachedComposition.CachedProjectedBundleConstruction.fiberLifted_support_iff_cachedCanonical
#print axioms Ipp.ShippingBundleCachedComposition.CachedProjectedBundleConstruction.fiberLifted_event_eq_cachedCanonical
#print axioms Ipp.ShippingBundleCachedComposition.fsRandomFunction_event_eq_multiStatementFsProbComp
#print axioms Ipp.ShippingBundleCachedComposition.CachedProjectedBundleConstruction.fiberLifted_event_eq_multiStatementFsProbComp
#print axioms Ipp.ShippingBundleCachedComposition.RepeatedQueryCounterexample.rawSequential_distinctAnswers_not_coherent
#print axioms Ipp.ShippingBundleCachedComposition.RepeatedQueryCounterexample.rawSequential_and_coherentCached_log_lengths
