import Ipp.ShippingAdaptiveRandomizerBound

/-!
Audit surface for the cache-preserving adaptive S1 reduction.

Keeping this separate from the global-game foundations limits proof-only CI
rebuilds to this reduction's import closure.
-/

#print axioms Ipp.ShippingMultiStatement.selectionAt?_eq_some_exposes_outcome
#print axioms Ipp.ShippingMultiStatement.projectCommonStatementTree_all_accepts_and_invalid
#print axioms Ipp.ShippingMultiStatement.cachePreservingS1ExtractionExperimentAt_isTotalQueryBound_iff
#print axioms Ipp.ShippingMultiStatement.commonAcceptedInvalidFork_implies_extraction_or_randomizerBad
#print axioms Ipp.ShippingMultiStatement.cachePreservingS1Extraction_probability_le_component_sum
#print axioms Ipp.ShippingMultiStatement.rawForkFormalStatementSucceededAt_le_cachePreservingS1Extraction
#print axioms Ipp.ShippingMultiStatement.cachePreserving_rawForkExtractionReductionHolds
#print axioms Ipp.ShippingMultiStatement.adaptiveSelectedStatementWin_le_standalone
#print axioms Ipp.ShippingMultiStatement.rawForkFormalStatementSucceededAt_le_adaptive_error_add_intermediateBounds
#print axioms Ipp.ShippingMultiStatement.globalAdaptiveRandomizerPointBadFinset_card
#print axioms Ipp.ShippingMultiStatement.sourceOutcome_statement_materialized
#print axioms Ipp.ShippingMultiStatement.packedAcceptedRandomizerRootBadAt_log_witness
#print axioms Ipp.ShippingMultiStatement.globalSourceAcceptedRandomizerRootBadAt_le
#print axioms Ipp.ShippingMultiStatement.globalWrappedAcceptedRandomizerRootBadAt_le
#print axioms Ipp.ShippingMultiStatement.randomizerGoodMultiStatementForkExperimentAt_support_hasCommonStatement
#print axioms Ipp.ShippingMultiStatement.projectCommonStatementTree_root_data_exact
#print axioms Ipp.ShippingMultiStatement.projectCommonStatementTree_not_randomizerRootBad
#print axioms Ipp.ShippingMultiStatement.randomizerGoodFork_isSome_le_cachePreservingCryptoExtraction
#print axioms Ipp.ShippingMultiStatement.invalidAccepted_sub_randomizerError_le_good
#print axioms Ipp.ShippingMultiStatement.invalidAccepted_randomizerAdjustedForkTransform_le_goodFork
#print axioms Ipp.ShippingMultiStatement.invalidAccepted_randomizerAdjustedForkTransform_le_cryptoExtraction
