-- GENERATED by generate_rounds.py; edit the generator.
import ShielddSecurity.TransferPoseidonRound01Data01
import ShielddSecurity.CompilerCompletion
set_option maxHeartbeats 900000
set_option maxRecDepth 8192
namespace ShielddSecurity.TransferPoseidonRound01Program01
open Compiler CompilerCompletion ShielddSecurity.TransferPoseidonRound01
def materializedSteps : List Step := [
  .square lc49 [] 23076,
  .square lc55 [] 23077,
  .product lc56 lc49 [] 23078 23079,
  .square lc50 [] 23080,
  .square lc59 [] 23081,
  .product lc60 lc50 [] 23082 23083,
  .square lc51 [] 23084,
  .square lc63 [] 23085,
  .product lc64 lc51 [] 23086 23087,
  .square lc52 [] 23088,
  .square lc67 [] 23089,
  .product lc68 lc52 [] 23090 23091,
  .square lc53 [] 23092,
  .square lc71 [] 23093,
  .product lc72 lc53 [] 23094 23095,
  .square lc54 [] 23096,
  .square lc75 [] 23097,
  .product lc76 lc54 [] 23098 23099]
def copyStep : Step := .equal [(0,1)] [(0,1)]
def steps : List Step := materializedSteps++[copyStep]
def emittedRows : Array Row := (emitted steps).toArray
def rowMapping : Array Nat := (List.range 25).toArray
end ShielddSecurity.TransferPoseidonRound01Program01
