"""Supplement actual review02's explicit omissions, SOURCE/evidence only."""
from pathlib import Path
import hashlib,json,subprocess,sys
assert sys.flags.isolated and sys.flags.dont_write_bytecode and sys.flags.no_site
V=Path(__file__).resolve().parent;P=V.parent;R=V.parents[2];F=P/'final-two-result06';C=P/'final-two-control-candidate06';repo=R/'work/shared-build-handoff'
sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest();load=lambda p:json.loads(p.read_bytes())
prior=load(V/'opus55-final-call14-review02.json');assert prior['is_error'] is False and 'claude-opus-5-5' in prior['modelUsage']
si=load(C/'source-inventory06.json')
paths=[Path(e['path']) for e in load(F/'final-result-manifest06.json')['entries'].values()]+[F/n for n in ['final-result-manifest06.json','append-only-envelope06.json','postseal-guard06.json']]+[V/n for n in ['opus55-final-call14-review02.json','parent-final-RAW-inspection01.json','parent-RAW398-type-audits01.json','make-portable-result01.py','portable-actual-result01.json','publication-plan03.json','parent-final-source-replay02.json','parent-final-probe-replay01.json','fresh-budget-after-DATA-replay01.json','stage-publication02.py','inspect-staged-publication01.py']]+[Path(e['path']) for e in si['modules'].values()]+[repo/'circuits/lakefile.lean',repo/'circuits/ShielddSecurity/CompilerPriorFrame01.lean',repo/'circuits/ShielddSecurity/CompilerSegmentCompletion11.lean',P/'successor-source03/maintained/generate_successors.py',Path(__file__)]
paths=list(dict.fromkeys(paths));assert all(p.is_file() and not p.is_symlink() for p in paths)
before={str(p):sha(p) for p in paths};(V/'review-inputs03.json').open('x').write(json.dumps(before,indent=2)+'\n')
prompt='''Actual Claude Opus5.5 high focused supplemental SOURCE/evidence review03. Read/Glob/Grep only. Never execute/edit Python, Lean, lake, generators, validators, initializer, controller, native, WSL or Git. No kernel replay, admission or certification. Same workers and original limits.
V=/Users/antoinecyr/Documents/Codex/2026-10-08/can/work/mac-poseidon-call1-plan14/parent-final-call14-review01; P=V.parent; F=P/final-two-result06; C=P/final-two-control-candidate06; repo=/Users/antoinecyr/Documents/Codex/2026-10-08/can/work/shared-build-handoff.
Actual successful review02 in V/opus55-final-call14-review02.json found no defect in new Proof01/Combined+Semantic/Program/B0Absorb proof/data, fulltotal_call/logtypes/generator. It explicitly did NOT read parentRAWinspection, publication-scope06, mostmetadata, oldSOURCE03generator, portableproducer/result. Read that full verdict; supplement only omissions. The earlier prompt incorrectly referred generically to a Call14 Frame01: no such separate new module exists in the selected57; Call14 frame/writes/prior proof lives in Program01, which review02 fully read. Full read inherited repo/circuits/ShielddSecurity/CompilerSegmentCompletion11.lean and CompilerPriorFrame01.lean to assess frame contracts if relevant, and actual Program01 path from C/source-inventory06.json. Do not claim a nonexistent Frame01 review or a fresh inherited qualification.
FULL READ V/parent-final-RAW-inspection01.json (48707B); F/publication-scope06.json; V/make-portable-result01.py (3847B); V/portable-actual-result01.json (411775B, paginate all lines for complete structural/accounting review); P/successor-source03/maintained/generate_successors.py (45126B, confirm path with Glob if needed); V/parent-final-source-replay02.json; parent-final-probe-replay01.json; fresh-budget-after-DATA-replay01.json. Read full publication-plan03.json (127831B) as selection/identity/mapping review, not a mathematical review of all214 files. Inspect final60-observation06.json only relevant observed_fields/local_scope/OPEN/accounting records; no full3.5MB read claim required. V/parent-RAW398-type-audits01.json620867B: targeted samples/types and census if useful, state precise partial scope, do not invent full398 mathematicalread.
Check portable producer derives exactly60originalraw-local-only receipts ordinal1..60/57passed/398audits/failed55,56,58 zero, preserves actual receipt/module/source/object/log/runner/inventory/admission/typedexit/environment/resource/cleanup fields and exact182deduplicated import records. Hash is identity only. Compare portable fields with existing parent inspection and original immutable final185manifest SHAa1860ff75f5117b55d5366c5aa96e0a1358830df831118fb0469065f35bbb995 and selected actual receipt samples. No reexecution; parent already independently rehashed7658unique paths/reparsed57RAWlogs all398fulltype+standardaxiom pairs/60intent180event60claim60receipt/chained59->60admissions/ownedemptycleanup. Currentcharged57376472B underoriginal512MiB includes additional DATAcopies; historicalcompletion54272345B unchanged; seconds362.77325166806986; flatdispatchmetadata2455370Bunder16MiB. Original60ALLEXHAUSTED,57passed,3failed allzero. Review02 gives no claims about these counts; now assess report/portablederivation consistency separately from kernel verification.
Publicationplan214files9013826B, exactly57canonicalnewLean modules. Combined exportsoldChecked/Controls namespaces. Historical unbuilt Checked01/Controls01 .lean files retained under handoffs/.../generator-inputs/historical-math06 as inputbytes ONLY; never circuits/ShielddSecurity or any Lean sourcepath. Full read repo/circuits/lakefile.lean (lean_lib ShielddSecurity) and V/stage-publication02.py + inspect-staged-publication01.py. Confirm only selected canonical57 go circuits namespace, all historical copies/otherreplaydirs stay outside atomicselection. Factory requires actualret0/model/is_errorfalse+explicitparentacceptance+cleanbasea1962598ad440af95b0237697c7ee6bcc4226fbd+lock844389ee069e1fb2e576708842d0b389b4d9a44a, noGit/Lean. It preservesexactmapping/aliases, excludesrawlogs/objects/caches/toolchains/DB/composedworkspaces and maintained/generated split. Record whether duplicate-namespace publication conditions from review02 are addressed by exact sourcepath/selection design, or actionable SOURCE packaging defect exists. Originalgenerator needs localfailed58 rawlog identity intentionallyunshipped, so no standalone originalobject replay claim.
Endpoint628steps837selectedrows/domain24arity6IV1560/preserve22735inputs/copy/outside23472..24308; prior onlyinitialsatisfaction+actualsupportoutside.13checkerfalsecontrols onlylocalR00syntax/representativetailrow+offset/fixedmetadata. FullparentrowAt/nativecallsite/consumer/fullrelation/G3/G4/G5/G7/Hasse/cardinality/fullTransfer OPEN. Join15 oldaggregateMD>16MiB and owncachegap BLOCKED; foreign3ALL exhausted/nativeTOTALunknown zero execution. No budget reset/refill/capescalation/publication approval by reviewer. Return actionable findings or nofindings WITH exact full/partial readscope; distinguish SOURCE report consistency from independentkernelverification. Do not omit the required finite full reads silently; explain any read limit.
'''
(V/'review-prompt03.txt').open('x').write(prompt)
r=subprocess.run(['/Users/antoinecyr/.local/bin/claude','--model','claude-opus-5-5','--effort','high','--permission-mode','plan','--tools','Read,Glob,Grep','--strict-mcp-config','--no-session-persistence','--output-format','json','--print',prompt],capture_output=True,text=True,timeout=900)
(V/'opus55-final-call14-review03.json').open('x').write(r.stdout);(V/'opus55-final-call14-review03.stderr').open('x').write(r.stderr)
assert all(sha(Path(p))==h for p,h in before.items());assert r.returncode==0,r.stderr
d=json.loads(r.stdout);assert d.get('is_error') is False and 'claude-opus-5-5' in d.get('modelUsage',{})
print(json.dumps(dict(returncode=r.returncode,inputs_unchanged=True,result=d.get('result','')[:28000])))
