-- GENERATED by generate_full_block_proofs.py; edit maintained template.
import ShielddSecurity.TransferPoseidonWidth3Call08ConsumerChecks06
import ShielddSecurity.TransferPoseidonWidth3Call08CoverageChecks06
import ShielddSecurity.TransferPoseidonWidth3Call08ProgramChecks06
import ShielddSecurity.PoseidonCallComposition04
set_option maxHeartbeats 900000
set_option maxRecDepth 8192
namespace ShielddSecurity.TransferPoseidonWidth3Call08R48Proof
open Compiler CompilerIndexed01 CompilerCompletion Poseidon PoseidonIndexedFolded02 ShielddSecurity.TransferPoseidonWidth3Call08Shared01 ShielddSecurity.TransferPoseidonWidth3Call08R48 ShielddSecurity.TransferPoseidonWidth3Call08R48Checks
theorem column_cases (column : Fin 3) : column=0 ∨ column=1 ∨ column=2 := by
  have bound := column.isLt
  simp only [Fin.ext_iff]
  omega
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonWidth3Call08R48Proof.column_cases
#print axioms ShielddSecurity.TransferPoseidonWidth3Call08R48Proof.column_cases
theorem round_checked : checkRound p copy originalRows parameters 48 before shifted transformed after fifthHints=true := by
  simp only [checkRound,Bool.and_eq_true]
  constructor
  · apply List.all_eq_true.mpr
    intro column _
    rcases column_cases column with rfl|rfl|rfl
    · exact column0_checked
    · exact column1_checked
    · exact column2_checked
  · apply List.all_eq_true.mpr
    intro column _
    simp only [decide_eq_true_eq]
    rcases column_cases column with rfl|rfl|rfl
    · exact mix0_checked
    · exact mix1_checked
    · exact mix2_checked

set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonWidth3Call08R48Proof.round_checked
#print axioms ShielddSecurity.TransferPoseidonWidth3Call08R48Proof.round_checked
theorem round_certificate : RoundCertificate p (unoutlineRows copy originalRows.toList) parameters 48 before shifted transformed after :=
  checkRound_sound p copy originalRows parameters 48 before shifted transformed after fifthHints round_checked
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonWidth3Call08R48Proof.round_certificate
#print axioms ShielddSecurity.TransferPoseidonWidth3Call08R48Proof.round_certificate
theorem reverse_checked : checkOriginalCoverage p copy arithmeticRows emittedArith rowMapping=true := by
  simp only [checkOriginalCoverage,Bool.and_eq_true]
  constructor
  · decide +kernel
  · apply List.all_eq_true.mpr
    intro index member
    have bound := List.mem_range.mp member
    rw [rows_shape.1] at bound
    have cases : index=0 ∨ index=1 ∨ index=2 ∨ index=3 := by omega
    rcases cases with rfl|rfl|rfl|rfl
    · exact row0_checked
    · exact row1_checked
    · exact row2_checked
    · exact row3_checked

set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonWidth3Call08R48Proof.reverse_checked
#print axioms ShielddSecurity.TransferPoseidonWidth3Call08R48Proof.reverse_checked
theorem reverse_coverage : ∀ actual∈arithmeticRows.toList,∃ expected∈emitted materializedSteps,canonical p (unoutline copy actual.a)=canonical p expected.a ∧ canonical p (unoutline copy actual.b)=canonical p expected.b := by
  simpa [emittedArith] using checkOriginalCoverage_sound p copy arithmeticRows emittedArith rowMapping reverse_checked
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonWidth3Call08R48Proof.reverse_coverage
#print axioms ShielddSecurity.TransferPoseidonWidth3Call08R48Proof.reverse_coverage
theorem ordered : Topological [0,copy] [] materializedSteps := CompilerOrder.checked_order _ _ _ ordered_checked
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonWidth3Call08R48Proof.ordered
#print axioms ShielddSecurity.TransferPoseidonWidth3Call08R48Proof.ordered
theorem write_bounds (column : Nat) (member : column∈PoseidonCompletion.writes materializedSteps) : 24944≤column ∧ column≤24947 :=
  of_decide_eq_true (List.all_eq_true.mp writes_checked column member)
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonWidth3Call08R48Proof.write_bounds
#print axioms ShielddSecurity.TransferPoseidonWidth3Call08R48Proof.write_bounds
theorem emitted_support (row : Row) (member : row∈emitted materializedSteps) (term : Nat × Int) (present : term∈row.a++row.b) : term.1<24948 :=
  of_decide_eq_true (List.all_eq_true.mp (List.all_eq_true.mp emitted_support_checked row member) term present)
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonWidth3Call08R48Proof.emitted_support
#print axioms ShielddSecurity.TransferPoseidonWidth3Call08R48Proof.emitted_support
variable {F : Type} [Field F] [CharP F p]
theorem legal (base : Nat → F) : Legal base materializedSteps := by
  simp [materializedSteps,Legal,Step.Legal]
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonWidth3Call08R48Proof.legal
#print axioms ShielddSecurity.TransferPoseidonWidth3Call08R48Proof.legal
theorem arbitrary_round_sound (rho : Nat → F) (one : rho 0=1) (four : (4:F)≠0) (satisfied : Satisfies rho originalRows.toList) :
    (fun column => eval rho (after column))=Poseidon.round (castParameters parameters) 48 (fun column => eval rho (before column)) := by
  have unoutlined := unoutline_rows_sound rho copy originalRows.toList satisfied (checkRowAt_sound p originalRows 4 _ copy_checked)
  exact round_certificate_sound rho (unoutlineRows copy originalRows.toList) parameters 48 before shifted transformed after one four unoutlined round_certificate
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonWidth3Call08R48Proof.arbitrary_round_sound
#print axioms ShielddSecurity.TransferPoseidonWidth3Call08R48Proof.arbitrary_round_sound
end ShielddSecurity.TransferPoseidonWidth3Call08R48Proof
namespace ShielddSecurity.TransferPoseidonWidth3Call08R49Proof
open Compiler CompilerIndexed01 CompilerCompletion Poseidon PoseidonIndexedFolded02 ShielddSecurity.TransferPoseidonWidth3Call08Shared01 ShielddSecurity.TransferPoseidonWidth3Call08R49 ShielddSecurity.TransferPoseidonWidth3Call08R49Checks
theorem column_cases (column : Fin 3) : column=0 ∨ column=1 ∨ column=2 := by
  have bound := column.isLt
  simp only [Fin.ext_iff]
  omega
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonWidth3Call08R49Proof.column_cases
#print axioms ShielddSecurity.TransferPoseidonWidth3Call08R49Proof.column_cases
theorem round_checked : checkRound p copy originalRows parameters 49 before shifted transformed after fifthHints=true := by
  simp only [checkRound,Bool.and_eq_true]
  constructor
  · apply List.all_eq_true.mpr
    intro column _
    rcases column_cases column with rfl|rfl|rfl
    · exact column0_checked
    · exact column1_checked
    · exact column2_checked
  · apply List.all_eq_true.mpr
    intro column _
    simp only [decide_eq_true_eq]
    rcases column_cases column with rfl|rfl|rfl
    · exact mix0_checked
    · exact mix1_checked
    · exact mix2_checked

set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonWidth3Call08R49Proof.round_checked
#print axioms ShielddSecurity.TransferPoseidonWidth3Call08R49Proof.round_checked
theorem round_certificate : RoundCertificate p (unoutlineRows copy originalRows.toList) parameters 49 before shifted transformed after :=
  checkRound_sound p copy originalRows parameters 49 before shifted transformed after fifthHints round_checked
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonWidth3Call08R49Proof.round_certificate
#print axioms ShielddSecurity.TransferPoseidonWidth3Call08R49Proof.round_certificate
theorem reverse_checked : checkOriginalCoverage p copy arithmeticRows emittedArith rowMapping=true := by
  simp only [checkOriginalCoverage,Bool.and_eq_true]
  constructor
  · decide +kernel
  · apply List.all_eq_true.mpr
    intro index member
    have bound := List.mem_range.mp member
    rw [rows_shape.1] at bound
    have cases : index=0 ∨ index=1 ∨ index=2 ∨ index=3 := by omega
    rcases cases with rfl|rfl|rfl|rfl
    · exact row0_checked
    · exact row1_checked
    · exact row2_checked
    · exact row3_checked

set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonWidth3Call08R49Proof.reverse_checked
#print axioms ShielddSecurity.TransferPoseidonWidth3Call08R49Proof.reverse_checked
theorem reverse_coverage : ∀ actual∈arithmeticRows.toList,∃ expected∈emitted materializedSteps,canonical p (unoutline copy actual.a)=canonical p expected.a ∧ canonical p (unoutline copy actual.b)=canonical p expected.b := by
  simpa [emittedArith] using checkOriginalCoverage_sound p copy arithmeticRows emittedArith rowMapping reverse_checked
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonWidth3Call08R49Proof.reverse_coverage
#print axioms ShielddSecurity.TransferPoseidonWidth3Call08R49Proof.reverse_coverage
theorem ordered : Topological [0,copy] [] materializedSteps := CompilerOrder.checked_order _ _ _ ordered_checked
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonWidth3Call08R49Proof.ordered
#print axioms ShielddSecurity.TransferPoseidonWidth3Call08R49Proof.ordered
theorem write_bounds (column : Nat) (member : column∈PoseidonCompletion.writes materializedSteps) : 24948≤column ∧ column≤24951 :=
  of_decide_eq_true (List.all_eq_true.mp writes_checked column member)
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonWidth3Call08R49Proof.write_bounds
#print axioms ShielddSecurity.TransferPoseidonWidth3Call08R49Proof.write_bounds
theorem emitted_support (row : Row) (member : row∈emitted materializedSteps) (term : Nat × Int) (present : term∈row.a++row.b) : term.1<24952 :=
  of_decide_eq_true (List.all_eq_true.mp (List.all_eq_true.mp emitted_support_checked row member) term present)
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonWidth3Call08R49Proof.emitted_support
#print axioms ShielddSecurity.TransferPoseidonWidth3Call08R49Proof.emitted_support
variable {F : Type} [Field F] [CharP F p]
theorem legal (base : Nat → F) : Legal base materializedSteps := by
  simp [materializedSteps,Legal,Step.Legal]
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonWidth3Call08R49Proof.legal
#print axioms ShielddSecurity.TransferPoseidonWidth3Call08R49Proof.legal
theorem arbitrary_round_sound (rho : Nat → F) (one : rho 0=1) (four : (4:F)≠0) (satisfied : Satisfies rho originalRows.toList) :
    (fun column => eval rho (after column))=Poseidon.round (castParameters parameters) 49 (fun column => eval rho (before column)) := by
  have unoutlined := unoutline_rows_sound rho copy originalRows.toList satisfied (checkRowAt_sound p originalRows 4 _ copy_checked)
  exact round_certificate_sound rho (unoutlineRows copy originalRows.toList) parameters 49 before shifted transformed after one four unoutlined round_certificate
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonWidth3Call08R49Proof.arbitrary_round_sound
#print axioms ShielddSecurity.TransferPoseidonWidth3Call08R49Proof.arbitrary_round_sound
end ShielddSecurity.TransferPoseidonWidth3Call08R49Proof
namespace ShielddSecurity.TransferPoseidonWidth3Call08R50Proof
open Compiler CompilerIndexed01 CompilerCompletion Poseidon PoseidonIndexedFolded02 ShielddSecurity.TransferPoseidonWidth3Call08Shared01 ShielddSecurity.TransferPoseidonWidth3Call08R50 ShielddSecurity.TransferPoseidonWidth3Call08R50Checks
theorem column_cases (column : Fin 3) : column=0 ∨ column=1 ∨ column=2 := by
  have bound := column.isLt
  simp only [Fin.ext_iff]
  omega
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonWidth3Call08R50Proof.column_cases
#print axioms ShielddSecurity.TransferPoseidonWidth3Call08R50Proof.column_cases
theorem round_checked : checkRound p copy originalRows parameters 50 before shifted transformed after fifthHints=true := by
  simp only [checkRound,Bool.and_eq_true]
  constructor
  · apply List.all_eq_true.mpr
    intro column _
    rcases column_cases column with rfl|rfl|rfl
    · exact column0_checked
    · exact column1_checked
    · exact column2_checked
  · apply List.all_eq_true.mpr
    intro column _
    simp only [decide_eq_true_eq]
    rcases column_cases column with rfl|rfl|rfl
    · exact mix0_checked
    · exact mix1_checked
    · exact mix2_checked

set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonWidth3Call08R50Proof.round_checked
#print axioms ShielddSecurity.TransferPoseidonWidth3Call08R50Proof.round_checked
theorem round_certificate : RoundCertificate p (unoutlineRows copy originalRows.toList) parameters 50 before shifted transformed after :=
  checkRound_sound p copy originalRows parameters 50 before shifted transformed after fifthHints round_checked
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonWidth3Call08R50Proof.round_certificate
#print axioms ShielddSecurity.TransferPoseidonWidth3Call08R50Proof.round_certificate
theorem reverse_checked : checkOriginalCoverage p copy arithmeticRows emittedArith rowMapping=true := by
  simp only [checkOriginalCoverage,Bool.and_eq_true]
  constructor
  · decide +kernel
  · apply List.all_eq_true.mpr
    intro index member
    have bound := List.mem_range.mp member
    rw [rows_shape.1] at bound
    have cases : index=0 ∨ index=1 ∨ index=2 ∨ index=3 := by omega
    rcases cases with rfl|rfl|rfl|rfl
    · exact row0_checked
    · exact row1_checked
    · exact row2_checked
    · exact row3_checked

set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonWidth3Call08R50Proof.reverse_checked
#print axioms ShielddSecurity.TransferPoseidonWidth3Call08R50Proof.reverse_checked
theorem reverse_coverage : ∀ actual∈arithmeticRows.toList,∃ expected∈emitted materializedSteps,canonical p (unoutline copy actual.a)=canonical p expected.a ∧ canonical p (unoutline copy actual.b)=canonical p expected.b := by
  simpa [emittedArith] using checkOriginalCoverage_sound p copy arithmeticRows emittedArith rowMapping reverse_checked
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonWidth3Call08R50Proof.reverse_coverage
#print axioms ShielddSecurity.TransferPoseidonWidth3Call08R50Proof.reverse_coverage
theorem ordered : Topological [0,copy] [] materializedSteps := CompilerOrder.checked_order _ _ _ ordered_checked
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonWidth3Call08R50Proof.ordered
#print axioms ShielddSecurity.TransferPoseidonWidth3Call08R50Proof.ordered
theorem write_bounds (column : Nat) (member : column∈PoseidonCompletion.writes materializedSteps) : 24952≤column ∧ column≤24955 :=
  of_decide_eq_true (List.all_eq_true.mp writes_checked column member)
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonWidth3Call08R50Proof.write_bounds
#print axioms ShielddSecurity.TransferPoseidonWidth3Call08R50Proof.write_bounds
theorem emitted_support (row : Row) (member : row∈emitted materializedSteps) (term : Nat × Int) (present : term∈row.a++row.b) : term.1<24956 :=
  of_decide_eq_true (List.all_eq_true.mp (List.all_eq_true.mp emitted_support_checked row member) term present)
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonWidth3Call08R50Proof.emitted_support
#print axioms ShielddSecurity.TransferPoseidonWidth3Call08R50Proof.emitted_support
variable {F : Type} [Field F] [CharP F p]
theorem legal (base : Nat → F) : Legal base materializedSteps := by
  simp [materializedSteps,Legal,Step.Legal]
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonWidth3Call08R50Proof.legal
#print axioms ShielddSecurity.TransferPoseidonWidth3Call08R50Proof.legal
theorem arbitrary_round_sound (rho : Nat → F) (one : rho 0=1) (four : (4:F)≠0) (satisfied : Satisfies rho originalRows.toList) :
    (fun column => eval rho (after column))=Poseidon.round (castParameters parameters) 50 (fun column => eval rho (before column)) := by
  have unoutlined := unoutline_rows_sound rho copy originalRows.toList satisfied (checkRowAt_sound p originalRows 4 _ copy_checked)
  exact round_certificate_sound rho (unoutlineRows copy originalRows.toList) parameters 50 before shifted transformed after one four unoutlined round_certificate
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonWidth3Call08R50Proof.arbitrary_round_sound
#print axioms ShielddSecurity.TransferPoseidonWidth3Call08R50Proof.arbitrary_round_sound
end ShielddSecurity.TransferPoseidonWidth3Call08R50Proof
namespace ShielddSecurity.TransferPoseidonWidth3Call08R51Proof
open Compiler CompilerIndexed01 CompilerCompletion Poseidon PoseidonIndexedFolded02 ShielddSecurity.TransferPoseidonWidth3Call08Shared01 ShielddSecurity.TransferPoseidonWidth3Call08R51 ShielddSecurity.TransferPoseidonWidth3Call08R51Checks
theorem column_cases (column : Fin 3) : column=0 ∨ column=1 ∨ column=2 := by
  have bound := column.isLt
  simp only [Fin.ext_iff]
  omega
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonWidth3Call08R51Proof.column_cases
#print axioms ShielddSecurity.TransferPoseidonWidth3Call08R51Proof.column_cases
theorem round_checked : checkRound p copy originalRows parameters 51 before shifted transformed after fifthHints=true := by
  simp only [checkRound,Bool.and_eq_true]
  constructor
  · apply List.all_eq_true.mpr
    intro column _
    rcases column_cases column with rfl|rfl|rfl
    · exact column0_checked
    · exact column1_checked
    · exact column2_checked
  · apply List.all_eq_true.mpr
    intro column _
    simp only [decide_eq_true_eq]
    rcases column_cases column with rfl|rfl|rfl
    · exact mix0_checked
    · exact mix1_checked
    · exact mix2_checked

set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonWidth3Call08R51Proof.round_checked
#print axioms ShielddSecurity.TransferPoseidonWidth3Call08R51Proof.round_checked
theorem round_certificate : RoundCertificate p (unoutlineRows copy originalRows.toList) parameters 51 before shifted transformed after :=
  checkRound_sound p copy originalRows parameters 51 before shifted transformed after fifthHints round_checked
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonWidth3Call08R51Proof.round_certificate
#print axioms ShielddSecurity.TransferPoseidonWidth3Call08R51Proof.round_certificate
theorem reverse_checked : checkOriginalCoverage p copy arithmeticRows emittedArith rowMapping=true := by
  simp only [checkOriginalCoverage,Bool.and_eq_true]
  constructor
  · decide +kernel
  · apply List.all_eq_true.mpr
    intro index member
    have bound := List.mem_range.mp member
    rw [rows_shape.1] at bound
    have cases : index=0 ∨ index=1 ∨ index=2 ∨ index=3 := by omega
    rcases cases with rfl|rfl|rfl|rfl
    · exact row0_checked
    · exact row1_checked
    · exact row2_checked
    · exact row3_checked

set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonWidth3Call08R51Proof.reverse_checked
#print axioms ShielddSecurity.TransferPoseidonWidth3Call08R51Proof.reverse_checked
theorem reverse_coverage : ∀ actual∈arithmeticRows.toList,∃ expected∈emitted materializedSteps,canonical p (unoutline copy actual.a)=canonical p expected.a ∧ canonical p (unoutline copy actual.b)=canonical p expected.b := by
  simpa [emittedArith] using checkOriginalCoverage_sound p copy arithmeticRows emittedArith rowMapping reverse_checked
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonWidth3Call08R51Proof.reverse_coverage
#print axioms ShielddSecurity.TransferPoseidonWidth3Call08R51Proof.reverse_coverage
theorem ordered : Topological [0,copy] [] materializedSteps := CompilerOrder.checked_order _ _ _ ordered_checked
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonWidth3Call08R51Proof.ordered
#print axioms ShielddSecurity.TransferPoseidonWidth3Call08R51Proof.ordered
theorem write_bounds (column : Nat) (member : column∈PoseidonCompletion.writes materializedSteps) : 24956≤column ∧ column≤24959 :=
  of_decide_eq_true (List.all_eq_true.mp writes_checked column member)
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonWidth3Call08R51Proof.write_bounds
#print axioms ShielddSecurity.TransferPoseidonWidth3Call08R51Proof.write_bounds
theorem emitted_support (row : Row) (member : row∈emitted materializedSteps) (term : Nat × Int) (present : term∈row.a++row.b) : term.1<24960 :=
  of_decide_eq_true (List.all_eq_true.mp (List.all_eq_true.mp emitted_support_checked row member) term present)
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonWidth3Call08R51Proof.emitted_support
#print axioms ShielddSecurity.TransferPoseidonWidth3Call08R51Proof.emitted_support
variable {F : Type} [Field F] [CharP F p]
theorem legal (base : Nat → F) : Legal base materializedSteps := by
  simp [materializedSteps,Legal,Step.Legal]
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonWidth3Call08R51Proof.legal
#print axioms ShielddSecurity.TransferPoseidonWidth3Call08R51Proof.legal
theorem arbitrary_round_sound (rho : Nat → F) (one : rho 0=1) (four : (4:F)≠0) (satisfied : Satisfies rho originalRows.toList) :
    (fun column => eval rho (after column))=Poseidon.round (castParameters parameters) 51 (fun column => eval rho (before column)) := by
  have unoutlined := unoutline_rows_sound rho copy originalRows.toList satisfied (checkRowAt_sound p originalRows 4 _ copy_checked)
  exact round_certificate_sound rho (unoutlineRows copy originalRows.toList) parameters 51 before shifted transformed after one four unoutlined round_certificate
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonWidth3Call08R51Proof.arbitrary_round_sound
#print axioms ShielddSecurity.TransferPoseidonWidth3Call08R51Proof.arbitrary_round_sound
end ShielddSecurity.TransferPoseidonWidth3Call08R51Proof
namespace ShielddSecurity.TransferPoseidonWidth3Call08R52Proof
open Compiler CompilerIndexed01 CompilerCompletion Poseidon PoseidonIndexedFolded02 ShielddSecurity.TransferPoseidonWidth3Call08Shared01 ShielddSecurity.TransferPoseidonWidth3Call08R52 ShielddSecurity.TransferPoseidonWidth3Call08R52Checks
theorem column_cases (column : Fin 3) : column=0 ∨ column=1 ∨ column=2 := by
  have bound := column.isLt
  simp only [Fin.ext_iff]
  omega
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonWidth3Call08R52Proof.column_cases
#print axioms ShielddSecurity.TransferPoseidonWidth3Call08R52Proof.column_cases
theorem round_checked : checkRound p copy originalRows parameters 52 before shifted transformed after fifthHints=true := by
  simp only [checkRound,Bool.and_eq_true]
  constructor
  · apply List.all_eq_true.mpr
    intro column _
    rcases column_cases column with rfl|rfl|rfl
    · exact column0_checked
    · exact column1_checked
    · exact column2_checked
  · apply List.all_eq_true.mpr
    intro column _
    simp only [decide_eq_true_eq]
    rcases column_cases column with rfl|rfl|rfl
    · exact mix0_checked
    · exact mix1_checked
    · exact mix2_checked

set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonWidth3Call08R52Proof.round_checked
#print axioms ShielddSecurity.TransferPoseidonWidth3Call08R52Proof.round_checked
theorem round_certificate : RoundCertificate p (unoutlineRows copy originalRows.toList) parameters 52 before shifted transformed after :=
  checkRound_sound p copy originalRows parameters 52 before shifted transformed after fifthHints round_checked
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonWidth3Call08R52Proof.round_certificate
#print axioms ShielddSecurity.TransferPoseidonWidth3Call08R52Proof.round_certificate
theorem reverse_checked : checkOriginalCoverage p copy arithmeticRows emittedArith rowMapping=true := by
  simp only [checkOriginalCoverage,Bool.and_eq_true]
  constructor
  · decide +kernel
  · apply List.all_eq_true.mpr
    intro index member
    have bound := List.mem_range.mp member
    rw [rows_shape.1] at bound
    have cases : index=0 ∨ index=1 ∨ index=2 ∨ index=3 := by omega
    rcases cases with rfl|rfl|rfl|rfl
    · exact row0_checked
    · exact row1_checked
    · exact row2_checked
    · exact row3_checked

set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonWidth3Call08R52Proof.reverse_checked
#print axioms ShielddSecurity.TransferPoseidonWidth3Call08R52Proof.reverse_checked
theorem reverse_coverage : ∀ actual∈arithmeticRows.toList,∃ expected∈emitted materializedSteps,canonical p (unoutline copy actual.a)=canonical p expected.a ∧ canonical p (unoutline copy actual.b)=canonical p expected.b := by
  simpa [emittedArith] using checkOriginalCoverage_sound p copy arithmeticRows emittedArith rowMapping reverse_checked
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonWidth3Call08R52Proof.reverse_coverage
#print axioms ShielddSecurity.TransferPoseidonWidth3Call08R52Proof.reverse_coverage
theorem ordered : Topological [0,copy] [] materializedSteps := CompilerOrder.checked_order _ _ _ ordered_checked
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonWidth3Call08R52Proof.ordered
#print axioms ShielddSecurity.TransferPoseidonWidth3Call08R52Proof.ordered
theorem write_bounds (column : Nat) (member : column∈PoseidonCompletion.writes materializedSteps) : 24960≤column ∧ column≤24963 :=
  of_decide_eq_true (List.all_eq_true.mp writes_checked column member)
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonWidth3Call08R52Proof.write_bounds
#print axioms ShielddSecurity.TransferPoseidonWidth3Call08R52Proof.write_bounds
theorem emitted_support (row : Row) (member : row∈emitted materializedSteps) (term : Nat × Int) (present : term∈row.a++row.b) : term.1<24964 :=
  of_decide_eq_true (List.all_eq_true.mp (List.all_eq_true.mp emitted_support_checked row member) term present)
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonWidth3Call08R52Proof.emitted_support
#print axioms ShielddSecurity.TransferPoseidonWidth3Call08R52Proof.emitted_support
variable {F : Type} [Field F] [CharP F p]
theorem legal (base : Nat → F) : Legal base materializedSteps := by
  simp [materializedSteps,Legal,Step.Legal]
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonWidth3Call08R52Proof.legal
#print axioms ShielddSecurity.TransferPoseidonWidth3Call08R52Proof.legal
theorem arbitrary_round_sound (rho : Nat → F) (one : rho 0=1) (four : (4:F)≠0) (satisfied : Satisfies rho originalRows.toList) :
    (fun column => eval rho (after column))=Poseidon.round (castParameters parameters) 52 (fun column => eval rho (before column)) := by
  have unoutlined := unoutline_rows_sound rho copy originalRows.toList satisfied (checkRowAt_sound p originalRows 4 _ copy_checked)
  exact round_certificate_sound rho (unoutlineRows copy originalRows.toList) parameters 52 before shifted transformed after one four unoutlined round_certificate
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonWidth3Call08R52Proof.arbitrary_round_sound
#print axioms ShielddSecurity.TransferPoseidonWidth3Call08R52Proof.arbitrary_round_sound
end ShielddSecurity.TransferPoseidonWidth3Call08R52Proof
namespace ShielddSecurity.TransferPoseidonWidth3Call08R53Proof
open Compiler CompilerIndexed01 CompilerCompletion Poseidon PoseidonIndexedFolded02 ShielddSecurity.TransferPoseidonWidth3Call08Shared01 ShielddSecurity.TransferPoseidonWidth3Call08R53 ShielddSecurity.TransferPoseidonWidth3Call08R53Checks
theorem column_cases (column : Fin 3) : column=0 ∨ column=1 ∨ column=2 := by
  have bound := column.isLt
  simp only [Fin.ext_iff]
  omega
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonWidth3Call08R53Proof.column_cases
#print axioms ShielddSecurity.TransferPoseidonWidth3Call08R53Proof.column_cases
theorem round_checked : checkRound p copy originalRows parameters 53 before shifted transformed after fifthHints=true := by
  simp only [checkRound,Bool.and_eq_true]
  constructor
  · apply List.all_eq_true.mpr
    intro column _
    rcases column_cases column with rfl|rfl|rfl
    · exact column0_checked
    · exact column1_checked
    · exact column2_checked
  · apply List.all_eq_true.mpr
    intro column _
    simp only [decide_eq_true_eq]
    rcases column_cases column with rfl|rfl|rfl
    · exact mix0_checked
    · exact mix1_checked
    · exact mix2_checked

set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonWidth3Call08R53Proof.round_checked
#print axioms ShielddSecurity.TransferPoseidonWidth3Call08R53Proof.round_checked
theorem round_certificate : RoundCertificate p (unoutlineRows copy originalRows.toList) parameters 53 before shifted transformed after :=
  checkRound_sound p copy originalRows parameters 53 before shifted transformed after fifthHints round_checked
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonWidth3Call08R53Proof.round_certificate
#print axioms ShielddSecurity.TransferPoseidonWidth3Call08R53Proof.round_certificate
theorem reverse_checked : checkOriginalCoverage p copy arithmeticRows emittedArith rowMapping=true := by
  simp only [checkOriginalCoverage,Bool.and_eq_true]
  constructor
  · decide +kernel
  · apply List.all_eq_true.mpr
    intro index member
    have bound := List.mem_range.mp member
    rw [rows_shape.1] at bound
    have cases : index=0 ∨ index=1 ∨ index=2 ∨ index=3 := by omega
    rcases cases with rfl|rfl|rfl|rfl
    · exact row0_checked
    · exact row1_checked
    · exact row2_checked
    · exact row3_checked

set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonWidth3Call08R53Proof.reverse_checked
#print axioms ShielddSecurity.TransferPoseidonWidth3Call08R53Proof.reverse_checked
theorem reverse_coverage : ∀ actual∈arithmeticRows.toList,∃ expected∈emitted materializedSteps,canonical p (unoutline copy actual.a)=canonical p expected.a ∧ canonical p (unoutline copy actual.b)=canonical p expected.b := by
  simpa [emittedArith] using checkOriginalCoverage_sound p copy arithmeticRows emittedArith rowMapping reverse_checked
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonWidth3Call08R53Proof.reverse_coverage
#print axioms ShielddSecurity.TransferPoseidonWidth3Call08R53Proof.reverse_coverage
theorem ordered : Topological [0,copy] [] materializedSteps := CompilerOrder.checked_order _ _ _ ordered_checked
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonWidth3Call08R53Proof.ordered
#print axioms ShielddSecurity.TransferPoseidonWidth3Call08R53Proof.ordered
theorem write_bounds (column : Nat) (member : column∈PoseidonCompletion.writes materializedSteps) : 24964≤column ∧ column≤24967 :=
  of_decide_eq_true (List.all_eq_true.mp writes_checked column member)
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonWidth3Call08R53Proof.write_bounds
#print axioms ShielddSecurity.TransferPoseidonWidth3Call08R53Proof.write_bounds
theorem emitted_support (row : Row) (member : row∈emitted materializedSteps) (term : Nat × Int) (present : term∈row.a++row.b) : term.1<24968 :=
  of_decide_eq_true (List.all_eq_true.mp (List.all_eq_true.mp emitted_support_checked row member) term present)
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonWidth3Call08R53Proof.emitted_support
#print axioms ShielddSecurity.TransferPoseidonWidth3Call08R53Proof.emitted_support
variable {F : Type} [Field F] [CharP F p]
theorem legal (base : Nat → F) : Legal base materializedSteps := by
  simp [materializedSteps,Legal,Step.Legal]
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonWidth3Call08R53Proof.legal
#print axioms ShielddSecurity.TransferPoseidonWidth3Call08R53Proof.legal
theorem arbitrary_round_sound (rho : Nat → F) (one : rho 0=1) (four : (4:F)≠0) (satisfied : Satisfies rho originalRows.toList) :
    (fun column => eval rho (after column))=Poseidon.round (castParameters parameters) 53 (fun column => eval rho (before column)) := by
  have unoutlined := unoutline_rows_sound rho copy originalRows.toList satisfied (checkRowAt_sound p originalRows 4 _ copy_checked)
  exact round_certificate_sound rho (unoutlineRows copy originalRows.toList) parameters 53 before shifted transformed after one four unoutlined round_certificate
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonWidth3Call08R53Proof.arbitrary_round_sound
#print axioms ShielddSecurity.TransferPoseidonWidth3Call08R53Proof.arbitrary_round_sound
end ShielddSecurity.TransferPoseidonWidth3Call08R53Proof
namespace ShielddSecurity.TransferPoseidonWidth3Call08R54Proof
open Compiler CompilerIndexed01 CompilerCompletion Poseidon PoseidonIndexedFolded02 ShielddSecurity.TransferPoseidonWidth3Call08Shared01 ShielddSecurity.TransferPoseidonWidth3Call08R54 ShielddSecurity.TransferPoseidonWidth3Call08R54Checks
theorem column_cases (column : Fin 3) : column=0 ∨ column=1 ∨ column=2 := by
  have bound := column.isLt
  simp only [Fin.ext_iff]
  omega
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonWidth3Call08R54Proof.column_cases
#print axioms ShielddSecurity.TransferPoseidonWidth3Call08R54Proof.column_cases
theorem round_checked : checkRound p copy originalRows parameters 54 before shifted transformed after fifthHints=true := by
  simp only [checkRound,Bool.and_eq_true]
  constructor
  · apply List.all_eq_true.mpr
    intro column _
    rcases column_cases column with rfl|rfl|rfl
    · exact column0_checked
    · exact column1_checked
    · exact column2_checked
  · apply List.all_eq_true.mpr
    intro column _
    simp only [decide_eq_true_eq]
    rcases column_cases column with rfl|rfl|rfl
    · exact mix0_checked
    · exact mix1_checked
    · exact mix2_checked

set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonWidth3Call08R54Proof.round_checked
#print axioms ShielddSecurity.TransferPoseidonWidth3Call08R54Proof.round_checked
theorem round_certificate : RoundCertificate p (unoutlineRows copy originalRows.toList) parameters 54 before shifted transformed after :=
  checkRound_sound p copy originalRows parameters 54 before shifted transformed after fifthHints round_checked
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonWidth3Call08R54Proof.round_certificate
#print axioms ShielddSecurity.TransferPoseidonWidth3Call08R54Proof.round_certificate
theorem reverse_checked : checkOriginalCoverage p copy arithmeticRows emittedArith rowMapping=true := by
  simp only [checkOriginalCoverage,Bool.and_eq_true]
  constructor
  · decide +kernel
  · apply List.all_eq_true.mpr
    intro index member
    have bound := List.mem_range.mp member
    rw [rows_shape.1] at bound
    have cases : index=0 ∨ index=1 ∨ index=2 ∨ index=3 := by omega
    rcases cases with rfl|rfl|rfl|rfl
    · exact row0_checked
    · exact row1_checked
    · exact row2_checked
    · exact row3_checked

set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonWidth3Call08R54Proof.reverse_checked
#print axioms ShielddSecurity.TransferPoseidonWidth3Call08R54Proof.reverse_checked
theorem reverse_coverage : ∀ actual∈arithmeticRows.toList,∃ expected∈emitted materializedSteps,canonical p (unoutline copy actual.a)=canonical p expected.a ∧ canonical p (unoutline copy actual.b)=canonical p expected.b := by
  simpa [emittedArith] using checkOriginalCoverage_sound p copy arithmeticRows emittedArith rowMapping reverse_checked
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonWidth3Call08R54Proof.reverse_coverage
#print axioms ShielddSecurity.TransferPoseidonWidth3Call08R54Proof.reverse_coverage
theorem ordered : Topological [0,copy] [] materializedSteps := CompilerOrder.checked_order _ _ _ ordered_checked
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonWidth3Call08R54Proof.ordered
#print axioms ShielddSecurity.TransferPoseidonWidth3Call08R54Proof.ordered
theorem write_bounds (column : Nat) (member : column∈PoseidonCompletion.writes materializedSteps) : 24968≤column ∧ column≤24971 :=
  of_decide_eq_true (List.all_eq_true.mp writes_checked column member)
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonWidth3Call08R54Proof.write_bounds
#print axioms ShielddSecurity.TransferPoseidonWidth3Call08R54Proof.write_bounds
theorem emitted_support (row : Row) (member : row∈emitted materializedSteps) (term : Nat × Int) (present : term∈row.a++row.b) : term.1<24972 :=
  of_decide_eq_true (List.all_eq_true.mp (List.all_eq_true.mp emitted_support_checked row member) term present)
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonWidth3Call08R54Proof.emitted_support
#print axioms ShielddSecurity.TransferPoseidonWidth3Call08R54Proof.emitted_support
variable {F : Type} [Field F] [CharP F p]
theorem legal (base : Nat → F) : Legal base materializedSteps := by
  simp [materializedSteps,Legal,Step.Legal]
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonWidth3Call08R54Proof.legal
#print axioms ShielddSecurity.TransferPoseidonWidth3Call08R54Proof.legal
theorem arbitrary_round_sound (rho : Nat → F) (one : rho 0=1) (four : (4:F)≠0) (satisfied : Satisfies rho originalRows.toList) :
    (fun column => eval rho (after column))=Poseidon.round (castParameters parameters) 54 (fun column => eval rho (before column)) := by
  have unoutlined := unoutline_rows_sound rho copy originalRows.toList satisfied (checkRowAt_sound p originalRows 4 _ copy_checked)
  exact round_certificate_sound rho (unoutlineRows copy originalRows.toList) parameters 54 before shifted transformed after one four unoutlined round_certificate
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonWidth3Call08R54Proof.arbitrary_round_sound
#print axioms ShielddSecurity.TransferPoseidonWidth3Call08R54Proof.arbitrary_round_sound
end ShielddSecurity.TransferPoseidonWidth3Call08R54Proof
namespace ShielddSecurity.TransferPoseidonWidth3Call08R55Proof
open Compiler CompilerIndexed01 CompilerCompletion Poseidon PoseidonIndexedFolded02 ShielddSecurity.TransferPoseidonWidth3Call08Shared01 ShielddSecurity.TransferPoseidonWidth3Call08R55 ShielddSecurity.TransferPoseidonWidth3Call08R55Checks
theorem column_cases (column : Fin 3) : column=0 ∨ column=1 ∨ column=2 := by
  have bound := column.isLt
  simp only [Fin.ext_iff]
  omega
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonWidth3Call08R55Proof.column_cases
#print axioms ShielddSecurity.TransferPoseidonWidth3Call08R55Proof.column_cases
theorem round_checked : checkRound p copy originalRows parameters 55 before shifted transformed after fifthHints=true := by
  simp only [checkRound,Bool.and_eq_true]
  constructor
  · apply List.all_eq_true.mpr
    intro column _
    rcases column_cases column with rfl|rfl|rfl
    · exact column0_checked
    · exact column1_checked
    · exact column2_checked
  · apply List.all_eq_true.mpr
    intro column _
    simp only [decide_eq_true_eq]
    rcases column_cases column with rfl|rfl|rfl
    · exact mix0_checked
    · exact mix1_checked
    · exact mix2_checked

set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonWidth3Call08R55Proof.round_checked
#print axioms ShielddSecurity.TransferPoseidonWidth3Call08R55Proof.round_checked
theorem round_certificate : RoundCertificate p (unoutlineRows copy originalRows.toList) parameters 55 before shifted transformed after :=
  checkRound_sound p copy originalRows parameters 55 before shifted transformed after fifthHints round_checked
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonWidth3Call08R55Proof.round_certificate
#print axioms ShielddSecurity.TransferPoseidonWidth3Call08R55Proof.round_certificate
theorem reverse_checked : checkOriginalCoverage p copy arithmeticRows emittedArith rowMapping=true := by
  simp only [checkOriginalCoverage,Bool.and_eq_true]
  constructor
  · decide +kernel
  · apply List.all_eq_true.mpr
    intro index member
    have bound := List.mem_range.mp member
    rw [rows_shape.1] at bound
    have cases : index=0 ∨ index=1 ∨ index=2 ∨ index=3 := by omega
    rcases cases with rfl|rfl|rfl|rfl
    · exact row0_checked
    · exact row1_checked
    · exact row2_checked
    · exact row3_checked

set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonWidth3Call08R55Proof.reverse_checked
#print axioms ShielddSecurity.TransferPoseidonWidth3Call08R55Proof.reverse_checked
theorem reverse_coverage : ∀ actual∈arithmeticRows.toList,∃ expected∈emitted materializedSteps,canonical p (unoutline copy actual.a)=canonical p expected.a ∧ canonical p (unoutline copy actual.b)=canonical p expected.b := by
  simpa [emittedArith] using checkOriginalCoverage_sound p copy arithmeticRows emittedArith rowMapping reverse_checked
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonWidth3Call08R55Proof.reverse_coverage
#print axioms ShielddSecurity.TransferPoseidonWidth3Call08R55Proof.reverse_coverage
theorem ordered : Topological [0,copy] [] materializedSteps := CompilerOrder.checked_order _ _ _ ordered_checked
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonWidth3Call08R55Proof.ordered
#print axioms ShielddSecurity.TransferPoseidonWidth3Call08R55Proof.ordered
theorem write_bounds (column : Nat) (member : column∈PoseidonCompletion.writes materializedSteps) : 24972≤column ∧ column≤24975 :=
  of_decide_eq_true (List.all_eq_true.mp writes_checked column member)
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonWidth3Call08R55Proof.write_bounds
#print axioms ShielddSecurity.TransferPoseidonWidth3Call08R55Proof.write_bounds
theorem emitted_support (row : Row) (member : row∈emitted materializedSteps) (term : Nat × Int) (present : term∈row.a++row.b) : term.1<24976 :=
  of_decide_eq_true (List.all_eq_true.mp (List.all_eq_true.mp emitted_support_checked row member) term present)
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonWidth3Call08R55Proof.emitted_support
#print axioms ShielddSecurity.TransferPoseidonWidth3Call08R55Proof.emitted_support
variable {F : Type} [Field F] [CharP F p]
theorem legal (base : Nat → F) : Legal base materializedSteps := by
  simp [materializedSteps,Legal,Step.Legal]
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonWidth3Call08R55Proof.legal
#print axioms ShielddSecurity.TransferPoseidonWidth3Call08R55Proof.legal
theorem arbitrary_round_sound (rho : Nat → F) (one : rho 0=1) (four : (4:F)≠0) (satisfied : Satisfies rho originalRows.toList) :
    (fun column => eval rho (after column))=Poseidon.round (castParameters parameters) 55 (fun column => eval rho (before column)) := by
  have unoutlined := unoutline_rows_sound rho copy originalRows.toList satisfied (checkRowAt_sound p originalRows 4 _ copy_checked)
  exact round_certificate_sound rho (unoutlineRows copy originalRows.toList) parameters 55 before shifted transformed after one four unoutlined round_certificate
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonWidth3Call08R55Proof.arbitrary_round_sound
#print axioms ShielddSecurity.TransferPoseidonWidth3Call08R55Proof.arbitrary_round_sound
end ShielddSecurity.TransferPoseidonWidth3Call08R55Proof
