-- GENERATED by generate_full_block_proofs.py; edit maintained template.
import ShielddSecurity.TransferPoseidonWidth3Call08ConsumerChecks00
import ShielddSecurity.TransferPoseidonWidth3Call08CoverageChecks00
import ShielddSecurity.TransferPoseidonWidth3Call08ProgramChecks00
import ShielddSecurity.PoseidonCallComposition04
set_option maxHeartbeats 900000
set_option maxRecDepth 8192
namespace ShielddSecurity.TransferPoseidonWidth3Call08R00Proof
open Compiler CompilerIndexed01 CompilerCompletion Poseidon PoseidonIndexedFolded02 ShielddSecurity.TransferPoseidonWidth3Call08Shared01 ShielddSecurity.TransferPoseidonWidth3Call08R00 ShielddSecurity.TransferPoseidonWidth3Call08R00Checks
theorem column_cases (column : Fin 3) : column=0 ∨ column=1 ∨ column=2 := by
  have bound := column.isLt
  simp only [Fin.ext_iff]
  omega
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonWidth3Call08R00Proof.column_cases
#print axioms ShielddSecurity.TransferPoseidonWidth3Call08R00Proof.column_cases
theorem round_checked : checkRound p copy originalRows parameters 0 before shifted transformed after fifthHints=true := by
  simp only [checkRound,Bool.and_eq_true]
  constructor
  · apply List.all_eq_true.mpr
    intro column _
    rcases column_cases column with rfl|rfl|rfl
    · exact column0_checked
    · exact column1_checked
    · exact column2_checked
  · apply List.all_eq_true.mpr
    intro column _
    simp only [decide_eq_true_eq]
    rcases column_cases column with rfl|rfl|rfl
    · exact mix0_checked
    · exact mix1_checked
    · exact mix2_checked

set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonWidth3Call08R00Proof.round_checked
#print axioms ShielddSecurity.TransferPoseidonWidth3Call08R00Proof.round_checked
theorem round_certificate : RoundCertificate p (unoutlineRows copy originalRows.toList) parameters 0 before shifted transformed after :=
  checkRound_sound p copy originalRows parameters 0 before shifted transformed after fifthHints round_checked
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonWidth3Call08R00Proof.round_certificate
#print axioms ShielddSecurity.TransferPoseidonWidth3Call08R00Proof.round_certificate
theorem reverse_checked : checkOriginalCoverage p copy arithmeticRows emittedArith rowMapping=true := by
  simp only [checkOriginalCoverage,Bool.and_eq_true]
  constructor
  · decide +kernel
  · apply List.all_eq_true.mpr
    intro index member
    have bound := List.mem_range.mp member
    rw [rows_shape.1] at bound
    have cases : index=0 ∨ index=1 ∨ index=2 ∨ index=3 ∨ index=4 ∨ index=5 ∨ index=6 ∨ index=7 := by omega
    rcases cases with rfl|rfl|rfl|rfl|rfl|rfl|rfl|rfl
    · exact row0_checked
    · exact row1_checked
    · exact row2_checked
    · exact row3_checked
    · exact row4_checked
    · exact row5_checked
    · exact row6_checked
    · exact row7_checked

set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonWidth3Call08R00Proof.reverse_checked
#print axioms ShielddSecurity.TransferPoseidonWidth3Call08R00Proof.reverse_checked
theorem reverse_coverage : ∀ actual∈arithmeticRows.toList,∃ expected∈emitted materializedSteps,canonical p (unoutline copy actual.a)=canonical p expected.a ∧ canonical p (unoutline copy actual.b)=canonical p expected.b := by
  simpa [emittedArith] using checkOriginalCoverage_sound p copy arithmeticRows emittedArith rowMapping reverse_checked
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonWidth3Call08R00Proof.reverse_coverage
#print axioms ShielddSecurity.TransferPoseidonWidth3Call08R00Proof.reverse_coverage
theorem ordered : Topological [0,copy] [] materializedSteps := CompilerOrder.checked_order _ _ _ ordered_checked
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonWidth3Call08R00Proof.ordered
#print axioms ShielddSecurity.TransferPoseidonWidth3Call08R00Proof.ordered
theorem write_bounds (column : Nat) (member : column∈PoseidonCompletion.writes materializedSteps) : 24724≤column ∧ column≤24731 :=
  of_decide_eq_true (List.all_eq_true.mp writes_checked column member)
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonWidth3Call08R00Proof.write_bounds
#print axioms ShielddSecurity.TransferPoseidonWidth3Call08R00Proof.write_bounds
theorem emitted_support (row : Row) (member : row∈emitted materializedSteps) (term : Nat × Int) (present : term∈row.a++row.b) : term.1<24732 :=
  of_decide_eq_true (List.all_eq_true.mp (List.all_eq_true.mp emitted_support_checked row member) term present)
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonWidth3Call08R00Proof.emitted_support
#print axioms ShielddSecurity.TransferPoseidonWidth3Call08R00Proof.emitted_support
variable {F : Type} [Field F] [CharP F p]
theorem legal (base : Nat → F) : Legal base materializedSteps := by
  simp [materializedSteps,Legal,Step.Legal]
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonWidth3Call08R00Proof.legal
#print axioms ShielddSecurity.TransferPoseidonWidth3Call08R00Proof.legal
theorem arbitrary_round_sound (rho : Nat → F) (one : rho 0=1) (four : (4:F)≠0) (satisfied : Satisfies rho originalRows.toList) :
    (fun column => eval rho (after column))=Poseidon.round (castParameters parameters) 0 (fun column => eval rho (before column)) := by
  have unoutlined := unoutline_rows_sound rho copy originalRows.toList satisfied (checkRowAt_sound p originalRows 8 _ copy_checked)
  exact round_certificate_sound rho (unoutlineRows copy originalRows.toList) parameters 0 before shifted transformed after one four unoutlined round_certificate
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonWidth3Call08R00Proof.arbitrary_round_sound
#print axioms ShielddSecurity.TransferPoseidonWidth3Call08R00Proof.arbitrary_round_sound
end ShielddSecurity.TransferPoseidonWidth3Call08R00Proof
namespace ShielddSecurity.TransferPoseidonWidth3Call08R01Proof
open Compiler CompilerIndexed01 CompilerCompletion Poseidon PoseidonIndexedFolded02 ShielddSecurity.TransferPoseidonWidth3Call08Shared01 ShielddSecurity.TransferPoseidonWidth3Call08R01 ShielddSecurity.TransferPoseidonWidth3Call08R01Checks
theorem column_cases (column : Fin 3) : column=0 ∨ column=1 ∨ column=2 := by
  have bound := column.isLt
  simp only [Fin.ext_iff]
  omega
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonWidth3Call08R01Proof.column_cases
#print axioms ShielddSecurity.TransferPoseidonWidth3Call08R01Proof.column_cases
theorem round_checked : checkRound p copy originalRows parameters 1 before shifted transformed after fifthHints=true := by
  simp only [checkRound,Bool.and_eq_true]
  constructor
  · apply List.all_eq_true.mpr
    intro column _
    rcases column_cases column with rfl|rfl|rfl
    · exact column0_checked
    · exact column1_checked
    · exact column2_checked
  · apply List.all_eq_true.mpr
    intro column _
    simp only [decide_eq_true_eq]
    rcases column_cases column with rfl|rfl|rfl
    · exact mix0_checked
    · exact mix1_checked
    · exact mix2_checked

set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonWidth3Call08R01Proof.round_checked
#print axioms ShielddSecurity.TransferPoseidonWidth3Call08R01Proof.round_checked
theorem round_certificate : RoundCertificate p (unoutlineRows copy originalRows.toList) parameters 1 before shifted transformed after :=
  checkRound_sound p copy originalRows parameters 1 before shifted transformed after fifthHints round_checked
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonWidth3Call08R01Proof.round_certificate
#print axioms ShielddSecurity.TransferPoseidonWidth3Call08R01Proof.round_certificate
theorem reverse_checked : checkOriginalCoverage p copy arithmeticRows emittedArith rowMapping=true := by
  simp only [checkOriginalCoverage,Bool.and_eq_true]
  constructor
  · decide +kernel
  · apply List.all_eq_true.mpr
    intro index member
    have bound := List.mem_range.mp member
    rw [rows_shape.1] at bound
    have cases : index=0 ∨ index=1 ∨ index=2 ∨ index=3 ∨ index=4 ∨ index=5 ∨ index=6 ∨ index=7 ∨ index=8 ∨ index=9 ∨ index=10 ∨ index=11 := by omega
    rcases cases with rfl|rfl|rfl|rfl|rfl|rfl|rfl|rfl|rfl|rfl|rfl|rfl
    · exact row0_checked
    · exact row1_checked
    · exact row2_checked
    · exact row3_checked
    · exact row4_checked
    · exact row5_checked
    · exact row6_checked
    · exact row7_checked
    · exact row8_checked
    · exact row9_checked
    · exact row10_checked
    · exact row11_checked

set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonWidth3Call08R01Proof.reverse_checked
#print axioms ShielddSecurity.TransferPoseidonWidth3Call08R01Proof.reverse_checked
theorem reverse_coverage : ∀ actual∈arithmeticRows.toList,∃ expected∈emitted materializedSteps,canonical p (unoutline copy actual.a)=canonical p expected.a ∧ canonical p (unoutline copy actual.b)=canonical p expected.b := by
  simpa [emittedArith] using checkOriginalCoverage_sound p copy arithmeticRows emittedArith rowMapping reverse_checked
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonWidth3Call08R01Proof.reverse_coverage
#print axioms ShielddSecurity.TransferPoseidonWidth3Call08R01Proof.reverse_coverage
theorem ordered : Topological [0,copy] [] materializedSteps := CompilerOrder.checked_order _ _ _ ordered_checked
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonWidth3Call08R01Proof.ordered
#print axioms ShielddSecurity.TransferPoseidonWidth3Call08R01Proof.ordered
theorem write_bounds (column : Nat) (member : column∈PoseidonCompletion.writes materializedSteps) : 24732≤column ∧ column≤24743 :=
  of_decide_eq_true (List.all_eq_true.mp writes_checked column member)
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonWidth3Call08R01Proof.write_bounds
#print axioms ShielddSecurity.TransferPoseidonWidth3Call08R01Proof.write_bounds
theorem emitted_support (row : Row) (member : row∈emitted materializedSteps) (term : Nat × Int) (present : term∈row.a++row.b) : term.1<24744 :=
  of_decide_eq_true (List.all_eq_true.mp (List.all_eq_true.mp emitted_support_checked row member) term present)
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonWidth3Call08R01Proof.emitted_support
#print axioms ShielddSecurity.TransferPoseidonWidth3Call08R01Proof.emitted_support
variable {F : Type} [Field F] [CharP F p]
theorem legal (base : Nat → F) : Legal base materializedSteps := by
  simp [materializedSteps,Legal,Step.Legal]
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonWidth3Call08R01Proof.legal
#print axioms ShielddSecurity.TransferPoseidonWidth3Call08R01Proof.legal
theorem arbitrary_round_sound (rho : Nat → F) (one : rho 0=1) (four : (4:F)≠0) (satisfied : Satisfies rho originalRows.toList) :
    (fun column => eval rho (after column))=Poseidon.round (castParameters parameters) 1 (fun column => eval rho (before column)) := by
  have unoutlined := unoutline_rows_sound rho copy originalRows.toList satisfied (checkRowAt_sound p originalRows 12 _ copy_checked)
  exact round_certificate_sound rho (unoutlineRows copy originalRows.toList) parameters 1 before shifted transformed after one four unoutlined round_certificate
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonWidth3Call08R01Proof.arbitrary_round_sound
#print axioms ShielddSecurity.TransferPoseidonWidth3Call08R01Proof.arbitrary_round_sound
end ShielddSecurity.TransferPoseidonWidth3Call08R01Proof
namespace ShielddSecurity.TransferPoseidonWidth3Call08R02Proof
open Compiler CompilerIndexed01 CompilerCompletion Poseidon PoseidonIndexedFolded02 ShielddSecurity.TransferPoseidonWidth3Call08Shared01 ShielddSecurity.TransferPoseidonWidth3Call08R02 ShielddSecurity.TransferPoseidonWidth3Call08R02Checks
theorem column_cases (column : Fin 3) : column=0 ∨ column=1 ∨ column=2 := by
  have bound := column.isLt
  simp only [Fin.ext_iff]
  omega
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonWidth3Call08R02Proof.column_cases
#print axioms ShielddSecurity.TransferPoseidonWidth3Call08R02Proof.column_cases
theorem round_checked : checkRound p copy originalRows parameters 2 before shifted transformed after fifthHints=true := by
  simp only [checkRound,Bool.and_eq_true]
  constructor
  · apply List.all_eq_true.mpr
    intro column _
    rcases column_cases column with rfl|rfl|rfl
    · exact column0_checked
    · exact column1_checked
    · exact column2_checked
  · apply List.all_eq_true.mpr
    intro column _
    simp only [decide_eq_true_eq]
    rcases column_cases column with rfl|rfl|rfl
    · exact mix0_checked
    · exact mix1_checked
    · exact mix2_checked

set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonWidth3Call08R02Proof.round_checked
#print axioms ShielddSecurity.TransferPoseidonWidth3Call08R02Proof.round_checked
theorem round_certificate : RoundCertificate p (unoutlineRows copy originalRows.toList) parameters 2 before shifted transformed after :=
  checkRound_sound p copy originalRows parameters 2 before shifted transformed after fifthHints round_checked
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonWidth3Call08R02Proof.round_certificate
#print axioms ShielddSecurity.TransferPoseidonWidth3Call08R02Proof.round_certificate
theorem reverse_checked : checkOriginalCoverage p copy arithmeticRows emittedArith rowMapping=true := by
  simp only [checkOriginalCoverage,Bool.and_eq_true]
  constructor
  · decide +kernel
  · apply List.all_eq_true.mpr
    intro index member
    have bound := List.mem_range.mp member
    rw [rows_shape.1] at bound
    have cases : index=0 ∨ index=1 ∨ index=2 ∨ index=3 ∨ index=4 ∨ index=5 ∨ index=6 ∨ index=7 ∨ index=8 ∨ index=9 ∨ index=10 ∨ index=11 := by omega
    rcases cases with rfl|rfl|rfl|rfl|rfl|rfl|rfl|rfl|rfl|rfl|rfl|rfl
    · exact row0_checked
    · exact row1_checked
    · exact row2_checked
    · exact row3_checked
    · exact row4_checked
    · exact row5_checked
    · exact row6_checked
    · exact row7_checked
    · exact row8_checked
    · exact row9_checked
    · exact row10_checked
    · exact row11_checked

set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonWidth3Call08R02Proof.reverse_checked
#print axioms ShielddSecurity.TransferPoseidonWidth3Call08R02Proof.reverse_checked
theorem reverse_coverage : ∀ actual∈arithmeticRows.toList,∃ expected∈emitted materializedSteps,canonical p (unoutline copy actual.a)=canonical p expected.a ∧ canonical p (unoutline copy actual.b)=canonical p expected.b := by
  simpa [emittedArith] using checkOriginalCoverage_sound p copy arithmeticRows emittedArith rowMapping reverse_checked
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonWidth3Call08R02Proof.reverse_coverage
#print axioms ShielddSecurity.TransferPoseidonWidth3Call08R02Proof.reverse_coverage
theorem ordered : Topological [0,copy] [] materializedSteps := CompilerOrder.checked_order _ _ _ ordered_checked
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonWidth3Call08R02Proof.ordered
#print axioms ShielddSecurity.TransferPoseidonWidth3Call08R02Proof.ordered
theorem write_bounds (column : Nat) (member : column∈PoseidonCompletion.writes materializedSteps) : 24744≤column ∧ column≤24755 :=
  of_decide_eq_true (List.all_eq_true.mp writes_checked column member)
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonWidth3Call08R02Proof.write_bounds
#print axioms ShielddSecurity.TransferPoseidonWidth3Call08R02Proof.write_bounds
theorem emitted_support (row : Row) (member : row∈emitted materializedSteps) (term : Nat × Int) (present : term∈row.a++row.b) : term.1<24756 :=
  of_decide_eq_true (List.all_eq_true.mp (List.all_eq_true.mp emitted_support_checked row member) term present)
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonWidth3Call08R02Proof.emitted_support
#print axioms ShielddSecurity.TransferPoseidonWidth3Call08R02Proof.emitted_support
variable {F : Type} [Field F] [CharP F p]
theorem legal (base : Nat → F) : Legal base materializedSteps := by
  simp [materializedSteps,Legal,Step.Legal]
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonWidth3Call08R02Proof.legal
#print axioms ShielddSecurity.TransferPoseidonWidth3Call08R02Proof.legal
theorem arbitrary_round_sound (rho : Nat → F) (one : rho 0=1) (four : (4:F)≠0) (satisfied : Satisfies rho originalRows.toList) :
    (fun column => eval rho (after column))=Poseidon.round (castParameters parameters) 2 (fun column => eval rho (before column)) := by
  have unoutlined := unoutline_rows_sound rho copy originalRows.toList satisfied (checkRowAt_sound p originalRows 12 _ copy_checked)
  exact round_certificate_sound rho (unoutlineRows copy originalRows.toList) parameters 2 before shifted transformed after one four unoutlined round_certificate
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonWidth3Call08R02Proof.arbitrary_round_sound
#print axioms ShielddSecurity.TransferPoseidonWidth3Call08R02Proof.arbitrary_round_sound
end ShielddSecurity.TransferPoseidonWidth3Call08R02Proof
namespace ShielddSecurity.TransferPoseidonWidth3Call08R03Proof
open Compiler CompilerIndexed01 CompilerCompletion Poseidon PoseidonIndexedFolded02 ShielddSecurity.TransferPoseidonWidth3Call08Shared01 ShielddSecurity.TransferPoseidonWidth3Call08R03 ShielddSecurity.TransferPoseidonWidth3Call08R03Checks
theorem column_cases (column : Fin 3) : column=0 ∨ column=1 ∨ column=2 := by
  have bound := column.isLt
  simp only [Fin.ext_iff]
  omega
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonWidth3Call08R03Proof.column_cases
#print axioms ShielddSecurity.TransferPoseidonWidth3Call08R03Proof.column_cases
theorem round_checked : checkRound p copy originalRows parameters 3 before shifted transformed after fifthHints=true := by
  simp only [checkRound,Bool.and_eq_true]
  constructor
  · apply List.all_eq_true.mpr
    intro column _
    rcases column_cases column with rfl|rfl|rfl
    · exact column0_checked
    · exact column1_checked
    · exact column2_checked
  · apply List.all_eq_true.mpr
    intro column _
    simp only [decide_eq_true_eq]
    rcases column_cases column with rfl|rfl|rfl
    · exact mix0_checked
    · exact mix1_checked
    · exact mix2_checked

set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonWidth3Call08R03Proof.round_checked
#print axioms ShielddSecurity.TransferPoseidonWidth3Call08R03Proof.round_checked
theorem round_certificate : RoundCertificate p (unoutlineRows copy originalRows.toList) parameters 3 before shifted transformed after :=
  checkRound_sound p copy originalRows parameters 3 before shifted transformed after fifthHints round_checked
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonWidth3Call08R03Proof.round_certificate
#print axioms ShielddSecurity.TransferPoseidonWidth3Call08R03Proof.round_certificate
theorem reverse_checked : checkOriginalCoverage p copy arithmeticRows emittedArith rowMapping=true := by
  simp only [checkOriginalCoverage,Bool.and_eq_true]
  constructor
  · decide +kernel
  · apply List.all_eq_true.mpr
    intro index member
    have bound := List.mem_range.mp member
    rw [rows_shape.1] at bound
    have cases : index=0 ∨ index=1 ∨ index=2 ∨ index=3 ∨ index=4 ∨ index=5 ∨ index=6 ∨ index=7 ∨ index=8 ∨ index=9 ∨ index=10 ∨ index=11 := by omega
    rcases cases with rfl|rfl|rfl|rfl|rfl|rfl|rfl|rfl|rfl|rfl|rfl|rfl
    · exact row0_checked
    · exact row1_checked
    · exact row2_checked
    · exact row3_checked
    · exact row4_checked
    · exact row5_checked
    · exact row6_checked
    · exact row7_checked
    · exact row8_checked
    · exact row9_checked
    · exact row10_checked
    · exact row11_checked

set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonWidth3Call08R03Proof.reverse_checked
#print axioms ShielddSecurity.TransferPoseidonWidth3Call08R03Proof.reverse_checked
theorem reverse_coverage : ∀ actual∈arithmeticRows.toList,∃ expected∈emitted materializedSteps,canonical p (unoutline copy actual.a)=canonical p expected.a ∧ canonical p (unoutline copy actual.b)=canonical p expected.b := by
  simpa [emittedArith] using checkOriginalCoverage_sound p copy arithmeticRows emittedArith rowMapping reverse_checked
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonWidth3Call08R03Proof.reverse_coverage
#print axioms ShielddSecurity.TransferPoseidonWidth3Call08R03Proof.reverse_coverage
theorem ordered : Topological [0,copy] [] materializedSteps := CompilerOrder.checked_order _ _ _ ordered_checked
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonWidth3Call08R03Proof.ordered
#print axioms ShielddSecurity.TransferPoseidonWidth3Call08R03Proof.ordered
theorem write_bounds (column : Nat) (member : column∈PoseidonCompletion.writes materializedSteps) : 24756≤column ∧ column≤24767 :=
  of_decide_eq_true (List.all_eq_true.mp writes_checked column member)
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonWidth3Call08R03Proof.write_bounds
#print axioms ShielddSecurity.TransferPoseidonWidth3Call08R03Proof.write_bounds
theorem emitted_support (row : Row) (member : row∈emitted materializedSteps) (term : Nat × Int) (present : term∈row.a++row.b) : term.1<24768 :=
  of_decide_eq_true (List.all_eq_true.mp (List.all_eq_true.mp emitted_support_checked row member) term present)
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonWidth3Call08R03Proof.emitted_support
#print axioms ShielddSecurity.TransferPoseidonWidth3Call08R03Proof.emitted_support
variable {F : Type} [Field F] [CharP F p]
theorem legal (base : Nat → F) : Legal base materializedSteps := by
  simp [materializedSteps,Legal,Step.Legal]
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonWidth3Call08R03Proof.legal
#print axioms ShielddSecurity.TransferPoseidonWidth3Call08R03Proof.legal
theorem arbitrary_round_sound (rho : Nat → F) (one : rho 0=1) (four : (4:F)≠0) (satisfied : Satisfies rho originalRows.toList) :
    (fun column => eval rho (after column))=Poseidon.round (castParameters parameters) 3 (fun column => eval rho (before column)) := by
  have unoutlined := unoutline_rows_sound rho copy originalRows.toList satisfied (checkRowAt_sound p originalRows 12 _ copy_checked)
  exact round_certificate_sound rho (unoutlineRows copy originalRows.toList) parameters 3 before shifted transformed after one four unoutlined round_certificate
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonWidth3Call08R03Proof.arbitrary_round_sound
#print axioms ShielddSecurity.TransferPoseidonWidth3Call08R03Proof.arbitrary_round_sound
end ShielddSecurity.TransferPoseidonWidth3Call08R03Proof
namespace ShielddSecurity.TransferPoseidonWidth3Call08R04Proof
open Compiler CompilerIndexed01 CompilerCompletion Poseidon PoseidonIndexedFolded02 ShielddSecurity.TransferPoseidonWidth3Call08Shared01 ShielddSecurity.TransferPoseidonWidth3Call08R04 ShielddSecurity.TransferPoseidonWidth3Call08R04Checks
theorem column_cases (column : Fin 3) : column=0 ∨ column=1 ∨ column=2 := by
  have bound := column.isLt
  simp only [Fin.ext_iff]
  omega
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonWidth3Call08R04Proof.column_cases
#print axioms ShielddSecurity.TransferPoseidonWidth3Call08R04Proof.column_cases
theorem round_checked : checkRound p copy originalRows parameters 4 before shifted transformed after fifthHints=true := by
  simp only [checkRound,Bool.and_eq_true]
  constructor
  · apply List.all_eq_true.mpr
    intro column _
    rcases column_cases column with rfl|rfl|rfl
    · exact column0_checked
    · exact column1_checked
    · exact column2_checked
  · apply List.all_eq_true.mpr
    intro column _
    simp only [decide_eq_true_eq]
    rcases column_cases column with rfl|rfl|rfl
    · exact mix0_checked
    · exact mix1_checked
    · exact mix2_checked

set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonWidth3Call08R04Proof.round_checked
#print axioms ShielddSecurity.TransferPoseidonWidth3Call08R04Proof.round_checked
theorem round_certificate : RoundCertificate p (unoutlineRows copy originalRows.toList) parameters 4 before shifted transformed after :=
  checkRound_sound p copy originalRows parameters 4 before shifted transformed after fifthHints round_checked
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonWidth3Call08R04Proof.round_certificate
#print axioms ShielddSecurity.TransferPoseidonWidth3Call08R04Proof.round_certificate
theorem reverse_checked : checkOriginalCoverage p copy arithmeticRows emittedArith rowMapping=true := by
  simp only [checkOriginalCoverage,Bool.and_eq_true]
  constructor
  · decide +kernel
  · apply List.all_eq_true.mpr
    intro index member
    have bound := List.mem_range.mp member
    rw [rows_shape.1] at bound
    have cases : index=0 ∨ index=1 ∨ index=2 ∨ index=3 := by omega
    rcases cases with rfl|rfl|rfl|rfl
    · exact row0_checked
    · exact row1_checked
    · exact row2_checked
    · exact row3_checked

set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonWidth3Call08R04Proof.reverse_checked
#print axioms ShielddSecurity.TransferPoseidonWidth3Call08R04Proof.reverse_checked
theorem reverse_coverage : ∀ actual∈arithmeticRows.toList,∃ expected∈emitted materializedSteps,canonical p (unoutline copy actual.a)=canonical p expected.a ∧ canonical p (unoutline copy actual.b)=canonical p expected.b := by
  simpa [emittedArith] using checkOriginalCoverage_sound p copy arithmeticRows emittedArith rowMapping reverse_checked
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonWidth3Call08R04Proof.reverse_coverage
#print axioms ShielddSecurity.TransferPoseidonWidth3Call08R04Proof.reverse_coverage
theorem ordered : Topological [0,copy] [] materializedSteps := CompilerOrder.checked_order _ _ _ ordered_checked
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonWidth3Call08R04Proof.ordered
#print axioms ShielddSecurity.TransferPoseidonWidth3Call08R04Proof.ordered
theorem write_bounds (column : Nat) (member : column∈PoseidonCompletion.writes materializedSteps) : 24768≤column ∧ column≤24771 :=
  of_decide_eq_true (List.all_eq_true.mp writes_checked column member)
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonWidth3Call08R04Proof.write_bounds
#print axioms ShielddSecurity.TransferPoseidonWidth3Call08R04Proof.write_bounds
theorem emitted_support (row : Row) (member : row∈emitted materializedSteps) (term : Nat × Int) (present : term∈row.a++row.b) : term.1<24772 :=
  of_decide_eq_true (List.all_eq_true.mp (List.all_eq_true.mp emitted_support_checked row member) term present)
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonWidth3Call08R04Proof.emitted_support
#print axioms ShielddSecurity.TransferPoseidonWidth3Call08R04Proof.emitted_support
variable {F : Type} [Field F] [CharP F p]
theorem legal (base : Nat → F) : Legal base materializedSteps := by
  simp [materializedSteps,Legal,Step.Legal]
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonWidth3Call08R04Proof.legal
#print axioms ShielddSecurity.TransferPoseidonWidth3Call08R04Proof.legal
theorem arbitrary_round_sound (rho : Nat → F) (one : rho 0=1) (four : (4:F)≠0) (satisfied : Satisfies rho originalRows.toList) :
    (fun column => eval rho (after column))=Poseidon.round (castParameters parameters) 4 (fun column => eval rho (before column)) := by
  have unoutlined := unoutline_rows_sound rho copy originalRows.toList satisfied (checkRowAt_sound p originalRows 4 _ copy_checked)
  exact round_certificate_sound rho (unoutlineRows copy originalRows.toList) parameters 4 before shifted transformed after one four unoutlined round_certificate
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonWidth3Call08R04Proof.arbitrary_round_sound
#print axioms ShielddSecurity.TransferPoseidonWidth3Call08R04Proof.arbitrary_round_sound
end ShielddSecurity.TransferPoseidonWidth3Call08R04Proof
namespace ShielddSecurity.TransferPoseidonWidth3Call08R05Proof
open Compiler CompilerIndexed01 CompilerCompletion Poseidon PoseidonIndexedFolded02 ShielddSecurity.TransferPoseidonWidth3Call08Shared01 ShielddSecurity.TransferPoseidonWidth3Call08R05 ShielddSecurity.TransferPoseidonWidth3Call08R05Checks
theorem column_cases (column : Fin 3) : column=0 ∨ column=1 ∨ column=2 := by
  have bound := column.isLt
  simp only [Fin.ext_iff]
  omega
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonWidth3Call08R05Proof.column_cases
#print axioms ShielddSecurity.TransferPoseidonWidth3Call08R05Proof.column_cases
theorem round_checked : checkRound p copy originalRows parameters 5 before shifted transformed after fifthHints=true := by
  simp only [checkRound,Bool.and_eq_true]
  constructor
  · apply List.all_eq_true.mpr
    intro column _
    rcases column_cases column with rfl|rfl|rfl
    · exact column0_checked
    · exact column1_checked
    · exact column2_checked
  · apply List.all_eq_true.mpr
    intro column _
    simp only [decide_eq_true_eq]
    rcases column_cases column with rfl|rfl|rfl
    · exact mix0_checked
    · exact mix1_checked
    · exact mix2_checked

set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonWidth3Call08R05Proof.round_checked
#print axioms ShielddSecurity.TransferPoseidonWidth3Call08R05Proof.round_checked
theorem round_certificate : RoundCertificate p (unoutlineRows copy originalRows.toList) parameters 5 before shifted transformed after :=
  checkRound_sound p copy originalRows parameters 5 before shifted transformed after fifthHints round_checked
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonWidth3Call08R05Proof.round_certificate
#print axioms ShielddSecurity.TransferPoseidonWidth3Call08R05Proof.round_certificate
theorem reverse_checked : checkOriginalCoverage p copy arithmeticRows emittedArith rowMapping=true := by
  simp only [checkOriginalCoverage,Bool.and_eq_true]
  constructor
  · decide +kernel
  · apply List.all_eq_true.mpr
    intro index member
    have bound := List.mem_range.mp member
    rw [rows_shape.1] at bound
    have cases : index=0 ∨ index=1 ∨ index=2 ∨ index=3 := by omega
    rcases cases with rfl|rfl|rfl|rfl
    · exact row0_checked
    · exact row1_checked
    · exact row2_checked
    · exact row3_checked

set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonWidth3Call08R05Proof.reverse_checked
#print axioms ShielddSecurity.TransferPoseidonWidth3Call08R05Proof.reverse_checked
theorem reverse_coverage : ∀ actual∈arithmeticRows.toList,∃ expected∈emitted materializedSteps,canonical p (unoutline copy actual.a)=canonical p expected.a ∧ canonical p (unoutline copy actual.b)=canonical p expected.b := by
  simpa [emittedArith] using checkOriginalCoverage_sound p copy arithmeticRows emittedArith rowMapping reverse_checked
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonWidth3Call08R05Proof.reverse_coverage
#print axioms ShielddSecurity.TransferPoseidonWidth3Call08R05Proof.reverse_coverage
theorem ordered : Topological [0,copy] [] materializedSteps := CompilerOrder.checked_order _ _ _ ordered_checked
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonWidth3Call08R05Proof.ordered
#print axioms ShielddSecurity.TransferPoseidonWidth3Call08R05Proof.ordered
theorem write_bounds (column : Nat) (member : column∈PoseidonCompletion.writes materializedSteps) : 24772≤column ∧ column≤24775 :=
  of_decide_eq_true (List.all_eq_true.mp writes_checked column member)
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonWidth3Call08R05Proof.write_bounds
#print axioms ShielddSecurity.TransferPoseidonWidth3Call08R05Proof.write_bounds
theorem emitted_support (row : Row) (member : row∈emitted materializedSteps) (term : Nat × Int) (present : term∈row.a++row.b) : term.1<24776 :=
  of_decide_eq_true (List.all_eq_true.mp (List.all_eq_true.mp emitted_support_checked row member) term present)
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonWidth3Call08R05Proof.emitted_support
#print axioms ShielddSecurity.TransferPoseidonWidth3Call08R05Proof.emitted_support
variable {F : Type} [Field F] [CharP F p]
theorem legal (base : Nat → F) : Legal base materializedSteps := by
  simp [materializedSteps,Legal,Step.Legal]
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonWidth3Call08R05Proof.legal
#print axioms ShielddSecurity.TransferPoseidonWidth3Call08R05Proof.legal
theorem arbitrary_round_sound (rho : Nat → F) (one : rho 0=1) (four : (4:F)≠0) (satisfied : Satisfies rho originalRows.toList) :
    (fun column => eval rho (after column))=Poseidon.round (castParameters parameters) 5 (fun column => eval rho (before column)) := by
  have unoutlined := unoutline_rows_sound rho copy originalRows.toList satisfied (checkRowAt_sound p originalRows 4 _ copy_checked)
  exact round_certificate_sound rho (unoutlineRows copy originalRows.toList) parameters 5 before shifted transformed after one four unoutlined round_certificate
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonWidth3Call08R05Proof.arbitrary_round_sound
#print axioms ShielddSecurity.TransferPoseidonWidth3Call08R05Proof.arbitrary_round_sound
end ShielddSecurity.TransferPoseidonWidth3Call08R05Proof
namespace ShielddSecurity.TransferPoseidonWidth3Call08R06Proof
open Compiler CompilerIndexed01 CompilerCompletion Poseidon PoseidonIndexedFolded02 ShielddSecurity.TransferPoseidonWidth3Call08Shared01 ShielddSecurity.TransferPoseidonWidth3Call08R06 ShielddSecurity.TransferPoseidonWidth3Call08R06Checks
theorem column_cases (column : Fin 3) : column=0 ∨ column=1 ∨ column=2 := by
  have bound := column.isLt
  simp only [Fin.ext_iff]
  omega
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonWidth3Call08R06Proof.column_cases
#print axioms ShielddSecurity.TransferPoseidonWidth3Call08R06Proof.column_cases
theorem round_checked : checkRound p copy originalRows parameters 6 before shifted transformed after fifthHints=true := by
  simp only [checkRound,Bool.and_eq_true]
  constructor
  · apply List.all_eq_true.mpr
    intro column _
    rcases column_cases column with rfl|rfl|rfl
    · exact column0_checked
    · exact column1_checked
    · exact column2_checked
  · apply List.all_eq_true.mpr
    intro column _
    simp only [decide_eq_true_eq]
    rcases column_cases column with rfl|rfl|rfl
    · exact mix0_checked
    · exact mix1_checked
    · exact mix2_checked

set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonWidth3Call08R06Proof.round_checked
#print axioms ShielddSecurity.TransferPoseidonWidth3Call08R06Proof.round_checked
theorem round_certificate : RoundCertificate p (unoutlineRows copy originalRows.toList) parameters 6 before shifted transformed after :=
  checkRound_sound p copy originalRows parameters 6 before shifted transformed after fifthHints round_checked
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonWidth3Call08R06Proof.round_certificate
#print axioms ShielddSecurity.TransferPoseidonWidth3Call08R06Proof.round_certificate
theorem reverse_checked : checkOriginalCoverage p copy arithmeticRows emittedArith rowMapping=true := by
  simp only [checkOriginalCoverage,Bool.and_eq_true]
  constructor
  · decide +kernel
  · apply List.all_eq_true.mpr
    intro index member
    have bound := List.mem_range.mp member
    rw [rows_shape.1] at bound
    have cases : index=0 ∨ index=1 ∨ index=2 ∨ index=3 := by omega
    rcases cases with rfl|rfl|rfl|rfl
    · exact row0_checked
    · exact row1_checked
    · exact row2_checked
    · exact row3_checked

set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonWidth3Call08R06Proof.reverse_checked
#print axioms ShielddSecurity.TransferPoseidonWidth3Call08R06Proof.reverse_checked
theorem reverse_coverage : ∀ actual∈arithmeticRows.toList,∃ expected∈emitted materializedSteps,canonical p (unoutline copy actual.a)=canonical p expected.a ∧ canonical p (unoutline copy actual.b)=canonical p expected.b := by
  simpa [emittedArith] using checkOriginalCoverage_sound p copy arithmeticRows emittedArith rowMapping reverse_checked
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonWidth3Call08R06Proof.reverse_coverage
#print axioms ShielddSecurity.TransferPoseidonWidth3Call08R06Proof.reverse_coverage
theorem ordered : Topological [0,copy] [] materializedSteps := CompilerOrder.checked_order _ _ _ ordered_checked
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonWidth3Call08R06Proof.ordered
#print axioms ShielddSecurity.TransferPoseidonWidth3Call08R06Proof.ordered
theorem write_bounds (column : Nat) (member : column∈PoseidonCompletion.writes materializedSteps) : 24776≤column ∧ column≤24779 :=
  of_decide_eq_true (List.all_eq_true.mp writes_checked column member)
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonWidth3Call08R06Proof.write_bounds
#print axioms ShielddSecurity.TransferPoseidonWidth3Call08R06Proof.write_bounds
theorem emitted_support (row : Row) (member : row∈emitted materializedSteps) (term : Nat × Int) (present : term∈row.a++row.b) : term.1<24780 :=
  of_decide_eq_true (List.all_eq_true.mp (List.all_eq_true.mp emitted_support_checked row member) term present)
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonWidth3Call08R06Proof.emitted_support
#print axioms ShielddSecurity.TransferPoseidonWidth3Call08R06Proof.emitted_support
variable {F : Type} [Field F] [CharP F p]
theorem legal (base : Nat → F) : Legal base materializedSteps := by
  simp [materializedSteps,Legal,Step.Legal]
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonWidth3Call08R06Proof.legal
#print axioms ShielddSecurity.TransferPoseidonWidth3Call08R06Proof.legal
theorem arbitrary_round_sound (rho : Nat → F) (one : rho 0=1) (four : (4:F)≠0) (satisfied : Satisfies rho originalRows.toList) :
    (fun column => eval rho (after column))=Poseidon.round (castParameters parameters) 6 (fun column => eval rho (before column)) := by
  have unoutlined := unoutline_rows_sound rho copy originalRows.toList satisfied (checkRowAt_sound p originalRows 4 _ copy_checked)
  exact round_certificate_sound rho (unoutlineRows copy originalRows.toList) parameters 6 before shifted transformed after one four unoutlined round_certificate
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonWidth3Call08R06Proof.arbitrary_round_sound
#print axioms ShielddSecurity.TransferPoseidonWidth3Call08R06Proof.arbitrary_round_sound
end ShielddSecurity.TransferPoseidonWidth3Call08R06Proof
namespace ShielddSecurity.TransferPoseidonWidth3Call08R07Proof
open Compiler CompilerIndexed01 CompilerCompletion Poseidon PoseidonIndexedFolded02 ShielddSecurity.TransferPoseidonWidth3Call08Shared01 ShielddSecurity.TransferPoseidonWidth3Call08R07 ShielddSecurity.TransferPoseidonWidth3Call08R07Checks
theorem column_cases (column : Fin 3) : column=0 ∨ column=1 ∨ column=2 := by
  have bound := column.isLt
  simp only [Fin.ext_iff]
  omega
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonWidth3Call08R07Proof.column_cases
#print axioms ShielddSecurity.TransferPoseidonWidth3Call08R07Proof.column_cases
theorem round_checked : checkRound p copy originalRows parameters 7 before shifted transformed after fifthHints=true := by
  simp only [checkRound,Bool.and_eq_true]
  constructor
  · apply List.all_eq_true.mpr
    intro column _
    rcases column_cases column with rfl|rfl|rfl
    · exact column0_checked
    · exact column1_checked
    · exact column2_checked
  · apply List.all_eq_true.mpr
    intro column _
    simp only [decide_eq_true_eq]
    rcases column_cases column with rfl|rfl|rfl
    · exact mix0_checked
    · exact mix1_checked
    · exact mix2_checked

set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonWidth3Call08R07Proof.round_checked
#print axioms ShielddSecurity.TransferPoseidonWidth3Call08R07Proof.round_checked
theorem round_certificate : RoundCertificate p (unoutlineRows copy originalRows.toList) parameters 7 before shifted transformed after :=
  checkRound_sound p copy originalRows parameters 7 before shifted transformed after fifthHints round_checked
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonWidth3Call08R07Proof.round_certificate
#print axioms ShielddSecurity.TransferPoseidonWidth3Call08R07Proof.round_certificate
theorem reverse_checked : checkOriginalCoverage p copy arithmeticRows emittedArith rowMapping=true := by
  simp only [checkOriginalCoverage,Bool.and_eq_true]
  constructor
  · decide +kernel
  · apply List.all_eq_true.mpr
    intro index member
    have bound := List.mem_range.mp member
    rw [rows_shape.1] at bound
    have cases : index=0 ∨ index=1 ∨ index=2 ∨ index=3 := by omega
    rcases cases with rfl|rfl|rfl|rfl
    · exact row0_checked
    · exact row1_checked
    · exact row2_checked
    · exact row3_checked

set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonWidth3Call08R07Proof.reverse_checked
#print axioms ShielddSecurity.TransferPoseidonWidth3Call08R07Proof.reverse_checked
theorem reverse_coverage : ∀ actual∈arithmeticRows.toList,∃ expected∈emitted materializedSteps,canonical p (unoutline copy actual.a)=canonical p expected.a ∧ canonical p (unoutline copy actual.b)=canonical p expected.b := by
  simpa [emittedArith] using checkOriginalCoverage_sound p copy arithmeticRows emittedArith rowMapping reverse_checked
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonWidth3Call08R07Proof.reverse_coverage
#print axioms ShielddSecurity.TransferPoseidonWidth3Call08R07Proof.reverse_coverage
theorem ordered : Topological [0,copy] [] materializedSteps := CompilerOrder.checked_order _ _ _ ordered_checked
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonWidth3Call08R07Proof.ordered
#print axioms ShielddSecurity.TransferPoseidonWidth3Call08R07Proof.ordered
theorem write_bounds (column : Nat) (member : column∈PoseidonCompletion.writes materializedSteps) : 24780≤column ∧ column≤24783 :=
  of_decide_eq_true (List.all_eq_true.mp writes_checked column member)
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonWidth3Call08R07Proof.write_bounds
#print axioms ShielddSecurity.TransferPoseidonWidth3Call08R07Proof.write_bounds
theorem emitted_support (row : Row) (member : row∈emitted materializedSteps) (term : Nat × Int) (present : term∈row.a++row.b) : term.1<24784 :=
  of_decide_eq_true (List.all_eq_true.mp (List.all_eq_true.mp emitted_support_checked row member) term present)
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonWidth3Call08R07Proof.emitted_support
#print axioms ShielddSecurity.TransferPoseidonWidth3Call08R07Proof.emitted_support
variable {F : Type} [Field F] [CharP F p]
theorem legal (base : Nat → F) : Legal base materializedSteps := by
  simp [materializedSteps,Legal,Step.Legal]
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonWidth3Call08R07Proof.legal
#print axioms ShielddSecurity.TransferPoseidonWidth3Call08R07Proof.legal
theorem arbitrary_round_sound (rho : Nat → F) (one : rho 0=1) (four : (4:F)≠0) (satisfied : Satisfies rho originalRows.toList) :
    (fun column => eval rho (after column))=Poseidon.round (castParameters parameters) 7 (fun column => eval rho (before column)) := by
  have unoutlined := unoutline_rows_sound rho copy originalRows.toList satisfied (checkRowAt_sound p originalRows 4 _ copy_checked)
  exact round_certificate_sound rho (unoutlineRows copy originalRows.toList) parameters 7 before shifted transformed after one four unoutlined round_certificate
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonWidth3Call08R07Proof.arbitrary_round_sound
#print axioms ShielddSecurity.TransferPoseidonWidth3Call08R07Proof.arbitrary_round_sound
end ShielddSecurity.TransferPoseidonWidth3Call08R07Proof
