"""Review only maintained portable generation delta; mathematics separately reviewed."""
import json,hashlib,subprocess,time
from pathlib import Path
H=Path(__file__).resolve().parent;F=H/'frozen';R=H.parents[1]
sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
assert sha(F/'manifest.json')=='a305ab3443531633fc13fda491475f62efcca25a64e34b9e4db0fd94e707a6e7'
m=json.loads((F/'manifest.json').read_text());assert all(sha(F/x['path'])==x['sha256'] for x in m['files'])
prompt=f'''Read-only independent provenance delta review at {F}, tools Read/Glob/Grep only, no executions/builds/edits. Mathematical endpoint already independently Opus5.5high reviewed340files with no soundness/count/generator defect; only scopedB0R00 guardlabels acknowledged. Review NEW generation_common.py andgenerate_probe.py explicitpathadapters, make_portable_input.py, supported_verify_replay.py andinventory against prior immutable maintainedfiles {R/'work/parent-width6-upstream11-review02/frozen/maintained'}. Supportedadapter18maintained hashes+2handwrittenhelper hashes. Doesfreshreplay useonlyexplicitcompactinput/maintainedtemplates, writefreshdirectory, actuallyregenerate85sources via9generators, compareeveryproducedfile bytehash/count ratherthancopybaseline, and preserve mathematically acceptedproofbytes? Parent independentlyranrecipe:85sources1799905B byteexact,0Leanexecutions. Everyinventorygeneratedhash boundtoactualcompiledstage source; helpers separately sourcehashboundnotclaimedgenerated. CompactinputSHA74189456aa7380c35040e1c67d3b9d3ad48ce75d332ac80ad44971f1c0812ab9 (1717578B) parentverifiedrecursiveexactprojectionfromfullqualifieddescriptor3be245c6c55f473352481dbbc43d876591f8bbcedb61bd9c9c633de785112d6e. Prunesblocksroundphaseports to4neededendpoint entries, preservesfullprefix_scopes377nodes/837rows/pinnedparams+inputs/identities. ParentfullDATA DBaudit of3120roundports remainsseparate; compactdoesnotclaimallportsretained. Checkhashpinning/runtime/pins/shape/optimizedPython refusal, sourcepathenvhandling, baselinehashcircularity (byteidentity proves reproducibilityonly), failureprovenance, use oflocalfullDB fallback notneededinsupportedroute, unsupportedhistoricalbootstrapexcluded. NoKernel/native/fullTransfer creditfrombyterepay. Countscope:85rootreachablefreshmodules491audits excludesImportFloor1Trueaudit andTailLeafProbe4audits; allstage87fresh496separately. 85generatedcensus includes2unusedprobeoutputs instead2handwrittenhelpers, hence counts happen equalbutarenotidenticalsets. No needre-reviewwholemathorcosmeticFdeclarations. Report actionableprovenance/reproducibilitydefect ornone inexactportablebyte-generationroute; fullparentpageposition/globalrelation/native/cutformulaOPEN.'''
(H/'review-prompt.txt').write_text(prompt+'\n');start=time.monotonic()
cmd=['/Users/antoinecyr/.local/bin/claude','--model','claude-opus-5-5','--effort','high','--permission-mode','plan','--tools','Read,Glob,Grep','--strict-mcp-config','--no-session-persistence','--output-format','json','--print',prompt]
with (H/'opus55-review.json').open('w') as out,(H/'opus55-review.stderr').open('w') as err:r=subprocess.run(cmd,stdout=out,stderr=err,timeout=900)
j=json.loads((H/'opus55-review.json').read_text());assert r.returncode==0 and not j['is_error'] and 'claude-opus-5-5' in j['modelUsage']
assert all(sha(F/x['path'])==x['sha256'] for x in m['files'])
print(json.dumps({'review':'complete','delta_files':len(m['files']),'seconds':time.monotonic()-start,'model':list(j['modelUsage'])}))
