import ShielddGnarkFormal.Deployed.Contracts.Transfer.Seg3
import ShielddGnarkFormal.Deployed.Contracts.Transfer.Seg4
import ShielddGnarkFormal.Deployed.Contracts.Transfer.Seg12
import ShielddGnarkFormal.Deployed.Contracts.Transfer.Seg13
import ShielddGnarkFormal.Deployed.Contracts.Transfer.Seg14
import ShielddGnarkFormal.Deployed.Contracts.Transfer.Seg15
import ShielddGnarkFormal.Deployed.Contracts.Transfer.Seg16
import ShielddGnarkFormal.Deployed.Contracts.Transfer.Seg17

set_option maxRecDepth 1000000
set_option maxHeartbeats 4000000

/-! Exact deployed canonicalSender facts for the transfer deployment.
GENERATED by gen_deployed_family.py — do not edit by hand. -/

namespace Shieldd.GnarkFormal.Deployed.Contracts.Transfer

structure CanonicalSenderCircuitFacts (rho : Nat → Seg3.F) : Prop where
  AssertDecafNonIdentitySeg3 : Seg3.contract.spec rho
  AssertDecafNonIdentitySeg4 : Seg4.contract.spec rho
  DecafCompressToFieldSeg12 : Seg12.contract.spec rho
  DecafCompressToFieldSeg13 : Seg13.contract.spec rho
  AssertNeSeg14 : Seg14.contract.spec rho
  DecafDiversifiedTransmissionKeySeg15 : Seg15.contract.spec rho
  DecafAssertEquivalentSeg16 : Seg16.contract.spec rho
  AssertDecafNonIdentitySeg17 : Seg17.contract.spec rho

end Shieldd.GnarkFormal.Deployed.Contracts.Transfer
