import ShielddGnarkFormal.Deployed.Contracts.NoteReshape1x8.Seg53
import ShielddGnarkFormal.Deployed.Contracts.NoteReshape1x8.Seg54

set_option maxRecDepth 1000000
set_option maxHeartbeats 4000000

/-! Exact deployed output2 facts for the note_reshape1x8 deployment.
GENERATED by gen_note_reshape_family.py — do not edit by hand. -/

namespace Shieldd.GnarkFormal.Deployed.Contracts.NoteReshape1x8

structure Output2CircuitFacts (rho : Nat → Seg53.F) : Prop where
  GadgetNoteCommitmentSeg53 : Seg53.contract.spec rho
  AssertEqSeg54 : Seg54.contract.spec rho

end Shieldd.GnarkFormal.Deployed.Contracts.NoteReshape1x8
