"""Freeze worker source-only packet and run independent read-only Opus review."""
import hashlib,json,shutil,subprocess,time
from pathlib import Path
H=Path(__file__).resolve().parent; ROOT=H.parents[1]
S=ROOT/'work/mac-poseidon-width6-upstream11/review-snapshot01'; F=H/'frozen'
sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
assert sha(S/'manifest.json')=='0169acb3fcbe0f02e66b75f3eca07da851a45bec814e1efc54af3ed167ffafb9'
m=json.loads((S/'manifest.json').read_text()); assert not F.exists();F.mkdir()
for x in m['files']:
    src=S/x['path'];assert sha(src)==x['sha256'] and src.stat().st_size==x['bytes']
    dst=F/x['path'];dst.parent.mkdir(parents=True,exist_ok=True);shutil.copyfile(src,dst)
shutil.copyfile(S/'manifest.json',F/'manifest.json')
for name in ['data-plan01.json','descriptor-audit01.json','receipt-audit01.json']:
    d=F/'parent-data'/name;d.parent.mkdir(exist_ok=True);shutil.copyfile(ROOT/'work/parent-width6-upstream11-plan01'/name,d)
prompt=f'''Review immutable SOURCE-ONLY upstream width6 domain17 arity9 two-block scope at {F}. Read-only Read/Glob/Grep; no execution/build/edits. Actual Claude Opus5.5 high review requested. Whole upstream/global joined endpoint is not yet written and receives ZERO credit from this review. Focus NEW PoseidonTwoBlockComposition11, four Upstream11 B0/B1 R00/R01 Proof/Program/Data/Checks, two translated TailProof/Ports/RowChecks/Frame modules and maintained generate_probe.py/generate_tails.py/generate_prefix.py/generate_tail_frames.py/templates. Generic inherited CompilerColumnRenaming05, WindowRenaming05, TailTemplate05 Program+Semantic and width6 consumer facts are accepted dependencies, not fresh math. Both tails transport accepted rounds2..64 through injective renames offsets37722/38142, each279materialized+copy=280steps and372arithmetic+copy=373rows. Firsttail captures38084..38455 writes60822..61193; secondtail must exact descriptor actual corresponding bounds. Four freshprefixrounds total69materialized/92rows. Full intended upstream later627materialized+copy628steps/836arith+copy837rows, contiguousarith38040..38875, writes60778..61613. Outer inherited hash3 domain18 arity1 uses cut363983, rows38876..39191 and writes61614..61929; future composition must retain SAME FINAL rho. External cuts129141/129144 are two terms each cols[0,33796]/[0,33798], remain unconstrained; other9inputs have exact captured LCs. Block0 initial IV2321+[first5inputs], block1 addsremaining4inputs to first4ratecoords and padsonezero. Final resultword1 at LC363983. Parent DATA audit independently checked377prefixnodes/3120roundports/837rows/pinnedwidth6parameters and no kernelcredit. Check twochunk helper exact round0..64 semantics, add-one/chunk counts/state orientation, source->target rename direction, same-final-witness quantification, explicit Field/CharP p/rho0=1/4!=0/copylinked premises, completed constructors, frame/support checks, no hidden equality or tautological completion. Verify copy step occurs once in eventual join though individual constituents containcopy. Review finite exact row guard controls only; no semanticinequality/native correspondence from guard rejection. Review maintained generator reproducibility/provenance and no generatedhandedits. Check source/external dependency identities and audit attribution: manifest fresh_receipts only commandpaths upstream11, copied call10 -01 receipts inherited. Original outerAbsorb sourcehash0df58726edd35ed1679550882d0a6c71c698a452694ddbddc09e7ddaf7f5f0e2 differs corrected canonical header493588b4e0d6b18ed01bc711939e997690c8838232fa92d1143bddc9c09f7a92; original is valid immutable accepted historicalsource but must not be called currentcanonical. Report actionable mathematical/soundness/generator/scope defects with evidence, or no actionable defect in EXACT new partial source scope. FullTransfer, externalcutconstruction, native/raw/baseline correspondence and global200770-row relation OPEN.'''
(H/'review-prompt.txt').write_text(prompt+'\n'); start=time.monotonic()
cmd=['/Users/antoinecyr/.local/bin/claude','--model','claude-opus-5-5','--effort','high','--permission-mode','plan','--tools','Read,Glob,Grep','--strict-mcp-config','--no-session-persistence','--output-format','json','--print',prompt]
with (H/'opus55-review.json').open('w') as out,(H/'opus55-review.stderr').open('w') as err:r=subprocess.run(cmd,stdout=out,stderr=err,timeout=900)
j=json.loads((H/'opus55-review.json').read_text());assert r.returncode==0 and not j['is_error'] and 'claude-opus-5-5' in j['modelUsage']
assert all(sha(F/x['path'])==x['sha256'] for x in m['files'])
print(json.dumps({'review':'complete','files':len(m['files']),'seconds':time.monotonic()-start,'model':list(j['modelUsage'])}))
