/-
GENERATED by gen/gen_transfer_net_balance_semantics.py — do not edit by hand.
-/
import ShielddGnarkFormal.Deployed.Templates.Relations.TDecafNetBalanceCommitment_efd414b95488606e99678399b0406544c9fda192bad5db9de83ce274ba09a681
import ShielddGnarkFormal.Extracted.CanonicalFqBits
import ShielddGnarkFormal.ChoiceFreeZMod
import ShielddGnarkFormal.Deployed.Templates.Semantics.TDecafNetBalanceCommitment_efd414b95488606e99678399b0406544c9fda192bad5db9de83ce274ba09a681NbEncodeCanonTrueR13

set_option maxRecDepth 1000000
set_option maxHeartbeats 20000000
set_option linter.unusedVariables false

namespace Shieldd.GnarkFormal.Deployed.Templates.Semantics.TDecafNetBalanceCommitment_efd414b95488606e99678399b0406544c9fda192bad5db9de83ce274ba09a681.NbSupport

attribute [-instance] ZMod.instField
open scoped Shieldd.GnarkFormal.ChoiceFreeZMod

open Shieldd.GnarkFormal.Extracted.CanonicalFqBits

theorem nbEncodeCanon_flag_step_chunk14 (rho : Nat -> F) (h : Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafNetBalanceCommitment_efd414b95488606e99678399b0406544c9fda192bad5db9de83ce274ba09a681.relation rho) :
    ∀ m, 224 ≤ m → m < 240 → nbEncodeCanonFlag rho m = trueFactor (nbEncodeCanonBits rho) m * nbEncodeCanonFlag rho (m + 1) := by
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafNetBalanceCommitment_efd414b95488606e99678399b0406544c9fda192bad5db9de83ce274ba09a681.relation at h
  rcases h with ⟨
    _, _, _, _, _, _, p6, _, _, _,
    _, _, _, _, _, _, _, _, _, _,
    _, _, _, _, _, _, _, _, _, _,
    _, _, _, _, _, _, _, _, _, _,
    _, _, _, _, _, _, _, _, _, _,
    _, _, _, _, _, _, _, _, _, _,
    _, _, _, _, _, _, _, _, _, _,
    _, _, _, _, _, _, _, _
  ⟩
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafNetBalanceCommitment_efd414b95488606e99678399b0406544c9fda192bad5db9de83ce274ba09a681.relationPart6 at p6
  rcases p6 with ⟨_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, r518, r519, r520, r521, r522, r523, r524, r525, r526, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _⟩
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafNetBalanceCommitment_efd414b95488606e99678399b0406544c9fda192bad5db9de83ce274ba09a681.relationRow518 at r518
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafNetBalanceCommitment_efd414b95488606e99678399b0406544c9fda192bad5db9de83ce274ba09a681.relationRow519 at r519
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafNetBalanceCommitment_efd414b95488606e99678399b0406544c9fda192bad5db9de83ce274ba09a681.relationRow520 at r520
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafNetBalanceCommitment_efd414b95488606e99678399b0406544c9fda192bad5db9de83ce274ba09a681.relationRow521 at r521
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafNetBalanceCommitment_efd414b95488606e99678399b0406544c9fda192bad5db9de83ce274ba09a681.relationRow522 at r522
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafNetBalanceCommitment_efd414b95488606e99678399b0406544c9fda192bad5db9de83ce274ba09a681.relationRow523 at r523
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafNetBalanceCommitment_efd414b95488606e99678399b0406544c9fda192bad5db9de83ce274ba09a681.relationRow524 at r524
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafNetBalanceCommitment_efd414b95488606e99678399b0406544c9fda192bad5db9de83ce274ba09a681.relationRow525 at r525
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafNetBalanceCommitment_efd414b95488606e99678399b0406544c9fda192bad5db9de83ce274ba09a681.relationRow526 at r526
  intro m hmlo hmhi
  interval_cases m
  · rw [show nbEncodeCanonFlag rho 224 = rho 521 from rfl, show nbEncodeCanonFlag rho 225 = rho 521 from rfl]
    have hb : pmBit 224 = false := by decide +kernel
    rw [show trueFactor (nbEncodeCanonBits rho) 224 = 1 from by simp [trueFactor, hb]]
    ring
  · rw [show nbEncodeCanonFlag rho 225 = rho 521 from rfl, show nbEncodeCanonFlag rho 226 = rho 520 from rfl]
    have hb : pmBit 225 = true := by decide +kernel
    simp only [trueFactor, hb, ↓reduceIte]
    erw [nbEncodeCanonBits_get rho 225 (by omega)]
    simp only [Nat.reduceAdd]
    linear_combination -r526
  · rw [show nbEncodeCanonFlag rho 226 = rho 520 from rfl, show nbEncodeCanonFlag rho 227 = rho 519 from rfl]
    have hb : pmBit 226 = true := by decide +kernel
    simp only [trueFactor, hb, ↓reduceIte]
    erw [nbEncodeCanonBits_get rho 226 (by omega)]
    simp only [Nat.reduceAdd]
    linear_combination -r525
  · rw [show nbEncodeCanonFlag rho 227 = rho 519 from rfl, show nbEncodeCanonFlag rho 228 = rho 518 from rfl]
    have hb : pmBit 227 = true := by decide +kernel
    simp only [trueFactor, hb, ↓reduceIte]
    erw [nbEncodeCanonBits_get rho 227 (by omega)]
    simp only [Nat.reduceAdd]
    linear_combination -r524
  · rw [show nbEncodeCanonFlag rho 228 = rho 518 from rfl, show nbEncodeCanonFlag rho 229 = rho 517 from rfl]
    have hb : pmBit 228 = true := by decide +kernel
    simp only [trueFactor, hb, ↓reduceIte]
    erw [nbEncodeCanonBits_get rho 228 (by omega)]
    simp only [Nat.reduceAdd]
    linear_combination -r523
  · rw [show nbEncodeCanonFlag rho 229 = rho 517 from rfl, show nbEncodeCanonFlag rho 230 = rho 517 from rfl]
    have hb : pmBit 229 = false := by decide +kernel
    rw [show trueFactor (nbEncodeCanonBits rho) 229 = 1 from by simp [trueFactor, hb]]
    ring
  · rw [show nbEncodeCanonFlag rho 230 = rho 517 from rfl, show nbEncodeCanonFlag rho 231 = rho 516 from rfl]
    have hb : pmBit 230 = true := by decide +kernel
    simp only [trueFactor, hb, ↓reduceIte]
    erw [nbEncodeCanonBits_get rho 230 (by omega)]
    simp only [Nat.reduceAdd]
    linear_combination -r522
  · rw [show nbEncodeCanonFlag rho 231 = rho 516 from rfl, show nbEncodeCanonFlag rho 232 = rho 516 from rfl]
    have hb : pmBit 231 = false := by decide +kernel
    rw [show trueFactor (nbEncodeCanonBits rho) 231 = 1 from by simp [trueFactor, hb]]
    ring
  · rw [show nbEncodeCanonFlag rho 232 = rho 516 from rfl, show nbEncodeCanonFlag rho 233 = rho 515 from rfl]
    have hb : pmBit 232 = true := by decide +kernel
    simp only [trueFactor, hb, ↓reduceIte]
    erw [nbEncodeCanonBits_get rho 232 (by omega)]
    simp only [Nat.reduceAdd]
    linear_combination -r521
  · rw [show nbEncodeCanonFlag rho 233 = rho 515 from rfl, show nbEncodeCanonFlag rho 234 = rho 515 from rfl]
    have hb : pmBit 233 = false := by decide +kernel
    rw [show trueFactor (nbEncodeCanonBits rho) 233 = 1 from by simp [trueFactor, hb]]
    ring
  · rw [show nbEncodeCanonFlag rho 234 = rho 515 from rfl, show nbEncodeCanonFlag rho 235 = rho 514 from rfl]
    have hb : pmBit 234 = true := by decide +kernel
    simp only [trueFactor, hb, ↓reduceIte]
    erw [nbEncodeCanonBits_get rho 234 (by omega)]
    simp only [Nat.reduceAdd]
    linear_combination -r520
  · rw [show nbEncodeCanonFlag rho 235 = rho 514 from rfl, show nbEncodeCanonFlag rho 236 = rho 514 from rfl]
    have hb : pmBit 235 = false := by decide +kernel
    rw [show trueFactor (nbEncodeCanonBits rho) 235 = 1 from by simp [trueFactor, hb]]
    ring
  · rw [show nbEncodeCanonFlag rho 236 = rho 514 from rfl, show nbEncodeCanonFlag rho 237 = rho 514 from rfl]
    have hb : pmBit 236 = false := by decide +kernel
    rw [show trueFactor (nbEncodeCanonBits rho) 236 = 1 from by simp [trueFactor, hb]]
    ring
  · rw [show nbEncodeCanonFlag rho 237 = rho 514 from rfl, show nbEncodeCanonFlag rho 238 = rho 513 from rfl]
    have hb : pmBit 237 = true := by decide +kernel
    simp only [trueFactor, hb, ↓reduceIte]
    erw [nbEncodeCanonBits_get rho 237 (by omega)]
    simp only [Nat.reduceAdd]
    linear_combination -r519
  · rw [show nbEncodeCanonFlag rho 238 = rho 513 from rfl, show nbEncodeCanonFlag rho 239 = rho 512 from rfl]
    have hb : pmBit 238 = true := by decide +kernel
    simp only [trueFactor, hb, ↓reduceIte]
    erw [nbEncodeCanonBits_get rho 238 (by omega)]
    simp only [Nat.reduceAdd]
    linear_combination -r518
  · rw [show nbEncodeCanonFlag rho 239 = rho 512 from rfl, show nbEncodeCanonFlag rho 240 = rho 512 from rfl]
    have hb : pmBit 239 = false := by decide +kernel
    rw [show trueFactor (nbEncodeCanonBits rho) 239 = 1 from by simp [trueFactor, hb]]
    ring

end Shieldd.GnarkFormal.Deployed.Templates.Semantics.TDecafNetBalanceCommitment_efd414b95488606e99678399b0406544c9fda192bad5db9de83ce274ba09a681.NbSupport
