/-
GENERATED by gen/gen_note_reshape_nb_semantics.py — do not edit by hand.
-/
import ShielddGnarkFormal.ChoiceFreeZMod
import ShielddGnarkFormal.Deployed.Templates.Semantics.TDecafConservationNetBalanceCommitment2_236fd0549adf468bfd993cdf1a3c2b4bbf80d1c8f9b95e4fda163888ecd365f6NbBlindSel0_25
import ShielddGnarkFormal.Deployed.Templates.Semantics.TDecafConservationNetBalanceCommitment2_236fd0549adf468bfd993cdf1a3c2b4bbf80d1c8f9b95e4fda163888ecd365f6NbBlindSeed

set_option maxRecDepth 1000000
set_option maxHeartbeats 20000000
set_option linter.unusedVariables false

namespace Shieldd.GnarkFormal.Deployed.Templates.Semantics.TDecafConservationNetBalanceCommitment2_236fd0549adf468bfd993cdf1a3c2b4bbf80d1c8f9b95e4fda163888ecd365f6.NbSupport

open scoped Shieldd.GnarkFormal.ChoiceFreeZMod

theorem nbBlind_hstep (rho : Nat -> F) (h : Shieldd.GnarkFormal.Deployed.Templates.Relations.TDecafConservationNetBalanceCommitment2_236fd0549adf468bfd993cdf1a3c2b4bbf80d1c8f9b95e4fda163888ecd365f6.relation rho)
    (bits : List.Vector Bool 251)
    (hbitAt : ∀ i, i < 251 → rho (517 + i) = Bool.toZMod bits[i]!) :
    ∀ i, i < 251 →
      EdwardsBridge.onCurve (nbBlindAccState rho i) →
      Shieldd.GnarkFormal.Deployed.NetBalanceChoiceFree.NbFixedStepRel i
        (Bool.toZMod bits[i]!) (nbBlindAccState rho i)
        (nbBlindAccState rho (i + 1)) := by
  intro i hi hacc
  by_cases hzero : i = 0
  · subst i
    have hb0 : rho 517 = Bool.toZMod bits[0]! := by
      simpa using hbitAt 0 (by omega)
    exact nbBlind_hstep_zero rho bits hb0
  ·
    exact nbBlind_hstep_s0_25 rho h bits hbitAt i (by omega) hi hacc

end Shieldd.GnarkFormal.Deployed.Templates.Semantics.TDecafConservationNetBalanceCommitment2_236fd0549adf468bfd993cdf1a3c2b4bbf80d1c8f9b95e4fda163888ecd365f6.NbSupport
