/-
GENERATED by gen/gen_certified_composite_semantics.py -- do not edit.
-/
import ShielddGnarkFormal.Deployed.Templates.Semantics.TGadgetPoseidonEncryptionDetection_0a6a5e4c12f0e8b1d9f23e22029e1017258442dced1d768cadd8656136bd44eaPoseidonBlock3Base
import ShielddGnarkFormal.Deployed.Templates.Relations.TGadgetPoseidonEncryptionDetection_0a6a5e4c12f0e8b1d9f23e22029e1017258442dced1d768cadd8656136bd44ea
import ShielddGnarkFormal.Deployed.Poseidon2Link
import Mathlib.Tactic.LinearCombination
import Mathlib.Tactic.Ring

set_option maxRecDepth 1000000
set_option maxHeartbeats 10000000

namespace Shieldd.GnarkFormal.Deployed.Templates.Semantics.TGadgetPoseidonEncryptionDetection_0a6a5e4c12f0e8b1d9f23e22029e1017258442dced1d768cadd8656136bd44eaPoseidon.Block3.Gate0

open Shieldd.GnarkFormal.Deployed.Templates.Semantics.TGadgetPoseidonEncryptionDetection_0a6a5e4c12f0e8b1d9f23e22029e1017258442dced1d768cadd8656136bd44eaPoseidon.Block3
attribute [-instance] ZMod.instField
open scoped Shieldd.GnarkFormal.ChoiceFreeZMod

theorem block3Part0 (rho : Nat → F) (h1846 : Shieldd.GnarkFormal.Deployed.Templates.Relations.TGadgetPoseidonEncryptionDetection_0a6a5e4c12f0e8b1d9f23e22029e1017258442dced1d768cadd8656136bd44ea.relationRow1846 rho) (h1847 : Shieldd.GnarkFormal.Deployed.Templates.Relations.TGadgetPoseidonEncryptionDetection_0a6a5e4c12f0e8b1d9f23e22029e1017258442dced1d768cadd8656136bd44ea.relationRow1847 rho) (h1848 : Shieldd.GnarkFormal.Deployed.Templates.Relations.TGadgetPoseidonEncryptionDetection_0a6a5e4c12f0e8b1d9f23e22029e1017258442dced1d768cadd8656136bd44ea.relationRow1848 rho) (h1849 : Shieldd.GnarkFormal.Deployed.Templates.Relations.TGadgetPoseidonEncryptionDetection_0a6a5e4c12f0e8b1d9f23e22029e1017258442dced1d768cadd8656136bd44ea.relationRow1849 rho) (h1850 : Shieldd.GnarkFormal.Deployed.Templates.Relations.TGadgetPoseidonEncryptionDetection_0a6a5e4c12f0e8b1d9f23e22029e1017258442dced1d768cadd8656136bd44ea.relationRow1850 rho) :
    rho 1514 = Shieldd.GnarkFormal.Poseidon2Bridge.p17
      (block3RoundInput0 rho) := by
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TGadgetPoseidonEncryptionDetection_0a6a5e4c12f0e8b1d9f23e22029e1017258442dced1d768cadd8656136bd44ea.relationRow1846 at h1846
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TGadgetPoseidonEncryptionDetection_0a6a5e4c12f0e8b1d9f23e22029e1017258442dced1d768cadd8656136bd44ea.relationRow1847 at h1847
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TGadgetPoseidonEncryptionDetection_0a6a5e4c12f0e8b1d9f23e22029e1017258442dced1d768cadd8656136bd44ea.relationRow1848 at h1848
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TGadgetPoseidonEncryptionDetection_0a6a5e4c12f0e8b1d9f23e22029e1017258442dced1d768cadd8656136bd44ea.relationRow1849 at h1849
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TGadgetPoseidonEncryptionDetection_0a6a5e4c12f0e8b1d9f23e22029e1017258442dced1d768cadd8656136bd44ea.relationRow1850 at h1850
  have hblock3Input0 : block3RoundInput0 rho = (686850750308311448868354907988153221833589417264043199872750834851275630399 : F) + (6333346312071277818186618704086159898531924501365547870951425091938056929281 : F) * rho 969 + (6755569399542696339399059951025237225100719468123251062348186764733927391233 : F) * rho 974 + (7037051457856975353540687448984622109479916112628386523279361213264507699201 : F) * rho 979 := by
    unfold block3RoundInput0
    rfl
  apply Shieldd.GnarkFormal.Deployed.Templates.Semantics.TransferPoseidon2Trace.p17_from_rows
      (block3RoundInput0 rho)
      (rho 1510) (rho 1511) (rho 1512) (rho 1513) (rho 1514)
  · rw [hblock3Input0]; linear_combination h1846
  · linear_combination h1847
  · linear_combination h1848
  · linear_combination h1849
  · rw [hblock3Input0]; linear_combination h1850

theorem sound (rho : Nat → F)
    (h : Shieldd.GnarkFormal.Deployed.Templates.Relations.TGadgetPoseidonEncryptionDetection_0a6a5e4c12f0e8b1d9f23e22029e1017258442dced1d768cadd8656136bd44ea.relation rho) :
    Shieldd.GnarkFormal.Deployed.Templates.Semantics.TransferPoseidon2Trace.state0 block3Domain (block3Input0 rho)
      (block3Input1 rho) = block3Endpoint0 rho := by
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TGadgetPoseidonEncryptionDetection_0a6a5e4c12f0e8b1d9f23e22029e1017258442dced1d768cadd8656136bd44ea.relation at h
  rcases h with ⟨
    _, _, _, _, _, _, _, _,
    _, _, _, _, _, _, _, _,
    _, _, _, _, _, _, _, p23,
    _, _, _, _, _, _
  ⟩
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TGadgetPoseidonEncryptionDetection_0a6a5e4c12f0e8b1d9f23e22029e1017258442dced1d768cadd8656136bd44ea.relationPart23 at p23
  rcases p23 with ⟨_, _, _, _, _, _, h1846, h1847, h1848, h1849, h1850, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _⟩
  have hp0 := block3Part0 rho h1846 h1847 h1848 h1849 h1850
  have hd : (2291406258905483745986705272934958367779094442878820893808737928129816255727 : F) =
      Shieldd.GnarkFormal.Poseidon2Bridge.p17
        ((vec![block3Domain, block3Input0 rho, block3Input1 rho])[0] +
          Shieldd.GnarkFormal.Deployed.Templates.Semantics.TransferPoseidon2Trace.roundConstants0[0]) := by
    simpa [block3Domain, Shieldd.GnarkFormal.Deployed.Templates.Semantics.TransferPoseidon2Trace.roundConstants0] using block3DomainP17
  have hLane1 : rho 1514 =
      Shieldd.GnarkFormal.Poseidon2Bridge.p17
        ((vec![block3Domain, block3Input0 rho, block3Input1 rho])[1] +
          Shieldd.GnarkFormal.Deployed.Templates.Semantics.TransferPoseidon2Trace.roundConstants0[1]) := by
    rw [block3RoundInput0_eq_initial_arg] at hp0
    simpa [Shieldd.GnarkFormal.Deployed.Templates.Semantics.TransferPoseidon2Trace.roundConstants0] using hp0
  have hInput1 : (1719919187803793182314175058023251327673729762639004630196909638005543903614 : F) =
      Shieldd.GnarkFormal.Poseidon2Bridge.p17
        ((vec![block3Domain, block3Input0 rho, block3Input1 rho])[2] +
          Shieldd.GnarkFormal.Deployed.Templates.Semantics.TransferPoseidon2Trace.roundConstants0[2]) := by
    simpa [block3Input1, Shieldd.GnarkFormal.Deployed.Templates.Semantics.TransferPoseidon2Trace.roundConstants0] using block3Input1P17
  let raw : List.Vector F 3 := vec![
      Shieldd.GnarkFormal.Deployed.Poseidon2Link.row3 (5629641166285580282832549959187697687583932890102709218623488970611606159361 : F) (6333346312071277818186618704086159898531924501365547870951425091938056929281 : F) (6755569399542696339399059951025237225100719468123251062348186764733927391233 : F) (2291406258905483745986705272934958367779094442878820893808737928129816255727 : F) (rho 1514) (1719919187803793182314175058023251327673729762639004630196909638005543903614 : F),
        Shieldd.GnarkFormal.Deployed.Poseidon2Link.row3 (6333346312071277818186618704086159898531924501365547870951425091938056929281 : F) (6755569399542696339399059951025237225100719468123251062348186764733927391233 : F) (7037051457856975353540687448984622109479916112628386523279361213264507699201 : F) (2291406258905483745986705272934958367779094442878820893808737928129816255727 : F) (rho 1514) (1719919187803793182314175058023251327673729762639004630196909638005543903614 : F),
        Shieldd.GnarkFormal.Deployed.Poseidon2Link.row3 (6755569399542696339399059951025237225100719468123251062348186764733927391233 : F) (7037051457856975353540687448984622109479916112628386523279361213264507699201 : F) (7238110070938603220784707090384182741179342287274911852515914390786350776321 : F) (2291406258905483745986705272934958367779094442878820893808737928129816255727 : F) (rho 1514) (1719919187803793182314175058023251327673729762639004630196909638005543903614 : F)]
  have hRaw : Shieldd.GnarkFormal.Deployed.Templates.Semantics.TransferPoseidon2Trace.state0 block3Domain (block3Input0 rho) (block3Input1 rho) = raw := by
    unfold Shieldd.GnarkFormal.Deployed.Templates.Semantics.TransferPoseidon2Trace.state0 raw
    exact Shieldd.GnarkFormal.Deployed.Poseidon2Link.fr_eq3
      (vec![block3Domain, block3Input0 rho, block3Input1 rho])
      Shieldd.GnarkFormal.Deployed.Templates.Semantics.TransferPoseidon2Trace.roundConstants0
      (2291406258905483745986705272934958367779094442878820893808737928129816255727 : F) (rho 1514) (1719919187803793182314175058023251327673729762639004630196909638005543903614 : F)
      hd hLane1 hInput1
  have hCurrent : Shieldd.GnarkFormal.Deployed.Templates.Semantics.TransferPoseidon2Trace.state0 block3Domain (block3Input0 rho) (block3Input1 rho) = block3Endpoint0 rho := by
    rw [hRaw]
    unfold raw
    have hc0_0 : (24518828438632378932902938443201738405708499676139355961616060586620106153126074527834073880963702459489221418185518654929403452231862988252486111526509 : F) = (2796678273748260636641501757005945694402957300518220656229341261494529380440 : F) := by
      exact Shieldd.GnarkFormal.ChoiceFreeZMod.natCast_eq_natCast_of_mod_eq Order 24518828438632378932902938443201738405708499676139355961616060586620106153126074527834073880963702459489221418185518654929403452231862988252486111526509 2796678273748260636641501757005945694402957300518220656229341261494529380440 (by decide) (by decide)
    have hc1_0 : (26615429207226956875694989756675427711075463684944167341376191155447527382523995860386383627924012037340872136705348375184289183485584082352557899054701 : F) = (2970620200050762406277911729266334779401036738281388618802144452346063690961 : F) := by
      exact Shieldd.GnarkFormal.ChoiceFreeZMod.natCast_eq_natCast_of_mod_eq Order 26615429207226956875694989756675427711075463684944167341376191155447527382523995860386383627924012037340872136705348375184289183485584082352557899054701 2970620200050762406277911729266334779401036738281388618802144452346063690961 (by decide) (by decide)
    have hc2_0 : (27928718399025673322731410030012585751172590573124917490114662468429699665290882178074690094874147248025755835391042122113540620642660228726070803365485 : F) = (945254328593877787363618203984071764119948835671452378159455632652966929920 : F) := by
      exact Shieldd.GnarkFormal.ChoiceFreeZMod.natCast_eq_natCast_of_mod_eq Order 27928718399025673322731410030012585751172590573124917490114662468429699665290882178074690094874147248025755835391042122113540620642660228726070803365485 945254328593877787363618203984071764119948835671452378159455632652966929920 (by decide) (by decide)
    apply List.Vector.eq
    simp [block3Endpoint0, Shieldd.GnarkFormal.Deployed.Poseidon2Link.row3]
    constructor
    · ring_nf
      rw [hc0_0]
    · constructor
      · ring_nf
        rw [hc1_0]
      · ring_nf
        rw [hc2_0]
  exact hCurrent

end Shieldd.GnarkFormal.Deployed.Templates.Semantics.TGadgetPoseidonEncryptionDetection_0a6a5e4c12f0e8b1d9f23e22029e1017258442dced1d768cadd8656136bd44eaPoseidon.Block3.Gate0
