/-
GENERATED by gen/gen_certified_composite_semantics.py -- do not edit.
-/
import ShielddGnarkFormal.Deployed.Templates.Semantics.TGadgetPoseidonEncryptionDetection_0a6a5e4c12f0e8b1d9f23e22029e1017258442dced1d768cadd8656136bd44eaPoseidonBlock4Base
import ShielddGnarkFormal.Deployed.Templates.Relations.TGadgetPoseidonEncryptionDetection_0a6a5e4c12f0e8b1d9f23e22029e1017258442dced1d768cadd8656136bd44ea
import ShielddGnarkFormal.Deployed.Poseidon2Link
import Mathlib.Tactic.LinearCombination
import Mathlib.Tactic.Ring

set_option maxRecDepth 1000000
set_option maxHeartbeats 10000000

namespace Shieldd.GnarkFormal.Deployed.Templates.Semantics.TGadgetPoseidonEncryptionDetection_0a6a5e4c12f0e8b1d9f23e22029e1017258442dced1d768cadd8656136bd44eaPoseidon.Block4.Gate0

open Shieldd.GnarkFormal.Deployed.Templates.Semantics.TGadgetPoseidonEncryptionDetection_0a6a5e4c12f0e8b1d9f23e22029e1017258442dced1d768cadd8656136bd44eaPoseidon.Block4
attribute [-instance] ZMod.instField
open scoped Shieldd.GnarkFormal.ChoiceFreeZMod

theorem block4Part0 (rho : Nat → F) (h2111 : Shieldd.GnarkFormal.Deployed.Templates.Relations.TGadgetPoseidonEncryptionDetection_0a6a5e4c12f0e8b1d9f23e22029e1017258442dced1d768cadd8656136bd44ea.relationRow2111 rho) (h2112 : Shieldd.GnarkFormal.Deployed.Templates.Relations.TGadgetPoseidonEncryptionDetection_0a6a5e4c12f0e8b1d9f23e22029e1017258442dced1d768cadd8656136bd44ea.relationRow2112 rho) (h2113 : Shieldd.GnarkFormal.Deployed.Templates.Relations.TGadgetPoseidonEncryptionDetection_0a6a5e4c12f0e8b1d9f23e22029e1017258442dced1d768cadd8656136bd44ea.relationRow2113 rho) (h2114 : Shieldd.GnarkFormal.Deployed.Templates.Relations.TGadgetPoseidonEncryptionDetection_0a6a5e4c12f0e8b1d9f23e22029e1017258442dced1d768cadd8656136bd44ea.relationRow2114 rho) (h2115 : Shieldd.GnarkFormal.Deployed.Templates.Relations.TGadgetPoseidonEncryptionDetection_0a6a5e4c12f0e8b1d9f23e22029e1017258442dced1d768cadd8656136bd44ea.relationRow2115 rho) :
    rho 1779 = Shieldd.GnarkFormal.Poseidon2Bridge.p17
      (block4RoundInput0 rho) := by
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TGadgetPoseidonEncryptionDetection_0a6a5e4c12f0e8b1d9f23e22029e1017258442dced1d768cadd8656136bd44ea.relationRow2111 at h2111
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TGadgetPoseidonEncryptionDetection_0a6a5e4c12f0e8b1d9f23e22029e1017258442dced1d768cadd8656136bd44ea.relationRow2112 at h2112
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TGadgetPoseidonEncryptionDetection_0a6a5e4c12f0e8b1d9f23e22029e1017258442dced1d768cadd8656136bd44ea.relationRow2113 at h2113
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TGadgetPoseidonEncryptionDetection_0a6a5e4c12f0e8b1d9f23e22029e1017258442dced1d768cadd8656136bd44ea.relationRow2114 at h2114
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TGadgetPoseidonEncryptionDetection_0a6a5e4c12f0e8b1d9f23e22029e1017258442dced1d768cadd8656136bd44ea.relationRow2115 at h2115
  have hblock4Input0 : block4RoundInput0 rho = (686850750308311448868354907988153221833589417264043199872750834851275630399 : F) + (6333346312071277818186618704086159898531924501365547870951425091938056929281 : F) * rho 969 + (6755569399542696339399059951025237225100719468123251062348186764733927391233 : F) * rho 974 + (7037051457856975353540687448984622109479916112628386523279361213264507699201 : F) * rho 979 := by
    unfold block4RoundInput0
    rfl
  apply Shieldd.GnarkFormal.Deployed.Templates.Semantics.TransferPoseidon2Trace.p17_from_rows
      (block4RoundInput0 rho)
      (rho 1775) (rho 1776) (rho 1777) (rho 1778) (rho 1779)
  · rw [hblock4Input0]; linear_combination h2111
  · linear_combination h2112
  · linear_combination h2113
  · linear_combination h2114
  · rw [hblock4Input0]; linear_combination h2115

theorem sound (rho : Nat → F)
    (h : Shieldd.GnarkFormal.Deployed.Templates.Relations.TGadgetPoseidonEncryptionDetection_0a6a5e4c12f0e8b1d9f23e22029e1017258442dced1d768cadd8656136bd44ea.relation rho) :
    Shieldd.GnarkFormal.Deployed.Templates.Semantics.TransferPoseidon2Trace.state0 block4Domain (block4Input0 rho)
      (block4Input1 rho) = block4Endpoint0 rho := by
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TGadgetPoseidonEncryptionDetection_0a6a5e4c12f0e8b1d9f23e22029e1017258442dced1d768cadd8656136bd44ea.relation at h
  rcases h with ⟨
    _, _, _, _, _, _, _, _,
    _, _, _, _, _, _, _, _,
    _, _, _, _, _, _, _, _,
    _, _, p26, _, _, _
  ⟩
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TGadgetPoseidonEncryptionDetection_0a6a5e4c12f0e8b1d9f23e22029e1017258442dced1d768cadd8656136bd44ea.relationPart26 at p26
  rcases p26 with ⟨_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, h2111, h2112, h2113, h2114, h2115, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _⟩
  have hp0 := block4Part0 rho h2111 h2112 h2113 h2114 h2115
  have hd : (2291406258905483745986705272934958367779094442878820893808737928129816255727 : F) =
      Shieldd.GnarkFormal.Poseidon2Bridge.p17
        ((vec![block4Domain, block4Input0 rho, block4Input1 rho])[0] +
          Shieldd.GnarkFormal.Deployed.Templates.Semantics.TransferPoseidon2Trace.roundConstants0[0]) := by
    simpa [block4Domain, Shieldd.GnarkFormal.Deployed.Templates.Semantics.TransferPoseidon2Trace.roundConstants0] using block4DomainP17
  have hLane1 : rho 1779 =
      Shieldd.GnarkFormal.Poseidon2Bridge.p17
        ((vec![block4Domain, block4Input0 rho, block4Input1 rho])[1] +
          Shieldd.GnarkFormal.Deployed.Templates.Semantics.TransferPoseidon2Trace.roundConstants0[1]) := by
    rw [block4RoundInput0_eq_initial_arg] at hp0
    simpa [Shieldd.GnarkFormal.Deployed.Templates.Semantics.TransferPoseidon2Trace.roundConstants0] using hp0
  have hInput1 : (4681687090888128780555939887065221392490335784464065692533891770770061489736 : F) =
      Shieldd.GnarkFormal.Poseidon2Bridge.p17
        ((vec![block4Domain, block4Input0 rho, block4Input1 rho])[2] +
          Shieldd.GnarkFormal.Deployed.Templates.Semantics.TransferPoseidon2Trace.roundConstants0[2]) := by
    simpa [block4Input1, Shieldd.GnarkFormal.Deployed.Templates.Semantics.TransferPoseidon2Trace.roundConstants0] using block4Input1P17
  let raw : List.Vector F 3 := vec![
      Shieldd.GnarkFormal.Deployed.Poseidon2Link.row3 (5629641166285580282832549959187697687583932890102709218623488970611606159361 : F) (6333346312071277818186618704086159898531924501365547870951425091938056929281 : F) (6755569399542696339399059951025237225100719468123251062348186764733927391233 : F) (2291406258905483745986705272934958367779094442878820893808737928129816255727 : F) (rho 1779) (4681687090888128780555939887065221392490335784464065692533891770770061489736 : F),
        Shieldd.GnarkFormal.Deployed.Poseidon2Link.row3 (6333346312071277818186618704086159898531924501365547870951425091938056929281 : F) (6755569399542696339399059951025237225100719468123251062348186764733927391233 : F) (7037051457856975353540687448984622109479916112628386523279361213264507699201 : F) (2291406258905483745986705272934958367779094442878820893808737928129816255727 : F) (rho 1779) (4681687090888128780555939887065221392490335784464065692533891770770061489736 : F),
        Shieldd.GnarkFormal.Deployed.Poseidon2Link.row3 (6755569399542696339399059951025237225100719468123251062348186764733927391233 : F) (7037051457856975353540687448984622109479916112628386523279361213264507699201 : F) (7238110070938603220784707090384182741179342287274911852515914390786350776321 : F) (2291406258905483745986705272934958367779094442878820893808737928129816255727 : F) (rho 1779) (4681687090888128780555939887065221392490335784464065692533891770770061489736 : F)]
  have hRaw : Shieldd.GnarkFormal.Deployed.Templates.Semantics.TransferPoseidon2Trace.state0 block4Domain (block4Input0 rho) (block4Input1 rho) = raw := by
    unfold Shieldd.GnarkFormal.Deployed.Templates.Semantics.TransferPoseidon2Trace.state0 raw
    exact Shieldd.GnarkFormal.Deployed.Poseidon2Link.fr_eq3
      (vec![block4Domain, block4Input0 rho, block4Input1 rho])
      Shieldd.GnarkFormal.Deployed.Templates.Semantics.TransferPoseidon2Trace.roundConstants0
      (2291406258905483745986705272934958367779094442878820893808737928129816255727 : F) (rho 1779) (4681687090888128780555939887065221392490335784464065692533891770770061489736 : F)
      hd hLane1 hInput1
  have hCurrent : Shieldd.GnarkFormal.Deployed.Templates.Semantics.TransferPoseidon2Trace.state0 block4Domain (block4Input0 rho) (block4Input1 rho) = block4Endpoint0 rho := by
    rw [hRaw]
    unfold raw
    have hc0_0 : (44527257053256654815784861817798272987845787513945949255565101712818066530830327178281883501033403321673981001497363879747621053166768323750755976794935 : F) = (11247154593779586590324747301721094815918770821607337522644305680469202048 : F) := by
      exact Shieldd.GnarkFormal.ChoiceFreeZMod.natCast_eq_natCast_of_mod_eq Order 44527257053256654815784861817798272987845787513945949255565101712818066530830327178281883501033403321673981001497363879747621053166768323750755976794935 11247154593779586590324747301721094815918770821607337522644305680469202048 (by decide) (by decide)
    have hc1_0 : (47457542347460577587030326605213484567468471849326035355906442328570402775965802297606890134846690361915453287235819792452356473581846432574390487143223 : F) = (649427600755361531235264221179480946411837963534210853213230322501013542301 : F) := by
      exact Shieldd.GnarkFormal.ChoiceFreeZMod.natCast_eq_natCast_of_mod_eq Order 47457542347460577587030326605213484567468471849326035355906442328570402775965802297606890134846690361915453287235819792452356473581846432574390487143223 649427600755361531235264221179480946411837963534210853213230322501013542301 (by decide) (by decide)
    have hc2_0 : (49366320486123111768676327931366015660605398970774838876488635103641800069973798462989980092406095188593066676791960819702929117282749018036162479182647 : F) = (162012350544729955076895331164132268897192648053023411645419729345410979503 : F) := by
      exact Shieldd.GnarkFormal.ChoiceFreeZMod.natCast_eq_natCast_of_mod_eq Order 49366320486123111768676327931366015660605398970774838876488635103641800069973798462989980092406095188593066676791960819702929117282749018036162479182647 162012350544729955076895331164132268897192648053023411645419729345410979503 (by decide) (by decide)
    apply List.Vector.eq
    simp [block4Endpoint0, Shieldd.GnarkFormal.Deployed.Poseidon2Link.row3]
    constructor
    · ring_nf
      rw [hc0_0]
    · constructor
      · ring_nf
        rw [hc1_0]
      · ring_nf
        rw [hc2_0]
  exact hCurrent

end Shieldd.GnarkFormal.Deployed.Templates.Semantics.TGadgetPoseidonEncryptionDetection_0a6a5e4c12f0e8b1d9f23e22029e1017258442dced1d768cadd8656136bd44eaPoseidon.Block4.Gate0
