/-
GENERATED by gen/gen_certified_statement_hash_semantics.py -- do not edit.
-/
import ShielddGnarkFormal.ChoiceFreeZMod
import ShielddGnarkFormal.Deployed.Templates.Relations.TStatementHash_19301faada329781da94b45e73c6963e9c85b971e364be5e52987753c670f898
import ShielddGnarkFormal.Deployed.StatementHashDeployedBridge
import ShielddGnarkFormal.Deployed.PrimeOrderCertificate
import Mathlib.Tactic.LinearCombination

set_option maxRecDepth 1000000
set_option maxHeartbeats 20000000

namespace Shieldd.GnarkFormal.Deployed.Templates.Semantics.TStatementHash_19301faada329781da94b45e73c6963e9c85b971e364be5e52987753c670f898.Part4

open scoped Shieldd.GnarkFormal.ChoiceFreeZMod

abbrev Order : Nat := Shieldd.GnarkFormal.Extracted.Deployed.StatementHash470_5c3d95.Order
abbrev F := Shieldd.GnarkFormal.Extracted.Deployed.StatementHash470_5c3d95.F

local instance : Fact (Nat.Prime Order) :=
  ⟨Shieldd.GnarkFormal.Deployed.decaf377ScalarFieldPrime⟩

theorem sound (rho : Nat → F)
    (h : Shieldd.GnarkFormal.Deployed.Templates.Relations.TStatementHash_19301faada329781da94b45e73c6963e9c85b971e364be5e52987753c670f898.relationPart4 rho) :
    rho 35 = Shieldd.GnarkFormal.Poseidon7Bridge.p17 ((6272479754287970578862595324992340484978405419892931973174493569973500133363 : F) + (7600015574485533381823942444903391878238309401638657445141710110325668315137 : F) * rho 13 + (2303035022571373752067861346940421781284336182314744680345972760704747974284 : F) * rho 19 + (7740756603642672888894756193883084320427907723891225175607297334590958469121 : F) * rho 25) := by
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TStatementHash_19301faada329781da94b45e73c6963e9c85b971e364be5e52987753c670f898.relationPart4 Shieldd.GnarkFormal.Deployed.Templates.Relations.TStatementHash_19301faada329781da94b45e73c6963e9c85b971e364be5e52987753c670f898.relationRow20 Shieldd.GnarkFormal.Deployed.Templates.Relations.TStatementHash_19301faada329781da94b45e73c6963e9c85b971e364be5e52987753c670f898.relationRow21 Shieldd.GnarkFormal.Deployed.Templates.Relations.TStatementHash_19301faada329781da94b45e73c6963e9c85b971e364be5e52987753c670f898.relationRow22 Shieldd.GnarkFormal.Deployed.Templates.Relations.TStatementHash_19301faada329781da94b45e73c6963e9c85b971e364be5e52987753c670f898.relationRow23 Shieldd.GnarkFormal.Deployed.Templates.Relations.TStatementHash_19301faada329781da94b45e73c6963e9c85b971e364be5e52987753c670f898.relationRow24 at h
  rcases h with ⟨h0, h1, h2, h3, h4⟩

  exact Shieldd.GnarkFormal.Deployed.StatementHash.p17_from_rows
    ((6272479754287970578862595324992340484978405419892931973174493569973500133363 : F) + (7600015574485533381823942444903391878238309401638657445141710110325668315137 : F) * rho 13 + (2303035022571373752067861346940421781284336182314744680345972760704747974284 : F) * rho 19 + (7740756603642672888894756193883084320427907723891225175607297334590958469121 : F) * rho 25) (rho 31) (rho 32) (rho 33) (rho 34) (rho 35)
    (by simpa only [one_mul] using h0)
    (by simpa only [one_mul] using h1)
    (by simpa only [one_mul] using h2)
    (by simpa only [one_mul] using h3)
    (by simpa only [one_mul] using h4)

end Shieldd.GnarkFormal.Deployed.Templates.Semantics.TStatementHash_19301faada329781da94b45e73c6963e9c85b971e364be5e52987753c670f898.Part4
