/-
GENERATED by gen/gen_certified_statement_hash_semantics.py -- do not edit.
-/
import ShielddGnarkFormal.ChoiceFreeZMod
import ShielddGnarkFormal.Deployed.Templates.Relations.TStatementHash_5804cb48cce27e24aa8fa559e9e23e995c25c83d8af6b4ef440384b01de85476
import ShielddGnarkFormal.Deployed.StatementHashDeployedBridge
import ShielddGnarkFormal.Deployed.PrimeOrderCertificate
import Mathlib.Tactic.LinearCombination

set_option maxRecDepth 1000000
set_option maxHeartbeats 20000000

namespace Shieldd.GnarkFormal.Deployed.Templates.Semantics.TStatementHash_5804cb48cce27e24aa8fa559e9e23e995c25c83d8af6b4ef440384b01de85476.Part93

open scoped Shieldd.GnarkFormal.ChoiceFreeZMod

abbrev Order : Nat := Shieldd.GnarkFormal.Extracted.Deployed.StatementHash470_5c3d95.Order
abbrev F := Shieldd.GnarkFormal.Extracted.Deployed.StatementHash470_5c3d95.F

local instance : Fact (Nat.Prime Order) :=
  ⟨Shieldd.GnarkFormal.Deployed.decaf377ScalarFieldPrime⟩

theorem sound (rho : Nat → F)
    (h : Shieldd.GnarkFormal.Deployed.Templates.Relations.TStatementHash_5804cb48cce27e24aa8fa559e9e23e995c25c83d8af6b4ef440384b01de85476.relationPart93 rho) :
    rho 484 = Shieldd.GnarkFormal.Poseidon7Bridge.p17 ((2956062250044031925588211089300332661152138256628933421957907397358544574740 : F) + (7881497632799812395965569942862776762617506046143792906072884558856248623105 : F) * rho 409 + (7916682890089097272733273380107699873164905626706934838689281364922571161601 : F) * rho 414 + (5464063484924239686278651430976294814419699569805570712193386353828911860556 : F) * rho 419 + (2345683819285658451180229149661540703159972037542795507759787071088169233067 : F) * rho 424 + (5777789618029937658696564431797900258309825860894885777008317627732964216186 : F) * rho 429 + (8022238661956951903036383691842469204807104368396360636538471783121538777089 : F) * rho 434 + (8042344523265114689760785655982425267977046985861013169462127100873723084801 : F) * rho 439 + (1151517511285686876033930673470210890642168091157372340172986380352373987142 : F) * rho 444) := by
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TStatementHash_5804cb48cce27e24aa8fa559e9e23e995c25c83d8af6b4ef440384b01de85476.relationPart93 Shieldd.GnarkFormal.Deployed.Templates.Relations.TStatementHash_5804cb48cce27e24aa8fa559e9e23e995c25c83d8af6b4ef440384b01de85476.relationRow465 Shieldd.GnarkFormal.Deployed.Templates.Relations.TStatementHash_5804cb48cce27e24aa8fa559e9e23e995c25c83d8af6b4ef440384b01de85476.relationRow466 Shieldd.GnarkFormal.Deployed.Templates.Relations.TStatementHash_5804cb48cce27e24aa8fa559e9e23e995c25c83d8af6b4ef440384b01de85476.relationRow467 Shieldd.GnarkFormal.Deployed.Templates.Relations.TStatementHash_5804cb48cce27e24aa8fa559e9e23e995c25c83d8af6b4ef440384b01de85476.relationRow468 Shieldd.GnarkFormal.Deployed.Templates.Relations.TStatementHash_5804cb48cce27e24aa8fa559e9e23e995c25c83d8af6b4ef440384b01de85476.relationRow469 at h
  rcases h with ⟨h0, h1, h2, h3, h4⟩

  exact Shieldd.GnarkFormal.Deployed.StatementHash.p17_from_rows
    ((2956062250044031925588211089300332661152138256628933421957907397358544574740 : F) + (7881497632799812395965569942862776762617506046143792906072884558856248623105 : F) * rho 409 + (7916682890089097272733273380107699873164905626706934838689281364922571161601 : F) * rho 414 + (5464063484924239686278651430976294814419699569805570712193386353828911860556 : F) * rho 419 + (2345683819285658451180229149661540703159972037542795507759787071088169233067 : F) * rho 424 + (5777789618029937658696564431797900258309825860894885777008317627732964216186 : F) * rho 429 + (8022238661956951903036383691842469204807104368396360636538471783121538777089 : F) * rho 434 + (8042344523265114689760785655982425267977046985861013169462127100873723084801 : F) * rho 439 + (1151517511285686876033930673470210890642168091157372340172986380352373987142 : F) * rho 444) (rho 480) (rho 481) (rho 482) (rho 483) (rho 484)
    (by simpa only [one_mul] using h0)
    (by simpa only [one_mul] using h1)
    (by simpa only [one_mul] using h2)
    (by simpa only [one_mul] using h3)
    (by simpa only [one_mul] using h4)

end Shieldd.GnarkFormal.Deployed.Templates.Semantics.TStatementHash_5804cb48cce27e24aa8fa559e9e23e995c25c83d8af6b4ef440384b01de85476.Part93
