/-
GENERATED by gen/gen_certified_statement_hash_semantics.py -- do not edit.
-/
import ShielddGnarkFormal.ChoiceFreeZMod
import ShielddGnarkFormal.Deployed.Templates.Relations.TStatementHash_67a3df11145400695d1528410a7903b2252ede68702e91a980098b8499e5b5d4
import ShielddGnarkFormal.Deployed.StatementHashDeployedBridge
import ShielddGnarkFormal.Deployed.PrimeOrderCertificate
import Mathlib.Tactic.LinearCombination

set_option maxRecDepth 1000000
set_option maxHeartbeats 20000000

namespace Shieldd.GnarkFormal.Deployed.Templates.Semantics.TStatementHash_67a3df11145400695d1528410a7903b2252ede68702e91a980098b8499e5b5d4.Part12

open scoped Shieldd.GnarkFormal.ChoiceFreeZMod

abbrev Order : Nat := Shieldd.GnarkFormal.Extracted.Deployed.StatementHash470_5c3d95.Order
abbrev F := Shieldd.GnarkFormal.Extracted.Deployed.StatementHash470_5c3d95.F

local instance : Fact (Nat.Prime Order) :=
  ⟨Shieldd.GnarkFormal.Deployed.decaf377ScalarFieldPrime⟩

theorem sound (rho : Nat → F)
    (h : Shieldd.GnarkFormal.Deployed.Templates.Relations.TStatementHash_67a3df11145400695d1528410a7903b2252ede68702e91a980098b8499e5b5d4.relationPart12 rho) :
    rho 74 = Shieldd.GnarkFormal.Poseidon7Bridge.p17 ((3999957651426365003069058612905824322155416419513766652686530774743315394044 : F) + (7841285910183486822516766014582864636277620811214487840225573923351880007681 : F) * rho 6 + (7881497632799812395965569942862776762617506046143792906072884558856248623105 : F) * rho 12 + (7916682890089097272733273380107699873164905626706934838689281364922571161601 : F) * rho 19 + (5464063484924239686278651430976294814419699569805570712193386353828911860556 : F) * rho 25 + (2345683819285658451180229149661540703159972037542795507759787071088169233067 : F) * rho 31 + (5777789618029937658696564431797900258309825860894885777008317627732964216186 : F) * rho 38 + (8022238661956951903036383691842469204807104368396360636538471783121538777089 : F) * rho 44) := by
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TStatementHash_67a3df11145400695d1528410a7903b2252ede68702e91a980098b8499e5b5d4.relationPart12 Shieldd.GnarkFormal.Deployed.Templates.Relations.TStatementHash_67a3df11145400695d1528410a7903b2252ede68702e91a980098b8499e5b5d4.relationRow60 Shieldd.GnarkFormal.Deployed.Templates.Relations.TStatementHash_67a3df11145400695d1528410a7903b2252ede68702e91a980098b8499e5b5d4.relationRow61 Shieldd.GnarkFormal.Deployed.Templates.Relations.TStatementHash_67a3df11145400695d1528410a7903b2252ede68702e91a980098b8499e5b5d4.relationRow62 Shieldd.GnarkFormal.Deployed.Templates.Relations.TStatementHash_67a3df11145400695d1528410a7903b2252ede68702e91a980098b8499e5b5d4.relationRow63 Shieldd.GnarkFormal.Deployed.Templates.Relations.TStatementHash_67a3df11145400695d1528410a7903b2252ede68702e91a980098b8499e5b5d4.relationRow64 at h
  rcases h with ⟨h0, h1, h2, h3, h4⟩

  exact Shieldd.GnarkFormal.Deployed.StatementHash.p17_from_rows
    ((3999957651426365003069058612905824322155416419513766652686530774743315394044 : F) + (7841285910183486822516766014582864636277620811214487840225573923351880007681 : F) * rho 6 + (7881497632799812395965569942862776762617506046143792906072884558856248623105 : F) * rho 12 + (7916682890089097272733273380107699873164905626706934838689281364922571161601 : F) * rho 19 + (5464063484924239686278651430976294814419699569805570712193386353828911860556 : F) * rho 25 + (2345683819285658451180229149661540703159972037542795507759787071088169233067 : F) * rho 31 + (5777789618029937658696564431797900258309825860894885777008317627732964216186 : F) * rho 38 + (8022238661956951903036383691842469204807104368396360636538471783121538777089 : F) * rho 44) (rho 70) (rho 71) (rho 72) (rho 73) (rho 74)
    (by simpa only [one_mul] using h0)
    (by simpa only [one_mul] using h1)
    (by simpa only [one_mul] using h2)
    (by simpa only [one_mul] using h3)
    (by simpa only [one_mul] using h4)

end Shieldd.GnarkFormal.Deployed.Templates.Semantics.TStatementHash_67a3df11145400695d1528410a7903b2252ede68702e91a980098b8499e5b5d4.Part12
