/-
GENERATED by gen/gen_transfer_threshold_semantics.py — do not edit by hand.
-/
import ShielddGnarkFormal.Deployed.Templates.Semantics.TThresholdFlag_9cff3d70e943aa401049c5bfb32ca36b67892e27bb28d1be48bb6acb16e8a202Base
import ShielddGnarkFormal.Deployed.Templates.Semantics.BinaryRecomposition
import ShielddGnarkFormal.RvkToBinaryChoiceFree

set_option maxRecDepth 1000000
set_option maxHeartbeats 30000000

namespace Shieldd.GnarkFormal.Deployed.Templates.Semantics.TThresholdFlag_9cff3d70e943aa401049c5bfb32ca36b67892e27bb28d1be48bb6acb16e8a202

open scoped Shieldd.GnarkFormal.ChoiceFreeZMod

local instance thresholdEdwardsFactPrime :
    Fact (Nat.Prime Shieldd.GnarkFormal.Extracted.DecafEdwardsAdd.Order) :=
  ⟨Shieldd.GnarkFormal.Deployed.decaf377ScalarFieldPrime⟩

theorem amountBits_toBinary (rho : Nat → F) (h : Shieldd.GnarkFormal.Deployed.Templates.Relations.TThresholdFlag_9cff3d70e943aa401049c5bfb32ca36b67892e27bb28d1be48bb6acb16e8a202.relation rho) :
    GatesDef.to_binary (rho 129) 128 (amountBits rho) := by
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TThresholdFlag_9cff3d70e943aa401049c5bfb32ca36b67892e27bb28d1be48bb6acb16e8a202.relation at h
  rcases h with ⟨p0, p1, p2, p3, p4, p5, p6, p7, p8, p9, p10, p11, p12, p13, p14, p15, p16, p17, p18, p19, p20, p21, p22, p23, p24, p25, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _⟩
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TThresholdFlag_9cff3d70e943aa401049c5bfb32ca36b67892e27bb28d1be48bb6acb16e8a202.relationPart0 at p0
  rcases p0 with ⟨r0, r1, r2, r3, r4⟩
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TThresholdFlag_9cff3d70e943aa401049c5bfb32ca36b67892e27bb28d1be48bb6acb16e8a202.relationPart1 at p1
  rcases p1 with ⟨r5, r6, r7, r8, r9⟩
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TThresholdFlag_9cff3d70e943aa401049c5bfb32ca36b67892e27bb28d1be48bb6acb16e8a202.relationPart2 at p2
  rcases p2 with ⟨r10, r11, r12, r13, r14⟩
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TThresholdFlag_9cff3d70e943aa401049c5bfb32ca36b67892e27bb28d1be48bb6acb16e8a202.relationPart3 at p3
  rcases p3 with ⟨r15, r16, r17, r18, r19⟩
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TThresholdFlag_9cff3d70e943aa401049c5bfb32ca36b67892e27bb28d1be48bb6acb16e8a202.relationPart4 at p4
  rcases p4 with ⟨r20, r21, r22, r23, r24⟩
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TThresholdFlag_9cff3d70e943aa401049c5bfb32ca36b67892e27bb28d1be48bb6acb16e8a202.relationPart5 at p5
  rcases p5 with ⟨r25, r26, r27, r28, r29⟩
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TThresholdFlag_9cff3d70e943aa401049c5bfb32ca36b67892e27bb28d1be48bb6acb16e8a202.relationPart6 at p6
  rcases p6 with ⟨r30, r31, r32, r33, r34⟩
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TThresholdFlag_9cff3d70e943aa401049c5bfb32ca36b67892e27bb28d1be48bb6acb16e8a202.relationPart7 at p7
  rcases p7 with ⟨r35, r36, r37, r38, r39⟩
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TThresholdFlag_9cff3d70e943aa401049c5bfb32ca36b67892e27bb28d1be48bb6acb16e8a202.relationPart8 at p8
  rcases p8 with ⟨r40, r41, r42, r43, r44⟩
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TThresholdFlag_9cff3d70e943aa401049c5bfb32ca36b67892e27bb28d1be48bb6acb16e8a202.relationPart9 at p9
  rcases p9 with ⟨r45, r46, r47, r48, r49⟩
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TThresholdFlag_9cff3d70e943aa401049c5bfb32ca36b67892e27bb28d1be48bb6acb16e8a202.relationPart10 at p10
  rcases p10 with ⟨r50, r51, r52, r53, r54⟩
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TThresholdFlag_9cff3d70e943aa401049c5bfb32ca36b67892e27bb28d1be48bb6acb16e8a202.relationPart11 at p11
  rcases p11 with ⟨r55, r56, r57, r58, r59⟩
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TThresholdFlag_9cff3d70e943aa401049c5bfb32ca36b67892e27bb28d1be48bb6acb16e8a202.relationPart12 at p12
  rcases p12 with ⟨r60, r61, r62, r63, r64⟩
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TThresholdFlag_9cff3d70e943aa401049c5bfb32ca36b67892e27bb28d1be48bb6acb16e8a202.relationPart13 at p13
  rcases p13 with ⟨r65, r66, r67, r68, r69⟩
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TThresholdFlag_9cff3d70e943aa401049c5bfb32ca36b67892e27bb28d1be48bb6acb16e8a202.relationPart14 at p14
  rcases p14 with ⟨r70, r71, r72, r73, r74⟩
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TThresholdFlag_9cff3d70e943aa401049c5bfb32ca36b67892e27bb28d1be48bb6acb16e8a202.relationPart15 at p15
  rcases p15 with ⟨r75, r76, r77, r78, r79⟩
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TThresholdFlag_9cff3d70e943aa401049c5bfb32ca36b67892e27bb28d1be48bb6acb16e8a202.relationPart16 at p16
  rcases p16 with ⟨r80, r81, r82, r83, r84⟩
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TThresholdFlag_9cff3d70e943aa401049c5bfb32ca36b67892e27bb28d1be48bb6acb16e8a202.relationPart17 at p17
  rcases p17 with ⟨r85, r86, r87, r88, r89⟩
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TThresholdFlag_9cff3d70e943aa401049c5bfb32ca36b67892e27bb28d1be48bb6acb16e8a202.relationPart18 at p18
  rcases p18 with ⟨r90, r91, r92, r93, r94⟩
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TThresholdFlag_9cff3d70e943aa401049c5bfb32ca36b67892e27bb28d1be48bb6acb16e8a202.relationPart19 at p19
  rcases p19 with ⟨r95, r96, r97, r98, r99⟩
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TThresholdFlag_9cff3d70e943aa401049c5bfb32ca36b67892e27bb28d1be48bb6acb16e8a202.relationPart20 at p20
  rcases p20 with ⟨r100, r101, r102, r103, r104⟩
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TThresholdFlag_9cff3d70e943aa401049c5bfb32ca36b67892e27bb28d1be48bb6acb16e8a202.relationPart21 at p21
  rcases p21 with ⟨r105, r106, r107, r108, r109⟩
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TThresholdFlag_9cff3d70e943aa401049c5bfb32ca36b67892e27bb28d1be48bb6acb16e8a202.relationPart22 at p22
  rcases p22 with ⟨r110, r111, r112, r113, r114⟩
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TThresholdFlag_9cff3d70e943aa401049c5bfb32ca36b67892e27bb28d1be48bb6acb16e8a202.relationPart23 at p23
  rcases p23 with ⟨r115, r116, r117, r118, r119⟩
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TThresholdFlag_9cff3d70e943aa401049c5bfb32ca36b67892e27bb28d1be48bb6acb16e8a202.relationPart24 at p24
  rcases p24 with ⟨r120, r121, r122, r123, r124⟩
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TThresholdFlag_9cff3d70e943aa401049c5bfb32ca36b67892e27bb28d1be48bb6acb16e8a202.relationPart25 at p25
  rcases p25 with ⟨r125, r126, r127, r128, r129⟩
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TThresholdFlag_9cff3d70e943aa401049c5bfb32ca36b67892e27bb28d1be48bb6acb16e8a202.relationRow0 at r0
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TThresholdFlag_9cff3d70e943aa401049c5bfb32ca36b67892e27bb28d1be48bb6acb16e8a202.relationRow1 at r1
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TThresholdFlag_9cff3d70e943aa401049c5bfb32ca36b67892e27bb28d1be48bb6acb16e8a202.relationRow2 at r2
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TThresholdFlag_9cff3d70e943aa401049c5bfb32ca36b67892e27bb28d1be48bb6acb16e8a202.relationRow3 at r3
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TThresholdFlag_9cff3d70e943aa401049c5bfb32ca36b67892e27bb28d1be48bb6acb16e8a202.relationRow4 at r4
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TThresholdFlag_9cff3d70e943aa401049c5bfb32ca36b67892e27bb28d1be48bb6acb16e8a202.relationRow5 at r5
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TThresholdFlag_9cff3d70e943aa401049c5bfb32ca36b67892e27bb28d1be48bb6acb16e8a202.relationRow6 at r6
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TThresholdFlag_9cff3d70e943aa401049c5bfb32ca36b67892e27bb28d1be48bb6acb16e8a202.relationRow7 at r7
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TThresholdFlag_9cff3d70e943aa401049c5bfb32ca36b67892e27bb28d1be48bb6acb16e8a202.relationRow8 at r8
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TThresholdFlag_9cff3d70e943aa401049c5bfb32ca36b67892e27bb28d1be48bb6acb16e8a202.relationRow9 at r9
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TThresholdFlag_9cff3d70e943aa401049c5bfb32ca36b67892e27bb28d1be48bb6acb16e8a202.relationRow10 at r10
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TThresholdFlag_9cff3d70e943aa401049c5bfb32ca36b67892e27bb28d1be48bb6acb16e8a202.relationRow11 at r11
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TThresholdFlag_9cff3d70e943aa401049c5bfb32ca36b67892e27bb28d1be48bb6acb16e8a202.relationRow12 at r12
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TThresholdFlag_9cff3d70e943aa401049c5bfb32ca36b67892e27bb28d1be48bb6acb16e8a202.relationRow13 at r13
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TThresholdFlag_9cff3d70e943aa401049c5bfb32ca36b67892e27bb28d1be48bb6acb16e8a202.relationRow14 at r14
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TThresholdFlag_9cff3d70e943aa401049c5bfb32ca36b67892e27bb28d1be48bb6acb16e8a202.relationRow15 at r15
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TThresholdFlag_9cff3d70e943aa401049c5bfb32ca36b67892e27bb28d1be48bb6acb16e8a202.relationRow16 at r16
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TThresholdFlag_9cff3d70e943aa401049c5bfb32ca36b67892e27bb28d1be48bb6acb16e8a202.relationRow17 at r17
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TThresholdFlag_9cff3d70e943aa401049c5bfb32ca36b67892e27bb28d1be48bb6acb16e8a202.relationRow18 at r18
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TThresholdFlag_9cff3d70e943aa401049c5bfb32ca36b67892e27bb28d1be48bb6acb16e8a202.relationRow19 at r19
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TThresholdFlag_9cff3d70e943aa401049c5bfb32ca36b67892e27bb28d1be48bb6acb16e8a202.relationRow20 at r20
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TThresholdFlag_9cff3d70e943aa401049c5bfb32ca36b67892e27bb28d1be48bb6acb16e8a202.relationRow21 at r21
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TThresholdFlag_9cff3d70e943aa401049c5bfb32ca36b67892e27bb28d1be48bb6acb16e8a202.relationRow22 at r22
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TThresholdFlag_9cff3d70e943aa401049c5bfb32ca36b67892e27bb28d1be48bb6acb16e8a202.relationRow23 at r23
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TThresholdFlag_9cff3d70e943aa401049c5bfb32ca36b67892e27bb28d1be48bb6acb16e8a202.relationRow24 at r24
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TThresholdFlag_9cff3d70e943aa401049c5bfb32ca36b67892e27bb28d1be48bb6acb16e8a202.relationRow25 at r25
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TThresholdFlag_9cff3d70e943aa401049c5bfb32ca36b67892e27bb28d1be48bb6acb16e8a202.relationRow26 at r26
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TThresholdFlag_9cff3d70e943aa401049c5bfb32ca36b67892e27bb28d1be48bb6acb16e8a202.relationRow27 at r27
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TThresholdFlag_9cff3d70e943aa401049c5bfb32ca36b67892e27bb28d1be48bb6acb16e8a202.relationRow28 at r28
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TThresholdFlag_9cff3d70e943aa401049c5bfb32ca36b67892e27bb28d1be48bb6acb16e8a202.relationRow29 at r29
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TThresholdFlag_9cff3d70e943aa401049c5bfb32ca36b67892e27bb28d1be48bb6acb16e8a202.relationRow30 at r30
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TThresholdFlag_9cff3d70e943aa401049c5bfb32ca36b67892e27bb28d1be48bb6acb16e8a202.relationRow31 at r31
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TThresholdFlag_9cff3d70e943aa401049c5bfb32ca36b67892e27bb28d1be48bb6acb16e8a202.relationRow32 at r32
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TThresholdFlag_9cff3d70e943aa401049c5bfb32ca36b67892e27bb28d1be48bb6acb16e8a202.relationRow33 at r33
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TThresholdFlag_9cff3d70e943aa401049c5bfb32ca36b67892e27bb28d1be48bb6acb16e8a202.relationRow34 at r34
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TThresholdFlag_9cff3d70e943aa401049c5bfb32ca36b67892e27bb28d1be48bb6acb16e8a202.relationRow35 at r35
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TThresholdFlag_9cff3d70e943aa401049c5bfb32ca36b67892e27bb28d1be48bb6acb16e8a202.relationRow36 at r36
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TThresholdFlag_9cff3d70e943aa401049c5bfb32ca36b67892e27bb28d1be48bb6acb16e8a202.relationRow37 at r37
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TThresholdFlag_9cff3d70e943aa401049c5bfb32ca36b67892e27bb28d1be48bb6acb16e8a202.relationRow38 at r38
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TThresholdFlag_9cff3d70e943aa401049c5bfb32ca36b67892e27bb28d1be48bb6acb16e8a202.relationRow39 at r39
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TThresholdFlag_9cff3d70e943aa401049c5bfb32ca36b67892e27bb28d1be48bb6acb16e8a202.relationRow40 at r40
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TThresholdFlag_9cff3d70e943aa401049c5bfb32ca36b67892e27bb28d1be48bb6acb16e8a202.relationRow41 at r41
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TThresholdFlag_9cff3d70e943aa401049c5bfb32ca36b67892e27bb28d1be48bb6acb16e8a202.relationRow42 at r42
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TThresholdFlag_9cff3d70e943aa401049c5bfb32ca36b67892e27bb28d1be48bb6acb16e8a202.relationRow43 at r43
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TThresholdFlag_9cff3d70e943aa401049c5bfb32ca36b67892e27bb28d1be48bb6acb16e8a202.relationRow44 at r44
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TThresholdFlag_9cff3d70e943aa401049c5bfb32ca36b67892e27bb28d1be48bb6acb16e8a202.relationRow45 at r45
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TThresholdFlag_9cff3d70e943aa401049c5bfb32ca36b67892e27bb28d1be48bb6acb16e8a202.relationRow46 at r46
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TThresholdFlag_9cff3d70e943aa401049c5bfb32ca36b67892e27bb28d1be48bb6acb16e8a202.relationRow47 at r47
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TThresholdFlag_9cff3d70e943aa401049c5bfb32ca36b67892e27bb28d1be48bb6acb16e8a202.relationRow48 at r48
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TThresholdFlag_9cff3d70e943aa401049c5bfb32ca36b67892e27bb28d1be48bb6acb16e8a202.relationRow49 at r49
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TThresholdFlag_9cff3d70e943aa401049c5bfb32ca36b67892e27bb28d1be48bb6acb16e8a202.relationRow50 at r50
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TThresholdFlag_9cff3d70e943aa401049c5bfb32ca36b67892e27bb28d1be48bb6acb16e8a202.relationRow51 at r51
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TThresholdFlag_9cff3d70e943aa401049c5bfb32ca36b67892e27bb28d1be48bb6acb16e8a202.relationRow52 at r52
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TThresholdFlag_9cff3d70e943aa401049c5bfb32ca36b67892e27bb28d1be48bb6acb16e8a202.relationRow53 at r53
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TThresholdFlag_9cff3d70e943aa401049c5bfb32ca36b67892e27bb28d1be48bb6acb16e8a202.relationRow54 at r54
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TThresholdFlag_9cff3d70e943aa401049c5bfb32ca36b67892e27bb28d1be48bb6acb16e8a202.relationRow55 at r55
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TThresholdFlag_9cff3d70e943aa401049c5bfb32ca36b67892e27bb28d1be48bb6acb16e8a202.relationRow56 at r56
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TThresholdFlag_9cff3d70e943aa401049c5bfb32ca36b67892e27bb28d1be48bb6acb16e8a202.relationRow57 at r57
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TThresholdFlag_9cff3d70e943aa401049c5bfb32ca36b67892e27bb28d1be48bb6acb16e8a202.relationRow58 at r58
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TThresholdFlag_9cff3d70e943aa401049c5bfb32ca36b67892e27bb28d1be48bb6acb16e8a202.relationRow59 at r59
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TThresholdFlag_9cff3d70e943aa401049c5bfb32ca36b67892e27bb28d1be48bb6acb16e8a202.relationRow60 at r60
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TThresholdFlag_9cff3d70e943aa401049c5bfb32ca36b67892e27bb28d1be48bb6acb16e8a202.relationRow61 at r61
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TThresholdFlag_9cff3d70e943aa401049c5bfb32ca36b67892e27bb28d1be48bb6acb16e8a202.relationRow62 at r62
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TThresholdFlag_9cff3d70e943aa401049c5bfb32ca36b67892e27bb28d1be48bb6acb16e8a202.relationRow63 at r63
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TThresholdFlag_9cff3d70e943aa401049c5bfb32ca36b67892e27bb28d1be48bb6acb16e8a202.relationRow64 at r64
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TThresholdFlag_9cff3d70e943aa401049c5bfb32ca36b67892e27bb28d1be48bb6acb16e8a202.relationRow65 at r65
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TThresholdFlag_9cff3d70e943aa401049c5bfb32ca36b67892e27bb28d1be48bb6acb16e8a202.relationRow66 at r66
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TThresholdFlag_9cff3d70e943aa401049c5bfb32ca36b67892e27bb28d1be48bb6acb16e8a202.relationRow67 at r67
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TThresholdFlag_9cff3d70e943aa401049c5bfb32ca36b67892e27bb28d1be48bb6acb16e8a202.relationRow68 at r68
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TThresholdFlag_9cff3d70e943aa401049c5bfb32ca36b67892e27bb28d1be48bb6acb16e8a202.relationRow69 at r69
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TThresholdFlag_9cff3d70e943aa401049c5bfb32ca36b67892e27bb28d1be48bb6acb16e8a202.relationRow70 at r70
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TThresholdFlag_9cff3d70e943aa401049c5bfb32ca36b67892e27bb28d1be48bb6acb16e8a202.relationRow71 at r71
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TThresholdFlag_9cff3d70e943aa401049c5bfb32ca36b67892e27bb28d1be48bb6acb16e8a202.relationRow72 at r72
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TThresholdFlag_9cff3d70e943aa401049c5bfb32ca36b67892e27bb28d1be48bb6acb16e8a202.relationRow73 at r73
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TThresholdFlag_9cff3d70e943aa401049c5bfb32ca36b67892e27bb28d1be48bb6acb16e8a202.relationRow74 at r74
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TThresholdFlag_9cff3d70e943aa401049c5bfb32ca36b67892e27bb28d1be48bb6acb16e8a202.relationRow75 at r75
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TThresholdFlag_9cff3d70e943aa401049c5bfb32ca36b67892e27bb28d1be48bb6acb16e8a202.relationRow76 at r76
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TThresholdFlag_9cff3d70e943aa401049c5bfb32ca36b67892e27bb28d1be48bb6acb16e8a202.relationRow77 at r77
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TThresholdFlag_9cff3d70e943aa401049c5bfb32ca36b67892e27bb28d1be48bb6acb16e8a202.relationRow78 at r78
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TThresholdFlag_9cff3d70e943aa401049c5bfb32ca36b67892e27bb28d1be48bb6acb16e8a202.relationRow79 at r79
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TThresholdFlag_9cff3d70e943aa401049c5bfb32ca36b67892e27bb28d1be48bb6acb16e8a202.relationRow80 at r80
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TThresholdFlag_9cff3d70e943aa401049c5bfb32ca36b67892e27bb28d1be48bb6acb16e8a202.relationRow81 at r81
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TThresholdFlag_9cff3d70e943aa401049c5bfb32ca36b67892e27bb28d1be48bb6acb16e8a202.relationRow82 at r82
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TThresholdFlag_9cff3d70e943aa401049c5bfb32ca36b67892e27bb28d1be48bb6acb16e8a202.relationRow83 at r83
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TThresholdFlag_9cff3d70e943aa401049c5bfb32ca36b67892e27bb28d1be48bb6acb16e8a202.relationRow84 at r84
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TThresholdFlag_9cff3d70e943aa401049c5bfb32ca36b67892e27bb28d1be48bb6acb16e8a202.relationRow85 at r85
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TThresholdFlag_9cff3d70e943aa401049c5bfb32ca36b67892e27bb28d1be48bb6acb16e8a202.relationRow86 at r86
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TThresholdFlag_9cff3d70e943aa401049c5bfb32ca36b67892e27bb28d1be48bb6acb16e8a202.relationRow87 at r87
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TThresholdFlag_9cff3d70e943aa401049c5bfb32ca36b67892e27bb28d1be48bb6acb16e8a202.relationRow88 at r88
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TThresholdFlag_9cff3d70e943aa401049c5bfb32ca36b67892e27bb28d1be48bb6acb16e8a202.relationRow89 at r89
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TThresholdFlag_9cff3d70e943aa401049c5bfb32ca36b67892e27bb28d1be48bb6acb16e8a202.relationRow90 at r90
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TThresholdFlag_9cff3d70e943aa401049c5bfb32ca36b67892e27bb28d1be48bb6acb16e8a202.relationRow91 at r91
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TThresholdFlag_9cff3d70e943aa401049c5bfb32ca36b67892e27bb28d1be48bb6acb16e8a202.relationRow92 at r92
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TThresholdFlag_9cff3d70e943aa401049c5bfb32ca36b67892e27bb28d1be48bb6acb16e8a202.relationRow93 at r93
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TThresholdFlag_9cff3d70e943aa401049c5bfb32ca36b67892e27bb28d1be48bb6acb16e8a202.relationRow94 at r94
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TThresholdFlag_9cff3d70e943aa401049c5bfb32ca36b67892e27bb28d1be48bb6acb16e8a202.relationRow95 at r95
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TThresholdFlag_9cff3d70e943aa401049c5bfb32ca36b67892e27bb28d1be48bb6acb16e8a202.relationRow96 at r96
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TThresholdFlag_9cff3d70e943aa401049c5bfb32ca36b67892e27bb28d1be48bb6acb16e8a202.relationRow97 at r97
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TThresholdFlag_9cff3d70e943aa401049c5bfb32ca36b67892e27bb28d1be48bb6acb16e8a202.relationRow98 at r98
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TThresholdFlag_9cff3d70e943aa401049c5bfb32ca36b67892e27bb28d1be48bb6acb16e8a202.relationRow99 at r99
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TThresholdFlag_9cff3d70e943aa401049c5bfb32ca36b67892e27bb28d1be48bb6acb16e8a202.relationRow100 at r100
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TThresholdFlag_9cff3d70e943aa401049c5bfb32ca36b67892e27bb28d1be48bb6acb16e8a202.relationRow101 at r101
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TThresholdFlag_9cff3d70e943aa401049c5bfb32ca36b67892e27bb28d1be48bb6acb16e8a202.relationRow102 at r102
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TThresholdFlag_9cff3d70e943aa401049c5bfb32ca36b67892e27bb28d1be48bb6acb16e8a202.relationRow103 at r103
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TThresholdFlag_9cff3d70e943aa401049c5bfb32ca36b67892e27bb28d1be48bb6acb16e8a202.relationRow104 at r104
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TThresholdFlag_9cff3d70e943aa401049c5bfb32ca36b67892e27bb28d1be48bb6acb16e8a202.relationRow105 at r105
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TThresholdFlag_9cff3d70e943aa401049c5bfb32ca36b67892e27bb28d1be48bb6acb16e8a202.relationRow106 at r106
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TThresholdFlag_9cff3d70e943aa401049c5bfb32ca36b67892e27bb28d1be48bb6acb16e8a202.relationRow107 at r107
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TThresholdFlag_9cff3d70e943aa401049c5bfb32ca36b67892e27bb28d1be48bb6acb16e8a202.relationRow108 at r108
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TThresholdFlag_9cff3d70e943aa401049c5bfb32ca36b67892e27bb28d1be48bb6acb16e8a202.relationRow109 at r109
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TThresholdFlag_9cff3d70e943aa401049c5bfb32ca36b67892e27bb28d1be48bb6acb16e8a202.relationRow110 at r110
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TThresholdFlag_9cff3d70e943aa401049c5bfb32ca36b67892e27bb28d1be48bb6acb16e8a202.relationRow111 at r111
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TThresholdFlag_9cff3d70e943aa401049c5bfb32ca36b67892e27bb28d1be48bb6acb16e8a202.relationRow112 at r112
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TThresholdFlag_9cff3d70e943aa401049c5bfb32ca36b67892e27bb28d1be48bb6acb16e8a202.relationRow113 at r113
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TThresholdFlag_9cff3d70e943aa401049c5bfb32ca36b67892e27bb28d1be48bb6acb16e8a202.relationRow114 at r114
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TThresholdFlag_9cff3d70e943aa401049c5bfb32ca36b67892e27bb28d1be48bb6acb16e8a202.relationRow115 at r115
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TThresholdFlag_9cff3d70e943aa401049c5bfb32ca36b67892e27bb28d1be48bb6acb16e8a202.relationRow116 at r116
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TThresholdFlag_9cff3d70e943aa401049c5bfb32ca36b67892e27bb28d1be48bb6acb16e8a202.relationRow117 at r117
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TThresholdFlag_9cff3d70e943aa401049c5bfb32ca36b67892e27bb28d1be48bb6acb16e8a202.relationRow118 at r118
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TThresholdFlag_9cff3d70e943aa401049c5bfb32ca36b67892e27bb28d1be48bb6acb16e8a202.relationRow119 at r119
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TThresholdFlag_9cff3d70e943aa401049c5bfb32ca36b67892e27bb28d1be48bb6acb16e8a202.relationRow120 at r120
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TThresholdFlag_9cff3d70e943aa401049c5bfb32ca36b67892e27bb28d1be48bb6acb16e8a202.relationRow121 at r121
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TThresholdFlag_9cff3d70e943aa401049c5bfb32ca36b67892e27bb28d1be48bb6acb16e8a202.relationRow122 at r122
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TThresholdFlag_9cff3d70e943aa401049c5bfb32ca36b67892e27bb28d1be48bb6acb16e8a202.relationRow123 at r123
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TThresholdFlag_9cff3d70e943aa401049c5bfb32ca36b67892e27bb28d1be48bb6acb16e8a202.relationRow124 at r124
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TThresholdFlag_9cff3d70e943aa401049c5bfb32ca36b67892e27bb28d1be48bb6acb16e8a202.relationRow125 at r125
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TThresholdFlag_9cff3d70e943aa401049c5bfb32ca36b67892e27bb28d1be48bb6acb16e8a202.relationRow126 at r126
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TThresholdFlag_9cff3d70e943aa401049c5bfb32ca36b67892e27bb28d1be48bb6acb16e8a202.relationRow127 at r127
  unfold Shieldd.GnarkFormal.Deployed.Templates.Relations.TThresholdFlag_9cff3d70e943aa401049c5bfb32ca36b67892e27bb28d1be48bb6acb16e8a202.relationRow128 Shieldd.GnarkFormal.Deployed.Templates.Relations.TThresholdFlag_9cff3d70e943aa401049c5bfb32ca36b67892e27bb28d1be48bb6acb16e8a202.relationLc0 Shieldd.GnarkFormal.Deployed.Templates.Relations.TThresholdFlag_9cff3d70e943aa401049c5bfb32ca36b67892e27bb28d1be48bb6acb16e8a202.relationLc0Part0 Shieldd.GnarkFormal.Deployed.Templates.Relations.TThresholdFlag_9cff3d70e943aa401049c5bfb32ca36b67892e27bb28d1be48bb6acb16e8a202.relationLc0Part1 Shieldd.GnarkFormal.Deployed.Templates.Relations.TThresholdFlag_9cff3d70e943aa401049c5bfb32ca36b67892e27bb28d1be48bb6acb16e8a202.relationLc0Part2 Shieldd.GnarkFormal.Deployed.Templates.Relations.TThresholdFlag_9cff3d70e943aa401049c5bfb32ca36b67892e27bb28d1be48bb6acb16e8a202.relationLc0Part3 at r128
  have hrecover := recover_ofFn_eq_recBits rho 1 128
  have hacc : powSumAcc rho 0 1 1 128 = rho 129 := by
    simp only [powSumAcc]
    linear_combination r128
  have hrec : recover_binary_zmod' (amountBits rho) = rho 129 := by
    simp only [amountBits]
    rw [hrecover]
    rw [powSumAcc_eq] at hacc
    simpa using hacc
  refine Shieldd.GnarkFormal.RvkToBinaryChoiceFree.to_binary_of_deployed
      (rho 129) (amountBits rho) ?_ hrec
  intro i hi
  have key := amountBits_get rho i hi
  have hgoal : rho (1 + i) * (1 - rho (1 + i)) = 0 := by
    interval_cases i
    · linear_combination r0
    · linear_combination r1
    · linear_combination r2
    · linear_combination r3
    · linear_combination r4
    · linear_combination r5
    · linear_combination r6
    · linear_combination r7
    · linear_combination r8
    · linear_combination r9
    · linear_combination r10
    · linear_combination r11
    · linear_combination r12
    · linear_combination r13
    · linear_combination r14
    · linear_combination r15
    · linear_combination r16
    · linear_combination r17
    · linear_combination r18
    · linear_combination r19
    · linear_combination r20
    · linear_combination r21
    · linear_combination r22
    · linear_combination r23
    · linear_combination r24
    · linear_combination r25
    · linear_combination r26
    · linear_combination r27
    · linear_combination r28
    · linear_combination r29
    · linear_combination r30
    · linear_combination r31
    · linear_combination r32
    · linear_combination r33
    · linear_combination r34
    · linear_combination r35
    · linear_combination r36
    · linear_combination r37
    · linear_combination r38
    · linear_combination r39
    · linear_combination r40
    · linear_combination r41
    · linear_combination r42
    · linear_combination r43
    · linear_combination r44
    · linear_combination r45
    · linear_combination r46
    · linear_combination r47
    · linear_combination r48
    · linear_combination r49
    · linear_combination r50
    · linear_combination r51
    · linear_combination r52
    · linear_combination r53
    · linear_combination r54
    · linear_combination r55
    · linear_combination r56
    · linear_combination r57
    · linear_combination r58
    · linear_combination r59
    · linear_combination r60
    · linear_combination r61
    · linear_combination r62
    · linear_combination r63
    · linear_combination r64
    · linear_combination r65
    · linear_combination r66
    · linear_combination r67
    · linear_combination r68
    · linear_combination r69
    · linear_combination r70
    · linear_combination r71
    · linear_combination r72
    · linear_combination r73
    · linear_combination r74
    · linear_combination r75
    · linear_combination r76
    · linear_combination r77
    · linear_combination r78
    · linear_combination r79
    · linear_combination r80
    · linear_combination r81
    · linear_combination r82
    · linear_combination r83
    · linear_combination r84
    · linear_combination r85
    · linear_combination r86
    · linear_combination r87
    · linear_combination r88
    · linear_combination r89
    · linear_combination r90
    · linear_combination r91
    · linear_combination r92
    · linear_combination r93
    · linear_combination r94
    · linear_combination r95
    · linear_combination r96
    · linear_combination r97
    · linear_combination r98
    · linear_combination r99
    · linear_combination r100
    · linear_combination r101
    · linear_combination r102
    · linear_combination r103
    · linear_combination r104
    · linear_combination r105
    · linear_combination r106
    · linear_combination r107
    · linear_combination r108
    · linear_combination r109
    · linear_combination r110
    · linear_combination r111
    · linear_combination r112
    · linear_combination r113
    · linear_combination r114
    · linear_combination r115
    · linear_combination r116
    · linear_combination r117
    · linear_combination r118
    · linear_combination r119
    · linear_combination r120
    · linear_combination r121
    · linear_combination r122
    · linear_combination r123
    · linear_combination r124
    · linear_combination r125
    · linear_combination r126
    · linear_combination r127
  have key' : (amountBits rho)[i] = rho (1 + i) := by
    rw [← getElem!_pos (amountBits rho) i (by simpa using hi)]
    exact key
  exact key' ▸ hgoal

end Shieldd.GnarkFormal.Deployed.Templates.Semantics.TThresholdFlag_9cff3d70e943aa401049c5bfb32ca36b67892e27bb28d1be48bb6acb16e8a202
