-- GENERATED by generate_prefix.py; exact admitted probe data and fresh materialized program.
import ShielddSecurity.TransferPoseidonUpstream11ProbeData01
import ShielddSecurity.CompilerOrder
import ShielddSecurity.CompilerPriorFrame01
set_option autoImplicit false
namespace ShielddSecurity.TransferPoseidonUpstream11B0R00
open Compiler CompilerIndexed01 CompilerCompletion Poseidon PoseidonIndexedFolded02
def p : Nat := TransferPoseidonCall04Shared01.p
def copy : Nat := TransferPoseidonCall04Shared01.copy
def parameters : Parameters Int 6 := TransferPoseidonCall04Shared01.parameters
def before := TransferPoseidonUpstream11ProbeData01.B0R0before
def shifted := TransferPoseidonUpstream11ProbeData01.B0R0after_ark
def transformed := TransferPoseidonUpstream11ProbeData01.B0R0after_sbox
def after := TransferPoseidonUpstream11ProbeData01.B0R0after
def fifthHints := TransferPoseidonUpstream11ProbeData01.B0R0Hints
def originalRows := TransferPoseidonUpstream11ProbeData01.B0R0Rows
def captureIndices : Array Nat := Array.mk [38040, 38041, 38042, 38043, 38044, 38045, 38046, 38047, 38048, 38049, 38050, 38051, 38052, 38053, 38054, 38055, 38056, 38057, 38058, 38059, 200769]
def materializedSteps : List Step := [
.square [(0,15382421503051706193178845678852385662391627627917820301092068733207529541963), (3763,1)] [] 60778,
.square [(60778,1)] [] 60779,
.product [(60779,1)] [(0,15382421503051706193178845678852385662391627627917820301092068733207529541963), (3763,1)] [] 60780 60781,
.square [(0,51905121302834822973999532172558179730894455480391315755580656618825892714104), (3764,1)] [] 60782,
.square [(60782,1)] [] 60783,
.product [(60783,1)] [(0,51905121302834822973999532172558179730894455480391315755580656618825892714104), (3764,1)] [] 60784 60785,
.square [(0,11828198013949670630619275840967967061780213095608795619376254543574401299037), (1504,1)] [] 60786,
.square [(60786,1)] [] 60787,
.product [(60787,1)] [(0,11828198013949670630619275840967967061780213095608795619376254543574401299037), (1504,1)] [] 60788 60789,
.square [(0,7789132657317287123310771928749050854272187015289180960303174711442023318297), (1505,1)] [] 60790,
.square [(60790,1)] [] 60791,
.product [(60791,1)] [(0,7789132657317287123310771928749050854272187015289180960303174711442023318297), (1505,1)] [] 60792 60793,
.square [(0,8610900935412111704557536373428805555438069111451607813541963853286423586434), (1512,1)] [] 60794,
.square [(60794,1)] [] 60795,
.product [(60795,1)] [(0,8610900935412111704557536373428805555438069111451607813541963853286423586434), (1512,1)] [] 60796 60797]
def copyStep : Step := .equal [(0,1)] [(0,1)]
def steps : List Step := materializedSteps++[copyStep]
def emittedRows : Array Row := (emitted steps).toArray
def rowMapping : Array Nat := (List.range 21).toArray
def cutTerms (state : State Linear 6) (input : Nat) : Linear := if bound : input<6 then state ⟨input,bound⟩ else []
def productionCheck (candidateRows : Array Row) (candidateParameters : Parameters Int 6)
    (candidateBefore candidateAfter : State Linear 6) (candidateHints : Fin 6 → FifthHint) (mapping : Array Nat) : Bool :=
  checkRowAt p candidateRows 20 ⟨[(0,1),(copy,-1)],[]⟩ &&
  checkRound p copy candidateRows candidateParameters 0 candidateBefore shifted transformed candidateAfter candidateHints &&
  checkOriginalCoverage p copy candidateRows emittedRows mapping &&
  CompilerPriorFrame01.checkSupport 6 (cutTerms candidateBefore) steps
end ShielddSecurity.TransferPoseidonUpstream11B0R00
