import ShielddSecurity.TransferPoseidonUpstream11ProbeData01
namespace ShielddSecurity.TransferPoseidonUpstream11ImportFloor01
theorem marker : True := by trivial
end ShielddSecurity.TransferPoseidonUpstream11ImportFloor01
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonUpstream11ImportFloor01.marker
#print axioms ShielddSecurity.TransferPoseidonUpstream11ImportFloor01.marker
