-- GENERATED by generate_blocks.py; edit generator.
import ShielddSecurity.TransferPoseidonCall04Data06
set_option maxHeartbeats 900000
set_option maxRecDepth 8192
namespace ShielddSecurity.TransferPoseidonCall04R48Checks
open Compiler CompilerIndexed01 CompilerCompletion Poseidon PoseidonIndexedRound01 ShielddSecurity.TransferPoseidonCall04Shared01 ShielddSecurity.TransferPoseidonCall04R48
theorem column0_checked : checkColumn p copy originalRows parameters 48 before shifted transformed fifthHints ⟨0,by decide⟩=true := by decide +kernel
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonCall04R48Checks.column0_checked
#print axioms ShielddSecurity.TransferPoseidonCall04R48Checks.column0_checked
end ShielddSecurity.TransferPoseidonCall04R48Checks
namespace ShielddSecurity.TransferPoseidonCall04R48Checks
open Compiler CompilerIndexed01 CompilerCompletion Poseidon PoseidonIndexedRound01 ShielddSecurity.TransferPoseidonCall04Shared01 ShielddSecurity.TransferPoseidonCall04R48
theorem column1_checked : checkColumn p copy originalRows parameters 48 before shifted transformed fifthHints ⟨1,by decide⟩=true := by decide +kernel
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonCall04R48Checks.column1_checked
#print axioms ShielddSecurity.TransferPoseidonCall04R48Checks.column1_checked
end ShielddSecurity.TransferPoseidonCall04R48Checks
namespace ShielddSecurity.TransferPoseidonCall04R48Checks
open Compiler CompilerIndexed01 CompilerCompletion Poseidon PoseidonIndexedRound01 ShielddSecurity.TransferPoseidonCall04Shared01 ShielddSecurity.TransferPoseidonCall04R48
theorem column2_checked : checkColumn p copy originalRows parameters 48 before shifted transformed fifthHints ⟨2,by decide⟩=true := by decide +kernel
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonCall04R48Checks.column2_checked
#print axioms ShielddSecurity.TransferPoseidonCall04R48Checks.column2_checked
end ShielddSecurity.TransferPoseidonCall04R48Checks
namespace ShielddSecurity.TransferPoseidonCall04R48Checks
open Compiler CompilerIndexed01 CompilerCompletion Poseidon PoseidonIndexedRound01 ShielddSecurity.TransferPoseidonCall04Shared01 ShielddSecurity.TransferPoseidonCall04R48
theorem column3_checked : checkColumn p copy originalRows parameters 48 before shifted transformed fifthHints ⟨3,by decide⟩=true := by decide +kernel
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonCall04R48Checks.column3_checked
#print axioms ShielddSecurity.TransferPoseidonCall04R48Checks.column3_checked
end ShielddSecurity.TransferPoseidonCall04R48Checks
namespace ShielddSecurity.TransferPoseidonCall04R48Checks
open Compiler CompilerIndexed01 CompilerCompletion Poseidon PoseidonIndexedRound01 ShielddSecurity.TransferPoseidonCall04Shared01 ShielddSecurity.TransferPoseidonCall04R48
theorem column4_checked : checkColumn p copy originalRows parameters 48 before shifted transformed fifthHints ⟨4,by decide⟩=true := by decide +kernel
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonCall04R48Checks.column4_checked
#print axioms ShielddSecurity.TransferPoseidonCall04R48Checks.column4_checked
end ShielddSecurity.TransferPoseidonCall04R48Checks
namespace ShielddSecurity.TransferPoseidonCall04R48Checks
open Compiler CompilerIndexed01 CompilerCompletion Poseidon PoseidonIndexedRound01 ShielddSecurity.TransferPoseidonCall04Shared01 ShielddSecurity.TransferPoseidonCall04R48
theorem column5_checked : checkColumn p copy originalRows parameters 48 before shifted transformed fifthHints ⟨5,by decide⟩=true := by decide +kernel
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonCall04R48Checks.column5_checked
#print axioms ShielddSecurity.TransferPoseidonCall04R48Checks.column5_checked
end ShielddSecurity.TransferPoseidonCall04R48Checks
namespace ShielddSecurity.TransferPoseidonCall04R48Checks
open Compiler CompilerIndexed01 CompilerCompletion Poseidon PoseidonIndexedRound01 ShielddSecurity.TransferPoseidonCall04Shared01 ShielddSecurity.TransferPoseidonCall04R48
theorem mix0_checked : canonical p (after ⟨0,by decide⟩)=canonical p (mixLinear parameters.mds transformed ⟨0,by decide⟩) := by decide +kernel
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonCall04R48Checks.mix0_checked
#print axioms ShielddSecurity.TransferPoseidonCall04R48Checks.mix0_checked
end ShielddSecurity.TransferPoseidonCall04R48Checks
namespace ShielddSecurity.TransferPoseidonCall04R48Checks
open Compiler CompilerIndexed01 CompilerCompletion Poseidon PoseidonIndexedRound01 ShielddSecurity.TransferPoseidonCall04Shared01 ShielddSecurity.TransferPoseidonCall04R48
theorem mix1_checked : canonical p (after ⟨1,by decide⟩)=canonical p (mixLinear parameters.mds transformed ⟨1,by decide⟩) := by decide +kernel
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonCall04R48Checks.mix1_checked
#print axioms ShielddSecurity.TransferPoseidonCall04R48Checks.mix1_checked
end ShielddSecurity.TransferPoseidonCall04R48Checks
namespace ShielddSecurity.TransferPoseidonCall04R48Checks
open Compiler CompilerIndexed01 CompilerCompletion Poseidon PoseidonIndexedRound01 ShielddSecurity.TransferPoseidonCall04Shared01 ShielddSecurity.TransferPoseidonCall04R48
theorem mix2_checked : canonical p (after ⟨2,by decide⟩)=canonical p (mixLinear parameters.mds transformed ⟨2,by decide⟩) := by decide +kernel
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonCall04R48Checks.mix2_checked
#print axioms ShielddSecurity.TransferPoseidonCall04R48Checks.mix2_checked
end ShielddSecurity.TransferPoseidonCall04R48Checks
namespace ShielddSecurity.TransferPoseidonCall04R48Checks
open Compiler CompilerIndexed01 CompilerCompletion Poseidon PoseidonIndexedRound01 ShielddSecurity.TransferPoseidonCall04Shared01 ShielddSecurity.TransferPoseidonCall04R48
theorem mix3_checked : canonical p (after ⟨3,by decide⟩)=canonical p (mixLinear parameters.mds transformed ⟨3,by decide⟩) := by decide +kernel
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonCall04R48Checks.mix3_checked
#print axioms ShielddSecurity.TransferPoseidonCall04R48Checks.mix3_checked
end ShielddSecurity.TransferPoseidonCall04R48Checks
namespace ShielddSecurity.TransferPoseidonCall04R48Checks
open Compiler CompilerIndexed01 CompilerCompletion Poseidon PoseidonIndexedRound01 ShielddSecurity.TransferPoseidonCall04Shared01 ShielddSecurity.TransferPoseidonCall04R48
theorem mix4_checked : canonical p (after ⟨4,by decide⟩)=canonical p (mixLinear parameters.mds transformed ⟨4,by decide⟩) := by decide +kernel
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonCall04R48Checks.mix4_checked
#print axioms ShielddSecurity.TransferPoseidonCall04R48Checks.mix4_checked
end ShielddSecurity.TransferPoseidonCall04R48Checks
namespace ShielddSecurity.TransferPoseidonCall04R48Checks
open Compiler CompilerIndexed01 CompilerCompletion Poseidon PoseidonIndexedRound01 ShielddSecurity.TransferPoseidonCall04Shared01 ShielddSecurity.TransferPoseidonCall04R48
theorem mix5_checked : canonical p (after ⟨5,by decide⟩)=canonical p (mixLinear parameters.mds transformed ⟨5,by decide⟩) := by decide +kernel
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonCall04R48Checks.mix5_checked
#print axioms ShielddSecurity.TransferPoseidonCall04R48Checks.mix5_checked
end ShielddSecurity.TransferPoseidonCall04R48Checks
namespace ShielddSecurity.TransferPoseidonCall04R49Checks
open Compiler CompilerIndexed01 CompilerCompletion Poseidon PoseidonIndexedRound01 ShielddSecurity.TransferPoseidonCall04Shared01 ShielddSecurity.TransferPoseidonCall04R49
theorem column0_checked : checkColumn p copy originalRows parameters 49 before shifted transformed fifthHints ⟨0,by decide⟩=true := by decide +kernel
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonCall04R49Checks.column0_checked
#print axioms ShielddSecurity.TransferPoseidonCall04R49Checks.column0_checked
end ShielddSecurity.TransferPoseidonCall04R49Checks
namespace ShielddSecurity.TransferPoseidonCall04R49Checks
open Compiler CompilerIndexed01 CompilerCompletion Poseidon PoseidonIndexedRound01 ShielddSecurity.TransferPoseidonCall04Shared01 ShielddSecurity.TransferPoseidonCall04R49
theorem column1_checked : checkColumn p copy originalRows parameters 49 before shifted transformed fifthHints ⟨1,by decide⟩=true := by decide +kernel
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonCall04R49Checks.column1_checked
#print axioms ShielddSecurity.TransferPoseidonCall04R49Checks.column1_checked
end ShielddSecurity.TransferPoseidonCall04R49Checks
namespace ShielddSecurity.TransferPoseidonCall04R49Checks
open Compiler CompilerIndexed01 CompilerCompletion Poseidon PoseidonIndexedRound01 ShielddSecurity.TransferPoseidonCall04Shared01 ShielddSecurity.TransferPoseidonCall04R49
theorem column2_checked : checkColumn p copy originalRows parameters 49 before shifted transformed fifthHints ⟨2,by decide⟩=true := by decide +kernel
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonCall04R49Checks.column2_checked
#print axioms ShielddSecurity.TransferPoseidonCall04R49Checks.column2_checked
end ShielddSecurity.TransferPoseidonCall04R49Checks
namespace ShielddSecurity.TransferPoseidonCall04R49Checks
open Compiler CompilerIndexed01 CompilerCompletion Poseidon PoseidonIndexedRound01 ShielddSecurity.TransferPoseidonCall04Shared01 ShielddSecurity.TransferPoseidonCall04R49
theorem column3_checked : checkColumn p copy originalRows parameters 49 before shifted transformed fifthHints ⟨3,by decide⟩=true := by decide +kernel
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonCall04R49Checks.column3_checked
#print axioms ShielddSecurity.TransferPoseidonCall04R49Checks.column3_checked
end ShielddSecurity.TransferPoseidonCall04R49Checks
namespace ShielddSecurity.TransferPoseidonCall04R49Checks
open Compiler CompilerIndexed01 CompilerCompletion Poseidon PoseidonIndexedRound01 ShielddSecurity.TransferPoseidonCall04Shared01 ShielddSecurity.TransferPoseidonCall04R49
theorem column4_checked : checkColumn p copy originalRows parameters 49 before shifted transformed fifthHints ⟨4,by decide⟩=true := by decide +kernel
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonCall04R49Checks.column4_checked
#print axioms ShielddSecurity.TransferPoseidonCall04R49Checks.column4_checked
end ShielddSecurity.TransferPoseidonCall04R49Checks
namespace ShielddSecurity.TransferPoseidonCall04R49Checks
open Compiler CompilerIndexed01 CompilerCompletion Poseidon PoseidonIndexedRound01 ShielddSecurity.TransferPoseidonCall04Shared01 ShielddSecurity.TransferPoseidonCall04R49
theorem column5_checked : checkColumn p copy originalRows parameters 49 before shifted transformed fifthHints ⟨5,by decide⟩=true := by decide +kernel
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonCall04R49Checks.column5_checked
#print axioms ShielddSecurity.TransferPoseidonCall04R49Checks.column5_checked
end ShielddSecurity.TransferPoseidonCall04R49Checks
namespace ShielddSecurity.TransferPoseidonCall04R49Checks
open Compiler CompilerIndexed01 CompilerCompletion Poseidon PoseidonIndexedRound01 ShielddSecurity.TransferPoseidonCall04Shared01 ShielddSecurity.TransferPoseidonCall04R49
theorem mix0_checked : canonical p (after ⟨0,by decide⟩)=canonical p (mixLinear parameters.mds transformed ⟨0,by decide⟩) := by decide +kernel
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonCall04R49Checks.mix0_checked
#print axioms ShielddSecurity.TransferPoseidonCall04R49Checks.mix0_checked
end ShielddSecurity.TransferPoseidonCall04R49Checks
namespace ShielddSecurity.TransferPoseidonCall04R49Checks
open Compiler CompilerIndexed01 CompilerCompletion Poseidon PoseidonIndexedRound01 ShielddSecurity.TransferPoseidonCall04Shared01 ShielddSecurity.TransferPoseidonCall04R49
theorem mix1_checked : canonical p (after ⟨1,by decide⟩)=canonical p (mixLinear parameters.mds transformed ⟨1,by decide⟩) := by decide +kernel
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonCall04R49Checks.mix1_checked
#print axioms ShielddSecurity.TransferPoseidonCall04R49Checks.mix1_checked
end ShielddSecurity.TransferPoseidonCall04R49Checks
namespace ShielddSecurity.TransferPoseidonCall04R49Checks
open Compiler CompilerIndexed01 CompilerCompletion Poseidon PoseidonIndexedRound01 ShielddSecurity.TransferPoseidonCall04Shared01 ShielddSecurity.TransferPoseidonCall04R49
theorem mix2_checked : canonical p (after ⟨2,by decide⟩)=canonical p (mixLinear parameters.mds transformed ⟨2,by decide⟩) := by decide +kernel
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonCall04R49Checks.mix2_checked
#print axioms ShielddSecurity.TransferPoseidonCall04R49Checks.mix2_checked
end ShielddSecurity.TransferPoseidonCall04R49Checks
namespace ShielddSecurity.TransferPoseidonCall04R49Checks
open Compiler CompilerIndexed01 CompilerCompletion Poseidon PoseidonIndexedRound01 ShielddSecurity.TransferPoseidonCall04Shared01 ShielddSecurity.TransferPoseidonCall04R49
theorem mix3_checked : canonical p (after ⟨3,by decide⟩)=canonical p (mixLinear parameters.mds transformed ⟨3,by decide⟩) := by decide +kernel
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonCall04R49Checks.mix3_checked
#print axioms ShielddSecurity.TransferPoseidonCall04R49Checks.mix3_checked
end ShielddSecurity.TransferPoseidonCall04R49Checks
namespace ShielddSecurity.TransferPoseidonCall04R49Checks
open Compiler CompilerIndexed01 CompilerCompletion Poseidon PoseidonIndexedRound01 ShielddSecurity.TransferPoseidonCall04Shared01 ShielddSecurity.TransferPoseidonCall04R49
theorem mix4_checked : canonical p (after ⟨4,by decide⟩)=canonical p (mixLinear parameters.mds transformed ⟨4,by decide⟩) := by decide +kernel
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonCall04R49Checks.mix4_checked
#print axioms ShielddSecurity.TransferPoseidonCall04R49Checks.mix4_checked
end ShielddSecurity.TransferPoseidonCall04R49Checks
namespace ShielddSecurity.TransferPoseidonCall04R49Checks
open Compiler CompilerIndexed01 CompilerCompletion Poseidon PoseidonIndexedRound01 ShielddSecurity.TransferPoseidonCall04Shared01 ShielddSecurity.TransferPoseidonCall04R49
theorem mix5_checked : canonical p (after ⟨5,by decide⟩)=canonical p (mixLinear parameters.mds transformed ⟨5,by decide⟩) := by decide +kernel
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonCall04R49Checks.mix5_checked
#print axioms ShielddSecurity.TransferPoseidonCall04R49Checks.mix5_checked
end ShielddSecurity.TransferPoseidonCall04R49Checks
namespace ShielddSecurity.TransferPoseidonCall04R50Checks
open Compiler CompilerIndexed01 CompilerCompletion Poseidon PoseidonIndexedRound01 ShielddSecurity.TransferPoseidonCall04Shared01 ShielddSecurity.TransferPoseidonCall04R50
theorem column0_checked : checkColumn p copy originalRows parameters 50 before shifted transformed fifthHints ⟨0,by decide⟩=true := by decide +kernel
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonCall04R50Checks.column0_checked
#print axioms ShielddSecurity.TransferPoseidonCall04R50Checks.column0_checked
end ShielddSecurity.TransferPoseidonCall04R50Checks
namespace ShielddSecurity.TransferPoseidonCall04R50Checks
open Compiler CompilerIndexed01 CompilerCompletion Poseidon PoseidonIndexedRound01 ShielddSecurity.TransferPoseidonCall04Shared01 ShielddSecurity.TransferPoseidonCall04R50
theorem column1_checked : checkColumn p copy originalRows parameters 50 before shifted transformed fifthHints ⟨1,by decide⟩=true := by decide +kernel
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonCall04R50Checks.column1_checked
#print axioms ShielddSecurity.TransferPoseidonCall04R50Checks.column1_checked
end ShielddSecurity.TransferPoseidonCall04R50Checks
namespace ShielddSecurity.TransferPoseidonCall04R50Checks
open Compiler CompilerIndexed01 CompilerCompletion Poseidon PoseidonIndexedRound01 ShielddSecurity.TransferPoseidonCall04Shared01 ShielddSecurity.TransferPoseidonCall04R50
theorem column2_checked : checkColumn p copy originalRows parameters 50 before shifted transformed fifthHints ⟨2,by decide⟩=true := by decide +kernel
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonCall04R50Checks.column2_checked
#print axioms ShielddSecurity.TransferPoseidonCall04R50Checks.column2_checked
end ShielddSecurity.TransferPoseidonCall04R50Checks
namespace ShielddSecurity.TransferPoseidonCall04R50Checks
open Compiler CompilerIndexed01 CompilerCompletion Poseidon PoseidonIndexedRound01 ShielddSecurity.TransferPoseidonCall04Shared01 ShielddSecurity.TransferPoseidonCall04R50
theorem column3_checked : checkColumn p copy originalRows parameters 50 before shifted transformed fifthHints ⟨3,by decide⟩=true := by decide +kernel
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonCall04R50Checks.column3_checked
#print axioms ShielddSecurity.TransferPoseidonCall04R50Checks.column3_checked
end ShielddSecurity.TransferPoseidonCall04R50Checks
namespace ShielddSecurity.TransferPoseidonCall04R50Checks
open Compiler CompilerIndexed01 CompilerCompletion Poseidon PoseidonIndexedRound01 ShielddSecurity.TransferPoseidonCall04Shared01 ShielddSecurity.TransferPoseidonCall04R50
theorem column4_checked : checkColumn p copy originalRows parameters 50 before shifted transformed fifthHints ⟨4,by decide⟩=true := by decide +kernel
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonCall04R50Checks.column4_checked
#print axioms ShielddSecurity.TransferPoseidonCall04R50Checks.column4_checked
end ShielddSecurity.TransferPoseidonCall04R50Checks
namespace ShielddSecurity.TransferPoseidonCall04R50Checks
open Compiler CompilerIndexed01 CompilerCompletion Poseidon PoseidonIndexedRound01 ShielddSecurity.TransferPoseidonCall04Shared01 ShielddSecurity.TransferPoseidonCall04R50
theorem column5_checked : checkColumn p copy originalRows parameters 50 before shifted transformed fifthHints ⟨5,by decide⟩=true := by decide +kernel
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonCall04R50Checks.column5_checked
#print axioms ShielddSecurity.TransferPoseidonCall04R50Checks.column5_checked
end ShielddSecurity.TransferPoseidonCall04R50Checks
namespace ShielddSecurity.TransferPoseidonCall04R50Checks
open Compiler CompilerIndexed01 CompilerCompletion Poseidon PoseidonIndexedRound01 ShielddSecurity.TransferPoseidonCall04Shared01 ShielddSecurity.TransferPoseidonCall04R50
theorem mix0_checked : canonical p (after ⟨0,by decide⟩)=canonical p (mixLinear parameters.mds transformed ⟨0,by decide⟩) := by decide +kernel
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonCall04R50Checks.mix0_checked
#print axioms ShielddSecurity.TransferPoseidonCall04R50Checks.mix0_checked
end ShielddSecurity.TransferPoseidonCall04R50Checks
namespace ShielddSecurity.TransferPoseidonCall04R50Checks
open Compiler CompilerIndexed01 CompilerCompletion Poseidon PoseidonIndexedRound01 ShielddSecurity.TransferPoseidonCall04Shared01 ShielddSecurity.TransferPoseidonCall04R50
theorem mix1_checked : canonical p (after ⟨1,by decide⟩)=canonical p (mixLinear parameters.mds transformed ⟨1,by decide⟩) := by decide +kernel
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonCall04R50Checks.mix1_checked
#print axioms ShielddSecurity.TransferPoseidonCall04R50Checks.mix1_checked
end ShielddSecurity.TransferPoseidonCall04R50Checks
namespace ShielddSecurity.TransferPoseidonCall04R50Checks
open Compiler CompilerIndexed01 CompilerCompletion Poseidon PoseidonIndexedRound01 ShielddSecurity.TransferPoseidonCall04Shared01 ShielddSecurity.TransferPoseidonCall04R50
theorem mix2_checked : canonical p (after ⟨2,by decide⟩)=canonical p (mixLinear parameters.mds transformed ⟨2,by decide⟩) := by decide +kernel
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonCall04R50Checks.mix2_checked
#print axioms ShielddSecurity.TransferPoseidonCall04R50Checks.mix2_checked
end ShielddSecurity.TransferPoseidonCall04R50Checks
namespace ShielddSecurity.TransferPoseidonCall04R50Checks
open Compiler CompilerIndexed01 CompilerCompletion Poseidon PoseidonIndexedRound01 ShielddSecurity.TransferPoseidonCall04Shared01 ShielddSecurity.TransferPoseidonCall04R50
theorem mix3_checked : canonical p (after ⟨3,by decide⟩)=canonical p (mixLinear parameters.mds transformed ⟨3,by decide⟩) := by decide +kernel
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonCall04R50Checks.mix3_checked
#print axioms ShielddSecurity.TransferPoseidonCall04R50Checks.mix3_checked
end ShielddSecurity.TransferPoseidonCall04R50Checks
namespace ShielddSecurity.TransferPoseidonCall04R50Checks
open Compiler CompilerIndexed01 CompilerCompletion Poseidon PoseidonIndexedRound01 ShielddSecurity.TransferPoseidonCall04Shared01 ShielddSecurity.TransferPoseidonCall04R50
theorem mix4_checked : canonical p (after ⟨4,by decide⟩)=canonical p (mixLinear parameters.mds transformed ⟨4,by decide⟩) := by decide +kernel
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonCall04R50Checks.mix4_checked
#print axioms ShielddSecurity.TransferPoseidonCall04R50Checks.mix4_checked
end ShielddSecurity.TransferPoseidonCall04R50Checks
namespace ShielddSecurity.TransferPoseidonCall04R50Checks
open Compiler CompilerIndexed01 CompilerCompletion Poseidon PoseidonIndexedRound01 ShielddSecurity.TransferPoseidonCall04Shared01 ShielddSecurity.TransferPoseidonCall04R50
theorem mix5_checked : canonical p (after ⟨5,by decide⟩)=canonical p (mixLinear parameters.mds transformed ⟨5,by decide⟩) := by decide +kernel
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonCall04R50Checks.mix5_checked
#print axioms ShielddSecurity.TransferPoseidonCall04R50Checks.mix5_checked
end ShielddSecurity.TransferPoseidonCall04R50Checks
namespace ShielddSecurity.TransferPoseidonCall04R51Checks
open Compiler CompilerIndexed01 CompilerCompletion Poseidon PoseidonIndexedRound01 ShielddSecurity.TransferPoseidonCall04Shared01 ShielddSecurity.TransferPoseidonCall04R51
theorem column0_checked : checkColumn p copy originalRows parameters 51 before shifted transformed fifthHints ⟨0,by decide⟩=true := by decide +kernel
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonCall04R51Checks.column0_checked
#print axioms ShielddSecurity.TransferPoseidonCall04R51Checks.column0_checked
end ShielddSecurity.TransferPoseidonCall04R51Checks
namespace ShielddSecurity.TransferPoseidonCall04R51Checks
open Compiler CompilerIndexed01 CompilerCompletion Poseidon PoseidonIndexedRound01 ShielddSecurity.TransferPoseidonCall04Shared01 ShielddSecurity.TransferPoseidonCall04R51
theorem column1_checked : checkColumn p copy originalRows parameters 51 before shifted transformed fifthHints ⟨1,by decide⟩=true := by decide +kernel
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonCall04R51Checks.column1_checked
#print axioms ShielddSecurity.TransferPoseidonCall04R51Checks.column1_checked
end ShielddSecurity.TransferPoseidonCall04R51Checks
namespace ShielddSecurity.TransferPoseidonCall04R51Checks
open Compiler CompilerIndexed01 CompilerCompletion Poseidon PoseidonIndexedRound01 ShielddSecurity.TransferPoseidonCall04Shared01 ShielddSecurity.TransferPoseidonCall04R51
theorem column2_checked : checkColumn p copy originalRows parameters 51 before shifted transformed fifthHints ⟨2,by decide⟩=true := by decide +kernel
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonCall04R51Checks.column2_checked
#print axioms ShielddSecurity.TransferPoseidonCall04R51Checks.column2_checked
end ShielddSecurity.TransferPoseidonCall04R51Checks
namespace ShielddSecurity.TransferPoseidonCall04R51Checks
open Compiler CompilerIndexed01 CompilerCompletion Poseidon PoseidonIndexedRound01 ShielddSecurity.TransferPoseidonCall04Shared01 ShielddSecurity.TransferPoseidonCall04R51
theorem column3_checked : checkColumn p copy originalRows parameters 51 before shifted transformed fifthHints ⟨3,by decide⟩=true := by decide +kernel
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonCall04R51Checks.column3_checked
#print axioms ShielddSecurity.TransferPoseidonCall04R51Checks.column3_checked
end ShielddSecurity.TransferPoseidonCall04R51Checks
namespace ShielddSecurity.TransferPoseidonCall04R51Checks
open Compiler CompilerIndexed01 CompilerCompletion Poseidon PoseidonIndexedRound01 ShielddSecurity.TransferPoseidonCall04Shared01 ShielddSecurity.TransferPoseidonCall04R51
theorem column4_checked : checkColumn p copy originalRows parameters 51 before shifted transformed fifthHints ⟨4,by decide⟩=true := by decide +kernel
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonCall04R51Checks.column4_checked
#print axioms ShielddSecurity.TransferPoseidonCall04R51Checks.column4_checked
end ShielddSecurity.TransferPoseidonCall04R51Checks
namespace ShielddSecurity.TransferPoseidonCall04R51Checks
open Compiler CompilerIndexed01 CompilerCompletion Poseidon PoseidonIndexedRound01 ShielddSecurity.TransferPoseidonCall04Shared01 ShielddSecurity.TransferPoseidonCall04R51
theorem column5_checked : checkColumn p copy originalRows parameters 51 before shifted transformed fifthHints ⟨5,by decide⟩=true := by decide +kernel
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonCall04R51Checks.column5_checked
#print axioms ShielddSecurity.TransferPoseidonCall04R51Checks.column5_checked
end ShielddSecurity.TransferPoseidonCall04R51Checks
namespace ShielddSecurity.TransferPoseidonCall04R51Checks
open Compiler CompilerIndexed01 CompilerCompletion Poseidon PoseidonIndexedRound01 ShielddSecurity.TransferPoseidonCall04Shared01 ShielddSecurity.TransferPoseidonCall04R51
theorem mix0_checked : canonical p (after ⟨0,by decide⟩)=canonical p (mixLinear parameters.mds transformed ⟨0,by decide⟩) := by decide +kernel
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonCall04R51Checks.mix0_checked
#print axioms ShielddSecurity.TransferPoseidonCall04R51Checks.mix0_checked
end ShielddSecurity.TransferPoseidonCall04R51Checks
namespace ShielddSecurity.TransferPoseidonCall04R51Checks
open Compiler CompilerIndexed01 CompilerCompletion Poseidon PoseidonIndexedRound01 ShielddSecurity.TransferPoseidonCall04Shared01 ShielddSecurity.TransferPoseidonCall04R51
theorem mix1_checked : canonical p (after ⟨1,by decide⟩)=canonical p (mixLinear parameters.mds transformed ⟨1,by decide⟩) := by decide +kernel
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonCall04R51Checks.mix1_checked
#print axioms ShielddSecurity.TransferPoseidonCall04R51Checks.mix1_checked
end ShielddSecurity.TransferPoseidonCall04R51Checks
namespace ShielddSecurity.TransferPoseidonCall04R51Checks
open Compiler CompilerIndexed01 CompilerCompletion Poseidon PoseidonIndexedRound01 ShielddSecurity.TransferPoseidonCall04Shared01 ShielddSecurity.TransferPoseidonCall04R51
theorem mix2_checked : canonical p (after ⟨2,by decide⟩)=canonical p (mixLinear parameters.mds transformed ⟨2,by decide⟩) := by decide +kernel
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonCall04R51Checks.mix2_checked
#print axioms ShielddSecurity.TransferPoseidonCall04R51Checks.mix2_checked
end ShielddSecurity.TransferPoseidonCall04R51Checks
namespace ShielddSecurity.TransferPoseidonCall04R51Checks
open Compiler CompilerIndexed01 CompilerCompletion Poseidon PoseidonIndexedRound01 ShielddSecurity.TransferPoseidonCall04Shared01 ShielddSecurity.TransferPoseidonCall04R51
theorem mix3_checked : canonical p (after ⟨3,by decide⟩)=canonical p (mixLinear parameters.mds transformed ⟨3,by decide⟩) := by decide +kernel
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonCall04R51Checks.mix3_checked
#print axioms ShielddSecurity.TransferPoseidonCall04R51Checks.mix3_checked
end ShielddSecurity.TransferPoseidonCall04R51Checks
namespace ShielddSecurity.TransferPoseidonCall04R51Checks
open Compiler CompilerIndexed01 CompilerCompletion Poseidon PoseidonIndexedRound01 ShielddSecurity.TransferPoseidonCall04Shared01 ShielddSecurity.TransferPoseidonCall04R51
theorem mix4_checked : canonical p (after ⟨4,by decide⟩)=canonical p (mixLinear parameters.mds transformed ⟨4,by decide⟩) := by decide +kernel
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonCall04R51Checks.mix4_checked
#print axioms ShielddSecurity.TransferPoseidonCall04R51Checks.mix4_checked
end ShielddSecurity.TransferPoseidonCall04R51Checks
namespace ShielddSecurity.TransferPoseidonCall04R51Checks
open Compiler CompilerIndexed01 CompilerCompletion Poseidon PoseidonIndexedRound01 ShielddSecurity.TransferPoseidonCall04Shared01 ShielddSecurity.TransferPoseidonCall04R51
theorem mix5_checked : canonical p (after ⟨5,by decide⟩)=canonical p (mixLinear parameters.mds transformed ⟨5,by decide⟩) := by decide +kernel
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonCall04R51Checks.mix5_checked
#print axioms ShielddSecurity.TransferPoseidonCall04R51Checks.mix5_checked
end ShielddSecurity.TransferPoseidonCall04R51Checks
namespace ShielddSecurity.TransferPoseidonCall04R52Checks
open Compiler CompilerIndexed01 CompilerCompletion Poseidon PoseidonIndexedRound01 ShielddSecurity.TransferPoseidonCall04Shared01 ShielddSecurity.TransferPoseidonCall04R52
theorem column0_checked : checkColumn p copy originalRows parameters 52 before shifted transformed fifthHints ⟨0,by decide⟩=true := by decide +kernel
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonCall04R52Checks.column0_checked
#print axioms ShielddSecurity.TransferPoseidonCall04R52Checks.column0_checked
end ShielddSecurity.TransferPoseidonCall04R52Checks
namespace ShielddSecurity.TransferPoseidonCall04R52Checks
open Compiler CompilerIndexed01 CompilerCompletion Poseidon PoseidonIndexedRound01 ShielddSecurity.TransferPoseidonCall04Shared01 ShielddSecurity.TransferPoseidonCall04R52
theorem column1_checked : checkColumn p copy originalRows parameters 52 before shifted transformed fifthHints ⟨1,by decide⟩=true := by decide +kernel
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonCall04R52Checks.column1_checked
#print axioms ShielddSecurity.TransferPoseidonCall04R52Checks.column1_checked
end ShielddSecurity.TransferPoseidonCall04R52Checks
namespace ShielddSecurity.TransferPoseidonCall04R52Checks
open Compiler CompilerIndexed01 CompilerCompletion Poseidon PoseidonIndexedRound01 ShielddSecurity.TransferPoseidonCall04Shared01 ShielddSecurity.TransferPoseidonCall04R52
theorem column2_checked : checkColumn p copy originalRows parameters 52 before shifted transformed fifthHints ⟨2,by decide⟩=true := by decide +kernel
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonCall04R52Checks.column2_checked
#print axioms ShielddSecurity.TransferPoseidonCall04R52Checks.column2_checked
end ShielddSecurity.TransferPoseidonCall04R52Checks
namespace ShielddSecurity.TransferPoseidonCall04R52Checks
open Compiler CompilerIndexed01 CompilerCompletion Poseidon PoseidonIndexedRound01 ShielddSecurity.TransferPoseidonCall04Shared01 ShielddSecurity.TransferPoseidonCall04R52
theorem column3_checked : checkColumn p copy originalRows parameters 52 before shifted transformed fifthHints ⟨3,by decide⟩=true := by decide +kernel
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonCall04R52Checks.column3_checked
#print axioms ShielddSecurity.TransferPoseidonCall04R52Checks.column3_checked
end ShielddSecurity.TransferPoseidonCall04R52Checks
namespace ShielddSecurity.TransferPoseidonCall04R52Checks
open Compiler CompilerIndexed01 CompilerCompletion Poseidon PoseidonIndexedRound01 ShielddSecurity.TransferPoseidonCall04Shared01 ShielddSecurity.TransferPoseidonCall04R52
theorem column4_checked : checkColumn p copy originalRows parameters 52 before shifted transformed fifthHints ⟨4,by decide⟩=true := by decide +kernel
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonCall04R52Checks.column4_checked
#print axioms ShielddSecurity.TransferPoseidonCall04R52Checks.column4_checked
end ShielddSecurity.TransferPoseidonCall04R52Checks
namespace ShielddSecurity.TransferPoseidonCall04R52Checks
open Compiler CompilerIndexed01 CompilerCompletion Poseidon PoseidonIndexedRound01 ShielddSecurity.TransferPoseidonCall04Shared01 ShielddSecurity.TransferPoseidonCall04R52
theorem column5_checked : checkColumn p copy originalRows parameters 52 before shifted transformed fifthHints ⟨5,by decide⟩=true := by decide +kernel
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonCall04R52Checks.column5_checked
#print axioms ShielddSecurity.TransferPoseidonCall04R52Checks.column5_checked
end ShielddSecurity.TransferPoseidonCall04R52Checks
namespace ShielddSecurity.TransferPoseidonCall04R52Checks
open Compiler CompilerIndexed01 CompilerCompletion Poseidon PoseidonIndexedRound01 ShielddSecurity.TransferPoseidonCall04Shared01 ShielddSecurity.TransferPoseidonCall04R52
theorem mix0_checked : canonical p (after ⟨0,by decide⟩)=canonical p (mixLinear parameters.mds transformed ⟨0,by decide⟩) := by decide +kernel
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonCall04R52Checks.mix0_checked
#print axioms ShielddSecurity.TransferPoseidonCall04R52Checks.mix0_checked
end ShielddSecurity.TransferPoseidonCall04R52Checks
namespace ShielddSecurity.TransferPoseidonCall04R52Checks
open Compiler CompilerIndexed01 CompilerCompletion Poseidon PoseidonIndexedRound01 ShielddSecurity.TransferPoseidonCall04Shared01 ShielddSecurity.TransferPoseidonCall04R52
theorem mix1_checked : canonical p (after ⟨1,by decide⟩)=canonical p (mixLinear parameters.mds transformed ⟨1,by decide⟩) := by decide +kernel
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonCall04R52Checks.mix1_checked
#print axioms ShielddSecurity.TransferPoseidonCall04R52Checks.mix1_checked
end ShielddSecurity.TransferPoseidonCall04R52Checks
namespace ShielddSecurity.TransferPoseidonCall04R52Checks
open Compiler CompilerIndexed01 CompilerCompletion Poseidon PoseidonIndexedRound01 ShielddSecurity.TransferPoseidonCall04Shared01 ShielddSecurity.TransferPoseidonCall04R52
theorem mix2_checked : canonical p (after ⟨2,by decide⟩)=canonical p (mixLinear parameters.mds transformed ⟨2,by decide⟩) := by decide +kernel
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonCall04R52Checks.mix2_checked
#print axioms ShielddSecurity.TransferPoseidonCall04R52Checks.mix2_checked
end ShielddSecurity.TransferPoseidonCall04R52Checks
namespace ShielddSecurity.TransferPoseidonCall04R52Checks
open Compiler CompilerIndexed01 CompilerCompletion Poseidon PoseidonIndexedRound01 ShielddSecurity.TransferPoseidonCall04Shared01 ShielddSecurity.TransferPoseidonCall04R52
theorem mix3_checked : canonical p (after ⟨3,by decide⟩)=canonical p (mixLinear parameters.mds transformed ⟨3,by decide⟩) := by decide +kernel
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonCall04R52Checks.mix3_checked
#print axioms ShielddSecurity.TransferPoseidonCall04R52Checks.mix3_checked
end ShielddSecurity.TransferPoseidonCall04R52Checks
namespace ShielddSecurity.TransferPoseidonCall04R52Checks
open Compiler CompilerIndexed01 CompilerCompletion Poseidon PoseidonIndexedRound01 ShielddSecurity.TransferPoseidonCall04Shared01 ShielddSecurity.TransferPoseidonCall04R52
theorem mix4_checked : canonical p (after ⟨4,by decide⟩)=canonical p (mixLinear parameters.mds transformed ⟨4,by decide⟩) := by decide +kernel
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonCall04R52Checks.mix4_checked
#print axioms ShielddSecurity.TransferPoseidonCall04R52Checks.mix4_checked
end ShielddSecurity.TransferPoseidonCall04R52Checks
namespace ShielddSecurity.TransferPoseidonCall04R52Checks
open Compiler CompilerIndexed01 CompilerCompletion Poseidon PoseidonIndexedRound01 ShielddSecurity.TransferPoseidonCall04Shared01 ShielddSecurity.TransferPoseidonCall04R52
theorem mix5_checked : canonical p (after ⟨5,by decide⟩)=canonical p (mixLinear parameters.mds transformed ⟨5,by decide⟩) := by decide +kernel
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonCall04R52Checks.mix5_checked
#print axioms ShielddSecurity.TransferPoseidonCall04R52Checks.mix5_checked
end ShielddSecurity.TransferPoseidonCall04R52Checks
namespace ShielddSecurity.TransferPoseidonCall04R53Checks
open Compiler CompilerIndexed01 CompilerCompletion Poseidon PoseidonIndexedRound01 ShielddSecurity.TransferPoseidonCall04Shared01 ShielddSecurity.TransferPoseidonCall04R53
theorem column0_checked : checkColumn p copy originalRows parameters 53 before shifted transformed fifthHints ⟨0,by decide⟩=true := by decide +kernel
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonCall04R53Checks.column0_checked
#print axioms ShielddSecurity.TransferPoseidonCall04R53Checks.column0_checked
end ShielddSecurity.TransferPoseidonCall04R53Checks
namespace ShielddSecurity.TransferPoseidonCall04R53Checks
open Compiler CompilerIndexed01 CompilerCompletion Poseidon PoseidonIndexedRound01 ShielddSecurity.TransferPoseidonCall04Shared01 ShielddSecurity.TransferPoseidonCall04R53
theorem column1_checked : checkColumn p copy originalRows parameters 53 before shifted transformed fifthHints ⟨1,by decide⟩=true := by decide +kernel
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonCall04R53Checks.column1_checked
#print axioms ShielddSecurity.TransferPoseidonCall04R53Checks.column1_checked
end ShielddSecurity.TransferPoseidonCall04R53Checks
namespace ShielddSecurity.TransferPoseidonCall04R53Checks
open Compiler CompilerIndexed01 CompilerCompletion Poseidon PoseidonIndexedRound01 ShielddSecurity.TransferPoseidonCall04Shared01 ShielddSecurity.TransferPoseidonCall04R53
theorem column2_checked : checkColumn p copy originalRows parameters 53 before shifted transformed fifthHints ⟨2,by decide⟩=true := by decide +kernel
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonCall04R53Checks.column2_checked
#print axioms ShielddSecurity.TransferPoseidonCall04R53Checks.column2_checked
end ShielddSecurity.TransferPoseidonCall04R53Checks
namespace ShielddSecurity.TransferPoseidonCall04R53Checks
open Compiler CompilerIndexed01 CompilerCompletion Poseidon PoseidonIndexedRound01 ShielddSecurity.TransferPoseidonCall04Shared01 ShielddSecurity.TransferPoseidonCall04R53
theorem column3_checked : checkColumn p copy originalRows parameters 53 before shifted transformed fifthHints ⟨3,by decide⟩=true := by decide +kernel
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonCall04R53Checks.column3_checked
#print axioms ShielddSecurity.TransferPoseidonCall04R53Checks.column3_checked
end ShielddSecurity.TransferPoseidonCall04R53Checks
namespace ShielddSecurity.TransferPoseidonCall04R53Checks
open Compiler CompilerIndexed01 CompilerCompletion Poseidon PoseidonIndexedRound01 ShielddSecurity.TransferPoseidonCall04Shared01 ShielddSecurity.TransferPoseidonCall04R53
theorem column4_checked : checkColumn p copy originalRows parameters 53 before shifted transformed fifthHints ⟨4,by decide⟩=true := by decide +kernel
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonCall04R53Checks.column4_checked
#print axioms ShielddSecurity.TransferPoseidonCall04R53Checks.column4_checked
end ShielddSecurity.TransferPoseidonCall04R53Checks
namespace ShielddSecurity.TransferPoseidonCall04R53Checks
open Compiler CompilerIndexed01 CompilerCompletion Poseidon PoseidonIndexedRound01 ShielddSecurity.TransferPoseidonCall04Shared01 ShielddSecurity.TransferPoseidonCall04R53
theorem column5_checked : checkColumn p copy originalRows parameters 53 before shifted transformed fifthHints ⟨5,by decide⟩=true := by decide +kernel
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonCall04R53Checks.column5_checked
#print axioms ShielddSecurity.TransferPoseidonCall04R53Checks.column5_checked
end ShielddSecurity.TransferPoseidonCall04R53Checks
namespace ShielddSecurity.TransferPoseidonCall04R53Checks
open Compiler CompilerIndexed01 CompilerCompletion Poseidon PoseidonIndexedRound01 ShielddSecurity.TransferPoseidonCall04Shared01 ShielddSecurity.TransferPoseidonCall04R53
theorem mix0_checked : canonical p (after ⟨0,by decide⟩)=canonical p (mixLinear parameters.mds transformed ⟨0,by decide⟩) := by decide +kernel
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonCall04R53Checks.mix0_checked
#print axioms ShielddSecurity.TransferPoseidonCall04R53Checks.mix0_checked
end ShielddSecurity.TransferPoseidonCall04R53Checks
namespace ShielddSecurity.TransferPoseidonCall04R53Checks
open Compiler CompilerIndexed01 CompilerCompletion Poseidon PoseidonIndexedRound01 ShielddSecurity.TransferPoseidonCall04Shared01 ShielddSecurity.TransferPoseidonCall04R53
theorem mix1_checked : canonical p (after ⟨1,by decide⟩)=canonical p (mixLinear parameters.mds transformed ⟨1,by decide⟩) := by decide +kernel
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonCall04R53Checks.mix1_checked
#print axioms ShielddSecurity.TransferPoseidonCall04R53Checks.mix1_checked
end ShielddSecurity.TransferPoseidonCall04R53Checks
namespace ShielddSecurity.TransferPoseidonCall04R53Checks
open Compiler CompilerIndexed01 CompilerCompletion Poseidon PoseidonIndexedRound01 ShielddSecurity.TransferPoseidonCall04Shared01 ShielddSecurity.TransferPoseidonCall04R53
theorem mix2_checked : canonical p (after ⟨2,by decide⟩)=canonical p (mixLinear parameters.mds transformed ⟨2,by decide⟩) := by decide +kernel
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonCall04R53Checks.mix2_checked
#print axioms ShielddSecurity.TransferPoseidonCall04R53Checks.mix2_checked
end ShielddSecurity.TransferPoseidonCall04R53Checks
namespace ShielddSecurity.TransferPoseidonCall04R53Checks
open Compiler CompilerIndexed01 CompilerCompletion Poseidon PoseidonIndexedRound01 ShielddSecurity.TransferPoseidonCall04Shared01 ShielddSecurity.TransferPoseidonCall04R53
theorem mix3_checked : canonical p (after ⟨3,by decide⟩)=canonical p (mixLinear parameters.mds transformed ⟨3,by decide⟩) := by decide +kernel
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonCall04R53Checks.mix3_checked
#print axioms ShielddSecurity.TransferPoseidonCall04R53Checks.mix3_checked
end ShielddSecurity.TransferPoseidonCall04R53Checks
namespace ShielddSecurity.TransferPoseidonCall04R53Checks
open Compiler CompilerIndexed01 CompilerCompletion Poseidon PoseidonIndexedRound01 ShielddSecurity.TransferPoseidonCall04Shared01 ShielddSecurity.TransferPoseidonCall04R53
theorem mix4_checked : canonical p (after ⟨4,by decide⟩)=canonical p (mixLinear parameters.mds transformed ⟨4,by decide⟩) := by decide +kernel
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonCall04R53Checks.mix4_checked
#print axioms ShielddSecurity.TransferPoseidonCall04R53Checks.mix4_checked
end ShielddSecurity.TransferPoseidonCall04R53Checks
namespace ShielddSecurity.TransferPoseidonCall04R53Checks
open Compiler CompilerIndexed01 CompilerCompletion Poseidon PoseidonIndexedRound01 ShielddSecurity.TransferPoseidonCall04Shared01 ShielddSecurity.TransferPoseidonCall04R53
theorem mix5_checked : canonical p (after ⟨5,by decide⟩)=canonical p (mixLinear parameters.mds transformed ⟨5,by decide⟩) := by decide +kernel
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonCall04R53Checks.mix5_checked
#print axioms ShielddSecurity.TransferPoseidonCall04R53Checks.mix5_checked
end ShielddSecurity.TransferPoseidonCall04R53Checks
namespace ShielddSecurity.TransferPoseidonCall04R54Checks
open Compiler CompilerIndexed01 CompilerCompletion Poseidon PoseidonIndexedRound01 ShielddSecurity.TransferPoseidonCall04Shared01 ShielddSecurity.TransferPoseidonCall04R54
theorem column0_checked : checkColumn p copy originalRows parameters 54 before shifted transformed fifthHints ⟨0,by decide⟩=true := by decide +kernel
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonCall04R54Checks.column0_checked
#print axioms ShielddSecurity.TransferPoseidonCall04R54Checks.column0_checked
end ShielddSecurity.TransferPoseidonCall04R54Checks
namespace ShielddSecurity.TransferPoseidonCall04R54Checks
open Compiler CompilerIndexed01 CompilerCompletion Poseidon PoseidonIndexedRound01 ShielddSecurity.TransferPoseidonCall04Shared01 ShielddSecurity.TransferPoseidonCall04R54
theorem column1_checked : checkColumn p copy originalRows parameters 54 before shifted transformed fifthHints ⟨1,by decide⟩=true := by decide +kernel
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonCall04R54Checks.column1_checked
#print axioms ShielddSecurity.TransferPoseidonCall04R54Checks.column1_checked
end ShielddSecurity.TransferPoseidonCall04R54Checks
namespace ShielddSecurity.TransferPoseidonCall04R54Checks
open Compiler CompilerIndexed01 CompilerCompletion Poseidon PoseidonIndexedRound01 ShielddSecurity.TransferPoseidonCall04Shared01 ShielddSecurity.TransferPoseidonCall04R54
theorem column2_checked : checkColumn p copy originalRows parameters 54 before shifted transformed fifthHints ⟨2,by decide⟩=true := by decide +kernel
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonCall04R54Checks.column2_checked
#print axioms ShielddSecurity.TransferPoseidonCall04R54Checks.column2_checked
end ShielddSecurity.TransferPoseidonCall04R54Checks
namespace ShielddSecurity.TransferPoseidonCall04R54Checks
open Compiler CompilerIndexed01 CompilerCompletion Poseidon PoseidonIndexedRound01 ShielddSecurity.TransferPoseidonCall04Shared01 ShielddSecurity.TransferPoseidonCall04R54
theorem column3_checked : checkColumn p copy originalRows parameters 54 before shifted transformed fifthHints ⟨3,by decide⟩=true := by decide +kernel
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonCall04R54Checks.column3_checked
#print axioms ShielddSecurity.TransferPoseidonCall04R54Checks.column3_checked
end ShielddSecurity.TransferPoseidonCall04R54Checks
namespace ShielddSecurity.TransferPoseidonCall04R54Checks
open Compiler CompilerIndexed01 CompilerCompletion Poseidon PoseidonIndexedRound01 ShielddSecurity.TransferPoseidonCall04Shared01 ShielddSecurity.TransferPoseidonCall04R54
theorem column4_checked : checkColumn p copy originalRows parameters 54 before shifted transformed fifthHints ⟨4,by decide⟩=true := by decide +kernel
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonCall04R54Checks.column4_checked
#print axioms ShielddSecurity.TransferPoseidonCall04R54Checks.column4_checked
end ShielddSecurity.TransferPoseidonCall04R54Checks
namespace ShielddSecurity.TransferPoseidonCall04R54Checks
open Compiler CompilerIndexed01 CompilerCompletion Poseidon PoseidonIndexedRound01 ShielddSecurity.TransferPoseidonCall04Shared01 ShielddSecurity.TransferPoseidonCall04R54
theorem column5_checked : checkColumn p copy originalRows parameters 54 before shifted transformed fifthHints ⟨5,by decide⟩=true := by decide +kernel
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonCall04R54Checks.column5_checked
#print axioms ShielddSecurity.TransferPoseidonCall04R54Checks.column5_checked
end ShielddSecurity.TransferPoseidonCall04R54Checks
namespace ShielddSecurity.TransferPoseidonCall04R54Checks
open Compiler CompilerIndexed01 CompilerCompletion Poseidon PoseidonIndexedRound01 ShielddSecurity.TransferPoseidonCall04Shared01 ShielddSecurity.TransferPoseidonCall04R54
theorem mix0_checked : canonical p (after ⟨0,by decide⟩)=canonical p (mixLinear parameters.mds transformed ⟨0,by decide⟩) := by decide +kernel
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonCall04R54Checks.mix0_checked
#print axioms ShielddSecurity.TransferPoseidonCall04R54Checks.mix0_checked
end ShielddSecurity.TransferPoseidonCall04R54Checks
namespace ShielddSecurity.TransferPoseidonCall04R54Checks
open Compiler CompilerIndexed01 CompilerCompletion Poseidon PoseidonIndexedRound01 ShielddSecurity.TransferPoseidonCall04Shared01 ShielddSecurity.TransferPoseidonCall04R54
theorem mix1_checked : canonical p (after ⟨1,by decide⟩)=canonical p (mixLinear parameters.mds transformed ⟨1,by decide⟩) := by decide +kernel
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonCall04R54Checks.mix1_checked
#print axioms ShielddSecurity.TransferPoseidonCall04R54Checks.mix1_checked
end ShielddSecurity.TransferPoseidonCall04R54Checks
namespace ShielddSecurity.TransferPoseidonCall04R54Checks
open Compiler CompilerIndexed01 CompilerCompletion Poseidon PoseidonIndexedRound01 ShielddSecurity.TransferPoseidonCall04Shared01 ShielddSecurity.TransferPoseidonCall04R54
theorem mix2_checked : canonical p (after ⟨2,by decide⟩)=canonical p (mixLinear parameters.mds transformed ⟨2,by decide⟩) := by decide +kernel
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonCall04R54Checks.mix2_checked
#print axioms ShielddSecurity.TransferPoseidonCall04R54Checks.mix2_checked
end ShielddSecurity.TransferPoseidonCall04R54Checks
namespace ShielddSecurity.TransferPoseidonCall04R54Checks
open Compiler CompilerIndexed01 CompilerCompletion Poseidon PoseidonIndexedRound01 ShielddSecurity.TransferPoseidonCall04Shared01 ShielddSecurity.TransferPoseidonCall04R54
theorem mix3_checked : canonical p (after ⟨3,by decide⟩)=canonical p (mixLinear parameters.mds transformed ⟨3,by decide⟩) := by decide +kernel
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonCall04R54Checks.mix3_checked
#print axioms ShielddSecurity.TransferPoseidonCall04R54Checks.mix3_checked
end ShielddSecurity.TransferPoseidonCall04R54Checks
namespace ShielddSecurity.TransferPoseidonCall04R54Checks
open Compiler CompilerIndexed01 CompilerCompletion Poseidon PoseidonIndexedRound01 ShielddSecurity.TransferPoseidonCall04Shared01 ShielddSecurity.TransferPoseidonCall04R54
theorem mix4_checked : canonical p (after ⟨4,by decide⟩)=canonical p (mixLinear parameters.mds transformed ⟨4,by decide⟩) := by decide +kernel
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonCall04R54Checks.mix4_checked
#print axioms ShielddSecurity.TransferPoseidonCall04R54Checks.mix4_checked
end ShielddSecurity.TransferPoseidonCall04R54Checks
namespace ShielddSecurity.TransferPoseidonCall04R54Checks
open Compiler CompilerIndexed01 CompilerCompletion Poseidon PoseidonIndexedRound01 ShielddSecurity.TransferPoseidonCall04Shared01 ShielddSecurity.TransferPoseidonCall04R54
theorem mix5_checked : canonical p (after ⟨5,by decide⟩)=canonical p (mixLinear parameters.mds transformed ⟨5,by decide⟩) := by decide +kernel
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonCall04R54Checks.mix5_checked
#print axioms ShielddSecurity.TransferPoseidonCall04R54Checks.mix5_checked
end ShielddSecurity.TransferPoseidonCall04R54Checks
namespace ShielddSecurity.TransferPoseidonCall04R55Checks
open Compiler CompilerIndexed01 CompilerCompletion Poseidon PoseidonIndexedRound01 ShielddSecurity.TransferPoseidonCall04Shared01 ShielddSecurity.TransferPoseidonCall04R55
theorem column0_checked : checkColumn p copy originalRows parameters 55 before shifted transformed fifthHints ⟨0,by decide⟩=true := by decide +kernel
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonCall04R55Checks.column0_checked
#print axioms ShielddSecurity.TransferPoseidonCall04R55Checks.column0_checked
end ShielddSecurity.TransferPoseidonCall04R55Checks
namespace ShielddSecurity.TransferPoseidonCall04R55Checks
open Compiler CompilerIndexed01 CompilerCompletion Poseidon PoseidonIndexedRound01 ShielddSecurity.TransferPoseidonCall04Shared01 ShielddSecurity.TransferPoseidonCall04R55
theorem column1_checked : checkColumn p copy originalRows parameters 55 before shifted transformed fifthHints ⟨1,by decide⟩=true := by decide +kernel
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonCall04R55Checks.column1_checked
#print axioms ShielddSecurity.TransferPoseidonCall04R55Checks.column1_checked
end ShielddSecurity.TransferPoseidonCall04R55Checks
namespace ShielddSecurity.TransferPoseidonCall04R55Checks
open Compiler CompilerIndexed01 CompilerCompletion Poseidon PoseidonIndexedRound01 ShielddSecurity.TransferPoseidonCall04Shared01 ShielddSecurity.TransferPoseidonCall04R55
theorem column2_checked : checkColumn p copy originalRows parameters 55 before shifted transformed fifthHints ⟨2,by decide⟩=true := by decide +kernel
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonCall04R55Checks.column2_checked
#print axioms ShielddSecurity.TransferPoseidonCall04R55Checks.column2_checked
end ShielddSecurity.TransferPoseidonCall04R55Checks
namespace ShielddSecurity.TransferPoseidonCall04R55Checks
open Compiler CompilerIndexed01 CompilerCompletion Poseidon PoseidonIndexedRound01 ShielddSecurity.TransferPoseidonCall04Shared01 ShielddSecurity.TransferPoseidonCall04R55
theorem column3_checked : checkColumn p copy originalRows parameters 55 before shifted transformed fifthHints ⟨3,by decide⟩=true := by decide +kernel
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonCall04R55Checks.column3_checked
#print axioms ShielddSecurity.TransferPoseidonCall04R55Checks.column3_checked
end ShielddSecurity.TransferPoseidonCall04R55Checks
namespace ShielddSecurity.TransferPoseidonCall04R55Checks
open Compiler CompilerIndexed01 CompilerCompletion Poseidon PoseidonIndexedRound01 ShielddSecurity.TransferPoseidonCall04Shared01 ShielddSecurity.TransferPoseidonCall04R55
theorem column4_checked : checkColumn p copy originalRows parameters 55 before shifted transformed fifthHints ⟨4,by decide⟩=true := by decide +kernel
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonCall04R55Checks.column4_checked
#print axioms ShielddSecurity.TransferPoseidonCall04R55Checks.column4_checked
end ShielddSecurity.TransferPoseidonCall04R55Checks
namespace ShielddSecurity.TransferPoseidonCall04R55Checks
open Compiler CompilerIndexed01 CompilerCompletion Poseidon PoseidonIndexedRound01 ShielddSecurity.TransferPoseidonCall04Shared01 ShielddSecurity.TransferPoseidonCall04R55
theorem column5_checked : checkColumn p copy originalRows parameters 55 before shifted transformed fifthHints ⟨5,by decide⟩=true := by decide +kernel
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonCall04R55Checks.column5_checked
#print axioms ShielddSecurity.TransferPoseidonCall04R55Checks.column5_checked
end ShielddSecurity.TransferPoseidonCall04R55Checks
namespace ShielddSecurity.TransferPoseidonCall04R55Checks
open Compiler CompilerIndexed01 CompilerCompletion Poseidon PoseidonIndexedRound01 ShielddSecurity.TransferPoseidonCall04Shared01 ShielddSecurity.TransferPoseidonCall04R55
theorem mix0_checked : canonical p (after ⟨0,by decide⟩)=canonical p (mixLinear parameters.mds transformed ⟨0,by decide⟩) := by decide +kernel
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonCall04R55Checks.mix0_checked
#print axioms ShielddSecurity.TransferPoseidonCall04R55Checks.mix0_checked
end ShielddSecurity.TransferPoseidonCall04R55Checks
namespace ShielddSecurity.TransferPoseidonCall04R55Checks
open Compiler CompilerIndexed01 CompilerCompletion Poseidon PoseidonIndexedRound01 ShielddSecurity.TransferPoseidonCall04Shared01 ShielddSecurity.TransferPoseidonCall04R55
theorem mix1_checked : canonical p (after ⟨1,by decide⟩)=canonical p (mixLinear parameters.mds transformed ⟨1,by decide⟩) := by decide +kernel
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonCall04R55Checks.mix1_checked
#print axioms ShielddSecurity.TransferPoseidonCall04R55Checks.mix1_checked
end ShielddSecurity.TransferPoseidonCall04R55Checks
namespace ShielddSecurity.TransferPoseidonCall04R55Checks
open Compiler CompilerIndexed01 CompilerCompletion Poseidon PoseidonIndexedRound01 ShielddSecurity.TransferPoseidonCall04Shared01 ShielddSecurity.TransferPoseidonCall04R55
theorem mix2_checked : canonical p (after ⟨2,by decide⟩)=canonical p (mixLinear parameters.mds transformed ⟨2,by decide⟩) := by decide +kernel
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonCall04R55Checks.mix2_checked
#print axioms ShielddSecurity.TransferPoseidonCall04R55Checks.mix2_checked
end ShielddSecurity.TransferPoseidonCall04R55Checks
namespace ShielddSecurity.TransferPoseidonCall04R55Checks
open Compiler CompilerIndexed01 CompilerCompletion Poseidon PoseidonIndexedRound01 ShielddSecurity.TransferPoseidonCall04Shared01 ShielddSecurity.TransferPoseidonCall04R55
theorem mix3_checked : canonical p (after ⟨3,by decide⟩)=canonical p (mixLinear parameters.mds transformed ⟨3,by decide⟩) := by decide +kernel
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonCall04R55Checks.mix3_checked
#print axioms ShielddSecurity.TransferPoseidonCall04R55Checks.mix3_checked
end ShielddSecurity.TransferPoseidonCall04R55Checks
namespace ShielddSecurity.TransferPoseidonCall04R55Checks
open Compiler CompilerIndexed01 CompilerCompletion Poseidon PoseidonIndexedRound01 ShielddSecurity.TransferPoseidonCall04Shared01 ShielddSecurity.TransferPoseidonCall04R55
theorem mix4_checked : canonical p (after ⟨4,by decide⟩)=canonical p (mixLinear parameters.mds transformed ⟨4,by decide⟩) := by decide +kernel
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonCall04R55Checks.mix4_checked
#print axioms ShielddSecurity.TransferPoseidonCall04R55Checks.mix4_checked
end ShielddSecurity.TransferPoseidonCall04R55Checks
namespace ShielddSecurity.TransferPoseidonCall04R55Checks
open Compiler CompilerIndexed01 CompilerCompletion Poseidon PoseidonIndexedRound01 ShielddSecurity.TransferPoseidonCall04Shared01 ShielddSecurity.TransferPoseidonCall04R55
theorem mix5_checked : canonical p (after ⟨5,by decide⟩)=canonical p (mixLinear parameters.mds transformed ⟨5,by decide⟩) := by decide +kernel
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonCall04R55Checks.mix5_checked
#print axioms ShielddSecurity.TransferPoseidonCall04R55Checks.mix5_checked
end ShielddSecurity.TransferPoseidonCall04R55Checks
