import ShielddGnarkFormal.Deployed.Contracts.NoteReshape1x8.Seg5
import ShielddGnarkFormal.Deployed.Contracts.NoteReshape1x8.Seg7
import ShielddGnarkFormal.Deployed.Contracts.NoteReshape1x8.Seg9
import ShielddGnarkFormal.Deployed.Contracts.NoteReshape1x8.SemanticBindings
import ShielddGnarkFormal.Deployed.NoteReshape1x8DtkSeating

set_option maxRecDepth 1000000
set_option maxHeartbeats 4000000

/-! Exact compiler-LC and cross-segment seams for the note_reshape1x8 deployment.
GENERATED by gen_note_reshape_family.py — do not edit by hand. -/

namespace Shieldd.GnarkFormal.Deployed.Contracts.NoteReshape1x8

open Shieldd.GnarkFormal

/-- The compiler-labelled DTK x-coordinate is the exact DTK gadget output LC. -/
theorem sharedTransmissionComputed0_eq_dtkOutX
    (rho : Nat → SemanticF) :
    sharedTransmissionComputed0 rho =
      (Deployed.Templates.Semantics.TDecafDiversifiedTransmissionKey_a03dfc8083159402252a47c3be906c0878137600765dd0717aecbad037a5042c.DtkWindowSupport.output (Seg7.localRho rho)).x := by
  have h1 : Seg7.wireSeating 4961 = 5904 := by
    decide +kernel
  have h2 : Seg7.wireSeating 4969 = 5912 := by
    decide +kernel
  simpa only [
    sharedTransmissionComputed0,
    sharedTransmissionComputed0LC,
    Deployed.Templates.Semantics.TDecafDiversifiedTransmissionKey_a03dfc8083159402252a47c3be906c0878137600765dd0717aecbad037a5042c.DtkWindowSupport.output,
    StructuredLC.eval, StructuredLC.sumRuns, StructuredLC.sumResidual,
    StrideRun.eval, Seg7.localRho, Deployed.Templates.seated,
    h1, h2, zero_add, one_mul, add_zero]


end Shieldd.GnarkFormal.Deployed.Contracts.NoteReshape1x8
