"""Freeze and review tail constructor/recurrence and actual parent page scope."""
import hashlib,json,re,shutil,subprocess,time
from pathlib import Path
HERE=Path(__file__).resolve().parent;ROOT=HERE.parents[1];S=ROOT/'work/mac-poseidon-width3-rename09';P=S/'project/ShielddSecurity';F=HERE/'frozen';sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
assert not F.exists();F.mkdir();pending=['TransferPoseidonWidth3SecondTail09Proof01','TransferPoseidonWidth3ParentPage09Proof01'];seen=set();manifest={}
def copy(src,target):
    target.parent.mkdir(parents=True,exist_ok=True);shutil.copyfile(src,target);assert sha(src)==sha(target);manifest[str(target.relative_to(F))]={'source':str(src),'sha256':sha(src),'bytes':src.stat().st_size}
while pending:
    n=pending.pop()
    if n in seen:continue
    seen.add(n);src=P/(n+'.lean');copy(src,F/'ShielddSecurity'/src.name);pending.extend(re.findall(r'^import ShielddSecurity\.([A-Za-z0-9_]+)',src.read_text(),re.M))
for src in sorted(S.glob('*')):
    if src.is_file() and (src.name.startswith('generate') and src.suffix=='.py' or src.suffix=='.txt' or src.name in ['export_second_tail.py','validate_records.py']):copy(src,F/src.name)
copy(ROOT/'work/parent-width3-rename-review01/data-audit01.json',F/'parent-data-audit01.json')
(HERE/'source-manifest.json').write_text(json.dumps(manifest,indent=2)+'\n')
prompt=f'''Review the immutable frozen width3 tail/page source packet at {F}, read-only using Read/Glob/Grep. No edits, code execution or builds. Focus on CompilerPageSelection09,PoseidonRoundSuffix09,TransferPoseidonWidth3Tail09Program01/Tail09Semantic01,SecondTail09Proof01,ParentPage09Lookup01/Proof01 and maintained generator/templates. Verify: source tail rounds2..64,225materialized+copy steps,300arithmetic+copy rows; injective disjoint swap[24734,25044)<->[61620,61930); arbitrary target-base pullback, no unnecessary base equality; exacttarget rows/ports correspondence; same final assignment suffixrecurrence; preservation outside actualwrites[61630,61930),original22735inputs,copy and cutLCs; exact indexed inclusion in localoriginalpage38400..39423+copy200769; actual492prior-page-row frame. Later consumers39192..39423 are explicitly NOT claimed preserved. Full200770parent inclusion and wholecalltarget absorption/rounds0/1 remain OPEN, as do upstream/native/fullTransfer. CharP/Field/four!=0 and basecopylink premises are explicit; do not treat them as deployment theorems. Producer qualification descriptor SHAa9c0764846ed7c31012f295f3d4f77b952bcff27ce43d4b14c66d92e14ee43ae is DATA; parent independently checked1025DBrows,300translatedrows,63phasepairs,1548operations and492prior support. Prior fullwidth3/renaming helpers reviewed. The top source_nodes describes1548tailoperations starting364076, whereas the fullcensus span includes30round1nodes starting364046; this is an intentional finite-tail scope. Review for soundness/math defects, hiddenpremises, wrongstart/count/stateindex, forward-vs-pullback swap orientation, quantifier/frame mistakes, false page-vs-full relation claims. Generateddata can be checked through generators and generic kernel-checker contracts; do not read all large literals unnecessarily. Parent re-audits guards/existingtypes/axioms separately; no parentkernelrerun. Controls not yet included, no new control acceptance. Report actionable defects with evidence, otherwise no defect within the exact localtail/page scope.'''
(HERE/'review-prompt.txt').write_text(prompt+'\n');started=time.monotonic();cmd=['/Users/antoinecyr/.local/bin/claude','--model','claude-opus-5-5','--effort','high','--permission-mode','plan','--tools','Read,Glob,Grep','--strict-mcp-config','--no-session-persistence','--output-format','json','--print',prompt]
with (HERE/'opus55-review.json').open('w') as out,(HERE/'opus55-review.stderr').open('w') as err:r=subprocess.run(cmd,stdout=out,stderr=err,timeout=900)
j=json.loads((HERE/'opus55-review.json').read_text());assert r.returncode==0 and not j['is_error'] and 'claude-opus-5-5' in j['modelUsage'];assert all(sha(F/n)==x['sha256'] for n,x in manifest.items());print(json.dumps({'review':'complete','files':len(manifest),'seconds':time.monotonic()-started,'model':list(j['modelUsage'])}))
