-- GENERATED by generate_subgroup_primes.py from exact validated data.
import ShielddSecurity.LucasCertificate
import ShielddSecurity.FieldPrimeNode01
import ShielddSecurity.FieldPrimeNode02
import ShielddSecurity.FieldPrimeNode03
import ShielddSecurity.FieldPrimeNode09
set_option maxHeartbeats 300000
set_option maxRecDepth 4096
namespace ShielddSecurity.SubgroupPrimeNode16
open LucasCertificate
def certificate : Certificate := ⟨5521,11,[⟨2,2760,5520⟩, ⟨2,2760,5520⟩, ⟨2,2760,5520⟩, ⟨2,2760,5520⟩, ⟨3,1840,5180⟩, ⟨5,1104,1374⟩, ⟨23,240,485⟩]⟩
theorem checked : certificate.check=true := by decide +kernel
theorem prime : Nat.Prime 5521 := by
  change Nat.Prime certificate.n
  apply certificate_sound certificate _ checked
  simp [certificate, FieldPrimeNode01.prime, FieldPrimeNode02.prime, FieldPrimeNode03.prime, FieldPrimeNode09.prime]
set_option pp.all true in
#check @ShielddSecurity.SubgroupPrimeNode16.checked
#print axioms ShielddSecurity.SubgroupPrimeNode16.checked
set_option pp.all true in
#check @ShielddSecurity.SubgroupPrimeNode16.prime
#print axioms ShielddSecurity.SubgroupPrimeNode16.prime
end ShielddSecurity.SubgroupPrimeNode16
