-- GENERATED by generate_blocks.py; edit generator.
import ShielddSecurity.TransferPoseidonCall04Data08
set_option maxHeartbeats 900000
set_option maxRecDepth 8192
namespace ShielddSecurity.TransferPoseidonCall04R64Checks
open Compiler CompilerIndexed01 CompilerCompletion Poseidon PoseidonIndexedRound01 ShielddSecurity.TransferPoseidonCall04Shared01 ShielddSecurity.TransferPoseidonCall04R64
theorem ordered_checked : CompilerOrder.checkOrder [0,copy] [] materializedSteps=true := by decide +kernel
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonCall04R64Checks.ordered_checked
#print axioms ShielddSecurity.TransferPoseidonCall04R64Checks.ordered_checked
end ShielddSecurity.TransferPoseidonCall04R64Checks
namespace ShielddSecurity.TransferPoseidonCall04R64Checks
open Compiler CompilerIndexed01 CompilerCompletion Poseidon PoseidonIndexedRound01 ShielddSecurity.TransferPoseidonCall04Shared01 ShielddSecurity.TransferPoseidonCall04R64
theorem writes_checked : (PoseidonCompletion.writes materializedSteps).all (fun column => decide (23448≤column ∧ column≤23471))=true := by decide +kernel
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonCall04R64Checks.writes_checked
#print axioms ShielddSecurity.TransferPoseidonCall04R64Checks.writes_checked
end ShielddSecurity.TransferPoseidonCall04R64Checks
namespace ShielddSecurity.TransferPoseidonCall04R64Checks
open Compiler CompilerIndexed01 CompilerCompletion Poseidon PoseidonIndexedRound01 ShielddSecurity.TransferPoseidonCall04Shared01 ShielddSecurity.TransferPoseidonCall04R64
theorem emitted_support_checked : (emitted materializedSteps).all (fun row => (row.a++row.b).all (fun term => decide (term.1<23472)))=true := by decide +kernel
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonCall04R64Checks.emitted_support_checked
#print axioms ShielddSecurity.TransferPoseidonCall04R64Checks.emitted_support_checked
end ShielddSecurity.TransferPoseidonCall04R64Checks
namespace ShielddSecurity.TransferPoseidonCall04R64Checks
open Compiler CompilerIndexed01 CompilerCompletion Poseidon PoseidonIndexedRound01 ShielddSecurity.TransferPoseidonCall04Shared01 ShielddSecurity.TransferPoseidonCall04R64
theorem copy_checked : checkRowAt p originalRows 24 ⟨[(0,1),(copy,-1)],[]⟩=true := by decide +kernel
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonCall04R64Checks.copy_checked
#print axioms ShielddSecurity.TransferPoseidonCall04R64Checks.copy_checked
end ShielddSecurity.TransferPoseidonCall04R64Checks
namespace ShielddSecurity.TransferPoseidonCall04R64Checks
open Compiler CompilerIndexed01 CompilerCompletion Poseidon PoseidonIndexedRound01 ShielddSecurity.TransferPoseidonCall04Shared01 ShielddSecurity.TransferPoseidonCall04R64
theorem rows_shape : arithmeticRows.size=24 ∧ rowMapping.size=24 ∧ materializedSteps.length=18 := by decide +kernel
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonCall04R64Checks.rows_shape
#print axioms ShielddSecurity.TransferPoseidonCall04R64Checks.rows_shape
end ShielddSecurity.TransferPoseidonCall04R64Checks
