-- GENERATED by generate_blocks.py; edit generator.
import ShielddSecurity.TransferPoseidonCall04Data04
set_option maxHeartbeats 900000
set_option maxRecDepth 8192
namespace ShielddSecurity.TransferPoseidonCall04R32Checks
open Compiler CompilerIndexed01 CompilerCompletion Poseidon PoseidonIndexedRound01 ShielddSecurity.TransferPoseidonCall04Shared01 ShielddSecurity.TransferPoseidonCall04R32
theorem column0_checked : checkColumn p copy originalRows parameters 32 before shifted transformed fifthHints ⟨0,by decide⟩=true := by decide +kernel
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonCall04R32Checks.column0_checked
#print axioms ShielddSecurity.TransferPoseidonCall04R32Checks.column0_checked
end ShielddSecurity.TransferPoseidonCall04R32Checks
namespace ShielddSecurity.TransferPoseidonCall04R32Checks
open Compiler CompilerIndexed01 CompilerCompletion Poseidon PoseidonIndexedRound01 ShielddSecurity.TransferPoseidonCall04Shared01 ShielddSecurity.TransferPoseidonCall04R32
theorem column1_checked : checkColumn p copy originalRows parameters 32 before shifted transformed fifthHints ⟨1,by decide⟩=true := by decide +kernel
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonCall04R32Checks.column1_checked
#print axioms ShielddSecurity.TransferPoseidonCall04R32Checks.column1_checked
end ShielddSecurity.TransferPoseidonCall04R32Checks
namespace ShielddSecurity.TransferPoseidonCall04R32Checks
open Compiler CompilerIndexed01 CompilerCompletion Poseidon PoseidonIndexedRound01 ShielddSecurity.TransferPoseidonCall04Shared01 ShielddSecurity.TransferPoseidonCall04R32
theorem column2_checked : checkColumn p copy originalRows parameters 32 before shifted transformed fifthHints ⟨2,by decide⟩=true := by decide +kernel
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonCall04R32Checks.column2_checked
#print axioms ShielddSecurity.TransferPoseidonCall04R32Checks.column2_checked
end ShielddSecurity.TransferPoseidonCall04R32Checks
namespace ShielddSecurity.TransferPoseidonCall04R32Checks
open Compiler CompilerIndexed01 CompilerCompletion Poseidon PoseidonIndexedRound01 ShielddSecurity.TransferPoseidonCall04Shared01 ShielddSecurity.TransferPoseidonCall04R32
theorem column3_checked : checkColumn p copy originalRows parameters 32 before shifted transformed fifthHints ⟨3,by decide⟩=true := by decide +kernel
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonCall04R32Checks.column3_checked
#print axioms ShielddSecurity.TransferPoseidonCall04R32Checks.column3_checked
end ShielddSecurity.TransferPoseidonCall04R32Checks
namespace ShielddSecurity.TransferPoseidonCall04R32Checks
open Compiler CompilerIndexed01 CompilerCompletion Poseidon PoseidonIndexedRound01 ShielddSecurity.TransferPoseidonCall04Shared01 ShielddSecurity.TransferPoseidonCall04R32
theorem column4_checked : checkColumn p copy originalRows parameters 32 before shifted transformed fifthHints ⟨4,by decide⟩=true := by decide +kernel
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonCall04R32Checks.column4_checked
#print axioms ShielddSecurity.TransferPoseidonCall04R32Checks.column4_checked
end ShielddSecurity.TransferPoseidonCall04R32Checks
namespace ShielddSecurity.TransferPoseidonCall04R32Checks
open Compiler CompilerIndexed01 CompilerCompletion Poseidon PoseidonIndexedRound01 ShielddSecurity.TransferPoseidonCall04Shared01 ShielddSecurity.TransferPoseidonCall04R32
theorem column5_checked : checkColumn p copy originalRows parameters 32 before shifted transformed fifthHints ⟨5,by decide⟩=true := by decide +kernel
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonCall04R32Checks.column5_checked
#print axioms ShielddSecurity.TransferPoseidonCall04R32Checks.column5_checked
end ShielddSecurity.TransferPoseidonCall04R32Checks
namespace ShielddSecurity.TransferPoseidonCall04R32Checks
open Compiler CompilerIndexed01 CompilerCompletion Poseidon PoseidonIndexedRound01 ShielddSecurity.TransferPoseidonCall04Shared01 ShielddSecurity.TransferPoseidonCall04R32
theorem mix0_checked : canonical p (after ⟨0,by decide⟩)=canonical p (mixLinear parameters.mds transformed ⟨0,by decide⟩) := by decide +kernel
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonCall04R32Checks.mix0_checked
#print axioms ShielddSecurity.TransferPoseidonCall04R32Checks.mix0_checked
end ShielddSecurity.TransferPoseidonCall04R32Checks
namespace ShielddSecurity.TransferPoseidonCall04R32Checks
open Compiler CompilerIndexed01 CompilerCompletion Poseidon PoseidonIndexedRound01 ShielddSecurity.TransferPoseidonCall04Shared01 ShielddSecurity.TransferPoseidonCall04R32
theorem mix1_checked : canonical p (after ⟨1,by decide⟩)=canonical p (mixLinear parameters.mds transformed ⟨1,by decide⟩) := by decide +kernel
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonCall04R32Checks.mix1_checked
#print axioms ShielddSecurity.TransferPoseidonCall04R32Checks.mix1_checked
end ShielddSecurity.TransferPoseidonCall04R32Checks
namespace ShielddSecurity.TransferPoseidonCall04R32Checks
open Compiler CompilerIndexed01 CompilerCompletion Poseidon PoseidonIndexedRound01 ShielddSecurity.TransferPoseidonCall04Shared01 ShielddSecurity.TransferPoseidonCall04R32
theorem mix2_checked : canonical p (after ⟨2,by decide⟩)=canonical p (mixLinear parameters.mds transformed ⟨2,by decide⟩) := by decide +kernel
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonCall04R32Checks.mix2_checked
#print axioms ShielddSecurity.TransferPoseidonCall04R32Checks.mix2_checked
end ShielddSecurity.TransferPoseidonCall04R32Checks
namespace ShielddSecurity.TransferPoseidonCall04R32Checks
open Compiler CompilerIndexed01 CompilerCompletion Poseidon PoseidonIndexedRound01 ShielddSecurity.TransferPoseidonCall04Shared01 ShielddSecurity.TransferPoseidonCall04R32
theorem mix3_checked : canonical p (after ⟨3,by decide⟩)=canonical p (mixLinear parameters.mds transformed ⟨3,by decide⟩) := by decide +kernel
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonCall04R32Checks.mix3_checked
#print axioms ShielddSecurity.TransferPoseidonCall04R32Checks.mix3_checked
end ShielddSecurity.TransferPoseidonCall04R32Checks
namespace ShielddSecurity.TransferPoseidonCall04R32Checks
open Compiler CompilerIndexed01 CompilerCompletion Poseidon PoseidonIndexedRound01 ShielddSecurity.TransferPoseidonCall04Shared01 ShielddSecurity.TransferPoseidonCall04R32
theorem mix4_checked : canonical p (after ⟨4,by decide⟩)=canonical p (mixLinear parameters.mds transformed ⟨4,by decide⟩) := by decide +kernel
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonCall04R32Checks.mix4_checked
#print axioms ShielddSecurity.TransferPoseidonCall04R32Checks.mix4_checked
end ShielddSecurity.TransferPoseidonCall04R32Checks
namespace ShielddSecurity.TransferPoseidonCall04R32Checks
open Compiler CompilerIndexed01 CompilerCompletion Poseidon PoseidonIndexedRound01 ShielddSecurity.TransferPoseidonCall04Shared01 ShielddSecurity.TransferPoseidonCall04R32
theorem mix5_checked : canonical p (after ⟨5,by decide⟩)=canonical p (mixLinear parameters.mds transformed ⟨5,by decide⟩) := by decide +kernel
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonCall04R32Checks.mix5_checked
#print axioms ShielddSecurity.TransferPoseidonCall04R32Checks.mix5_checked
end ShielddSecurity.TransferPoseidonCall04R32Checks
namespace ShielddSecurity.TransferPoseidonCall04R33Checks
open Compiler CompilerIndexed01 CompilerCompletion Poseidon PoseidonIndexedRound01 ShielddSecurity.TransferPoseidonCall04Shared01 ShielddSecurity.TransferPoseidonCall04R33
theorem column0_checked : checkColumn p copy originalRows parameters 33 before shifted transformed fifthHints ⟨0,by decide⟩=true := by decide +kernel
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonCall04R33Checks.column0_checked
#print axioms ShielddSecurity.TransferPoseidonCall04R33Checks.column0_checked
end ShielddSecurity.TransferPoseidonCall04R33Checks
namespace ShielddSecurity.TransferPoseidonCall04R33Checks
open Compiler CompilerIndexed01 CompilerCompletion Poseidon PoseidonIndexedRound01 ShielddSecurity.TransferPoseidonCall04Shared01 ShielddSecurity.TransferPoseidonCall04R33
theorem column1_checked : checkColumn p copy originalRows parameters 33 before shifted transformed fifthHints ⟨1,by decide⟩=true := by decide +kernel
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonCall04R33Checks.column1_checked
#print axioms ShielddSecurity.TransferPoseidonCall04R33Checks.column1_checked
end ShielddSecurity.TransferPoseidonCall04R33Checks
namespace ShielddSecurity.TransferPoseidonCall04R33Checks
open Compiler CompilerIndexed01 CompilerCompletion Poseidon PoseidonIndexedRound01 ShielddSecurity.TransferPoseidonCall04Shared01 ShielddSecurity.TransferPoseidonCall04R33
theorem column2_checked : checkColumn p copy originalRows parameters 33 before shifted transformed fifthHints ⟨2,by decide⟩=true := by decide +kernel
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonCall04R33Checks.column2_checked
#print axioms ShielddSecurity.TransferPoseidonCall04R33Checks.column2_checked
end ShielddSecurity.TransferPoseidonCall04R33Checks
namespace ShielddSecurity.TransferPoseidonCall04R33Checks
open Compiler CompilerIndexed01 CompilerCompletion Poseidon PoseidonIndexedRound01 ShielddSecurity.TransferPoseidonCall04Shared01 ShielddSecurity.TransferPoseidonCall04R33
theorem column3_checked : checkColumn p copy originalRows parameters 33 before shifted transformed fifthHints ⟨3,by decide⟩=true := by decide +kernel
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonCall04R33Checks.column3_checked
#print axioms ShielddSecurity.TransferPoseidonCall04R33Checks.column3_checked
end ShielddSecurity.TransferPoseidonCall04R33Checks
namespace ShielddSecurity.TransferPoseidonCall04R33Checks
open Compiler CompilerIndexed01 CompilerCompletion Poseidon PoseidonIndexedRound01 ShielddSecurity.TransferPoseidonCall04Shared01 ShielddSecurity.TransferPoseidonCall04R33
theorem column4_checked : checkColumn p copy originalRows parameters 33 before shifted transformed fifthHints ⟨4,by decide⟩=true := by decide +kernel
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonCall04R33Checks.column4_checked
#print axioms ShielddSecurity.TransferPoseidonCall04R33Checks.column4_checked
end ShielddSecurity.TransferPoseidonCall04R33Checks
namespace ShielddSecurity.TransferPoseidonCall04R33Checks
open Compiler CompilerIndexed01 CompilerCompletion Poseidon PoseidonIndexedRound01 ShielddSecurity.TransferPoseidonCall04Shared01 ShielddSecurity.TransferPoseidonCall04R33
theorem column5_checked : checkColumn p copy originalRows parameters 33 before shifted transformed fifthHints ⟨5,by decide⟩=true := by decide +kernel
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonCall04R33Checks.column5_checked
#print axioms ShielddSecurity.TransferPoseidonCall04R33Checks.column5_checked
end ShielddSecurity.TransferPoseidonCall04R33Checks
namespace ShielddSecurity.TransferPoseidonCall04R33Checks
open Compiler CompilerIndexed01 CompilerCompletion Poseidon PoseidonIndexedRound01 ShielddSecurity.TransferPoseidonCall04Shared01 ShielddSecurity.TransferPoseidonCall04R33
theorem mix0_checked : canonical p (after ⟨0,by decide⟩)=canonical p (mixLinear parameters.mds transformed ⟨0,by decide⟩) := by decide +kernel
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonCall04R33Checks.mix0_checked
#print axioms ShielddSecurity.TransferPoseidonCall04R33Checks.mix0_checked
end ShielddSecurity.TransferPoseidonCall04R33Checks
namespace ShielddSecurity.TransferPoseidonCall04R33Checks
open Compiler CompilerIndexed01 CompilerCompletion Poseidon PoseidonIndexedRound01 ShielddSecurity.TransferPoseidonCall04Shared01 ShielddSecurity.TransferPoseidonCall04R33
theorem mix1_checked : canonical p (after ⟨1,by decide⟩)=canonical p (mixLinear parameters.mds transformed ⟨1,by decide⟩) := by decide +kernel
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonCall04R33Checks.mix1_checked
#print axioms ShielddSecurity.TransferPoseidonCall04R33Checks.mix1_checked
end ShielddSecurity.TransferPoseidonCall04R33Checks
namespace ShielddSecurity.TransferPoseidonCall04R33Checks
open Compiler CompilerIndexed01 CompilerCompletion Poseidon PoseidonIndexedRound01 ShielddSecurity.TransferPoseidonCall04Shared01 ShielddSecurity.TransferPoseidonCall04R33
theorem mix2_checked : canonical p (after ⟨2,by decide⟩)=canonical p (mixLinear parameters.mds transformed ⟨2,by decide⟩) := by decide +kernel
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonCall04R33Checks.mix2_checked
#print axioms ShielddSecurity.TransferPoseidonCall04R33Checks.mix2_checked
end ShielddSecurity.TransferPoseidonCall04R33Checks
namespace ShielddSecurity.TransferPoseidonCall04R33Checks
open Compiler CompilerIndexed01 CompilerCompletion Poseidon PoseidonIndexedRound01 ShielddSecurity.TransferPoseidonCall04Shared01 ShielddSecurity.TransferPoseidonCall04R33
theorem mix3_checked : canonical p (after ⟨3,by decide⟩)=canonical p (mixLinear parameters.mds transformed ⟨3,by decide⟩) := by decide +kernel
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonCall04R33Checks.mix3_checked
#print axioms ShielddSecurity.TransferPoseidonCall04R33Checks.mix3_checked
end ShielddSecurity.TransferPoseidonCall04R33Checks
namespace ShielddSecurity.TransferPoseidonCall04R33Checks
open Compiler CompilerIndexed01 CompilerCompletion Poseidon PoseidonIndexedRound01 ShielddSecurity.TransferPoseidonCall04Shared01 ShielddSecurity.TransferPoseidonCall04R33
theorem mix4_checked : canonical p (after ⟨4,by decide⟩)=canonical p (mixLinear parameters.mds transformed ⟨4,by decide⟩) := by decide +kernel
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonCall04R33Checks.mix4_checked
#print axioms ShielddSecurity.TransferPoseidonCall04R33Checks.mix4_checked
end ShielddSecurity.TransferPoseidonCall04R33Checks
namespace ShielddSecurity.TransferPoseidonCall04R33Checks
open Compiler CompilerIndexed01 CompilerCompletion Poseidon PoseidonIndexedRound01 ShielddSecurity.TransferPoseidonCall04Shared01 ShielddSecurity.TransferPoseidonCall04R33
theorem mix5_checked : canonical p (after ⟨5,by decide⟩)=canonical p (mixLinear parameters.mds transformed ⟨5,by decide⟩) := by decide +kernel
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonCall04R33Checks.mix5_checked
#print axioms ShielddSecurity.TransferPoseidonCall04R33Checks.mix5_checked
end ShielddSecurity.TransferPoseidonCall04R33Checks
namespace ShielddSecurity.TransferPoseidonCall04R34Checks
open Compiler CompilerIndexed01 CompilerCompletion Poseidon PoseidonIndexedRound01 ShielddSecurity.TransferPoseidonCall04Shared01 ShielddSecurity.TransferPoseidonCall04R34
theorem column0_checked : checkColumn p copy originalRows parameters 34 before shifted transformed fifthHints ⟨0,by decide⟩=true := by decide +kernel
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonCall04R34Checks.column0_checked
#print axioms ShielddSecurity.TransferPoseidonCall04R34Checks.column0_checked
end ShielddSecurity.TransferPoseidonCall04R34Checks
namespace ShielddSecurity.TransferPoseidonCall04R34Checks
open Compiler CompilerIndexed01 CompilerCompletion Poseidon PoseidonIndexedRound01 ShielddSecurity.TransferPoseidonCall04Shared01 ShielddSecurity.TransferPoseidonCall04R34
theorem column1_checked : checkColumn p copy originalRows parameters 34 before shifted transformed fifthHints ⟨1,by decide⟩=true := by decide +kernel
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonCall04R34Checks.column1_checked
#print axioms ShielddSecurity.TransferPoseidonCall04R34Checks.column1_checked
end ShielddSecurity.TransferPoseidonCall04R34Checks
namespace ShielddSecurity.TransferPoseidonCall04R34Checks
open Compiler CompilerIndexed01 CompilerCompletion Poseidon PoseidonIndexedRound01 ShielddSecurity.TransferPoseidonCall04Shared01 ShielddSecurity.TransferPoseidonCall04R34
theorem column2_checked : checkColumn p copy originalRows parameters 34 before shifted transformed fifthHints ⟨2,by decide⟩=true := by decide +kernel
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonCall04R34Checks.column2_checked
#print axioms ShielddSecurity.TransferPoseidonCall04R34Checks.column2_checked
end ShielddSecurity.TransferPoseidonCall04R34Checks
namespace ShielddSecurity.TransferPoseidonCall04R34Checks
open Compiler CompilerIndexed01 CompilerCompletion Poseidon PoseidonIndexedRound01 ShielddSecurity.TransferPoseidonCall04Shared01 ShielddSecurity.TransferPoseidonCall04R34
theorem column3_checked : checkColumn p copy originalRows parameters 34 before shifted transformed fifthHints ⟨3,by decide⟩=true := by decide +kernel
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonCall04R34Checks.column3_checked
#print axioms ShielddSecurity.TransferPoseidonCall04R34Checks.column3_checked
end ShielddSecurity.TransferPoseidonCall04R34Checks
namespace ShielddSecurity.TransferPoseidonCall04R34Checks
open Compiler CompilerIndexed01 CompilerCompletion Poseidon PoseidonIndexedRound01 ShielddSecurity.TransferPoseidonCall04Shared01 ShielddSecurity.TransferPoseidonCall04R34
theorem column4_checked : checkColumn p copy originalRows parameters 34 before shifted transformed fifthHints ⟨4,by decide⟩=true := by decide +kernel
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonCall04R34Checks.column4_checked
#print axioms ShielddSecurity.TransferPoseidonCall04R34Checks.column4_checked
end ShielddSecurity.TransferPoseidonCall04R34Checks
namespace ShielddSecurity.TransferPoseidonCall04R34Checks
open Compiler CompilerIndexed01 CompilerCompletion Poseidon PoseidonIndexedRound01 ShielddSecurity.TransferPoseidonCall04Shared01 ShielddSecurity.TransferPoseidonCall04R34
theorem column5_checked : checkColumn p copy originalRows parameters 34 before shifted transformed fifthHints ⟨5,by decide⟩=true := by decide +kernel
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonCall04R34Checks.column5_checked
#print axioms ShielddSecurity.TransferPoseidonCall04R34Checks.column5_checked
end ShielddSecurity.TransferPoseidonCall04R34Checks
namespace ShielddSecurity.TransferPoseidonCall04R34Checks
open Compiler CompilerIndexed01 CompilerCompletion Poseidon PoseidonIndexedRound01 ShielddSecurity.TransferPoseidonCall04Shared01 ShielddSecurity.TransferPoseidonCall04R34
theorem mix0_checked : canonical p (after ⟨0,by decide⟩)=canonical p (mixLinear parameters.mds transformed ⟨0,by decide⟩) := by decide +kernel
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonCall04R34Checks.mix0_checked
#print axioms ShielddSecurity.TransferPoseidonCall04R34Checks.mix0_checked
end ShielddSecurity.TransferPoseidonCall04R34Checks
namespace ShielddSecurity.TransferPoseidonCall04R34Checks
open Compiler CompilerIndexed01 CompilerCompletion Poseidon PoseidonIndexedRound01 ShielddSecurity.TransferPoseidonCall04Shared01 ShielddSecurity.TransferPoseidonCall04R34
theorem mix1_checked : canonical p (after ⟨1,by decide⟩)=canonical p (mixLinear parameters.mds transformed ⟨1,by decide⟩) := by decide +kernel
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonCall04R34Checks.mix1_checked
#print axioms ShielddSecurity.TransferPoseidonCall04R34Checks.mix1_checked
end ShielddSecurity.TransferPoseidonCall04R34Checks
namespace ShielddSecurity.TransferPoseidonCall04R34Checks
open Compiler CompilerIndexed01 CompilerCompletion Poseidon PoseidonIndexedRound01 ShielddSecurity.TransferPoseidonCall04Shared01 ShielddSecurity.TransferPoseidonCall04R34
theorem mix2_checked : canonical p (after ⟨2,by decide⟩)=canonical p (mixLinear parameters.mds transformed ⟨2,by decide⟩) := by decide +kernel
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonCall04R34Checks.mix2_checked
#print axioms ShielddSecurity.TransferPoseidonCall04R34Checks.mix2_checked
end ShielddSecurity.TransferPoseidonCall04R34Checks
namespace ShielddSecurity.TransferPoseidonCall04R34Checks
open Compiler CompilerIndexed01 CompilerCompletion Poseidon PoseidonIndexedRound01 ShielddSecurity.TransferPoseidonCall04Shared01 ShielddSecurity.TransferPoseidonCall04R34
theorem mix3_checked : canonical p (after ⟨3,by decide⟩)=canonical p (mixLinear parameters.mds transformed ⟨3,by decide⟩) := by decide +kernel
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonCall04R34Checks.mix3_checked
#print axioms ShielddSecurity.TransferPoseidonCall04R34Checks.mix3_checked
end ShielddSecurity.TransferPoseidonCall04R34Checks
namespace ShielddSecurity.TransferPoseidonCall04R34Checks
open Compiler CompilerIndexed01 CompilerCompletion Poseidon PoseidonIndexedRound01 ShielddSecurity.TransferPoseidonCall04Shared01 ShielddSecurity.TransferPoseidonCall04R34
theorem mix4_checked : canonical p (after ⟨4,by decide⟩)=canonical p (mixLinear parameters.mds transformed ⟨4,by decide⟩) := by decide +kernel
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonCall04R34Checks.mix4_checked
#print axioms ShielddSecurity.TransferPoseidonCall04R34Checks.mix4_checked
end ShielddSecurity.TransferPoseidonCall04R34Checks
namespace ShielddSecurity.TransferPoseidonCall04R34Checks
open Compiler CompilerIndexed01 CompilerCompletion Poseidon PoseidonIndexedRound01 ShielddSecurity.TransferPoseidonCall04Shared01 ShielddSecurity.TransferPoseidonCall04R34
theorem mix5_checked : canonical p (after ⟨5,by decide⟩)=canonical p (mixLinear parameters.mds transformed ⟨5,by decide⟩) := by decide +kernel
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonCall04R34Checks.mix5_checked
#print axioms ShielddSecurity.TransferPoseidonCall04R34Checks.mix5_checked
end ShielddSecurity.TransferPoseidonCall04R34Checks
namespace ShielddSecurity.TransferPoseidonCall04R35Checks
open Compiler CompilerIndexed01 CompilerCompletion Poseidon PoseidonIndexedRound01 ShielddSecurity.TransferPoseidonCall04Shared01 ShielddSecurity.TransferPoseidonCall04R35
theorem column0_checked : checkColumn p copy originalRows parameters 35 before shifted transformed fifthHints ⟨0,by decide⟩=true := by decide +kernel
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonCall04R35Checks.column0_checked
#print axioms ShielddSecurity.TransferPoseidonCall04R35Checks.column0_checked
end ShielddSecurity.TransferPoseidonCall04R35Checks
namespace ShielddSecurity.TransferPoseidonCall04R35Checks
open Compiler CompilerIndexed01 CompilerCompletion Poseidon PoseidonIndexedRound01 ShielddSecurity.TransferPoseidonCall04Shared01 ShielddSecurity.TransferPoseidonCall04R35
theorem column1_checked : checkColumn p copy originalRows parameters 35 before shifted transformed fifthHints ⟨1,by decide⟩=true := by decide +kernel
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonCall04R35Checks.column1_checked
#print axioms ShielddSecurity.TransferPoseidonCall04R35Checks.column1_checked
end ShielddSecurity.TransferPoseidonCall04R35Checks
namespace ShielddSecurity.TransferPoseidonCall04R35Checks
open Compiler CompilerIndexed01 CompilerCompletion Poseidon PoseidonIndexedRound01 ShielddSecurity.TransferPoseidonCall04Shared01 ShielddSecurity.TransferPoseidonCall04R35
theorem column2_checked : checkColumn p copy originalRows parameters 35 before shifted transformed fifthHints ⟨2,by decide⟩=true := by decide +kernel
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonCall04R35Checks.column2_checked
#print axioms ShielddSecurity.TransferPoseidonCall04R35Checks.column2_checked
end ShielddSecurity.TransferPoseidonCall04R35Checks
namespace ShielddSecurity.TransferPoseidonCall04R35Checks
open Compiler CompilerIndexed01 CompilerCompletion Poseidon PoseidonIndexedRound01 ShielddSecurity.TransferPoseidonCall04Shared01 ShielddSecurity.TransferPoseidonCall04R35
theorem column3_checked : checkColumn p copy originalRows parameters 35 before shifted transformed fifthHints ⟨3,by decide⟩=true := by decide +kernel
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonCall04R35Checks.column3_checked
#print axioms ShielddSecurity.TransferPoseidonCall04R35Checks.column3_checked
end ShielddSecurity.TransferPoseidonCall04R35Checks
namespace ShielddSecurity.TransferPoseidonCall04R35Checks
open Compiler CompilerIndexed01 CompilerCompletion Poseidon PoseidonIndexedRound01 ShielddSecurity.TransferPoseidonCall04Shared01 ShielddSecurity.TransferPoseidonCall04R35
theorem column4_checked : checkColumn p copy originalRows parameters 35 before shifted transformed fifthHints ⟨4,by decide⟩=true := by decide +kernel
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonCall04R35Checks.column4_checked
#print axioms ShielddSecurity.TransferPoseidonCall04R35Checks.column4_checked
end ShielddSecurity.TransferPoseidonCall04R35Checks
namespace ShielddSecurity.TransferPoseidonCall04R35Checks
open Compiler CompilerIndexed01 CompilerCompletion Poseidon PoseidonIndexedRound01 ShielddSecurity.TransferPoseidonCall04Shared01 ShielddSecurity.TransferPoseidonCall04R35
theorem column5_checked : checkColumn p copy originalRows parameters 35 before shifted transformed fifthHints ⟨5,by decide⟩=true := by decide +kernel
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonCall04R35Checks.column5_checked
#print axioms ShielddSecurity.TransferPoseidonCall04R35Checks.column5_checked
end ShielddSecurity.TransferPoseidonCall04R35Checks
namespace ShielddSecurity.TransferPoseidonCall04R35Checks
open Compiler CompilerIndexed01 CompilerCompletion Poseidon PoseidonIndexedRound01 ShielddSecurity.TransferPoseidonCall04Shared01 ShielddSecurity.TransferPoseidonCall04R35
theorem mix0_checked : canonical p (after ⟨0,by decide⟩)=canonical p (mixLinear parameters.mds transformed ⟨0,by decide⟩) := by decide +kernel
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonCall04R35Checks.mix0_checked
#print axioms ShielddSecurity.TransferPoseidonCall04R35Checks.mix0_checked
end ShielddSecurity.TransferPoseidonCall04R35Checks
namespace ShielddSecurity.TransferPoseidonCall04R35Checks
open Compiler CompilerIndexed01 CompilerCompletion Poseidon PoseidonIndexedRound01 ShielddSecurity.TransferPoseidonCall04Shared01 ShielddSecurity.TransferPoseidonCall04R35
theorem mix1_checked : canonical p (after ⟨1,by decide⟩)=canonical p (mixLinear parameters.mds transformed ⟨1,by decide⟩) := by decide +kernel
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonCall04R35Checks.mix1_checked
#print axioms ShielddSecurity.TransferPoseidonCall04R35Checks.mix1_checked
end ShielddSecurity.TransferPoseidonCall04R35Checks
namespace ShielddSecurity.TransferPoseidonCall04R35Checks
open Compiler CompilerIndexed01 CompilerCompletion Poseidon PoseidonIndexedRound01 ShielddSecurity.TransferPoseidonCall04Shared01 ShielddSecurity.TransferPoseidonCall04R35
theorem mix2_checked : canonical p (after ⟨2,by decide⟩)=canonical p (mixLinear parameters.mds transformed ⟨2,by decide⟩) := by decide +kernel
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonCall04R35Checks.mix2_checked
#print axioms ShielddSecurity.TransferPoseidonCall04R35Checks.mix2_checked
end ShielddSecurity.TransferPoseidonCall04R35Checks
namespace ShielddSecurity.TransferPoseidonCall04R35Checks
open Compiler CompilerIndexed01 CompilerCompletion Poseidon PoseidonIndexedRound01 ShielddSecurity.TransferPoseidonCall04Shared01 ShielddSecurity.TransferPoseidonCall04R35
theorem mix3_checked : canonical p (after ⟨3,by decide⟩)=canonical p (mixLinear parameters.mds transformed ⟨3,by decide⟩) := by decide +kernel
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonCall04R35Checks.mix3_checked
#print axioms ShielddSecurity.TransferPoseidonCall04R35Checks.mix3_checked
end ShielddSecurity.TransferPoseidonCall04R35Checks
namespace ShielddSecurity.TransferPoseidonCall04R35Checks
open Compiler CompilerIndexed01 CompilerCompletion Poseidon PoseidonIndexedRound01 ShielddSecurity.TransferPoseidonCall04Shared01 ShielddSecurity.TransferPoseidonCall04R35
theorem mix4_checked : canonical p (after ⟨4,by decide⟩)=canonical p (mixLinear parameters.mds transformed ⟨4,by decide⟩) := by decide +kernel
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonCall04R35Checks.mix4_checked
#print axioms ShielddSecurity.TransferPoseidonCall04R35Checks.mix4_checked
end ShielddSecurity.TransferPoseidonCall04R35Checks
namespace ShielddSecurity.TransferPoseidonCall04R35Checks
open Compiler CompilerIndexed01 CompilerCompletion Poseidon PoseidonIndexedRound01 ShielddSecurity.TransferPoseidonCall04Shared01 ShielddSecurity.TransferPoseidonCall04R35
theorem mix5_checked : canonical p (after ⟨5,by decide⟩)=canonical p (mixLinear parameters.mds transformed ⟨5,by decide⟩) := by decide +kernel
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonCall04R35Checks.mix5_checked
#print axioms ShielddSecurity.TransferPoseidonCall04R35Checks.mix5_checked
end ShielddSecurity.TransferPoseidonCall04R35Checks
namespace ShielddSecurity.TransferPoseidonCall04R36Checks
open Compiler CompilerIndexed01 CompilerCompletion Poseidon PoseidonIndexedRound01 ShielddSecurity.TransferPoseidonCall04Shared01 ShielddSecurity.TransferPoseidonCall04R36
theorem column0_checked : checkColumn p copy originalRows parameters 36 before shifted transformed fifthHints ⟨0,by decide⟩=true := by decide +kernel
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonCall04R36Checks.column0_checked
#print axioms ShielddSecurity.TransferPoseidonCall04R36Checks.column0_checked
end ShielddSecurity.TransferPoseidonCall04R36Checks
namespace ShielddSecurity.TransferPoseidonCall04R36Checks
open Compiler CompilerIndexed01 CompilerCompletion Poseidon PoseidonIndexedRound01 ShielddSecurity.TransferPoseidonCall04Shared01 ShielddSecurity.TransferPoseidonCall04R36
theorem column1_checked : checkColumn p copy originalRows parameters 36 before shifted transformed fifthHints ⟨1,by decide⟩=true := by decide +kernel
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonCall04R36Checks.column1_checked
#print axioms ShielddSecurity.TransferPoseidonCall04R36Checks.column1_checked
end ShielddSecurity.TransferPoseidonCall04R36Checks
namespace ShielddSecurity.TransferPoseidonCall04R36Checks
open Compiler CompilerIndexed01 CompilerCompletion Poseidon PoseidonIndexedRound01 ShielddSecurity.TransferPoseidonCall04Shared01 ShielddSecurity.TransferPoseidonCall04R36
theorem column2_checked : checkColumn p copy originalRows parameters 36 before shifted transformed fifthHints ⟨2,by decide⟩=true := by decide +kernel
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonCall04R36Checks.column2_checked
#print axioms ShielddSecurity.TransferPoseidonCall04R36Checks.column2_checked
end ShielddSecurity.TransferPoseidonCall04R36Checks
namespace ShielddSecurity.TransferPoseidonCall04R36Checks
open Compiler CompilerIndexed01 CompilerCompletion Poseidon PoseidonIndexedRound01 ShielddSecurity.TransferPoseidonCall04Shared01 ShielddSecurity.TransferPoseidonCall04R36
theorem column3_checked : checkColumn p copy originalRows parameters 36 before shifted transformed fifthHints ⟨3,by decide⟩=true := by decide +kernel
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonCall04R36Checks.column3_checked
#print axioms ShielddSecurity.TransferPoseidonCall04R36Checks.column3_checked
end ShielddSecurity.TransferPoseidonCall04R36Checks
namespace ShielddSecurity.TransferPoseidonCall04R36Checks
open Compiler CompilerIndexed01 CompilerCompletion Poseidon PoseidonIndexedRound01 ShielddSecurity.TransferPoseidonCall04Shared01 ShielddSecurity.TransferPoseidonCall04R36
theorem column4_checked : checkColumn p copy originalRows parameters 36 before shifted transformed fifthHints ⟨4,by decide⟩=true := by decide +kernel
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonCall04R36Checks.column4_checked
#print axioms ShielddSecurity.TransferPoseidonCall04R36Checks.column4_checked
end ShielddSecurity.TransferPoseidonCall04R36Checks
namespace ShielddSecurity.TransferPoseidonCall04R36Checks
open Compiler CompilerIndexed01 CompilerCompletion Poseidon PoseidonIndexedRound01 ShielddSecurity.TransferPoseidonCall04Shared01 ShielddSecurity.TransferPoseidonCall04R36
theorem column5_checked : checkColumn p copy originalRows parameters 36 before shifted transformed fifthHints ⟨5,by decide⟩=true := by decide +kernel
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonCall04R36Checks.column5_checked
#print axioms ShielddSecurity.TransferPoseidonCall04R36Checks.column5_checked
end ShielddSecurity.TransferPoseidonCall04R36Checks
namespace ShielddSecurity.TransferPoseidonCall04R36Checks
open Compiler CompilerIndexed01 CompilerCompletion Poseidon PoseidonIndexedRound01 ShielddSecurity.TransferPoseidonCall04Shared01 ShielddSecurity.TransferPoseidonCall04R36
theorem mix0_checked : canonical p (after ⟨0,by decide⟩)=canonical p (mixLinear parameters.mds transformed ⟨0,by decide⟩) := by decide +kernel
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonCall04R36Checks.mix0_checked
#print axioms ShielddSecurity.TransferPoseidonCall04R36Checks.mix0_checked
end ShielddSecurity.TransferPoseidonCall04R36Checks
namespace ShielddSecurity.TransferPoseidonCall04R36Checks
open Compiler CompilerIndexed01 CompilerCompletion Poseidon PoseidonIndexedRound01 ShielddSecurity.TransferPoseidonCall04Shared01 ShielddSecurity.TransferPoseidonCall04R36
theorem mix1_checked : canonical p (after ⟨1,by decide⟩)=canonical p (mixLinear parameters.mds transformed ⟨1,by decide⟩) := by decide +kernel
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonCall04R36Checks.mix1_checked
#print axioms ShielddSecurity.TransferPoseidonCall04R36Checks.mix1_checked
end ShielddSecurity.TransferPoseidonCall04R36Checks
namespace ShielddSecurity.TransferPoseidonCall04R36Checks
open Compiler CompilerIndexed01 CompilerCompletion Poseidon PoseidonIndexedRound01 ShielddSecurity.TransferPoseidonCall04Shared01 ShielddSecurity.TransferPoseidonCall04R36
theorem mix2_checked : canonical p (after ⟨2,by decide⟩)=canonical p (mixLinear parameters.mds transformed ⟨2,by decide⟩) := by decide +kernel
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonCall04R36Checks.mix2_checked
#print axioms ShielddSecurity.TransferPoseidonCall04R36Checks.mix2_checked
end ShielddSecurity.TransferPoseidonCall04R36Checks
namespace ShielddSecurity.TransferPoseidonCall04R36Checks
open Compiler CompilerIndexed01 CompilerCompletion Poseidon PoseidonIndexedRound01 ShielddSecurity.TransferPoseidonCall04Shared01 ShielddSecurity.TransferPoseidonCall04R36
theorem mix3_checked : canonical p (after ⟨3,by decide⟩)=canonical p (mixLinear parameters.mds transformed ⟨3,by decide⟩) := by decide +kernel
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonCall04R36Checks.mix3_checked
#print axioms ShielddSecurity.TransferPoseidonCall04R36Checks.mix3_checked
end ShielddSecurity.TransferPoseidonCall04R36Checks
namespace ShielddSecurity.TransferPoseidonCall04R36Checks
open Compiler CompilerIndexed01 CompilerCompletion Poseidon PoseidonIndexedRound01 ShielddSecurity.TransferPoseidonCall04Shared01 ShielddSecurity.TransferPoseidonCall04R36
theorem mix4_checked : canonical p (after ⟨4,by decide⟩)=canonical p (mixLinear parameters.mds transformed ⟨4,by decide⟩) := by decide +kernel
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonCall04R36Checks.mix4_checked
#print axioms ShielddSecurity.TransferPoseidonCall04R36Checks.mix4_checked
end ShielddSecurity.TransferPoseidonCall04R36Checks
namespace ShielddSecurity.TransferPoseidonCall04R36Checks
open Compiler CompilerIndexed01 CompilerCompletion Poseidon PoseidonIndexedRound01 ShielddSecurity.TransferPoseidonCall04Shared01 ShielddSecurity.TransferPoseidonCall04R36
theorem mix5_checked : canonical p (after ⟨5,by decide⟩)=canonical p (mixLinear parameters.mds transformed ⟨5,by decide⟩) := by decide +kernel
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonCall04R36Checks.mix5_checked
#print axioms ShielddSecurity.TransferPoseidonCall04R36Checks.mix5_checked
end ShielddSecurity.TransferPoseidonCall04R36Checks
namespace ShielddSecurity.TransferPoseidonCall04R37Checks
open Compiler CompilerIndexed01 CompilerCompletion Poseidon PoseidonIndexedRound01 ShielddSecurity.TransferPoseidonCall04Shared01 ShielddSecurity.TransferPoseidonCall04R37
theorem column0_checked : checkColumn p copy originalRows parameters 37 before shifted transformed fifthHints ⟨0,by decide⟩=true := by decide +kernel
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonCall04R37Checks.column0_checked
#print axioms ShielddSecurity.TransferPoseidonCall04R37Checks.column0_checked
end ShielddSecurity.TransferPoseidonCall04R37Checks
namespace ShielddSecurity.TransferPoseidonCall04R37Checks
open Compiler CompilerIndexed01 CompilerCompletion Poseidon PoseidonIndexedRound01 ShielddSecurity.TransferPoseidonCall04Shared01 ShielddSecurity.TransferPoseidonCall04R37
theorem column1_checked : checkColumn p copy originalRows parameters 37 before shifted transformed fifthHints ⟨1,by decide⟩=true := by decide +kernel
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonCall04R37Checks.column1_checked
#print axioms ShielddSecurity.TransferPoseidonCall04R37Checks.column1_checked
end ShielddSecurity.TransferPoseidonCall04R37Checks
namespace ShielddSecurity.TransferPoseidonCall04R37Checks
open Compiler CompilerIndexed01 CompilerCompletion Poseidon PoseidonIndexedRound01 ShielddSecurity.TransferPoseidonCall04Shared01 ShielddSecurity.TransferPoseidonCall04R37
theorem column2_checked : checkColumn p copy originalRows parameters 37 before shifted transformed fifthHints ⟨2,by decide⟩=true := by decide +kernel
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonCall04R37Checks.column2_checked
#print axioms ShielddSecurity.TransferPoseidonCall04R37Checks.column2_checked
end ShielddSecurity.TransferPoseidonCall04R37Checks
namespace ShielddSecurity.TransferPoseidonCall04R37Checks
open Compiler CompilerIndexed01 CompilerCompletion Poseidon PoseidonIndexedRound01 ShielddSecurity.TransferPoseidonCall04Shared01 ShielddSecurity.TransferPoseidonCall04R37
theorem column3_checked : checkColumn p copy originalRows parameters 37 before shifted transformed fifthHints ⟨3,by decide⟩=true := by decide +kernel
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonCall04R37Checks.column3_checked
#print axioms ShielddSecurity.TransferPoseidonCall04R37Checks.column3_checked
end ShielddSecurity.TransferPoseidonCall04R37Checks
namespace ShielddSecurity.TransferPoseidonCall04R37Checks
open Compiler CompilerIndexed01 CompilerCompletion Poseidon PoseidonIndexedRound01 ShielddSecurity.TransferPoseidonCall04Shared01 ShielddSecurity.TransferPoseidonCall04R37
theorem column4_checked : checkColumn p copy originalRows parameters 37 before shifted transformed fifthHints ⟨4,by decide⟩=true := by decide +kernel
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonCall04R37Checks.column4_checked
#print axioms ShielddSecurity.TransferPoseidonCall04R37Checks.column4_checked
end ShielddSecurity.TransferPoseidonCall04R37Checks
namespace ShielddSecurity.TransferPoseidonCall04R37Checks
open Compiler CompilerIndexed01 CompilerCompletion Poseidon PoseidonIndexedRound01 ShielddSecurity.TransferPoseidonCall04Shared01 ShielddSecurity.TransferPoseidonCall04R37
theorem column5_checked : checkColumn p copy originalRows parameters 37 before shifted transformed fifthHints ⟨5,by decide⟩=true := by decide +kernel
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonCall04R37Checks.column5_checked
#print axioms ShielddSecurity.TransferPoseidonCall04R37Checks.column5_checked
end ShielddSecurity.TransferPoseidonCall04R37Checks
namespace ShielddSecurity.TransferPoseidonCall04R37Checks
open Compiler CompilerIndexed01 CompilerCompletion Poseidon PoseidonIndexedRound01 ShielddSecurity.TransferPoseidonCall04Shared01 ShielddSecurity.TransferPoseidonCall04R37
theorem mix0_checked : canonical p (after ⟨0,by decide⟩)=canonical p (mixLinear parameters.mds transformed ⟨0,by decide⟩) := by decide +kernel
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonCall04R37Checks.mix0_checked
#print axioms ShielddSecurity.TransferPoseidonCall04R37Checks.mix0_checked
end ShielddSecurity.TransferPoseidonCall04R37Checks
namespace ShielddSecurity.TransferPoseidonCall04R37Checks
open Compiler CompilerIndexed01 CompilerCompletion Poseidon PoseidonIndexedRound01 ShielddSecurity.TransferPoseidonCall04Shared01 ShielddSecurity.TransferPoseidonCall04R37
theorem mix1_checked : canonical p (after ⟨1,by decide⟩)=canonical p (mixLinear parameters.mds transformed ⟨1,by decide⟩) := by decide +kernel
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonCall04R37Checks.mix1_checked
#print axioms ShielddSecurity.TransferPoseidonCall04R37Checks.mix1_checked
end ShielddSecurity.TransferPoseidonCall04R37Checks
namespace ShielddSecurity.TransferPoseidonCall04R37Checks
open Compiler CompilerIndexed01 CompilerCompletion Poseidon PoseidonIndexedRound01 ShielddSecurity.TransferPoseidonCall04Shared01 ShielddSecurity.TransferPoseidonCall04R37
theorem mix2_checked : canonical p (after ⟨2,by decide⟩)=canonical p (mixLinear parameters.mds transformed ⟨2,by decide⟩) := by decide +kernel
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonCall04R37Checks.mix2_checked
#print axioms ShielddSecurity.TransferPoseidonCall04R37Checks.mix2_checked
end ShielddSecurity.TransferPoseidonCall04R37Checks
namespace ShielddSecurity.TransferPoseidonCall04R37Checks
open Compiler CompilerIndexed01 CompilerCompletion Poseidon PoseidonIndexedRound01 ShielddSecurity.TransferPoseidonCall04Shared01 ShielddSecurity.TransferPoseidonCall04R37
theorem mix3_checked : canonical p (after ⟨3,by decide⟩)=canonical p (mixLinear parameters.mds transformed ⟨3,by decide⟩) := by decide +kernel
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonCall04R37Checks.mix3_checked
#print axioms ShielddSecurity.TransferPoseidonCall04R37Checks.mix3_checked
end ShielddSecurity.TransferPoseidonCall04R37Checks
namespace ShielddSecurity.TransferPoseidonCall04R37Checks
open Compiler CompilerIndexed01 CompilerCompletion Poseidon PoseidonIndexedRound01 ShielddSecurity.TransferPoseidonCall04Shared01 ShielddSecurity.TransferPoseidonCall04R37
theorem mix4_checked : canonical p (after ⟨4,by decide⟩)=canonical p (mixLinear parameters.mds transformed ⟨4,by decide⟩) := by decide +kernel
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonCall04R37Checks.mix4_checked
#print axioms ShielddSecurity.TransferPoseidonCall04R37Checks.mix4_checked
end ShielddSecurity.TransferPoseidonCall04R37Checks
namespace ShielddSecurity.TransferPoseidonCall04R37Checks
open Compiler CompilerIndexed01 CompilerCompletion Poseidon PoseidonIndexedRound01 ShielddSecurity.TransferPoseidonCall04Shared01 ShielddSecurity.TransferPoseidonCall04R37
theorem mix5_checked : canonical p (after ⟨5,by decide⟩)=canonical p (mixLinear parameters.mds transformed ⟨5,by decide⟩) := by decide +kernel
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonCall04R37Checks.mix5_checked
#print axioms ShielddSecurity.TransferPoseidonCall04R37Checks.mix5_checked
end ShielddSecurity.TransferPoseidonCall04R37Checks
namespace ShielddSecurity.TransferPoseidonCall04R38Checks
open Compiler CompilerIndexed01 CompilerCompletion Poseidon PoseidonIndexedRound01 ShielddSecurity.TransferPoseidonCall04Shared01 ShielddSecurity.TransferPoseidonCall04R38
theorem column0_checked : checkColumn p copy originalRows parameters 38 before shifted transformed fifthHints ⟨0,by decide⟩=true := by decide +kernel
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonCall04R38Checks.column0_checked
#print axioms ShielddSecurity.TransferPoseidonCall04R38Checks.column0_checked
end ShielddSecurity.TransferPoseidonCall04R38Checks
namespace ShielddSecurity.TransferPoseidonCall04R38Checks
open Compiler CompilerIndexed01 CompilerCompletion Poseidon PoseidonIndexedRound01 ShielddSecurity.TransferPoseidonCall04Shared01 ShielddSecurity.TransferPoseidonCall04R38
theorem column1_checked : checkColumn p copy originalRows parameters 38 before shifted transformed fifthHints ⟨1,by decide⟩=true := by decide +kernel
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonCall04R38Checks.column1_checked
#print axioms ShielddSecurity.TransferPoseidonCall04R38Checks.column1_checked
end ShielddSecurity.TransferPoseidonCall04R38Checks
namespace ShielddSecurity.TransferPoseidonCall04R38Checks
open Compiler CompilerIndexed01 CompilerCompletion Poseidon PoseidonIndexedRound01 ShielddSecurity.TransferPoseidonCall04Shared01 ShielddSecurity.TransferPoseidonCall04R38
theorem column2_checked : checkColumn p copy originalRows parameters 38 before shifted transformed fifthHints ⟨2,by decide⟩=true := by decide +kernel
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonCall04R38Checks.column2_checked
#print axioms ShielddSecurity.TransferPoseidonCall04R38Checks.column2_checked
end ShielddSecurity.TransferPoseidonCall04R38Checks
namespace ShielddSecurity.TransferPoseidonCall04R38Checks
open Compiler CompilerIndexed01 CompilerCompletion Poseidon PoseidonIndexedRound01 ShielddSecurity.TransferPoseidonCall04Shared01 ShielddSecurity.TransferPoseidonCall04R38
theorem column3_checked : checkColumn p copy originalRows parameters 38 before shifted transformed fifthHints ⟨3,by decide⟩=true := by decide +kernel
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonCall04R38Checks.column3_checked
#print axioms ShielddSecurity.TransferPoseidonCall04R38Checks.column3_checked
end ShielddSecurity.TransferPoseidonCall04R38Checks
namespace ShielddSecurity.TransferPoseidonCall04R38Checks
open Compiler CompilerIndexed01 CompilerCompletion Poseidon PoseidonIndexedRound01 ShielddSecurity.TransferPoseidonCall04Shared01 ShielddSecurity.TransferPoseidonCall04R38
theorem column4_checked : checkColumn p copy originalRows parameters 38 before shifted transformed fifthHints ⟨4,by decide⟩=true := by decide +kernel
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonCall04R38Checks.column4_checked
#print axioms ShielddSecurity.TransferPoseidonCall04R38Checks.column4_checked
end ShielddSecurity.TransferPoseidonCall04R38Checks
namespace ShielddSecurity.TransferPoseidonCall04R38Checks
open Compiler CompilerIndexed01 CompilerCompletion Poseidon PoseidonIndexedRound01 ShielddSecurity.TransferPoseidonCall04Shared01 ShielddSecurity.TransferPoseidonCall04R38
theorem column5_checked : checkColumn p copy originalRows parameters 38 before shifted transformed fifthHints ⟨5,by decide⟩=true := by decide +kernel
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonCall04R38Checks.column5_checked
#print axioms ShielddSecurity.TransferPoseidonCall04R38Checks.column5_checked
end ShielddSecurity.TransferPoseidonCall04R38Checks
namespace ShielddSecurity.TransferPoseidonCall04R38Checks
open Compiler CompilerIndexed01 CompilerCompletion Poseidon PoseidonIndexedRound01 ShielddSecurity.TransferPoseidonCall04Shared01 ShielddSecurity.TransferPoseidonCall04R38
theorem mix0_checked : canonical p (after ⟨0,by decide⟩)=canonical p (mixLinear parameters.mds transformed ⟨0,by decide⟩) := by decide +kernel
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonCall04R38Checks.mix0_checked
#print axioms ShielddSecurity.TransferPoseidonCall04R38Checks.mix0_checked
end ShielddSecurity.TransferPoseidonCall04R38Checks
namespace ShielddSecurity.TransferPoseidonCall04R38Checks
open Compiler CompilerIndexed01 CompilerCompletion Poseidon PoseidonIndexedRound01 ShielddSecurity.TransferPoseidonCall04Shared01 ShielddSecurity.TransferPoseidonCall04R38
theorem mix1_checked : canonical p (after ⟨1,by decide⟩)=canonical p (mixLinear parameters.mds transformed ⟨1,by decide⟩) := by decide +kernel
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonCall04R38Checks.mix1_checked
#print axioms ShielddSecurity.TransferPoseidonCall04R38Checks.mix1_checked
end ShielddSecurity.TransferPoseidonCall04R38Checks
namespace ShielddSecurity.TransferPoseidonCall04R38Checks
open Compiler CompilerIndexed01 CompilerCompletion Poseidon PoseidonIndexedRound01 ShielddSecurity.TransferPoseidonCall04Shared01 ShielddSecurity.TransferPoseidonCall04R38
theorem mix2_checked : canonical p (after ⟨2,by decide⟩)=canonical p (mixLinear parameters.mds transformed ⟨2,by decide⟩) := by decide +kernel
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonCall04R38Checks.mix2_checked
#print axioms ShielddSecurity.TransferPoseidonCall04R38Checks.mix2_checked
end ShielddSecurity.TransferPoseidonCall04R38Checks
namespace ShielddSecurity.TransferPoseidonCall04R38Checks
open Compiler CompilerIndexed01 CompilerCompletion Poseidon PoseidonIndexedRound01 ShielddSecurity.TransferPoseidonCall04Shared01 ShielddSecurity.TransferPoseidonCall04R38
theorem mix3_checked : canonical p (after ⟨3,by decide⟩)=canonical p (mixLinear parameters.mds transformed ⟨3,by decide⟩) := by decide +kernel
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonCall04R38Checks.mix3_checked
#print axioms ShielddSecurity.TransferPoseidonCall04R38Checks.mix3_checked
end ShielddSecurity.TransferPoseidonCall04R38Checks
namespace ShielddSecurity.TransferPoseidonCall04R38Checks
open Compiler CompilerIndexed01 CompilerCompletion Poseidon PoseidonIndexedRound01 ShielddSecurity.TransferPoseidonCall04Shared01 ShielddSecurity.TransferPoseidonCall04R38
theorem mix4_checked : canonical p (after ⟨4,by decide⟩)=canonical p (mixLinear parameters.mds transformed ⟨4,by decide⟩) := by decide +kernel
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonCall04R38Checks.mix4_checked
#print axioms ShielddSecurity.TransferPoseidonCall04R38Checks.mix4_checked
end ShielddSecurity.TransferPoseidonCall04R38Checks
namespace ShielddSecurity.TransferPoseidonCall04R38Checks
open Compiler CompilerIndexed01 CompilerCompletion Poseidon PoseidonIndexedRound01 ShielddSecurity.TransferPoseidonCall04Shared01 ShielddSecurity.TransferPoseidonCall04R38
theorem mix5_checked : canonical p (after ⟨5,by decide⟩)=canonical p (mixLinear parameters.mds transformed ⟨5,by decide⟩) := by decide +kernel
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonCall04R38Checks.mix5_checked
#print axioms ShielddSecurity.TransferPoseidonCall04R38Checks.mix5_checked
end ShielddSecurity.TransferPoseidonCall04R38Checks
namespace ShielddSecurity.TransferPoseidonCall04R39Checks
open Compiler CompilerIndexed01 CompilerCompletion Poseidon PoseidonIndexedRound01 ShielddSecurity.TransferPoseidonCall04Shared01 ShielddSecurity.TransferPoseidonCall04R39
theorem column0_checked : checkColumn p copy originalRows parameters 39 before shifted transformed fifthHints ⟨0,by decide⟩=true := by decide +kernel
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonCall04R39Checks.column0_checked
#print axioms ShielddSecurity.TransferPoseidonCall04R39Checks.column0_checked
end ShielddSecurity.TransferPoseidonCall04R39Checks
namespace ShielddSecurity.TransferPoseidonCall04R39Checks
open Compiler CompilerIndexed01 CompilerCompletion Poseidon PoseidonIndexedRound01 ShielddSecurity.TransferPoseidonCall04Shared01 ShielddSecurity.TransferPoseidonCall04R39
theorem column1_checked : checkColumn p copy originalRows parameters 39 before shifted transformed fifthHints ⟨1,by decide⟩=true := by decide +kernel
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonCall04R39Checks.column1_checked
#print axioms ShielddSecurity.TransferPoseidonCall04R39Checks.column1_checked
end ShielddSecurity.TransferPoseidonCall04R39Checks
namespace ShielddSecurity.TransferPoseidonCall04R39Checks
open Compiler CompilerIndexed01 CompilerCompletion Poseidon PoseidonIndexedRound01 ShielddSecurity.TransferPoseidonCall04Shared01 ShielddSecurity.TransferPoseidonCall04R39
theorem column2_checked : checkColumn p copy originalRows parameters 39 before shifted transformed fifthHints ⟨2,by decide⟩=true := by decide +kernel
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonCall04R39Checks.column2_checked
#print axioms ShielddSecurity.TransferPoseidonCall04R39Checks.column2_checked
end ShielddSecurity.TransferPoseidonCall04R39Checks
namespace ShielddSecurity.TransferPoseidonCall04R39Checks
open Compiler CompilerIndexed01 CompilerCompletion Poseidon PoseidonIndexedRound01 ShielddSecurity.TransferPoseidonCall04Shared01 ShielddSecurity.TransferPoseidonCall04R39
theorem column3_checked : checkColumn p copy originalRows parameters 39 before shifted transformed fifthHints ⟨3,by decide⟩=true := by decide +kernel
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonCall04R39Checks.column3_checked
#print axioms ShielddSecurity.TransferPoseidonCall04R39Checks.column3_checked
end ShielddSecurity.TransferPoseidonCall04R39Checks
namespace ShielddSecurity.TransferPoseidonCall04R39Checks
open Compiler CompilerIndexed01 CompilerCompletion Poseidon PoseidonIndexedRound01 ShielddSecurity.TransferPoseidonCall04Shared01 ShielddSecurity.TransferPoseidonCall04R39
theorem column4_checked : checkColumn p copy originalRows parameters 39 before shifted transformed fifthHints ⟨4,by decide⟩=true := by decide +kernel
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonCall04R39Checks.column4_checked
#print axioms ShielddSecurity.TransferPoseidonCall04R39Checks.column4_checked
end ShielddSecurity.TransferPoseidonCall04R39Checks
namespace ShielddSecurity.TransferPoseidonCall04R39Checks
open Compiler CompilerIndexed01 CompilerCompletion Poseidon PoseidonIndexedRound01 ShielddSecurity.TransferPoseidonCall04Shared01 ShielddSecurity.TransferPoseidonCall04R39
theorem column5_checked : checkColumn p copy originalRows parameters 39 before shifted transformed fifthHints ⟨5,by decide⟩=true := by decide +kernel
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonCall04R39Checks.column5_checked
#print axioms ShielddSecurity.TransferPoseidonCall04R39Checks.column5_checked
end ShielddSecurity.TransferPoseidonCall04R39Checks
namespace ShielddSecurity.TransferPoseidonCall04R39Checks
open Compiler CompilerIndexed01 CompilerCompletion Poseidon PoseidonIndexedRound01 ShielddSecurity.TransferPoseidonCall04Shared01 ShielddSecurity.TransferPoseidonCall04R39
theorem mix0_checked : canonical p (after ⟨0,by decide⟩)=canonical p (mixLinear parameters.mds transformed ⟨0,by decide⟩) := by decide +kernel
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonCall04R39Checks.mix0_checked
#print axioms ShielddSecurity.TransferPoseidonCall04R39Checks.mix0_checked
end ShielddSecurity.TransferPoseidonCall04R39Checks
namespace ShielddSecurity.TransferPoseidonCall04R39Checks
open Compiler CompilerIndexed01 CompilerCompletion Poseidon PoseidonIndexedRound01 ShielddSecurity.TransferPoseidonCall04Shared01 ShielddSecurity.TransferPoseidonCall04R39
theorem mix1_checked : canonical p (after ⟨1,by decide⟩)=canonical p (mixLinear parameters.mds transformed ⟨1,by decide⟩) := by decide +kernel
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonCall04R39Checks.mix1_checked
#print axioms ShielddSecurity.TransferPoseidonCall04R39Checks.mix1_checked
end ShielddSecurity.TransferPoseidonCall04R39Checks
namespace ShielddSecurity.TransferPoseidonCall04R39Checks
open Compiler CompilerIndexed01 CompilerCompletion Poseidon PoseidonIndexedRound01 ShielddSecurity.TransferPoseidonCall04Shared01 ShielddSecurity.TransferPoseidonCall04R39
theorem mix2_checked : canonical p (after ⟨2,by decide⟩)=canonical p (mixLinear parameters.mds transformed ⟨2,by decide⟩) := by decide +kernel
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonCall04R39Checks.mix2_checked
#print axioms ShielddSecurity.TransferPoseidonCall04R39Checks.mix2_checked
end ShielddSecurity.TransferPoseidonCall04R39Checks
namespace ShielddSecurity.TransferPoseidonCall04R39Checks
open Compiler CompilerIndexed01 CompilerCompletion Poseidon PoseidonIndexedRound01 ShielddSecurity.TransferPoseidonCall04Shared01 ShielddSecurity.TransferPoseidonCall04R39
theorem mix3_checked : canonical p (after ⟨3,by decide⟩)=canonical p (mixLinear parameters.mds transformed ⟨3,by decide⟩) := by decide +kernel
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonCall04R39Checks.mix3_checked
#print axioms ShielddSecurity.TransferPoseidonCall04R39Checks.mix3_checked
end ShielddSecurity.TransferPoseidonCall04R39Checks
namespace ShielddSecurity.TransferPoseidonCall04R39Checks
open Compiler CompilerIndexed01 CompilerCompletion Poseidon PoseidonIndexedRound01 ShielddSecurity.TransferPoseidonCall04Shared01 ShielddSecurity.TransferPoseidonCall04R39
theorem mix4_checked : canonical p (after ⟨4,by decide⟩)=canonical p (mixLinear parameters.mds transformed ⟨4,by decide⟩) := by decide +kernel
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonCall04R39Checks.mix4_checked
#print axioms ShielddSecurity.TransferPoseidonCall04R39Checks.mix4_checked
end ShielddSecurity.TransferPoseidonCall04R39Checks
namespace ShielddSecurity.TransferPoseidonCall04R39Checks
open Compiler CompilerIndexed01 CompilerCompletion Poseidon PoseidonIndexedRound01 ShielddSecurity.TransferPoseidonCall04Shared01 ShielddSecurity.TransferPoseidonCall04R39
theorem mix5_checked : canonical p (after ⟨5,by decide⟩)=canonical p (mixLinear parameters.mds transformed ⟨5,by decide⟩) := by decide +kernel
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonCall04R39Checks.mix5_checked
#print axioms ShielddSecurity.TransferPoseidonCall04R39Checks.mix5_checked
end ShielddSecurity.TransferPoseidonCall04R39Checks
