-- GENERATED by generate_direct.py; edit generator.
import ShielddSecurity.TransferPoseidonWidth3Prefix10R00Data01
set_option maxHeartbeats 900000
set_option maxRecDepth 8192
namespace ShielddSecurity.TransferPoseidonWidth3Prefix10R00ProgramChecks01
open Compiler CompilerIndexed01 CompilerCompletion Poseidon PoseidonIndexedFolded02 TransferPoseidonWidth3Prefix10R00
theorem actual_copy_checked : checkRowAt p originalRows 4 ⟨[(0,1),(copy,-1)],[]⟩=true := by decide +kernel
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonWidth3Prefix10R00ProgramChecks01.actual_copy_checked
#print axioms ShielddSecurity.TransferPoseidonWidth3Prefix10R00ProgramChecks01.actual_copy_checked
theorem ordered_checked : CompilerOrder.checkOrder [0,copy] [] steps=true := by decide +kernel
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonWidth3Prefix10R00ProgramChecks01.ordered_checked
#print axioms ShielddSecurity.TransferPoseidonWidth3Prefix10R00ProgramChecks01.ordered_checked
theorem writes_checked : (PoseidonCompletion.writes steps).all (fun column => decide (61614≤column ∧ column≤61617))=true := by decide +kernel
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonWidth3Prefix10R00ProgramChecks01.writes_checked
#print axioms ShielddSecurity.TransferPoseidonWidth3Prefix10R00ProgramChecks01.writes_checked
theorem cut_support_checked : CompilerPriorFrame01.checkSupport 3 (cutTerms before) steps=true := by decide +kernel
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonWidth3Prefix10R00ProgramChecks01.cut_support_checked
#print axioms ShielddSecurity.TransferPoseidonWidth3Prefix10R00ProgramChecks01.cut_support_checked
theorem raw_support_checked : originalRows.toList.all (fun row => (row.a++row.b).all (fun term => decide (term.1≤61617 ∨ term.1=copy)))=true := by decide +kernel
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonWidth3Prefix10R00ProgramChecks01.raw_support_checked
#print axioms ShielddSecurity.TransferPoseidonWidth3Prefix10R00ProgramChecks01.raw_support_checked
theorem rows_shape : originalRows.size=5 ∧ materializedSteps.length=3 ∧ steps.length=4 ∧ captureIndices.toList=List.range' 38876 4++[200769] := by decide +kernel
set_option pp.all true in
#check @ShielddSecurity.TransferPoseidonWidth3Prefix10R00ProgramChecks01.rows_shape
#print axioms ShielddSecurity.TransferPoseidonWidth3Prefix10R00ProgramChecks01.rows_shape
end ShielddSecurity.TransferPoseidonWidth3Prefix10R00ProgramChecks01
