import ShielddGnarkFormal.Deployed.Contracts.Transfer.RefinementAdapters
import ShielddGnarkFormal.Deployed.Contracts.Transfer.RefinementAction
import ShielddGnarkFormal.Deployed.Contracts.Transfer.ActionAckSeams
import ShielddGnarkFormal.DecafCompressionBridge
import ShielddGnarkFormal.PoseidonEncryptionBridge
import ShielddGnarkFormal.Poseidon7Bridge
import Mathlib.Tactic.LinearCombination
import Mathlib.Tactic.NormNum
import Mathlib.Tactic.Ring

set_option maxRecDepth 1000000
set_option maxHeartbeats 12000000

/-!
Exact Transfer threshold, EPK, salt, and shared-secret joins.  Every theorem consumes only
the exhaustive certified semantic-provider record; provider identities,
argument order, full issuer-point identity, and public-output seating are
authenticated by the generator before this source is emitted.
GENERATED by gen_deployed_family.py — do not edit by hand.
-/

namespace Shieldd.GnarkFormal.Deployed.Contracts.Transfer

open Shieldd.GnarkFormal
open Shieldd.GnarkFormal.Deployed.TransferRefinement
open Protocol
open scoped Shieldd.GnarkFormal.ChoiceFreeZMod

attribute [-instance] ZMod.instField
private local instance choiceFreeTransferTranscriptCommRing : CommRing DeployedF :=
  ZMod.commRing _

private theorem negOne :
    (8444461749428370424248824938781546531375899335154063827935233455917409239040 : DeployedF) = -1 := by
  decide +kernel

/-- The gated comparator output is exactly the action transcript flag. -/
theorem thresholdFlag_of_semantic
    (rho : Nat → DeployedF)
    (semantic : TransferSemanticProviders rho) :
    ThresholdRegulatedBridge.ThresholdFlagSpec
      (C.action rho).assetProof.isRegulated
      (C.action rho).receiver.note.amount
      (C.action rho).assetProof.leaf.threshold
      (C.action rho).transcript.isFlagged := by
  simpa only [
    ThresholdFlagSemanticSpec, Deployed.Templates.Semantics.TThresholdFlag_9cff3d70e943aa401049c5bfb32ca36b67892e27bb28d1be48bb6acb16e8a202.spec,
    C.action, C.assetProof, C.assetLeaf,
    C.receiver, C.receiverNote, C.transcript,
    isRegulated, isRegulatedLC,
    output0NoteAmount, output0NoteAmountLC,
    assetLeafThreshold, assetLeafThresholdLC,
    isFlagged, isFlaggedLC,
    StructuredLC.eval, StructuredLC.sumRuns,
    StructuredLC.sumResidual, StrideRun.eval,
    thresholdFlagAt129, thresholdFlagAt258,
    thresholdFlagAt896, thresholdFlagAt897,
    zero_add, one_mul, add_zero
  ] using semantic.thresholdFlag

/-- The `senderCore` published EPK is compressed to its action encoding. -/
theorem senderCoreEpkCompressed_of_semantic
    (rho : Nat → DeployedF)
    (semantic : TransferSemanticProviders rho) :
    Protocol.Common.Decaf.compressesTo
      (C.action rho).transcript.senderCore.epk
      (C.action rho).transcript.senderCore.epkEncoding := by
  have hspec :
      Decaf377Assumptions.CompressToFieldSpec
        ⟨Deployed.Templates.Semantics.TDecafCompressToField_231c7eb4774f4fae9c807afeb357aa9dcfa341b773263301f31075bbe10795fb.inputX (SenderCoreEpkCompressValuation rho),
         Deployed.Templates.Semantics.TDecafCompressToField_231c7eb4774f4fae9c807afeb357aa9dcfa341b773263301f31075bbe10795fb.inputY (SenderCoreEpkCompressValuation rho)⟩
        (Deployed.Templates.Semantics.TDecafCompressToField_231c7eb4774f4fae9c807afeb357aa9dcfa341b773263301f31075bbe10795fb.templateRho (SenderCoreEpkCompressValuation rho) 912 -
          Deployed.Templates.Semantics.TDecafCompressToField_231c7eb4774f4fae9c807afeb357aa9dcfa341b773263301f31075bbe10795fb.templateRho (SenderCoreEpkCompressValuation rho) 572) := by
    simpa [
      SenderCoreEpkCompressSemanticSpec, Deployed.Templates.Semantics.TDecafCompressToField_231c7eb4774f4fae9c807afeb357aa9dcfa341b773263301f31075bbe10795fb.spec,
      Decaf377Assumptions.CompressToFieldSpec
    ] using semantic.senderCoreEpkCompress
  have hprotocol :=
    DecafCompressionBridge.compressesTo_of_spec _ _ hspec
  simp [
    AckBridge.toProtocolPoint,
    Deployed.Templates.Semantics.TDecafCompressToField_231c7eb4774f4fae9c807afeb357aa9dcfa341b773263301f31075bbe10795fb.inputX, Deployed.Templates.Semantics.TDecafCompressToField_231c7eb4774f4fae9c807afeb357aa9dcfa341b773263301f31075bbe10795fb.inputY,
    Deployed.Templates.Semantics.TDecafCompressToField_231c7eb4774f4fae9c807afeb357aa9dcfa341b773263301f31075bbe10795fb.templateRho,
    C.action, C.transcript, C.senderCore,
    complianceSenderCoreEpk0, complianceSenderCoreEpk0LC,
    complianceSenderCoreEpk1, complianceSenderCoreEpk1LC,
    complianceSenderCoreEpkFq, complianceSenderCoreEpkFqLC,
    StructuredLC.eval, StructuredLC.sumRuns,
    StructuredLC.sumResidual, StrideRun.eval,
    senderCoreEpkCompressAt1, senderCoreEpkCompressAt3,
    senderCoreEpkCompressAt365, senderCoreEpkCompressAt705,
    negOne, sub_eq_add_neg,
    zero_add, one_mul, add_zero
  ] at hprotocol ⊢
  rw [negOne]
  ring_nf at hprotocol ⊢
  exact hprotocol

/-- The `senderExt` published EPK is compressed to its action encoding. -/
theorem senderExtEpkCompressed_of_semantic
    (rho : Nat → DeployedF)
    (semantic : TransferSemanticProviders rho) :
    Protocol.Common.Decaf.compressesTo
      (C.action rho).transcript.senderExt.epk
      (C.action rho).transcript.senderExt.epkEncoding := by
  have hspec :
      Decaf377Assumptions.CompressToFieldSpec
        ⟨Deployed.Templates.Semantics.TDecafCompressToField_231c7eb4774f4fae9c807afeb357aa9dcfa341b773263301f31075bbe10795fb.inputX (SenderExtEpkCompressValuation rho),
         Deployed.Templates.Semantics.TDecafCompressToField_231c7eb4774f4fae9c807afeb357aa9dcfa341b773263301f31075bbe10795fb.inputY (SenderExtEpkCompressValuation rho)⟩
        (Deployed.Templates.Semantics.TDecafCompressToField_231c7eb4774f4fae9c807afeb357aa9dcfa341b773263301f31075bbe10795fb.templateRho (SenderExtEpkCompressValuation rho) 912 -
          Deployed.Templates.Semantics.TDecafCompressToField_231c7eb4774f4fae9c807afeb357aa9dcfa341b773263301f31075bbe10795fb.templateRho (SenderExtEpkCompressValuation rho) 572) := by
    simpa [
      SenderExtEpkCompressSemanticSpec, Deployed.Templates.Semantics.TDecafCompressToField_231c7eb4774f4fae9c807afeb357aa9dcfa341b773263301f31075bbe10795fb.spec,
      Decaf377Assumptions.CompressToFieldSpec
    ] using semantic.senderExtEpkCompress
  have hprotocol :=
    DecafCompressionBridge.compressesTo_of_spec _ _ hspec
  simp [
    AckBridge.toProtocolPoint,
    Deployed.Templates.Semantics.TDecafCompressToField_231c7eb4774f4fae9c807afeb357aa9dcfa341b773263301f31075bbe10795fb.inputX, Deployed.Templates.Semantics.TDecafCompressToField_231c7eb4774f4fae9c807afeb357aa9dcfa341b773263301f31075bbe10795fb.inputY,
    Deployed.Templates.Semantics.TDecafCompressToField_231c7eb4774f4fae9c807afeb357aa9dcfa341b773263301f31075bbe10795fb.templateRho,
    C.action, C.transcript, C.senderExt,
    complianceSenderExtEpk0, complianceSenderExtEpk0LC,
    complianceSenderExtEpk1, complianceSenderExtEpk1LC,
    complianceSenderExtEpkFq, complianceSenderExtEpkFqLC,
    StructuredLC.eval, StructuredLC.sumRuns,
    StructuredLC.sumResidual, StrideRun.eval,
    senderExtEpkCompressAt1, senderExtEpkCompressAt3,
    senderExtEpkCompressAt365, senderExtEpkCompressAt705,
    negOne, sub_eq_add_neg,
    zero_add, one_mul, add_zero
  ] at hprotocol ⊢
  rw [negOne]
  ring_nf at hprotocol ⊢
  exact hprotocol

/-- The `outputCore` published EPK is compressed to its action encoding. -/
theorem outputCoreEpkCompressed_of_semantic
    (rho : Nat → DeployedF)
    (semantic : TransferSemanticProviders rho) :
    Protocol.Common.Decaf.compressesTo
      (C.action rho).transcript.outputCore.epk
      (C.action rho).transcript.outputCore.epkEncoding := by
  have hspec :
      Decaf377Assumptions.CompressToFieldSpec
        ⟨Deployed.Templates.Semantics.TDecafCompressToField_231c7eb4774f4fae9c807afeb357aa9dcfa341b773263301f31075bbe10795fb.inputX (OutputCoreEpkCompressValuation rho),
         Deployed.Templates.Semantics.TDecafCompressToField_231c7eb4774f4fae9c807afeb357aa9dcfa341b773263301f31075bbe10795fb.inputY (OutputCoreEpkCompressValuation rho)⟩
        (Deployed.Templates.Semantics.TDecafCompressToField_231c7eb4774f4fae9c807afeb357aa9dcfa341b773263301f31075bbe10795fb.templateRho (OutputCoreEpkCompressValuation rho) 912 -
          Deployed.Templates.Semantics.TDecafCompressToField_231c7eb4774f4fae9c807afeb357aa9dcfa341b773263301f31075bbe10795fb.templateRho (OutputCoreEpkCompressValuation rho) 572) := by
    simpa [
      OutputCoreEpkCompressSemanticSpec, Deployed.Templates.Semantics.TDecafCompressToField_231c7eb4774f4fae9c807afeb357aa9dcfa341b773263301f31075bbe10795fb.spec,
      Decaf377Assumptions.CompressToFieldSpec
    ] using semantic.outputCoreEpkCompress
  have hprotocol :=
    DecafCompressionBridge.compressesTo_of_spec _ _ hspec
  simp [
    AckBridge.toProtocolPoint,
    Deployed.Templates.Semantics.TDecafCompressToField_231c7eb4774f4fae9c807afeb357aa9dcfa341b773263301f31075bbe10795fb.inputX, Deployed.Templates.Semantics.TDecafCompressToField_231c7eb4774f4fae9c807afeb357aa9dcfa341b773263301f31075bbe10795fb.inputY,
    Deployed.Templates.Semantics.TDecafCompressToField_231c7eb4774f4fae9c807afeb357aa9dcfa341b773263301f31075bbe10795fb.templateRho,
    C.action, C.transcript, C.outputCore,
    complianceOutputCoreEpk0, complianceOutputCoreEpk0LC,
    complianceOutputCoreEpk1, complianceOutputCoreEpk1LC,
    complianceOutputCoreEpkFq, complianceOutputCoreEpkFqLC,
    StructuredLC.eval, StructuredLC.sumRuns,
    StructuredLC.sumResidual, StrideRun.eval,
    outputCoreEpkCompressAt1, outputCoreEpkCompressAt3,
    outputCoreEpkCompressAt365, outputCoreEpkCompressAt705,
    negOne, sub_eq_add_neg,
    zero_add, one_mul, add_zero
  ] at hprotocol ⊢
  rw [negOne]
  ring_nf at hprotocol ⊢
  exact hprotocol

/-- The `outputExt` published EPK is compressed to its action encoding. -/
theorem outputExtEpkCompressed_of_semantic
    (rho : Nat → DeployedF)
    (semantic : TransferSemanticProviders rho) :
    Protocol.Common.Decaf.compressesTo
      (C.action rho).transcript.outputExt.epk
      (C.action rho).transcript.outputExt.epkEncoding := by
  have hspec :
      Decaf377Assumptions.CompressToFieldSpec
        ⟨Deployed.Templates.Semantics.TDecafCompressToField_231c7eb4774f4fae9c807afeb357aa9dcfa341b773263301f31075bbe10795fb.inputX (OutputExtEpkCompressValuation rho),
         Deployed.Templates.Semantics.TDecafCompressToField_231c7eb4774f4fae9c807afeb357aa9dcfa341b773263301f31075bbe10795fb.inputY (OutputExtEpkCompressValuation rho)⟩
        (Deployed.Templates.Semantics.TDecafCompressToField_231c7eb4774f4fae9c807afeb357aa9dcfa341b773263301f31075bbe10795fb.templateRho (OutputExtEpkCompressValuation rho) 912 -
          Deployed.Templates.Semantics.TDecafCompressToField_231c7eb4774f4fae9c807afeb357aa9dcfa341b773263301f31075bbe10795fb.templateRho (OutputExtEpkCompressValuation rho) 572) := by
    simpa [
      OutputExtEpkCompressSemanticSpec, Deployed.Templates.Semantics.TDecafCompressToField_231c7eb4774f4fae9c807afeb357aa9dcfa341b773263301f31075bbe10795fb.spec,
      Decaf377Assumptions.CompressToFieldSpec
    ] using semantic.outputExtEpkCompress
  have hprotocol :=
    DecafCompressionBridge.compressesTo_of_spec _ _ hspec
  simp [
    AckBridge.toProtocolPoint,
    Deployed.Templates.Semantics.TDecafCompressToField_231c7eb4774f4fae9c807afeb357aa9dcfa341b773263301f31075bbe10795fb.inputX, Deployed.Templates.Semantics.TDecafCompressToField_231c7eb4774f4fae9c807afeb357aa9dcfa341b773263301f31075bbe10795fb.inputY,
    Deployed.Templates.Semantics.TDecafCompressToField_231c7eb4774f4fae9c807afeb357aa9dcfa341b773263301f31075bbe10795fb.templateRho,
    C.action, C.transcript, C.outputExt,
    complianceOutputExtEpk0, complianceOutputExtEpk0LC,
    complianceOutputExtEpk1, complianceOutputExtEpk1LC,
    complianceOutputExtEpkFq, complianceOutputExtEpkFqLC,
    StructuredLC.eval, StructuredLC.sumRuns,
    StructuredLC.sumResidual, StrideRun.eval,
    outputExtEpkCompressAt1, outputExtEpkCompressAt3,
    outputExtEpkCompressAt365, outputExtEpkCompressAt705,
    negOne, sub_eq_add_neg,
    zero_add, one_mul, add_zero
  ] at hprotocol ⊢
  rw [negOne]
  ring_nf at hprotocol ⊢
  exact hprotocol

/-- The action's salt 0 is the exact domain-separated transfer salt. -/
theorem salt0_of_semantic
    (rho : Nat → DeployedF)
    (semantic : TransferSemanticProviders rho) :
    (C.action rho).transcript.salts 0 =
      Protocol.Transfer.Concrete.transferSalt
        (C.action rho).transcript.transferNonceRoot
        Protocol.Transfer.Concrete.detectionSaltLabel := by
  have h := semantic.salt0
  unfold Salt0SemanticSpec Deployed.Templates.Semantics.TGadgetTransferSalt_f771a421e77b34e798b9a3684411305ddf046c31c0dcdd45f55a3341904f59c7.spec
    TransferSaltBridge.TransferSaltSpec at h
  have hdomain :
      Deployed.Templates.Semantics.TGadgetTransferSalt_f771a421e77b34e798b9a3684411305ddf046c31c0dcdd45f55a3341904f59c7.domain =
        Protocol.Transfer.Concrete.transferSaltDomain := by
    decide +kernel
  have hlabel :
      Deployed.Templates.Semantics.TGadgetTransferSalt_f771a421e77b34e798b9a3684411305ddf046c31c0dcdd45f55a3341904f59c7.label =
        Protocol.Transfer.Concrete.detectionSaltLabel := by
    decide +kernel
  rw [hdomain, hlabel] at h
  unfold Protocol.Transfer.Concrete.transferSalt
  simp [
    Deployed.Templates.Semantics.TGadgetTransferSalt_f771a421e77b34e798b9a3684411305ddf046c31c0dcdd45f55a3341904f59c7.endpoint38Lane1,
    C.action, C.transcript, C.saltAt,
    complianceTransferNonceRoot, complianceTransferNonceRootLC,
    salt0, salt0LC,
    StructuredLC.eval, StructuredLC.sumRuns,
    StructuredLC.sumResidual, StrideRun.eval,
    salt0At1, salt0At256,
    salt0At261, salt0At266,
    zero_add, one_mul, add_zero
  ] at h ⊢
  norm_num at h ⊢
  ring_nf at h ⊢
  exact h

/-- The action's salt 1 is the exact domain-separated transfer salt. -/
theorem salt1_of_semantic
    (rho : Nat → DeployedF)
    (semantic : TransferSemanticProviders rho) :
    (C.action rho).transcript.salts 1 =
      Protocol.Transfer.Concrete.transferSalt
        (C.action rho).transcript.transferNonceRoot
        Protocol.Transfer.Concrete.senderCoreSaltLabel := by
  have h := semantic.salt1
  unfold Salt1SemanticSpec Deployed.Templates.Semantics.TGadgetTransferSalt_6102356f10803bf3a14c647c07a6804c8be9ed25097c1247a5f07e703b892326.spec
    TransferSaltBridge.TransferSaltSpec at h
  have hdomain :
      Deployed.Templates.Semantics.TGadgetTransferSalt_6102356f10803bf3a14c647c07a6804c8be9ed25097c1247a5f07e703b892326.domain =
        Protocol.Transfer.Concrete.transferSaltDomain := by
    decide +kernel
  have hlabel :
      Deployed.Templates.Semantics.TGadgetTransferSalt_6102356f10803bf3a14c647c07a6804c8be9ed25097c1247a5f07e703b892326.label =
        Protocol.Transfer.Concrete.senderCoreSaltLabel := by
    decide +kernel
  rw [hdomain, hlabel] at h
  unfold Protocol.Transfer.Concrete.transferSalt
  simp [
    Deployed.Templates.Semantics.TGadgetTransferSalt_6102356f10803bf3a14c647c07a6804c8be9ed25097c1247a5f07e703b892326.endpoint38Lane1,
    C.action, C.transcript, C.saltAt,
    complianceTransferNonceRoot, complianceTransferNonceRootLC,
    salt1, salt1LC,
    StructuredLC.eval, StructuredLC.sumRuns,
    StructuredLC.sumResidual, StrideRun.eval,
    salt1At1, salt1At256,
    salt1At261, salt1At266,
    zero_add, one_mul, add_zero
  ] at h ⊢
  norm_num at h ⊢
  ring_nf at h ⊢
  exact h

/-- The action's salt 2 is the exact domain-separated transfer salt. -/
theorem salt2_of_semantic
    (rho : Nat → DeployedF)
    (semantic : TransferSemanticProviders rho) :
    (C.action rho).transcript.salts 2 =
      Protocol.Transfer.Concrete.transferSalt
        (C.action rho).transcript.transferNonceRoot
        Protocol.Transfer.Concrete.senderExtSaltLabel := by
  have h := semantic.salt2
  unfold Salt2SemanticSpec Deployed.Templates.Semantics.TGadgetTransferSalt_7ca1f127ae2aba8ae3ff0daa0762a2981d18913d868dc2742d5a74f22684c557.spec
    TransferSaltBridge.TransferSaltSpec at h
  have hdomain :
      Deployed.Templates.Semantics.TGadgetTransferSalt_7ca1f127ae2aba8ae3ff0daa0762a2981d18913d868dc2742d5a74f22684c557.domain =
        Protocol.Transfer.Concrete.transferSaltDomain := by
    decide +kernel
  have hlabel :
      Deployed.Templates.Semantics.TGadgetTransferSalt_7ca1f127ae2aba8ae3ff0daa0762a2981d18913d868dc2742d5a74f22684c557.label =
        Protocol.Transfer.Concrete.senderExtSaltLabel := by
    decide +kernel
  rw [hdomain, hlabel] at h
  unfold Protocol.Transfer.Concrete.transferSalt
  simp [
    Deployed.Templates.Semantics.TGadgetTransferSalt_7ca1f127ae2aba8ae3ff0daa0762a2981d18913d868dc2742d5a74f22684c557.endpoint38Lane1,
    C.action, C.transcript, C.saltAt,
    complianceTransferNonceRoot, complianceTransferNonceRootLC,
    salt2, salt2LC,
    StructuredLC.eval, StructuredLC.sumRuns,
    StructuredLC.sumResidual, StrideRun.eval,
    salt2At1, salt2At256,
    salt2At261, salt2At266,
    zero_add, one_mul, add_zero
  ] at h ⊢
  norm_num at h ⊢
  ring_nf at h ⊢
  exact h

/-- The action's salt 3 is the exact domain-separated transfer salt. -/
theorem salt3_of_semantic
    (rho : Nat → DeployedF)
    (semantic : TransferSemanticProviders rho) :
    (C.action rho).transcript.salts 3 =
      Protocol.Transfer.Concrete.transferSalt
        (C.action rho).transcript.transferNonceRoot
        Protocol.Transfer.Concrete.outputCoreSaltLabel := by
  have h := semantic.salt3
  unfold Salt3SemanticSpec Deployed.Templates.Semantics.TGadgetTransferSalt_afc1dab7ce4cb1d665f58c0e62c3211c7152d792a45bd80acbbe3444a7be5d4e.spec
    TransferSaltBridge.TransferSaltSpec at h
  have hdomain :
      Deployed.Templates.Semantics.TGadgetTransferSalt_afc1dab7ce4cb1d665f58c0e62c3211c7152d792a45bd80acbbe3444a7be5d4e.domain =
        Protocol.Transfer.Concrete.transferSaltDomain := by
    decide +kernel
  have hlabel :
      Deployed.Templates.Semantics.TGadgetTransferSalt_afc1dab7ce4cb1d665f58c0e62c3211c7152d792a45bd80acbbe3444a7be5d4e.label =
        Protocol.Transfer.Concrete.outputCoreSaltLabel := by
    decide +kernel
  rw [hdomain, hlabel] at h
  unfold Protocol.Transfer.Concrete.transferSalt
  simp [
    Deployed.Templates.Semantics.TGadgetTransferSalt_afc1dab7ce4cb1d665f58c0e62c3211c7152d792a45bd80acbbe3444a7be5d4e.endpoint38Lane1,
    C.action, C.transcript, C.saltAt,
    complianceTransferNonceRoot, complianceTransferNonceRootLC,
    salt3, salt3LC,
    StructuredLC.eval, StructuredLC.sumRuns,
    StructuredLC.sumResidual, StrideRun.eval,
    salt3At1, salt3At256,
    salt3At261, salt3At266,
    zero_add, one_mul, add_zero
  ] at h ⊢
  norm_num at h ⊢
  ring_nf at h ⊢
  exact h

/-- The action's salt 4 is the exact domain-separated transfer salt. -/
theorem salt4_of_semantic
    (rho : Nat → DeployedF)
    (semantic : TransferSemanticProviders rho) :
    (C.action rho).transcript.salts 4 =
      Protocol.Transfer.Concrete.transferSalt
        (C.action rho).transcript.transferNonceRoot
        Protocol.Transfer.Concrete.outputExtSaltLabel := by
  have h := semantic.salt4
  unfold Salt4SemanticSpec Deployed.Templates.Semantics.TGadgetTransferSalt_c897628fb413fa804e577bd04151d6ba3b460e6052b87493c17e1529720c3945.spec
    TransferSaltBridge.TransferSaltSpec at h
  have hdomain :
      Deployed.Templates.Semantics.TGadgetTransferSalt_c897628fb413fa804e577bd04151d6ba3b460e6052b87493c17e1529720c3945.domain =
        Protocol.Transfer.Concrete.transferSaltDomain := by
    decide +kernel
  have hlabel :
      Deployed.Templates.Semantics.TGadgetTransferSalt_c897628fb413fa804e577bd04151d6ba3b460e6052b87493c17e1529720c3945.label =
        Protocol.Transfer.Concrete.outputExtSaltLabel := by
    decide +kernel
  rw [hdomain, hlabel] at h
  unfold Protocol.Transfer.Concrete.transferSalt
  simp [
    Deployed.Templates.Semantics.TGadgetTransferSalt_c897628fb413fa804e577bd04151d6ba3b460e6052b87493c17e1529720c3945.endpoint38Lane1,
    C.action, C.transcript, C.saltAt,
    complianceTransferNonceRoot, complianceTransferNonceRootLC,
    salt4, salt4LC,
    StructuredLC.eval, StructuredLC.sumRuns,
    StructuredLC.sumResidual, StrideRun.eval,
    salt4At1, salt4At256,
    salt4At261, salt4At266,
    zero_add, one_mul, add_zero
  ] at h ⊢
  norm_num at h ⊢
  ring_nf at h ⊢
  exact h

/-- Provider-derived ACK point used by the `senderCore` shared-secret body. -/
def senderCoreSharedAck (rho : Nat → DeployedF) :
    Protocol.Common.Point DeployedF :=
  Deployed.Templates.Semantics.TDecafSharedSecret_0a9405fe9fa7b69f5919b41caaa6165a64f58cf75a38a13283885fbfe7b30f0b.ack (SenderCoreSharedSecretValuation rho)

/-- Provider-derived diversified transmission key for `senderCore`. -/
def senderCoreSharedDkPub (rho : Nat → DeployedF) :
    Protocol.Common.Point DeployedF :=
  Deployed.Templates.Semantics.TDecafSharedSecret_0a9405fe9fa7b69f5919b41caaa6165a64f58cf75a38a13283885fbfe7b30f0b.dkPub (SenderCoreSharedSecretValuation rho)

/-- Exact issuer, user, and selected shared points for `senderCore`. -/
def senderCoreSharedSecrets (rho : Nat → DeployedF) :
    SharedSecretBridge.SharedSecrets :=
  Deployed.Templates.Semantics.TDecafSharedSecret_0a9405fe9fa7b69f5919b41caaa6165a64f58cf75a38a13283885fbfe7b30f0b.output (SenderCoreSharedSecretValuation rho)

/-- The certified `senderCore` body consumes the exact action transcript. -/
theorem senderCoreSharedSecretBody_of_semantic
    (rho : Nat → DeployedF)
    (semantic : TransferSemanticProviders rho) :
    SharedSecretBridge.SharedSecretsBody
      (C.action rho).transcript.senderRCore
      (senderCoreSharedAck rho)
      (senderCoreSharedDkPub rho)
      (C.action rho).transcript.senderCore.epk
      (C.action rho).transcript.isFlagged
      (senderCoreSharedSecrets rho) := by
  simpa only [
    SenderCoreSharedSecretSemanticSpec, Deployed.Templates.Semantics.TDecafSharedSecret_0a9405fe9fa7b69f5919b41caaa6165a64f58cf75a38a13283885fbfe7b30f0b.spec,
    Deployed.Templates.Semantics.TDecafSharedSecret_0a9405fe9fa7b69f5919b41caaa6165a64f58cf75a38a13283885fbfe7b30f0b.esk, Deployed.Templates.Semantics.TDecafSharedSecret_0a9405fe9fa7b69f5919b41caaa6165a64f58cf75a38a13283885fbfe7b30f0b.publishedEpk,
    Deployed.Templates.Semantics.TDecafSharedSecret_0a9405fe9fa7b69f5919b41caaa6165a64f58cf75a38a13283885fbfe7b30f0b.isFlagged,
    senderCoreSharedAck, senderCoreSharedDkPub,
    senderCoreSharedSecrets,
    C.action, C.transcript, C.senderCore,
    complianceSenderRCore, complianceSenderRCoreLC,
    complianceSenderCoreEpk0, complianceSenderCoreEpk0LC,
    complianceSenderCoreEpk1, complianceSenderCoreEpk1LC,
    isFlagged, isFlaggedLC,
    StructuredLC.eval, StructuredLC.sumRuns,
    StructuredLC.sumResidual, StrideRun.eval,
    senderCoreSharedSecretAt253,
    senderCoreSharedSecretAt1809,
    senderCoreSharedSecretAt1807,
    senderCoreSharedSecretAt1,
    zero_add, one_mul, add_zero
  ] using semantic.senderCoreSharedSecret

/-- Provider-derived ACK point used by the `senderExt` shared-secret body. -/
def senderExtSharedAck (rho : Nat → DeployedF) :
    Protocol.Common.Point DeployedF :=
  Deployed.Templates.Semantics.TDecafSharedSecret_041af0b46add32e74aa6803586e275955f3d35f426ea6bf6fc76982a6e67cd41.ack (SenderExtSharedSecretValuation rho)

/-- Provider-derived diversified transmission key for `senderExt`. -/
def senderExtSharedDkPub (rho : Nat → DeployedF) :
    Protocol.Common.Point DeployedF :=
  Deployed.Templates.Semantics.TDecafSharedSecret_041af0b46add32e74aa6803586e275955f3d35f426ea6bf6fc76982a6e67cd41.dkPub (SenderExtSharedSecretValuation rho)

/-- Exact issuer, user, and selected shared points for `senderExt`. -/
def senderExtSharedSecrets (rho : Nat → DeployedF) :
    SharedSecretBridge.SharedSecrets :=
  Deployed.Templates.Semantics.TDecafSharedSecret_041af0b46add32e74aa6803586e275955f3d35f426ea6bf6fc76982a6e67cd41.output (SenderExtSharedSecretValuation rho)

/-- The certified `senderExt` body consumes the exact action transcript. -/
theorem senderExtSharedSecretBody_of_semantic
    (rho : Nat → DeployedF)
    (semantic : TransferSemanticProviders rho) :
    SharedSecretBridge.SharedSecretsBody
      (C.action rho).transcript.senderRExt
      (senderExtSharedAck rho)
      (senderExtSharedDkPub rho)
      (C.action rho).transcript.senderExt.epk
      (C.action rho).transcript.isFlagged
      (senderExtSharedSecrets rho) := by
  simpa only [
    SenderExtSharedSecretSemanticSpec, Deployed.Templates.Semantics.TDecafSharedSecret_041af0b46add32e74aa6803586e275955f3d35f426ea6bf6fc76982a6e67cd41.spec,
    Deployed.Templates.Semantics.TDecafSharedSecret_041af0b46add32e74aa6803586e275955f3d35f426ea6bf6fc76982a6e67cd41.esk, Deployed.Templates.Semantics.TDecafSharedSecret_041af0b46add32e74aa6803586e275955f3d35f426ea6bf6fc76982a6e67cd41.publishedEpk,
    Deployed.Templates.Semantics.TDecafSharedSecret_041af0b46add32e74aa6803586e275955f3d35f426ea6bf6fc76982a6e67cd41.isFlagged,
    senderExtSharedAck, senderExtSharedDkPub,
    senderExtSharedSecrets,
    C.action, C.transcript, C.senderExt,
    complianceSenderRExt, complianceSenderRExtLC,
    complianceSenderExtEpk0, complianceSenderExtEpk0LC,
    complianceSenderExtEpk1, complianceSenderExtEpk1LC,
    isFlagged, isFlaggedLC,
    StructuredLC.eval, StructuredLC.sumRuns,
    StructuredLC.sumResidual, StrideRun.eval,
    senderExtSharedSecretAt252,
    senderExtSharedSecretAt1808,
    senderExtSharedSecretAt1806,
    senderExtSharedSecretAt7332,
    zero_add, one_mul, add_zero
  ] using semantic.senderExtSharedSecret

/-- Provider-derived ACK point used by the `outputCore` shared-secret body. -/
def outputCoreSharedAck (rho : Nat → DeployedF) :
    Protocol.Common.Point DeployedF :=
  Deployed.Templates.Semantics.TDecafSharedSecret_041af0b46add32e74aa6803586e275955f3d35f426ea6bf6fc76982a6e67cd41.ack (OutputCoreSharedSecretValuation rho)

/-- Provider-derived diversified transmission key for `outputCore`. -/
def outputCoreSharedDkPub (rho : Nat → DeployedF) :
    Protocol.Common.Point DeployedF :=
  Deployed.Templates.Semantics.TDecafSharedSecret_041af0b46add32e74aa6803586e275955f3d35f426ea6bf6fc76982a6e67cd41.dkPub (OutputCoreSharedSecretValuation rho)

/-- Exact issuer, user, and selected shared points for `outputCore`. -/
def outputCoreSharedSecrets (rho : Nat → DeployedF) :
    SharedSecretBridge.SharedSecrets :=
  Deployed.Templates.Semantics.TDecafSharedSecret_041af0b46add32e74aa6803586e275955f3d35f426ea6bf6fc76982a6e67cd41.output (OutputCoreSharedSecretValuation rho)

/-- The certified `outputCore` body consumes the exact action transcript. -/
theorem outputCoreSharedSecretBody_of_semantic
    (rho : Nat → DeployedF)
    (semantic : TransferSemanticProviders rho) :
    SharedSecretBridge.SharedSecretsBody
      (C.action rho).transcript.outputRCore
      (outputCoreSharedAck rho)
      (outputCoreSharedDkPub rho)
      (C.action rho).transcript.outputCore.epk
      (C.action rho).transcript.isFlagged
      (outputCoreSharedSecrets rho) := by
  simpa only [
    OutputCoreSharedSecretSemanticSpec, Deployed.Templates.Semantics.TDecafSharedSecret_041af0b46add32e74aa6803586e275955f3d35f426ea6bf6fc76982a6e67cd41.spec,
    Deployed.Templates.Semantics.TDecafSharedSecret_041af0b46add32e74aa6803586e275955f3d35f426ea6bf6fc76982a6e67cd41.esk, Deployed.Templates.Semantics.TDecafSharedSecret_041af0b46add32e74aa6803586e275955f3d35f426ea6bf6fc76982a6e67cd41.publishedEpk,
    Deployed.Templates.Semantics.TDecafSharedSecret_041af0b46add32e74aa6803586e275955f3d35f426ea6bf6fc76982a6e67cd41.isFlagged,
    outputCoreSharedAck, outputCoreSharedDkPub,
    outputCoreSharedSecrets,
    C.action, C.transcript, C.outputCore,
    complianceOutputRCore, complianceOutputRCoreLC,
    complianceOutputCoreEpk0, complianceOutputCoreEpk0LC,
    complianceOutputCoreEpk1, complianceOutputCoreEpk1LC,
    isFlagged, isFlaggedLC,
    StructuredLC.eval, StructuredLC.sumRuns,
    StructuredLC.sumResidual, StrideRun.eval,
    outputCoreSharedSecretAt252,
    outputCoreSharedSecretAt1808,
    outputCoreSharedSecretAt1806,
    outputCoreSharedSecretAt7332,
    zero_add, one_mul, add_zero
  ] using semantic.outputCoreSharedSecret

/-- Provider-derived ACK point used by the `outputExt` shared-secret body. -/
def outputExtSharedAck (rho : Nat → DeployedF) :
    Protocol.Common.Point DeployedF :=
  Deployed.Templates.Semantics.TDecafSharedSecret_041af0b46add32e74aa6803586e275955f3d35f426ea6bf6fc76982a6e67cd41.ack (OutputExtSharedSecretValuation rho)

/-- Provider-derived diversified transmission key for `outputExt`. -/
def outputExtSharedDkPub (rho : Nat → DeployedF) :
    Protocol.Common.Point DeployedF :=
  Deployed.Templates.Semantics.TDecafSharedSecret_041af0b46add32e74aa6803586e275955f3d35f426ea6bf6fc76982a6e67cd41.dkPub (OutputExtSharedSecretValuation rho)

/-- Exact issuer, user, and selected shared points for `outputExt`. -/
def outputExtSharedSecrets (rho : Nat → DeployedF) :
    SharedSecretBridge.SharedSecrets :=
  Deployed.Templates.Semantics.TDecafSharedSecret_041af0b46add32e74aa6803586e275955f3d35f426ea6bf6fc76982a6e67cd41.output (OutputExtSharedSecretValuation rho)

/-- The certified `outputExt` body consumes the exact action transcript. -/
theorem outputExtSharedSecretBody_of_semantic
    (rho : Nat → DeployedF)
    (semantic : TransferSemanticProviders rho) :
    SharedSecretBridge.SharedSecretsBody
      (C.action rho).transcript.outputRExt
      (outputExtSharedAck rho)
      (outputExtSharedDkPub rho)
      (C.action rho).transcript.outputExt.epk
      (C.action rho).transcript.isFlagged
      (outputExtSharedSecrets rho) := by
  simpa only [
    OutputExtSharedSecretSemanticSpec, Deployed.Templates.Semantics.TDecafSharedSecret_041af0b46add32e74aa6803586e275955f3d35f426ea6bf6fc76982a6e67cd41.spec,
    Deployed.Templates.Semantics.TDecafSharedSecret_041af0b46add32e74aa6803586e275955f3d35f426ea6bf6fc76982a6e67cd41.esk, Deployed.Templates.Semantics.TDecafSharedSecret_041af0b46add32e74aa6803586e275955f3d35f426ea6bf6fc76982a6e67cd41.publishedEpk,
    Deployed.Templates.Semantics.TDecafSharedSecret_041af0b46add32e74aa6803586e275955f3d35f426ea6bf6fc76982a6e67cd41.isFlagged,
    outputExtSharedAck, outputExtSharedDkPub,
    outputExtSharedSecrets,
    C.action, C.transcript, C.outputExt,
    complianceOutputRExt, complianceOutputRExtLC,
    complianceOutputExtEpk0, complianceOutputExtEpk0LC,
    complianceOutputExtEpk1, complianceOutputExtEpk1LC,
    isFlagged, isFlaggedLC,
    StructuredLC.eval, StructuredLC.sumRuns,
    StructuredLC.sumResidual, StrideRun.eval,
    outputExtSharedSecretAt252,
    outputExtSharedSecretAt1808,
    outputExtSharedSecretAt1806,
    outputExtSharedSecretAt7332,
    zero_add, one_mul, add_zero
  ] using semantic.outputExtSharedSecret

/-- The exact threshold output is Boolean at the circuit boundary. -/
theorem transcriptFlagBooleanCircuit_of_semantic
    (rho : Nat → DeployedF)
    (semantic : TransferSemanticProviders rho)
    (isRegulatedBoolean :
      Protocol.Common.boolean (C.action rho).assetProof.isRegulated) :
    ThresholdRegulatedBridge.BooleanCircuit
      (C.action rho).transcript.isFlagged := by
  have h := thresholdFlag_of_semantic rho semantic
  rw [h.2.2.1]
  rcases isRegulatedBoolean with hzero | hone
  · simp [
      ThresholdRegulatedBridge.BooleanCircuit,
      Protocol.Transfer.Concrete.thresholdFlag,
      hzero
    ]
  · by_cases hthreshold :
      (C.action rho).receiver.note.amount.val <
        (C.action rho).assetProof.leaf.threshold.val
    · simp [
        ThresholdRegulatedBridge.BooleanCircuit,
        Protocol.Transfer.Concrete.thresholdFlag,
        Protocol.Transfer.Concrete.thresholdReached,
        hthreshold
      ]
    · simp [
        ThresholdRegulatedBridge.BooleanCircuit,
        Protocol.Transfer.Concrete.thresholdFlag,
        Protocol.Transfer.Concrete.thresholdReached,
        hthreshold, hone
      ]

/-- The `senderCore` shared ladder consumes the complete action ACK point. -/
theorem senderCoreSharedAck_eq_action
    (rho : Nat → DeployedF) :
    senderCoreSharedAck rho = senderAckPoint rho := by
  simp only [
    senderCoreSharedAck, Deployed.Templates.Semantics.TDecafSharedSecret_0a9405fe9fa7b69f5919b41caaa6165a64f58cf75a38a13283885fbfe7b30f0b.ack,
    Deployed.Templates.Semantics.TDecafSharedSecret_0a9405fe9fa7b69f5919b41caaa6165a64f58cf75a38a13283885fbfe7b30f0b.UserWindowSupport.base, senderAckPoint, Deployed.Templates.Semantics.TDecafAck_e3974880eca25a8b5cfa17d94f28498f1dc082a93526c584816508afe0778ca1.AckSupport.output,
    Protocol.Common.Point.mk.injEq
  ]
  constructor
  · simp only [
      senderCoreSharedAck, Deployed.Templates.Semantics.TDecafSharedSecret_0a9405fe9fa7b69f5919b41caaa6165a64f58cf75a38a13283885fbfe7b30f0b.ack,
      Deployed.Templates.Semantics.TDecafSharedSecret_0a9405fe9fa7b69f5919b41caaa6165a64f58cf75a38a13283885fbfe7b30f0b.UserWindowSupport.base, senderAckPoint, Deployed.Templates.Semantics.TDecafAck_e3974880eca25a8b5cfa17d94f28498f1dc082a93526c584816508afe0778ca1.AckSupport.output,
      SenderCoreSharedSecretValuation, Seg103.localRho,
      SenderAckValuation, ReceiverAckValuation,
      Seg31.localRho, Deployed.Templates.seated]
    rw [show Seg103.wireSeating 1811 =
      Seg31.wireSeating 3003 by decide +kernel]
    rw [show Seg103.wireSeating 1812 =
      Seg31.wireSeating 3011 by decide +kernel]
  · simp only [
      senderCoreSharedAck, Deployed.Templates.Semantics.TDecafSharedSecret_0a9405fe9fa7b69f5919b41caaa6165a64f58cf75a38a13283885fbfe7b30f0b.ack,
      Deployed.Templates.Semantics.TDecafSharedSecret_0a9405fe9fa7b69f5919b41caaa6165a64f58cf75a38a13283885fbfe7b30f0b.UserWindowSupport.base, senderAckPoint, Deployed.Templates.Semantics.TDecafAck_e3974880eca25a8b5cfa17d94f28498f1dc082a93526c584816508afe0778ca1.AckSupport.output,
      SenderCoreSharedSecretValuation, Seg103.localRho,
      SenderAckValuation, ReceiverAckValuation,
      Seg31.localRho, Deployed.Templates.seated]
    rw [show Seg103.wireSeating 1813 =
      Seg31.wireSeating 3004 by decide +kernel]
    rw [show Seg103.wireSeating 1814 =
      Seg31.wireSeating 3012 by decide +kernel]

/-- The `senderCore` shared ladder consumes the selected action detection key. -/
theorem senderCoreSharedDkPub_eq_action
    (rho : Nat → DeployedF)
    (semantic : TransferSemanticProviders rho) :
    senderCoreSharedDkPub rho =
      Protocol.Transfer.Concrete.effectiveDkPub (C.action rho) := by
  rw [← effectiveDkPoint_eq_action rho semantic]
  simp [
    senderCoreSharedDkPub, Deployed.Templates.Semantics.TDecafSharedSecret_0a9405fe9fa7b69f5919b41caaa6165a64f58cf75a38a13283885fbfe7b30f0b.dkPub,
    Deployed.Templates.Semantics.TDecafSharedSecret_0a9405fe9fa7b69f5919b41caaa6165a64f58cf75a38a13283885fbfe7b30f0b.IssuerWindowSupport.base,
    Deployed.Templates.Semantics.TSelectPoint_794c37cf14a957fde2cc9026bf435729f36540de636670284dc233839047d975.selectedX,
    Deployed.Templates.Semantics.TSelectPoint_794c37cf14a957fde2cc9026bf435729f36540de636670284dc233839047d975.selectedY,
    Protocol.Transfer.Concrete.unregulatedDkPub,
    senderCoreSharedSecretAt4573, senderCoreSharedSecretAt4574,
    effectiveDkPubAt4, effectiveDkPubAt5
  ]

/-- The `senderCore` body proves the independent protocol shared-secret relation. -/
theorem senderCoreSharedSecrets_of_semantic
    (rho : Nat → DeployedF)
    (semantic : TransferSemanticProviders rho)
    (isRegulatedBoolean :
      Protocol.Common.boolean (C.action rho).assetProof.isRegulated) :
    Protocol.Transfer.Concrete.sharedSecrets
      (C.action rho).transcript.senderRCore
      (Protocol.Transfer.Concrete.ack
        (Protocol.Transfer.Concrete.effectiveRingPk (C.action rho))
        (C.action rho).senderCompliance.d)
      (Protocol.Transfer.Concrete.effectiveDkPub (C.action rho))
      (C.action rho).transcript.senderCore.epk
      (C.action rho).transcript.isFlagged
      (senderCoreSharedSecrets rho).issuer
      (senderCoreSharedSecrets rho).user
      (senderCoreSharedSecrets rho).selected := by
  have hAck :=
    senderAckSpec_of_semantic rho semantic isRegulatedBoolean
  have hAckEq :
      senderAckPoint rho =
        Protocol.Transfer.Concrete.ack
          (Protocol.Transfer.Concrete.effectiveRingPk (C.action rho))
          (C.action rho).senderCompliance.d := by
    simpa only [Protocol.Transfer.Concrete.ack] using hAck.2.2.2
  have hBody :=
    senderCoreSharedSecretBody_of_semantic rho semantic
  rw [
    senderCoreSharedAck_eq_action rho,
    hAckEq,
    senderCoreSharedDkPub_eq_action rho semantic
  ] at hBody
  exact (SharedSecretBridge.shared_secrets_sound
    (C.action rho).transcript.senderRCore
    (Protocol.Transfer.Concrete.ack
      (Protocol.Transfer.Concrete.effectiveRingPk (C.action rho))
      (C.action rho).senderCompliance.d)
    (Protocol.Transfer.Concrete.effectiveDkPub (C.action rho))
    (C.action rho).transcript.senderCore.epk
    (C.action rho).transcript.isFlagged
    (senderCoreSharedSecrets rho)
    (transcriptFlagBooleanCircuit_of_semantic
      rho semantic isRegulatedBoolean)
    (by simpa only [← hAckEq] using hAck.2.2.1)
    (effectiveDkPub_onCurve rho semantic isRegulatedBoolean)
    (senderCoreEpkCompressed_of_semantic rho semantic).1
    hBody).2

/-- The `senderExt` shared ladder consumes the complete action ACK point. -/
theorem senderExtSharedAck_eq_action
    (rho : Nat → DeployedF) :
    senderExtSharedAck rho = senderAckPoint rho := by
  simp only [
    senderExtSharedAck, Deployed.Templates.Semantics.TDecafSharedSecret_041af0b46add32e74aa6803586e275955f3d35f426ea6bf6fc76982a6e67cd41.ack,
    Deployed.Templates.Semantics.TDecafSharedSecret_041af0b46add32e74aa6803586e275955f3d35f426ea6bf6fc76982a6e67cd41.UserWindowSupport.base, senderAckPoint, Deployed.Templates.Semantics.TDecafAck_e3974880eca25a8b5cfa17d94f28498f1dc082a93526c584816508afe0778ca1.AckSupport.output,
    Protocol.Common.Point.mk.injEq
  ]
  constructor
  · simp only [
      senderExtSharedAck, Deployed.Templates.Semantics.TDecafSharedSecret_041af0b46add32e74aa6803586e275955f3d35f426ea6bf6fc76982a6e67cd41.ack,
      Deployed.Templates.Semantics.TDecafSharedSecret_041af0b46add32e74aa6803586e275955f3d35f426ea6bf6fc76982a6e67cd41.UserWindowSupport.base, senderAckPoint, Deployed.Templates.Semantics.TDecafAck_e3974880eca25a8b5cfa17d94f28498f1dc082a93526c584816508afe0778ca1.AckSupport.output,
      SenderExtSharedSecretValuation, Seg104.localRho,
      SenderAckValuation, ReceiverAckValuation,
      Seg31.localRho, Deployed.Templates.seated]
    rw [show Seg104.wireSeating 1810 =
      Seg31.wireSeating 3003 by decide +kernel]
    rw [show Seg104.wireSeating 1811 =
      Seg31.wireSeating 3011 by decide +kernel]
  · simp only [
      senderExtSharedAck, Deployed.Templates.Semantics.TDecafSharedSecret_041af0b46add32e74aa6803586e275955f3d35f426ea6bf6fc76982a6e67cd41.ack,
      Deployed.Templates.Semantics.TDecafSharedSecret_041af0b46add32e74aa6803586e275955f3d35f426ea6bf6fc76982a6e67cd41.UserWindowSupport.base, senderAckPoint, Deployed.Templates.Semantics.TDecafAck_e3974880eca25a8b5cfa17d94f28498f1dc082a93526c584816508afe0778ca1.AckSupport.output,
      SenderExtSharedSecretValuation, Seg104.localRho,
      SenderAckValuation, ReceiverAckValuation,
      Seg31.localRho, Deployed.Templates.seated]
    rw [show Seg104.wireSeating 1812 =
      Seg31.wireSeating 3004 by decide +kernel]
    rw [show Seg104.wireSeating 1813 =
      Seg31.wireSeating 3012 by decide +kernel]

/-- The `senderExt` shared ladder consumes the selected action detection key. -/
theorem senderExtSharedDkPub_eq_action
    (rho : Nat → DeployedF)
    (semantic : TransferSemanticProviders rho) :
    senderExtSharedDkPub rho =
      Protocol.Transfer.Concrete.effectiveDkPub (C.action rho) := by
  rw [← effectiveDkPoint_eq_action rho semantic]
  simp [
    senderExtSharedDkPub, Deployed.Templates.Semantics.TDecafSharedSecret_041af0b46add32e74aa6803586e275955f3d35f426ea6bf6fc76982a6e67cd41.dkPub,
    Deployed.Templates.Semantics.TDecafSharedSecret_041af0b46add32e74aa6803586e275955f3d35f426ea6bf6fc76982a6e67cd41.IssuerWindowSupport.base,
    Deployed.Templates.Semantics.TSelectPoint_794c37cf14a957fde2cc9026bf435729f36540de636670284dc233839047d975.selectedX,
    Deployed.Templates.Semantics.TSelectPoint_794c37cf14a957fde2cc9026bf435729f36540de636670284dc233839047d975.selectedY,
    Protocol.Transfer.Concrete.unregulatedDkPub,
    senderExtSharedSecretAt4572, senderExtSharedSecretAt4573,
    effectiveDkPubAt4, effectiveDkPubAt5
  ]

/-- The `senderExt` body proves the independent protocol shared-secret relation. -/
theorem senderExtSharedSecrets_of_semantic
    (rho : Nat → DeployedF)
    (semantic : TransferSemanticProviders rho)
    (isRegulatedBoolean :
      Protocol.Common.boolean (C.action rho).assetProof.isRegulated) :
    Protocol.Transfer.Concrete.sharedSecrets
      (C.action rho).transcript.senderRExt
      (Protocol.Transfer.Concrete.ack
        (Protocol.Transfer.Concrete.effectiveRingPk (C.action rho))
        (C.action rho).senderCompliance.d)
      (Protocol.Transfer.Concrete.effectiveDkPub (C.action rho))
      (C.action rho).transcript.senderExt.epk
      (C.action rho).transcript.isFlagged
      (senderExtSharedSecrets rho).issuer
      (senderExtSharedSecrets rho).user
      (senderExtSharedSecrets rho).selected := by
  have hAck :=
    senderAckSpec_of_semantic rho semantic isRegulatedBoolean
  have hAckEq :
      senderAckPoint rho =
        Protocol.Transfer.Concrete.ack
          (Protocol.Transfer.Concrete.effectiveRingPk (C.action rho))
          (C.action rho).senderCompliance.d := by
    simpa only [Protocol.Transfer.Concrete.ack] using hAck.2.2.2
  have hBody :=
    senderExtSharedSecretBody_of_semantic rho semantic
  rw [
    senderExtSharedAck_eq_action rho,
    hAckEq,
    senderExtSharedDkPub_eq_action rho semantic
  ] at hBody
  exact (SharedSecretBridge.shared_secrets_sound
    (C.action rho).transcript.senderRExt
    (Protocol.Transfer.Concrete.ack
      (Protocol.Transfer.Concrete.effectiveRingPk (C.action rho))
      (C.action rho).senderCompliance.d)
    (Protocol.Transfer.Concrete.effectiveDkPub (C.action rho))
    (C.action rho).transcript.senderExt.epk
    (C.action rho).transcript.isFlagged
    (senderExtSharedSecrets rho)
    (transcriptFlagBooleanCircuit_of_semantic
      rho semantic isRegulatedBoolean)
    (by simpa only [← hAckEq] using hAck.2.2.1)
    (effectiveDkPub_onCurve rho semantic isRegulatedBoolean)
    (senderExtEpkCompressed_of_semantic rho semantic).1
    hBody).2

/-- The `outputCore` shared ladder consumes the complete action ACK point. -/
theorem outputCoreSharedAck_eq_action
    (rho : Nat → DeployedF) :
    outputCoreSharedAck rho = receiverAckPoint rho := by
  simp only [
    outputCoreSharedAck, Deployed.Templates.Semantics.TDecafSharedSecret_041af0b46add32e74aa6803586e275955f3d35f426ea6bf6fc76982a6e67cd41.ack,
    Deployed.Templates.Semantics.TDecafSharedSecret_041af0b46add32e74aa6803586e275955f3d35f426ea6bf6fc76982a6e67cd41.UserWindowSupport.base, receiverAckPoint, Deployed.Templates.Semantics.TDecafAck_e3974880eca25a8b5cfa17d94f28498f1dc082a93526c584816508afe0778ca1.AckSupport.output,
    Protocol.Common.Point.mk.injEq
  ]
  constructor
  · simp only [
      outputCoreSharedAck, Deployed.Templates.Semantics.TDecafSharedSecret_041af0b46add32e74aa6803586e275955f3d35f426ea6bf6fc76982a6e67cd41.ack,
      Deployed.Templates.Semantics.TDecafSharedSecret_041af0b46add32e74aa6803586e275955f3d35f426ea6bf6fc76982a6e67cd41.UserWindowSupport.base, receiverAckPoint, Deployed.Templates.Semantics.TDecafAck_e3974880eca25a8b5cfa17d94f28498f1dc082a93526c584816508afe0778ca1.AckSupport.output,
      OutputCoreSharedSecretValuation, Seg105.localRho,
      SenderAckValuation, ReceiverAckValuation,
      Seg71.localRho, Deployed.Templates.seated]
    rw [show Seg105.wireSeating 1810 =
      Seg71.wireSeating 3003 by decide +kernel]
    rw [show Seg105.wireSeating 1811 =
      Seg71.wireSeating 3011 by decide +kernel]
  · simp only [
      outputCoreSharedAck, Deployed.Templates.Semantics.TDecafSharedSecret_041af0b46add32e74aa6803586e275955f3d35f426ea6bf6fc76982a6e67cd41.ack,
      Deployed.Templates.Semantics.TDecafSharedSecret_041af0b46add32e74aa6803586e275955f3d35f426ea6bf6fc76982a6e67cd41.UserWindowSupport.base, receiverAckPoint, Deployed.Templates.Semantics.TDecafAck_e3974880eca25a8b5cfa17d94f28498f1dc082a93526c584816508afe0778ca1.AckSupport.output,
      OutputCoreSharedSecretValuation, Seg105.localRho,
      SenderAckValuation, ReceiverAckValuation,
      Seg71.localRho, Deployed.Templates.seated]
    rw [show Seg105.wireSeating 1812 =
      Seg71.wireSeating 3004 by decide +kernel]
    rw [show Seg105.wireSeating 1813 =
      Seg71.wireSeating 3012 by decide +kernel]

/-- The `outputCore` shared ladder consumes the selected action detection key. -/
theorem outputCoreSharedDkPub_eq_action
    (rho : Nat → DeployedF)
    (semantic : TransferSemanticProviders rho) :
    outputCoreSharedDkPub rho =
      Protocol.Transfer.Concrete.effectiveDkPub (C.action rho) := by
  rw [← effectiveDkPoint_eq_action rho semantic]
  simp [
    outputCoreSharedDkPub, Deployed.Templates.Semantics.TDecafSharedSecret_041af0b46add32e74aa6803586e275955f3d35f426ea6bf6fc76982a6e67cd41.dkPub,
    Deployed.Templates.Semantics.TDecafSharedSecret_041af0b46add32e74aa6803586e275955f3d35f426ea6bf6fc76982a6e67cd41.IssuerWindowSupport.base,
    Deployed.Templates.Semantics.TSelectPoint_794c37cf14a957fde2cc9026bf435729f36540de636670284dc233839047d975.selectedX,
    Deployed.Templates.Semantics.TSelectPoint_794c37cf14a957fde2cc9026bf435729f36540de636670284dc233839047d975.selectedY,
    Protocol.Transfer.Concrete.unregulatedDkPub,
    outputCoreSharedSecretAt4572, outputCoreSharedSecretAt4573,
    effectiveDkPubAt4, effectiveDkPubAt5
  ]

/-- The `outputCore` body proves the independent protocol shared-secret relation. -/
theorem outputCoreSharedSecrets_of_semantic
    (rho : Nat → DeployedF)
    (semantic : TransferSemanticProviders rho)
    (isRegulatedBoolean :
      Protocol.Common.boolean (C.action rho).assetProof.isRegulated) :
    Protocol.Transfer.Concrete.sharedSecrets
      (C.action rho).transcript.outputRCore
      (Protocol.Transfer.Concrete.ack
        (Protocol.Transfer.Concrete.effectiveRingPk (C.action rho))
        (C.action rho).receiverCompliance.d)
      (Protocol.Transfer.Concrete.effectiveDkPub (C.action rho))
      (C.action rho).transcript.outputCore.epk
      (C.action rho).transcript.isFlagged
      (outputCoreSharedSecrets rho).issuer
      (outputCoreSharedSecrets rho).user
      (outputCoreSharedSecrets rho).selected := by
  have hAck :=
    receiverAckSpec_of_semantic rho semantic isRegulatedBoolean
  have hAckEq :
      receiverAckPoint rho =
        Protocol.Transfer.Concrete.ack
          (Protocol.Transfer.Concrete.effectiveRingPk (C.action rho))
          (C.action rho).receiverCompliance.d := by
    simpa only [Protocol.Transfer.Concrete.ack] using hAck.2.2.2
  have hBody :=
    outputCoreSharedSecretBody_of_semantic rho semantic
  rw [
    outputCoreSharedAck_eq_action rho,
    hAckEq,
    outputCoreSharedDkPub_eq_action rho semantic
  ] at hBody
  exact (SharedSecretBridge.shared_secrets_sound
    (C.action rho).transcript.outputRCore
    (Protocol.Transfer.Concrete.ack
      (Protocol.Transfer.Concrete.effectiveRingPk (C.action rho))
      (C.action rho).receiverCompliance.d)
    (Protocol.Transfer.Concrete.effectiveDkPub (C.action rho))
    (C.action rho).transcript.outputCore.epk
    (C.action rho).transcript.isFlagged
    (outputCoreSharedSecrets rho)
    (transcriptFlagBooleanCircuit_of_semantic
      rho semantic isRegulatedBoolean)
    (by simpa only [← hAckEq] using hAck.2.2.1)
    (effectiveDkPub_onCurve rho semantic isRegulatedBoolean)
    (outputCoreEpkCompressed_of_semantic rho semantic).1
    hBody).2

/-- The `outputExt` shared ladder consumes the complete action ACK point. -/
theorem outputExtSharedAck_eq_action
    (rho : Nat → DeployedF) :
    outputExtSharedAck rho = receiverAckPoint rho := by
  simp only [
    outputExtSharedAck, Deployed.Templates.Semantics.TDecafSharedSecret_041af0b46add32e74aa6803586e275955f3d35f426ea6bf6fc76982a6e67cd41.ack,
    Deployed.Templates.Semantics.TDecafSharedSecret_041af0b46add32e74aa6803586e275955f3d35f426ea6bf6fc76982a6e67cd41.UserWindowSupport.base, receiverAckPoint, Deployed.Templates.Semantics.TDecafAck_e3974880eca25a8b5cfa17d94f28498f1dc082a93526c584816508afe0778ca1.AckSupport.output,
    Protocol.Common.Point.mk.injEq
  ]
  constructor
  · simp only [
      outputExtSharedAck, Deployed.Templates.Semantics.TDecafSharedSecret_041af0b46add32e74aa6803586e275955f3d35f426ea6bf6fc76982a6e67cd41.ack,
      Deployed.Templates.Semantics.TDecafSharedSecret_041af0b46add32e74aa6803586e275955f3d35f426ea6bf6fc76982a6e67cd41.UserWindowSupport.base, receiverAckPoint, Deployed.Templates.Semantics.TDecafAck_e3974880eca25a8b5cfa17d94f28498f1dc082a93526c584816508afe0778ca1.AckSupport.output,
      OutputExtSharedSecretValuation, Seg106.localRho,
      SenderAckValuation, ReceiverAckValuation,
      Seg71.localRho, Deployed.Templates.seated]
    rw [show Seg106.wireSeating 1810 =
      Seg71.wireSeating 3003 by decide +kernel]
    rw [show Seg106.wireSeating 1811 =
      Seg71.wireSeating 3011 by decide +kernel]
  · simp only [
      outputExtSharedAck, Deployed.Templates.Semantics.TDecafSharedSecret_041af0b46add32e74aa6803586e275955f3d35f426ea6bf6fc76982a6e67cd41.ack,
      Deployed.Templates.Semantics.TDecafSharedSecret_041af0b46add32e74aa6803586e275955f3d35f426ea6bf6fc76982a6e67cd41.UserWindowSupport.base, receiverAckPoint, Deployed.Templates.Semantics.TDecafAck_e3974880eca25a8b5cfa17d94f28498f1dc082a93526c584816508afe0778ca1.AckSupport.output,
      OutputExtSharedSecretValuation, Seg106.localRho,
      SenderAckValuation, ReceiverAckValuation,
      Seg71.localRho, Deployed.Templates.seated]
    rw [show Seg106.wireSeating 1812 =
      Seg71.wireSeating 3004 by decide +kernel]
    rw [show Seg106.wireSeating 1813 =
      Seg71.wireSeating 3012 by decide +kernel]

/-- The `outputExt` shared ladder consumes the selected action detection key. -/
theorem outputExtSharedDkPub_eq_action
    (rho : Nat → DeployedF)
    (semantic : TransferSemanticProviders rho) :
    outputExtSharedDkPub rho =
      Protocol.Transfer.Concrete.effectiveDkPub (C.action rho) := by
  rw [← effectiveDkPoint_eq_action rho semantic]
  simp [
    outputExtSharedDkPub, Deployed.Templates.Semantics.TDecafSharedSecret_041af0b46add32e74aa6803586e275955f3d35f426ea6bf6fc76982a6e67cd41.dkPub,
    Deployed.Templates.Semantics.TDecafSharedSecret_041af0b46add32e74aa6803586e275955f3d35f426ea6bf6fc76982a6e67cd41.IssuerWindowSupport.base,
    Deployed.Templates.Semantics.TSelectPoint_794c37cf14a957fde2cc9026bf435729f36540de636670284dc233839047d975.selectedX,
    Deployed.Templates.Semantics.TSelectPoint_794c37cf14a957fde2cc9026bf435729f36540de636670284dc233839047d975.selectedY,
    Protocol.Transfer.Concrete.unregulatedDkPub,
    outputExtSharedSecretAt4572, outputExtSharedSecretAt4573,
    effectiveDkPubAt4, effectiveDkPubAt5
  ]

/-- The `outputExt` body proves the independent protocol shared-secret relation. -/
theorem outputExtSharedSecrets_of_semantic
    (rho : Nat → DeployedF)
    (semantic : TransferSemanticProviders rho)
    (isRegulatedBoolean :
      Protocol.Common.boolean (C.action rho).assetProof.isRegulated) :
    Protocol.Transfer.Concrete.sharedSecrets
      (C.action rho).transcript.outputRExt
      (Protocol.Transfer.Concrete.ack
        (Protocol.Transfer.Concrete.effectiveRingPk (C.action rho))
        (C.action rho).receiverCompliance.d)
      (Protocol.Transfer.Concrete.effectiveDkPub (C.action rho))
      (C.action rho).transcript.outputExt.epk
      (C.action rho).transcript.isFlagged
      (outputExtSharedSecrets rho).issuer
      (outputExtSharedSecrets rho).user
      (outputExtSharedSecrets rho).selected := by
  have hAck :=
    receiverAckSpec_of_semantic rho semantic isRegulatedBoolean
  have hAckEq :
      receiverAckPoint rho =
        Protocol.Transfer.Concrete.ack
          (Protocol.Transfer.Concrete.effectiveRingPk (C.action rho))
          (C.action rho).receiverCompliance.d := by
    simpa only [Protocol.Transfer.Concrete.ack] using hAck.2.2.2
  have hBody :=
    outputExtSharedSecretBody_of_semantic rho semantic
  rw [
    outputExtSharedAck_eq_action rho,
    hAckEq,
    outputExtSharedDkPub_eq_action rho semantic
  ] at hBody
  exact (SharedSecretBridge.shared_secrets_sound
    (C.action rho).transcript.outputRExt
    (Protocol.Transfer.Concrete.ack
      (Protocol.Transfer.Concrete.effectiveRingPk (C.action rho))
      (C.action rho).receiverCompliance.d)
    (Protocol.Transfer.Concrete.effectiveDkPub (C.action rho))
    (C.action rho).transcript.outputExt.epk
    (C.action rho).transcript.isFlagged
    (outputExtSharedSecrets rho)
    (transcriptFlagBooleanCircuit_of_semantic
      rho semantic isRegulatedBoolean)
    (by simpa only [← hAckEq] using hAck.2.2.1)
    (effectiveDkPub_onCurve rho semantic isRegulatedBoolean)
    (outputExtEpkCompressed_of_semantic rho semantic).1
    hBody).2

end Shieldd.GnarkFormal.Deployed.Contracts.Transfer
