import ShielddSecurity.TransferPoseidonLate03ConsumerChecks01
import ShielddSecurity.TransferPoseidonLate03CoverageChecks01
import ShielddSecurity.TransferPoseidonLate03ProgramChecks01
set_option pp.all true in
#check @ShielddSecurity.Poseidon.round_certificate_sound
#print axioms ShielddSecurity.Poseidon.round_certificate_sound
