import ShielddGnarkFormal.Deployed.Contracts.NoteReshape8x1.Seg73
import ShielddGnarkFormal.Deployed.Contracts.NoteReshape8x1.Seg75
import ShielddGnarkFormal.Deployed.Contracts.NoteReshape8x1.Seg76
import ShielddGnarkFormal.Deployed.Contracts.NoteReshape8x1.Seg78
import ShielddGnarkFormal.Deployed.Contracts.NoteReshape8x1.Seg80
import ShielddGnarkFormal.Deployed.Contracts.NoteReshape8x1.Seg81
import ShielddGnarkFormal.Deployed.Contracts.NoteReshape8x1.Seg82
import ShielddGnarkFormal.Deployed.Contracts.NoteReshape8x1.Seg84
import ShielddGnarkFormal.Deployed.Contracts.NoteReshape8x1.Seg85

set_option maxRecDepth 1000000
set_option maxHeartbeats 4000000

/-! Exact deployed spend2 facts for the note_reshape8x1 deployment.
GENERATED by gen_note_reshape_family.py — do not edit by hand. -/

namespace Shieldd.GnarkFormal.Deployed.Contracts.NoteReshape8x1

structure Spend2CircuitFacts (rho : Nat → Seg73.F) : Prop where
  GadgetNoteCommitmentSeg73 : Seg73.contract.spec rho
  GadgetNullifierSeg75 : Seg75.contract.spec rho
  GadgetStateCommitmentPathSeg76 : Seg76.contract.spec rho
  GadgetSyntheticDummyNullifierSeg78 : Seg78.contract.spec rho
  AssertEqSeg80 : Seg80.contract.spec rho
  DecafRandomizedVerificationKeySeg81 : Seg81.contract.spec rho
  DecafAssertEquivalentIfSeg82 : Seg82.contract.spec rho
  DecafCompressToFieldSeg84 : Seg84.contract.spec rho
  HistoryClassifySeg85 : Seg85.contract.spec rho

end Shieldd.GnarkFormal.Deployed.Contracts.NoteReshape8x1
