import ShielddGnarkFormal.Deployed.Contracts.NoteReshape8x1.Seg43
import ShielddGnarkFormal.Deployed.Contracts.NoteReshape8x1.Seg45
import ShielddGnarkFormal.Deployed.Contracts.NoteReshape8x1.Seg46
import ShielddGnarkFormal.Deployed.Contracts.NoteReshape8x1.Seg48
import ShielddGnarkFormal.Deployed.Contracts.NoteReshape8x1.Seg50
import ShielddGnarkFormal.Deployed.Contracts.NoteReshape8x1.Seg51
import ShielddGnarkFormal.Deployed.Contracts.NoteReshape8x1.Seg52
import ShielddGnarkFormal.Deployed.Contracts.NoteReshape8x1.Seg54
import ShielddGnarkFormal.Deployed.Contracts.NoteReshape8x1.Seg55

set_option maxRecDepth 1000000
set_option maxHeartbeats 4000000

/-! Exact deployed spend0 facts for the note_reshape8x1 deployment.
GENERATED by gen_note_reshape_family.py — do not edit by hand. -/

namespace Shieldd.GnarkFormal.Deployed.Contracts.NoteReshape8x1

structure Spend0CircuitFacts (rho : Nat → Seg43.F) : Prop where
  GadgetNoteCommitmentSeg43 : Seg43.contract.spec rho
  GadgetNullifierSeg45 : Seg45.contract.spec rho
  GadgetStateCommitmentPathSeg46 : Seg46.contract.spec rho
  GadgetSyntheticDummyNullifierSeg48 : Seg48.contract.spec rho
  AssertEqSeg50 : Seg50.contract.spec rho
  DecafRandomizedVerificationKeySeg51 : Seg51.contract.spec rho
  DecafAssertEquivalentIfSeg52 : Seg52.contract.spec rho
  DecafCompressToFieldSeg54 : Seg54.contract.spec rho
  HistoryClassifySeg55 : Seg55.contract.spec rho

end Shieldd.GnarkFormal.Deployed.Contracts.NoteReshape8x1
